In [1]:
import pandas as pd

df = pd.read_csv('preprocessed_data.csv')

In [2]:
df.shape

(39127, 12)

In [3]:
df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...

In [7]:
df_rand = df.sample(n=1)

for col in ["preamble", "description", "sentence"]:
    print(df_rand[col].iloc[0])
    print(f"\nend of {col}\n")
    print()

Решение по уголовному делу
Информация по делу
Дело № 1-36/2016
П Р И Г О В О Р
Именем Российской Федерации
26 января 2016 года город Чебоксары
Калининский районный суд г.Чебоксары Чувашской Республики под председательством судьи Фадеевой О.М., при секретаре судебного заседания Бирюкове А.М., с участием: государственного обвинителя - помощника прокурора Калининского района г. Чебоксары Попова А.Ю.,
подсудимого
Иванова Р.В.
,
его защитника - адвоката коллегии адвокатов «Право» Чувашской Республики Мальцева А.В.,
рассмотрев в открытом судебном заседании уголовное дело в отношении
<данные изъяты>
по обвинению в совершении преступления, предусмотренного частью 1 статьи 105 Уголовного кодекса Российской Федерации,


end of preamble


у с т а н о в и л:
Иванов Р.В. совершил убийство, то есть умышленное причинение смерти другому человеку, при следующих обстоятельствах.
В период с
ДД.ММ.ГГГГ
Иванов Р.В., находясь в состоянии алкогольного опьянения в
<адрес>
, в ходе ссоры с малознакомой
ФИО1
, возникшей на почве личных неприязненных отношений, умышленно с целью совершения убийства последней, используя в качестве орудия преступления поочередно нож и топор, нанес ей их клинками не менее 26 ударов в область головы, грудной клетки, шеи и живота, причинив
физическую боль и телесные повреждения в виде:
открытой черепно-мозговой травмы с кровоизлияниями под мягкую мозговую оболочку большого мозга и мозжечка, повреждением твердой мозговой оболочки лобной области справа, вдавленными переломами правой и левой теменной костей, лобной кости в центре, открытым оскольчатым переломом костей спинки носа, кровоизлияниями в мягкие ткани свобода черепа, лица, ранами №№ 1-14 волосистой части головы и лица, кровоподтеками и ссадинами лица, размозжением слизистой и мягких тканей нижней губы, патологической подвижностью 1,2 зубов слева, 1-ого зуба справа на нижней челюсти, 1,2 зубов слева на верхней челюсти, травматической ампутацией 2-ого зуба справа на нижней челюсти, 1,2,3 зубов справа на верхней челюсти;
колото-резаных ран передней поверхности шеи справа (№№15-19), передней поверхности шеи слева (№№20-22), с повреждением подкожно-жировой клетчатки, мышц шеи, правой наружной яремной вены, нижнего края правой пластины щитовидного хряща, перстнещитовидной связки, внутреннего края левой наружной яремной вены, наружного края левой общей сонной артерии, с кровоизлияниями в мягкие ткани по ходу раневых каналов, в мягкие ткани передней поверхности шеи справа и слева; проникающих колото-резаных ран передней поверхности грудной клетки слева (рана № 23), живота справа (рана № 24), с повреждениями подкожной жировой клетчатки, мышц груди, 2 межреберья, мышц живота, большого сальника, брыжейки тонкого кишечника, с кровоизлияниями в мягкие ткани по ходу раневых каналов.
От аспирационной асфиксии кровью, обильной кровопотери, развившихся в результате комбинированной травмы – в виде открытой черепно-мозговой травмы и колото-резаных ран передней поверхности шеи справа, передней поверхности шеи слева, проникающих колото-резаных ран передней поверхности грудной клетки слева, относящихся по признаку опасности для жизни человека к категории повреждений, причинивших тяжкий вред здоровью,
скончалась на месте происшествия через небольшой промежуток времени.
Подсудимый Иванов Р.В. виновным себя в судебном заседании признал. Из его показаний следует, что днем
на улице он встретил
ФИО8
и
ФИО4
, вместе с которыми была ранее незнакомая ему девушка, как оказалось позже, -
Около 15 часов данные девушки по его приглашению пришли к нему в
по проспекту Мира
, где все вместе стали употреблять спиртное. Примерно в 19 часов
ушли, а
осталась у него в квартире, где они продолжили употреблять спиртное. В какой-то момент, когда он и
находились в зале, последняя неожиданно схватила кухонный нож и с оскорбительными словами набросилась на него, пытаясь нанести ему удар ножом, который он отобрал у нее и, развернув к себе спиной, нанес ей примерно шесть ударов ножом в область шеи. Затем он оттащил
в ванную комнату, где три раза ударил обухом топора по голове, после чего ушел в другую комнату и лег спать. Через некоторое время проснулся и обнаружил, что
мертва. После этого при помощи топора он разделил ее тело пополам в области таза. Части тела
по отдельности он обернул в палас и поочередно вынес на улицу, где выкинул в мусорный контейнер, расположенный возле его дома.
Однако будучи первоначально допрошен по обстоятельствам дела, Иванов Р.В. в ходе предварительного следствия давал несколько иные показания, не указывая о том, что во время распития спиртного в его квартире
пыталась нанести ему удар ножом. В частности, при допросе в качестве подозреваемого
Иванов Р.В. показал, что после совместного распития спиртного
, сидя на диване в зале квартиры, примерно в 20 часов в ходе разговора беспричинно оскорбила его, отчего он разозлился и решил убить ее. Сначала он нанес ей несколько ударов кулаком в область лица, после чего взял со стола на кухне нож с пластмассовой рукояткой черного цвета, подошел сзади к сидевшей на полу в зале
и перерезал ей ножом горло.
резко вскочила и стала бегать по квартире, при этом у нее из горла брызгала кровь. Через некоторое время
упала на пол перед входной дверью в ванную комнату. Он взял ее на руки и перенес в ванну, при этом она была еще жива. Разозлившись, он нанес ей еще несколько ударов ножом в туловище, после чего пошел спать. Проснувшись через несколько часов, он обнаружил, что
умерла. Тогда он решил разрубить ее тело на две части, для чего взял из спальни топор, прошел с ним в ванную комнату, где разрубил им тело
в области таза, затем завернул их в два паласа и поочередно вынес на улицу и выбросил в мусорный контейнер. (том № 1 л.д. 143-145)
Аналогичным образом Иванов Р.В. изложил обстоятельства дела и в собственноручно написанной им
явке с повинной, в которой он чистосердечно признался в том, что накануне вечером после употребления спиртного с малознакомой женщиной, последняя стала оскорблять его. Разозлившись, он ударил ее кулаком по лицу и локтем в область головы, после чего взял кухонный нож с длинным лезвием и стал наносить им удары ей в шею. Увидев, что женщина умерла, он положил ее в ванную, где топором разрубил ее пополам. После этого он завернул тело в палас, и выбросил его в мусорный контейнер. (том № 1 л.д. 64)
Все показания в стадии предварительного расследования уголовного дела излагались Ивановым Р.В. добровольно в присутствии защитника, вместе с которым они знакомились с содержанием протоколов его допроса; каких-либо замечаний и дополнений к ним не имели. Нарушений требований уголовно-процессуального законодательства в ходе их получения в судебном заседании не установлено. Суд считает, что, выдвигая версию как в ходе его повторных допросов в стадии предварительного следствия, так и в судебном заседании о том, что его действия были ответными на противоправное поведение
, Иванов Р.В. тем самым пытается смягчить свою ответственность за содеянное.
При оценке доказательств суд принимает во внимание его показания, которые он давал на протяжении всего предварительного расследования уголовного дела, так и в ходе судебного разбирательства, в совокупности в той части, в которой они не противоречат другим доказательствам, исследованным в ходе судебного следствия.
Виновность Иванова Р.В. в умышленном убийстве
установлена показаниями потерпевшей
ФИО3
, свидетелей обвинения
ФИО5
ФИО6
ФИО2
ФИО7
, а также протоколами следственных действий, заключениями экспертиз и иными приобщенными к уголовному делу документами, исследованными в ходе судебного разбирательства.
Из оглашенных на основании ч.1 ст.281 УПК РФ показаний потерпевшей
, данных ею в ходе предварительного расследования, следует, что
ее дочь
поехала на поиски работы в
. В последний раз она связывалась с ней по телефону
. Около 22 часов
ее племянник сообщил ей о необходимости ехать в морг для опознания трупа.
, находясь в морге
, в трупе женщины она опознала свою дочь
. Впоследствии ей стало известно, что труп ее дочери обнаружили в мусорном контейнере возле
(том № 1 л.д. 212-214).
В судебном заседании на основании ч.1 ст.281 УПК РФ с согласия сторон оглашены показания неявившихся свидетелей
, данные ими в ходе предварительного расследования.
Так, из показаний свидетеля
явствует, что около 14 часов
, когда она с
находилась возле
, они встретили ранее ей знакомого Иванова Р.В., который предложил им употребить спиртное у него дома, на что они согласились. В зале его
они выпили около 3 пузырьков с медицинским спиртом. При этом каких-либо конфликтов между ними не возникало. Около 17 часов она и
вместе с Ивановым Р.В. осталась в его квартире. (том № 1 л.д. 185-187)
Аналогичные показания дала и свидетель обвинения
, подтвердив, что после 15 часов
они употребляли спиртное совместно с
и Ивановым Р.В. в квартире последнего. Около 17 часов того же дня она и
осталась наедине с Ивановым Р.В. в его жилище. (том
№
л.д. 189-190)
Согласно показаниям свидетеля
, матери подсудимого, ее сын освободился из мест лишения свободы
, после чего стал проживать в
. Около 4-5 часов
Р.В. пришел к ней домой по адресу:
, и лег спать. Около полудня к ним приехали сотрудники полиции, которые задержали Иванова Р.В. и доставили его в отдел полиции (том № 1 л.д. 191-193).
Согласно показаниям свидетеля обвинения
он остался в гостях у своего друга
, проживающего в
. В ночь с 28 на
они неоднократно выходили на улицу к подъезду
, чтобы покурить. Примерно в 3 часа они увидели, как мужчина выволок что-то наподобие мешка из подъезда
, который затем поднял себе на плечо и понес в сторону мусорных контейнеров, расположенных возле дома. При них, данный мужчина обратно не возвращался.
от сотрудников полиции им стало известно, что в мусорном контейнере был обнаружен труд девушки (том № 1 л.д. 242-244).
Свидетель обвинения
в судебном заседании аналогичным образом, что и свидетель
, изложил известные ему обстоятельства дела, подтвердив, что около 3 часов
он видел, как из шестого подъезда
незнакомый мужчина выволок за собой что-то похожее на мешок, который затем взвалил себе на плечо и понес в сторону мусорных контейнеров, стоящих возле дома.
Свидетель обвинения Иванов И.П. суду показал, что около 10 часов 30 минут
он направился в сторону мусорных контейнеров, расположенных возле
, для того, чтобы выбросить мусор. В одном из контейнеров среди мусора он увидел человеческую ступню, о чем сообщил сотрудникам полиции, которые по приезду осмотрели мусорные контейнеры и обнаружили в одном из них труп женщины с признаками насильственной смерти, который был разрублен посередине туловища.
в 10 часов 28 минут в дежурную часть отдела полиции
Управления МВД России по
поступило телефонное сообщение от
о том, что в мусорном контейнере, расположенном между домами
, торчит ступня человека. (том № 1 л.д. 59)
В ходе осмотра мусорного контейнера, расположенного возле
, произведенного с соблюдением требований Уголовно-процессуального кодекса Российской Федерации
в период времени с 11 часов до 12 часов 20 минут, в нем среди твердых бытовых предметов обнаружена стопа человека и палас красного цвета с черным рисунком, в который завернут фрагмент тела женщины, состоящий из головы, шеи, туловища до уровня средней трети, с повреждениями относительно ровными краями и с надрезами по краям. Из повреждений определяются петли кишечника серовато-розового цвета, жировая клетчатка. На туловище трупа надеты куртка кожаная черного цвета, пропитанная пятнами красно-бурого цвета с щелевидным повреждением на левом рукаве; джемпер светло-красного цвета с черным рисунком, пропитанный кровью; трусы и джинсы темно-синего цвета, приспущенные до уровня верхнего третьего бедра, пропитанные кровью; на джинсах имеются повреждения клепки пояса и молнии. Кожа всех поверхностей испачкана подсохшей кровью в виде помарок. В наружных слуховых проходах, носовых ходах и в полости рта имеются подтеки подсохшей крови. В полости рта жидкая темная кровь. На волосистой части головы и на лице множество повреждений с кровоподтечными краями в просвете, в части поврежденных ран – поврежденные кости. На шее имеются раны веретенообразной и щелевидной формы с ровными кровоподтечными краями, на передней поверхности грудной клетки слева и на животе справа – раны веретенообразной формы. Определяется патологическая подвижность и крепитация левого плеча в средней трети. Ладонные и тыльные поверхности кистей испачканы кровью в виде помарок с наложением ворсинок темного и светлого цвета. На ладонных поверхностях правой и левой кисти – раны щелевидной формы с ровными кровоподтечными краями. Плоскость пресечения на уровне гребней подвздошных костей поясничного позвонка, на которых имеются дополнительные повреждения. В правой и левой паховых областях щелевидные раны с ровными кровоподтечными краями, кожа испачкана подсохшей кровью в виде помарок. С места происшествия изъяты смыв с лица трупа, микроволокно с пальца его правой руки и смывы с ладоней его обеих рук (том № 1 л.д. 8-22).
В тот же день в период времени с 13 часов 10 минут до 14 часов 03 минут осмотрен лестничный марш между первым и вторым этажами в подъезде
, где на одной из ступеней обнаружена частица волокна красного цвета с белыми вкраплениями. На лестничной площадке второго этажа обнаружены пятна бурого цвета, похожие на кровь, 3 волокна белого цвета, биологические следы и волокна, откопированные на светлые дактилоскопические пленки, а на входной двери, ведущей в
– след обуви, который откопирован на темную дактилоскопическую пленку. Марлевые тампоны со следами биологического происхождения и микроволокнами изъяты с места происшествия. (том № 1 л.д. 23-27).
В ходе произведенного с соблюдением требований уголовно-процессуального законодательства
в период времени с 14 часов 20 минут до 16 часов 10 минут осмотра
в указанном жилище на полу и стенах возле входа, на обоях в комнате имеются множественные следы в виде брызг красно-бурого цвета. В ванной комнате ванна, стены и пол обильно испачканы веществом бурого цвета, непосредственно в ванной лежат пять следов биологического происхождения. Там же справа от входной двери возле стены обнаружен топор, испачканный веществом бурого цвета. Немного правее от ванной под зеркалом обнаружен нож, а возле входной двери в комнату, расположенную напротив входа в квартиру, на полу – кусок ткани. Все вышеперечисленные предметы вместе со смывами вещества бурого цвета на ватные тампоны и срезами с обоев изъяты из указанного жилища. (том № 1 л.д. 28-37)
у Иванова Р.В. с соблюдением требований уголовно-процессуального законодательства получен смывы с правой и левой рук, образцы ногтевых пластин с обеих рук, защечного эпителия, а
– образцы его крови. (том № 1 л.д. 114-116, 118-120, 122-123, 235-236)
В тот же день в ходе выемки
Р.В. добровольно выдал старшему следователю СО по Калининскому району
предметы одежды, а именно: футболку, штаны и кроссовки. (том
л.д. 132-135)
в танатологическом отделении Бюджетного учреждения «Республиканское бюро судебно-медицинской экспертизы» Минздравсоцразвития Чувашии изъяты вещи с трупа
, в том числе куртка кожаная черного цвета, джемпер светло-красного цвета, трусы красного цвета, бюстгальтер синего цвета, джинсовые брюки темно-синего цвета, а также 2 паласа красного и темно-коричневого цветов. (том № 1 л.д. 199-200)
В ходе выемки, произведенной
, в биологическом отделении БУ «Республиканское бюро судебно-медицинской экспертизы» Минздравсоцразвития Чувашии изъяты образцы крови
(том № 2 л.д. 128-130)
Впоследствии все обнаруженные в ходе осмотров места происшествия и при производстве выемок предметы осмотрены и вместе с полученными образцами представлены на исследование экспертам.
В ходе осмотра установлено, что на футболке, брюках и кроссовках Иванова Р.В., бюстгальтере, джемпере, куртке, джинсовых брюках
, а также на двух паласах темно-коричневого и красного цветов, срезах обоев со стены
, куске ткани, обнаруженном в указанном жилище, имеются пятна и помарки коричневого цвета неопределенной формы.
Изъятый в квартире нож с пластмассовой ручкой имеет общую длину от уровня острия до уровня свободного конца ручки 29,6 см. Лезвие клинка ножа и острие заточены не остро, а на уровне острия лезвие тупое. Обух имеет П-образную форму с выраженными ребрами, его поверхность прямолинейная.
Топор имеет деревянное топорище, его лезвие заточено не совсем остро, на уровне носка лезвие тупое. Ребра клинка топора со стороны пятки и носка почти выраженные. Обух имеет П-образную форму, поверхность обуха несколько деформирована. (том № 2 л.д. 87-93)
Согласно заключению эксперта
(экспертиза вещественных доказательств) от
кровь как
, так и Иванова Р.В. относится к группе О??. На смыве с ладоней рук, с лица, на джемпере, куртке, джинсах обнаружена кровь женщины группы О??, происхождение которой не исключается от
и исключается от Иванова Р.В.
На красном и коричневом паласах обнаружена кровь человека, половую принадлежность которой установить не представилось возможным, следовательно, не исключается ее происхождение как от
, так и от Иванова Р.В.
На джемпере и на бюстгальтере установлено присутствие пота и выявлен антиген Н, свойственный
и Иванову Р.В., следовательно, не исключается его происхождение от указанных лиц. (том № 2 л.д. 19-23)
Согласно выводов, изложенных в заключении эксперта (экспертиза вещественных доказательств)
от
, кровь на брюках Иванова Р.В. в пятнах об. 13,14 обнаружена кровь женщины группы О??, происхождение которой не исключается от
В остальных пятнах на брюках и в пятнах на паре кроссовок Иванова Р.В. обнаружена кровь человека группы О??, половую принадлежность которой установить не представилось возможным, происхождение которой не исключается как от
На футболке и брюках Иванова Р.В. установлено наличие пота и выявлен антиген Н, свойственный
и Иванову Р.В., следовательно, не исключается его происхождение от указанных лиц (том № 2 л.д. 29-33).
Из заключения эксперта (экспертизы вещественных доказательств)
от 12-
усматривается, что на тампонах-смывах около двери, ведущей в комнату, с пола ванной комнаты, на пяти предметах биологического происхождения, на ноже (об. 32), топоре (об. 26), на куске ватина, на кусках обоев (об. 8, 23) изъятых из
, обнаружены кровь женщины группы О??, происхождение которой не исключается от
В остальных пятнах на ноже, топоре, двух кусках обоев, на микроволокне с правой руки обнаружена кровь человека группы О??, половую принадлежность которой установить не представилось возможным, происхождение которой не исключается от
и от Иванова Р.В. (том № 2 л.д. 59-64).
Обнаруженные в ходе осмотра места происшествия фрагменты тела, завернутые в палас, были направлены в отделение экспертизы трупов бюджетного учреждения «Республиканское бюро судебно-медицинской экспертизы» Минздравсоцразвития Чувашии.
, мать убитой, по чертам лица, цвету волос, шрамам на левой и правой руках и надписи «Костик» на руке опознала в указанном трупе свою дочь
(том № 1 л.д. 201-204).
Все вышеприведенные доказательства, которые суд находит не противоречащими друг другу, допустимыми и достоверными, у суда сомнений не вызывают, и суд принимает их во внимание при постановлении приговора. Их совокупность достоверно свидетельствует о том, что Иванов Р.В. вечером
находился у себя в
совместно с
и имеет непосредственное отношение к нанесению ей телесных повреждений.
Согласно заключению экспертизы трупа
при исследовании трупа
смерть последней наступила от аспирационной асфиксии кровью, обильной кровопотери, развившихся в результате комбинированной травмы – в виде открытой черепно-мозговой травмы и колото-резаных ран передней поверхности шеи справа, передней поверхности шеи слева, проникающих колото-резаных ран передней поверхности грудной клетки слева, живота справа.
С момента смерти до осмотра трупа на месте происшествия прошло не менее 12 часов, но не более 18 часов.
При исследовании трупа
обнаружены следующие телесные повреждения:

In [5]:
# df["entryDate"] = pd.to_datetime(df["entryDate"])
# df["yearFromEntry"] = df["entryDate"].dt.year

# def get_season(month):
#     if month in [12, 1, 2]:
#         return "Зима"
#     elif month in [3, 4, 5]:
#         return "Весна"
#     elif month in [6, 7, 8]:
#         return "Лето"
#     else:
#         return "Осень"

# df["seasonFromEntry"] = df["entryDate"].dt.month.apply(get_season)

In [6]:
# df

In [8]:
df = df.assign(
    gender_accused="", age_accused="", alcohol="", drugs="", mental_disorder="", prior_convictions="",
    gender_victim="", age_victim="", relationship_between_accused_and_victim="",
    time_of_day="", day_of_week="", season="", year="",
    crime_region="", location="", method="", cruelty="", intentional="", motive="",
    witnesses="", precrime_argument="", prison_term=""
)

df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,,,,,,,,,,
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,,,,,,,,,,
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,,,,,,,,,,
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,,,,,,,,,,
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,,,,,,,,,,

In [7]:
df_sample = df.sample(n=100, random_state=42)
df_sample

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
16281,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,,,,,,,,,,
22629,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,,,,,,,,,,
11306,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,,,,,,,,,,
34974,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
30211,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715,7557,28,2016-05-06,Логадырь Николай Владимирович - ст.105 ч.1 УК РФ,Едакова М.А.,Вынесен ПРИГОВОР,Логадырь Николай Владимирович,ст.105 ч.1,http://shimanovskiy--amr.sudrf.ru/modules.php?...,Дело № 1-82/2016\nП Р И Г О В О Р\nИменем Росс...,...,,,,,,,,,,
23431,92323,56,2019-11-08,Петрова Лариса Алексеевна - ст.105 ч.1 УК РФ,Топильская С.А.,Вынесен ПРИГОВОР,Петрова Лариса Алексеевна,ст.105 ч.1,http://centralny--orb.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
34075,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,...,,,,,,,,,,
19090,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,...,,,,,,,,,,
11821,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,...,,,,,,,,,,

In [16]:
import numpy as np

df_sample1, df_sample2, df_sample3, df_sample4 = np.array_split(df_sample, 4)

c:\Users\Zephyrus\Documents\GitHub\criminal-research\myenv\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [17]:
df_sample1.shape, df_sample2.shape, df_sample3.shape, df_sample4.shape

((25, 34), (25, 34), (25, 34), (25, 34))

In [19]:
df_sample1.to_csv('df_sample1.csv', index=False)
df_sample2.to_csv('df_sample2.csv', index=False)
df_sample3.to_csv('df_sample3.csv', index=False)
df_sample4.to_csv('df_sample4.csv', index=False)

In [ ]:
df_sample1.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
16281,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,,,,,,,,,,
22629,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,,,,,,,,,,
11306,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,,,,,,,,,,
34974,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
30211,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,,,,,,,,,,

In [9]:
df_with_marking = pd.read_csv('df_all_cleaned.csv')
df_with_marking

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,неизвестно,Архангельская область,улица,"руки, нож",жестокое,умышленное,"личная неприязнь, месть",да,была,6.5
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,неизвестно \n,Краснодарский край,улица,ружье,не жестокое,умышленное,"личная неприязнь, ревность",да,была,8.08
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,2015,Московская область,квартира,"камень, электропроводной шнур, подушка",жестокое,умышленное,"деньги, имущество",нет,нет,18
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,неизвестно \n,Московская область,дом,травматический пистолет,не жестокое,умышленное (не убил),личная неприязнь,да,была,3
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,неизвестно \n,неизвестно,улица,"руки, ноги",жестокое,умышленное,личная неприязнь,нет,была,9.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7557,28,2016-05-06,Логадырь Николай Владимирович - ст.105 ч.1 УК РФ,Едакова М.А.,Вынесен ПРИГОВОР,Логадырь Николай Владимирович,ст.105 ч.1,http://shimanovskiy--amr.sudrf.ru/modules.php?...,Дело № 1-82/2016\nП Р И Г О В О Р\nИменем Росс...,...,неизвестно,неизвестно,квартира,молоток,жестокое,умышленное,личная неприязнь,нет,была,6
96,92323,56,2019-11-08,Петрова Лариса Алексеевна - ст.105 ч.1 УК РФ,Топильская С.А.,Вынесен ПРИГОВОР,Петрова Лариса Алексеевна,ст.105 ч.1,http://centralny--orb.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,неизвестно,неизвестно,квартира,нож,не жестокое,умышленное,ревность,нет,была,7.5
97,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,...,2021,Санкт-Петербург,подъезд,нож,не жестокое,умышленное,личная неприязнь,нет,была,4
98,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,...,2017,Псковская область,улица,"лопата, избиение",жестокое,умышленное,личная неприязнь,нет,была,12
99,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,...,2017,неизвестно,квартира,нож,не жестокое,умышленное,личная неприязнь,нет,была,8

In [17]:
for col in df_with_marking.columns:
    print(df_with_marking[col].value_counts())
    print("sdfdv'd'")
    print()

id
57844     1
71745     1
41579     1
116462    1
102232    1
         ..
7557      1
92323     1
122495    1
79171     1
31607     1
Name: count, Length: 98, dtype: int64
sdfdv'd'

region
50    9
29    7
3     5
2     5
59    4
54    4
23    3
52    3
24    3
71    3
66    2
47    2
22    2
40    2
27    2
56    2
42    2
10    2
38    2
60    2
75    2
69    1
14    1
65    1
73    1
61    1
34    1
17    1
5     1
26    1
72    1
55    1
45    1
64    1
25    1
67    1
31    1
11    1
33    1
8     1
16    1
89    1
39    1
53    1
21    1
12    1
63    1
74    1
19    1
28    1
78    1
Name: count, dtype: int64
sdfdv'd'

entryDate
2015-11-20    2
2020-02-28    2
2018-11-29    2
2016-06-29    2
2022-01-31    2
             ..
2016-05-06    1
2019-11-08    1
2022-03-01    1
2018-12-04    1
2017-07-31    1
Name: count, Length: 93, dtype: int64
sdfdv'd'

names
Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч.1 УК РФ                                                                                                                                                                                1
Скворцов Евгений Владимирович - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ, Скородумов Сергей Юрьевич - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ    1
Матвеев Сергей Владимирович - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                            1
Шамов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                            1
                                                                                                                                                                                                                                     ..
Логадырь Николай Владимирович - ст.105 ч.1 УК РФ                                                                                                                                                                                      1
Петрова Лариса Алексеевна - ст.105 ч.1 УК РФ                                                                                                                                                                                          1
ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                        1
Немтинов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Name: count, Length: 98, dtype: int64
sdfdv'd'

judge
Хорошева Екатерина Александровна    2
Вальков Алексей Львович             2
Мядзелец О.А.                       1
Аршинов Алексей Александрович       1
Иванов Д.В.                         1
                                   ..
Едакова М.А.                        1
Топильская С.А.                     1
Гулевич Станислав Анатольевич       1
Сергеева Надежда Николаевна         1
Безрукова Ольга Васильевна          1
Name: count, Length: 96, dtype: int64
sdfdv'd'

decision
Вынесен ПРИГОВОР    98
Name: count, dtype: int64
sdfdv'd'

accused
Газизов Дмитрий Рустамович                                  1
Жмурко Юрий Геннадьевич                                     1
Скворцов Евгений Владимирович, Скородумов Сергей Юрьевич    1
Матвеев Сергей Владимирович                                 1
Шамов Сергей Викторович                                     1
                                                           ..
Логадырь Николай Владимирович                               1
Петрова Лариса Алексеевна                                   1
Тараканов Владимир Владимирович                             1
Немтинов Сергей Викторович                                  1
Баженов Дмитрий Викторович                                  1
Name: count, Length: 98, dtype: int64
sdfdv'd'

articles
ст.105 ч.1                                                                                                                                                                                                                                                                                     62
ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                                         18
ст.167 ч.1, ст.105 ч.1                                                                                                                                                                                                                                                                          1
ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з, ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з                                                                                                                                      1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.2 п.з                                                                                                                                                                                                                                                          1
ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                                              1
ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з, ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з                                                                                                                                                                                                                          1
ст.105 ч.2 п.а                                                                                                                                                                                                                                                                                  1
ст.161 ч.2 п.г, ст.158 ч.2 п.в, ст.158 ч.2 п.в, ст.158 ч.3 п.а, ст.105 ч.1                                                                                                                                                                                                                      1
ст.105 ч.1, ст. 30 ч.3, ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                      1
ст. 30 ч.3, ст.158 ч.1, ст.158 ч.2 п.в, ст.158 ч.3 п.г, ст.105 ч.1                                                                                                                                                                                                                              1
ст.119 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.105 ч.2 п.п.б,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.33 ч.3, ст.105 ч.2 п.п.б,з     1
ст.158 ч.2 п.в, ст.105 ч.1                                                                                                                                                                                                                                                                      1
ст. 30 ч.1, ст.126 ч.2 п.п.а,в,г, ст. 30 ч.1, ст.105 ч.2 п.в                                                                                                                                                                                                                                    1
ст.166 ч.1, ст.158 ч.3 п.а, ст. 30 ч.3, ст.105 ч.2 п.п.а,б,к, ст.105 ч.2 п.п.а,д                                                                                                                                                                                                                1
ст. 30 ч.3, ст.167 ч.2, ст.105 ч.2 п.а                                                                                                                                                                                                                                                          1
ст. 30 ч.3, ст.105 ч.2 п.п.в,и                                                                                                                                                                                                                                                                  1
ст.115 ч.1, ст.158 ч.1, ст.316, ст.158 ч.1, ст.222 ч.1, ст.222.1 ч.1, ст.105 ч.1                                                                                                                                                                                                                1
Name: count, dtype: int64
sdfdv'd'

link_text
http://lomonosovsky--arh.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=50375462&delo_id=1540006&new=0&text_number=1                                                  1
http://novopokrovsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=148629400&delo_id=1540006&new=0&text_number=1                                                1
http://oblsud--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6598636&delo_id=1540006&new=0&text_number=1                                                          1
http://volokolamsk--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=546713735&delo_id=1540006&new=0&text_number=1                                                   1
http://angarsky--irk.sudrf.ru/modules.php?name=sud_delo&srv_num=2&name_op=doc&number=324517332&delo_id=1540006&new=0&text_number=1                                                     1
                                                                                                                                                                                      ..
http://shimanovskiy--amr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=4556070b-6491-48d4-add7-df4552a04a91&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0    1
http://centralny--orb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=96358776&delo_id=1540006&new=0&text_number=1                                                     1
http://nvs--spb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=676164658&delo_id=1540006&new=0&text_number=1                                                          1
http://pskovsky--psk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=43570893&delo_id=1540006&new=0&text_number=1                                                      1
http://igarka--krk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=234170582&delo_id=1540006&new=0&text_number=1                                                       1
Name: count, Length: 97, dtype: int64
sdfdv'd'

preamble
Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Российской Федерации\n<Дата>\nг.Архангельск\nЛомоносовский районный суд г. Архангельска в составе\nпредседательствующего Аршинова А.А.\nпри секретаре Поваровой А.М.\nс участием государственного обвинителя - старшего помощника прокурора г. Архангельска Брагина С.Л.,\nподсудимого Г.Д.Р.,\nзащитника – адвоката Долгановой Е.В.,\nрассмотрев в открытом судебном заседании материалы уголовного дела в отношении\nГ.Д.Р., родившегося <Дата> в ..., гражданина России, в браке не состоящего, детей не имеющего, со средним профессиональным образованием, неработающего, постоянной регистрации на территории Российской Федерации не имеющего, проживающего по адресу: ..., ранее не судимого, содержащегося под стражей с <Дата>,\nобвиняемого в совершении преступления, предусмотренного ч. 1 ст. 105 УК РФ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Российской Федерации\nст. Новопокровская 19 сентября 2019 г.\nНовопокровский районный суд Краснодарского края в составе:\nпредседательствующего Сапега Н.Н.\nс участием заместителя прокурора Новопокровского района Краснодарского края Завальнюк Ю.А.,\nподсудимого Жмурко Ю.Г. и его защитника Андриенко В.Р., представившего удостоверение № 6702 и ордер № 224833,\nпотерпевших Звержановской Н.П. и Алексеевой Н.В.\nпри секретаре Кашкиной Т.А.,\nрассмотрев материалы уголовного дела в отношении Жмурко Юрия Геннадьевича, <данные изъяты>, ранее не судимого, обвиняемого в совершении преступлений, предусмотренных ч. 1 ст. 105, ч. 1 ст. 167 УК РФ,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 декабря 2017 г. г. Красногорск\nМосковской области\nМосковский областной суд с участием присяжных заседателей в составе:\nпредседательствующего судьи Мядзелец О.А.\nс участием прокуроров отдела государственных обвинителей управления прокуратуры Московской области Матюхиной О.К., Щетинина Г.В. и помощника Красногорского городского прокурора Чесноковой М.Н.\nобвиняемого Скородумова С.Ю. и его защитника – адвоката Шварските А.А. предоставившей удостоверение № и ордер.\nобвиняемого Скворцова Е.В. его защитника – адвоката Ярина А.Н. предоставившего удостоверение № и ордер.\nпри секретарях Бабаевой М.Э., Мусиной М.С., Горковенко Е.И.\nрассмотрев в открытом судебном заседании материалы уголовного дела в отношении\nСкородумова Сергея Юрьевича, обвиняемого в совершении преступлений, предусмотренных п.п. «б,в» ч. 4 ст. 162, п.п. «а,ж,з» ч. 2 ст. 105, ч. 1 ст. 325, ч. 2 ст. 325, ч.1 ст. 325 УК РФ,\nСкворцова Евгения Владимировича, обвиняемого в совершении преступлений, предусмотренных п.п. «б,в» ч. 4 ст. 162, п.п. «а,ж,з» ч. 2 ст. 105, ч. 1 ст. 325, ч. 2 ст. 325, ч.1 ст. 325 УК РФ,                                                                                                                                                                                                                                                                                                                                                                               1
Решение по уголовному делу\nИнформация по делу\nдело № 1-225/22\nПРИГОВОР\nИменем Российской Федерации\n13 июля 2022 года                                                                                              г.Волоколамск\nВолоколамский городской суд Московской области в составе\nпредседательствующего судьи                                                               Перминовой Е.А.,\nпри секретаре                                                                                           Чижовой Е.В.,\nс участием государственного обвинителя                                             Черняховской С.М.,\nподсудимого                                                                                             Матвеева С.В.,\nзащитника адвоката                                                                                 Котова А.Г.,\nрассмотрев в открытом судебном заседании уголовное дело по обвинению\nМАТВЕЕВА\nС.В.\nДД.ММ.ГГГГ\nгода рождения, место рождения\n<адрес>\n, русского, гражданина РФ, образование среднее специальное, разведен, иждивенцев не имеет, не военнообязанный, снят с учета по достижении предельного возраста, зарегистрирован и проживает по адресу:\n<адрес>\n, ранее не судим,\nсодержится под стражей по настоящему делу с\nДД.ММ.ГГГГ\n,\nв совершении преступления, предусмотренного ч.3 ст.30 – ч.1 ст.105 УК РФ,                                                                                                                                                  1

In [18]:
df_with_marking

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,неизвестно,Архангельская область,улица,"руки, нож",жестокое,умышленное,"личная неприязнь, месть",да,была,6.5
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,неизвестно \n,Краснодарский край,улица,ружье,не жестокое,умышленное,"личная неприязнь, ревность",да,была,8.08
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,2015,Московская область,квартира,"камень, электропроводной шнур, подушка",жестокое,умышленное,"деньги, имущество",нет,нет,18
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,неизвестно \n,Московская область,дом,травматический пистолет,не жестокое,умышленное (не убил),личная неприязнь,да,была,3
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,неизвестно \n,неизвестно,улица,"руки, ноги",жестокое,умышленное,личная неприязнь,нет,была,9.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,...,2021,Санкт-Петербург,подъезд,нож,не жестокое,умышленное,личная неприязнь,нет,была,4
96,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,...,2017,Псковская область,улица,"лопата, избиение",жестокое,умышленное,личная неприязнь,нет,была,12
97,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,...,2017,неизвестно,квартира,нож,не жестокое,умышленное,личная неприязнь,нет,была,8
98,14640,50,2016-01-11,Меликян Тарон Акопи - ст.105 ч.1 УК РФ,Попова Марина Николаевна,Вынесен ПРИГОВОР,Меликян Тарон Акопи,ст.105 ч.1,http://luberetzy--mo.sudrf.ru/modules.php?name...,Дело №\nПРИГОВОР\nименем Российской Федерации\...,...,неизвестно,неизвестно,квартира,"нож, молоток, избиение, скидывание с высоты",жестокое,умышленное,ревность,да,была,8
99,2220,16,2016-03-01,Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ,Токтаров Денис Витальевич,Вынесен ПРИГОВОР,Мичурин Евгений Андреевич,ст.105 ч.1,http://chistopolsky--tat.sudrf.ru/modules.php?...,копия\nДело №\nП Р И Г О В О Р\nи м е н е м Р ...,...,неизвестно,республика Татарстан,улица,кирпич,жестокое,умышленное,личная неприязнь,да,нет,9.5

In [44]:
for col in df_with_marking.columns:
    if col != 'preamble' and col != 'description' and col != 'sentence':
        print(col)
        print(df_with_marking[col].value_counts())
        print("sdfdv'd'")
        print()

id
id
57844     1
71745     1
41579     1
116462    1
102232    1
         ..
122495    1
79171     1
31607     1
2220      1
14640     1
Name: count, Length: 100, dtype: int64
sdfdv'd'

region
region
50    10
29     7
3      5
2      5
59     4
54     4
23     3
52     3
24     3
71     3
66     2
47     2
16     2
40     2
27     2
56     2
42     2
10     2
38     2
60     2
22     2
75     2
69     1
65     1
73     1
61     1
34     1
17     1
14     1
26     1
72     1
5      1
45     1
64     1
25     1
67     1
31     1
11     1
55     1
8      1
33     1
89     1
39     1
53     1
21     1
12     1
63     1
74     1
19     1
28     1
78     1
Name: count, dtype: int64
sdfdv'd'

entryDate
entryDate
2015-11-20    2
2016-06-29    2
2020-02-28    2
2018-11-29    2
2022-01-31    2
             ..
2022-03-01    1
2018-12-04    1
2017-07-31    1
2016-03-01    1
2016-01-11    1
Name: count, Length: 95, dtype: int64
sdfdv'd'

names
names
Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч.1 УК РФ                                                                                                                                                                                1
Скворцов Евгений Владимирович - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ, Скородумов Сергей Юрьевич - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ    1
Матвеев Сергей Владимирович - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                            1
Шамов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                            1
                                                                                                                                                                                                                                     ..
ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                        1
Немтинов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ                                                                                                                                                                                          1
Меликян Тарон Акопи - ст.105 ч.1 УК РФ                                                                                                                                                                                                1
Name: count, Length: 100, dtype: int64
sdfdv'd'

judge
judge
Хорошева Екатерина Александровна    2
Вальков Алексей Львович             2
Сапега Н.Н.                         1
Мядзелец О.А.                       1
Иванов Д.В.                         1
                                   ..
Гулевич Станислав Анатольевич       1
Сергеева Надежда Николаевна         1
Безрукова Ольга Васильевна          1
Токтаров Денис Витальевич           1
Попова Марина Николаевна            1
Name: count, Length: 98, dtype: int64
sdfdv'd'

decision
decision
Вынесен ПРИГОВОР    100
Name: count, dtype: int64
sdfdv'd'

accused
accused
Газизов Дмитрий Рустамович                                  1
Жмурко Юрий Геннадьевич                                     1
Скворцов Евгений Владимирович, Скородумов Сергей Юрьевич    1
Матвеев Сергей Владимирович                                 1
Шамов Сергей Викторович                                     1
                                                           ..
Тараканов Владимир Владимирович                             1
Немтинов Сергей Викторович                                  1
Баженов Дмитрий Викторович                                  1
Мичурин Евгений Андреевич                                   1
Меликян Тарон Акопи                                         1
Name: count, Length: 100, dtype: int64
sdfdv'd'

articles
articles
ст.105 ч.1                                                                                                                                                                                                                                                                                     64
ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                                         18
ст.167 ч.1, ст.105 ч.1                                                                                                                                                                                                                                                                          1
ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з, ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з                                                                                                                                      1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.2 п.з                                                                                                                                                                                                                                                          1
ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                                              1
ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з, ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з                                                                                                                                                                                                                          1
ст.105 ч.2 п.а                                                                                                                                                                                                                                                                                  1
ст.161 ч.2 п.г, ст.158 ч.2 п.в, ст.158 ч.2 п.в, ст.158 ч.3 п.а, ст.105 ч.1                                                                                                                                                                                                                      1
ст.105 ч.1, ст. 30 ч.3, ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                      1
ст. 30 ч.3, ст.158 ч.1, ст.158 ч.2 п.в, ст.158 ч.3 п.г, ст.105 ч.1                                                                                                                                                                                                                              1
ст.119 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.105 ч.2 п.п.б,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.33 ч.3, ст.105 ч.2 п.п.б,з     1
ст.158 ч.2 п.в, ст.105 ч.1                                                                                                                                                                                                                                                                      1
ст. 30 ч.1, ст.126 ч.2 п.п.а,в,г, ст. 30 ч.1, ст.105 ч.2 п.в                                                                                                                                                                                                                                    1
ст.166 ч.1, ст.158 ч.3 п.а, ст. 30 ч.3, ст.105 ч.2 п.п.а,б,к, ст.105 ч.2 п.п.а,д                                                                                                                                                                                                                1
ст. 30 ч.3, ст.167 ч.2, ст.105 ч.2 п.а                                                                                                                                                                                                                                                          1
ст. 30 ч.3, ст.105 ч.2 п.п.в,и                                                                                                                                                                                                                                                                  1
ст.115 ч.1, ст.158 ч.1, ст.316, ст.158 ч.1, ст.222 ч.1, ст.222.1 ч.1, ст.105 ч.1                                                                                                                                                                                                                1
Name: count, dtype: int64
sdfdv'd'

link_text
link_text
http://lomonosovsky--arh.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=50375462&delo_id=1540006&new=0&text_number=1      1
http://novopokrovsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=148629400&delo_id=1540006&new=0&text_number=1    1
http://oblsud--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6598636&delo_id=1540006&new=0&text_number=1              1
http://volokolamsk--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=546713735&delo_id=1540006&new=0&text_number=1       1
http://angarsky--irk.sudrf.ru/modules.php?name=sud_delo&srv_num=2&name_op=doc&number=324517332&delo_id=1540006&new=0&text_number=1         1
                                                                                                                                          ..
http://nvs--spb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=676164658&delo_id=1540006&new=0&text_number=1              1
http://pskovsky--psk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=43570893&delo_id=1540006&new=0&text_number=1          1
http://igarka--krk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=234170582&delo_id=1540006&new=0&text_number=1           1
http://chistopolsky--tat.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=205265520&delo_id=1540006&new=0&text_number=1     1
http://luberetzy--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=64696535&delo_id=1540006&new=0&text_number=1          1
Name: count, Length: 99, dtype: int64
sdfdv'd'

gender_accused
gender_accused
мужчина             80
женщина             17
мужчина, мужчина     3
Name: count, dtype: int64
sdfdv'd'

age_accused
age_accused
неизвестно                   64
неизвестно\n                 23
незизвестно                   7
неизвестно, неизвестно \n     2
45                            1
неизвестно,неизвестно         1
62                            1
Name: count, dtype: int64
sdfdv'd'

alcohol
alcohol
да          78
нет         19
нет, нет     2
да, да       1
Name: count, dtype: int64
sdfdv'd'

drugs
drugs
нет           89
неизвестно     6
нет, нет       3
да             2
Name: count, dtype: int64
sdfdv'd'

mental_disorder
mental_disorder
нет         89
да           8
нет, нет     3
Name: count, dtype: int64
sdfdv'd'

prior_convictions
prior_convictions
нет           76
да            20
нет, нет       2
нет, да        1
неизвестно     1
Name: count, dtype: int64
sdfdv'd'

gender_victim
gender_victim
мужчина             71
женщина             23
женщина, женщина     2
мужчина, мужчина     2
женщина, мужчина     1
мужчина, женщина     1
Name: count, dtype: int64
sdfdv'd'

age_victim
age_victim
неизвестно                93
неизвестно, неизвестно     4
неизестно                  1
1990                       1
меньше 14                  1
Name: count, dtype: int64
sdfdv'd'

relationship_between_accused_and_victim
relationship_between_accused_and_victim
знакомый                  45
сожитель                  17
супруг                     7
незнакомец                 6
друг                       4
родственник                3
коллега                    3
интимные отношения         2
брат                       2
зять                       2
сосед                      2
неизвестно                 1
неизвестно, неизвестно     1
мать сожительницы          1
знакомый, знакомый         1
работник                   1
сын, знакомый              1
бывший супруг              1
Name: count, dtype: int64
sdfdv'd'

time_of_day
time_of_day
вечер          33
ночь           24
день           13
утро           12
неизвестно      6
ночь-утро       4
утро-день       2
день-вечер      2
вечер-ночь      1
вечер, ночь     1
ночь, утро      1
утро, день      1
Name: count, dtype: int64
sdfdv'd'

day_of_week
day_of_week
неизвестно             69
понедельник             6
четверг                 5
среда                   5
суббота                 5
вторник                 4
воскресенье             3
пятница                 2
понедельник-вторник     1
Name: count, dtype: int64
sdfdv'd'

season
season
неизвестно    53
весна         15
лето          13
осень         11
зима           8
Name: count, dtype: int64
sdfdv'd'

year
year
неизвестно        34
неизвестно \n     11
2016               9
2019               7
2017               6
2021               6
2020               6
2018               5
2015               4
2023               3
2016.0             2
неизвестно         2
 неизвестно \n     1
неизвестно\n       1
2021.0             1
2017.0             1
2019.0             1
Name: count, dtype: int64
sdfdv'd'

crime_region
crime_region
неизвестно                                             63
Архангельская областьая областьая областьая область     3
Новосибирская область                                   2
Московская область                                      2
Республика Башкортостан                                 2
Ямало-Ненецкий автономный округ                         2
Архангельская область                                   1
Краснодарский край                                      1
Республика Тыва                                         1
Ленинградская область                                   1
Владивосток                                             1
Республика Башкоростан                                  1
Республика Карелия                                      1
Сахалинская о́бласть                                    1
Ульяновская область                                     1
Тверская область                                        1
Курганская область                                      1
Новосибирск                                             1
Саратовская область                                     1
Республика Дагестан                                     1
Тульская область                                        1
Свердловская область                                    1
Хабаровский край                                        1
Нижний Новгород                                         1
Смоленская область                                      1
Республика Татарстан                                    1
Новгородская область                                    1
Чувашская Республика                                    1
Республика Хакасия                                      1
Санкт-Петербург                                         1
Псковская область                                       1
республика Татарстан                                    1
Name: count, dtype: int64
sdfdv'd'

location
location
квартира               56
улица                  16
дом                    13
общежитие               3
подъезд                 2
такси, берег озера      1
дача                    1
гараж                   1
лес                     1
безлюдная местность     1
хостел                  1
двор                    1
лестничная площадка     1
чердак                  1
база отдыха             1
Name: count, dtype: int64
sdfdv'd'

method
method
нож                                            55
избиение                                        6
удушение                                        5
молоток                                         4
топор                                           4
огнестрел                                       3
руки, нож                                       2
травматический пистолет                         1
удар предметом                                  1
камень, электропроводной шнур, подушка          1
ружье                                           1
руки, ноги                                      1
кирпич, руки                                    1
полено                                          1
огнестрельное оружие                            1
клинок                                          1
избиение, удушение                              1
избиение, молоток                               1
нож, удушение                                   1
нож, избиение                                   1
удушение, избиение                              1
молоток, топор                                  1
избиение, нож                                   1
избиение, нож, вилка                            1
повешение                                       1
лопата, избиение                                1
кирпич                                          1
нож, молоток, избиение, скидывание с высоты     1
Name: count, dtype: int64
sdfdv'd'

cruelty
cruelty
не жестокое    53
жестокое       47
Name: count, dtype: int64
sdfdv'd'

intentional
intentional
умышленное              93
умышленное (не убил)     7
Name: count, dtype: int64
sdfdv'd'

motive
motive
личная неприязнь                            54
конфликт                                    19
ревность                                     7
личная неприязнь, ревность                   2
месть, конфликт                              2
наемное убийство                             1
деньги, имущество                            1
личная неприязнь, месть                      1
имущество                                    1
личная неприязнь, кража                      1
конфликт, личная неприязнь                   1
ревность, личная неприязнь                   1

In [19]:
def clean_value(value, column):
    if isinstance(value, list):
        return value
    if pd.isna(value):
        print(value, column)
        return "неизвестно"
    else:
        value = value.replace("\n", "")
        if column != "crime_region":
            value = value.replace("-", ",")
        value = value.replace("о́", "о")
        value = value.replace("конфликт, личная неприязнь", "личная неприязнь")
        value = value.replace("конфликт", "личная неприязнь")
        value = value.replace("незизвестно", "неизвестно")
        value = value.replace("неизестно", "неизвестно")
        value = value.replace("умышленное (не убил)", "умышленное")

        if "неизвестно" in value:
            value = value.strip()

        if column in ["prior_convictions", "drugs"]:
            if value == "неизвестно":
                value = "нет"
        if column in ["relationship_between_accused_and_victim", "time_of_day", "day_of_week", "season", "year", "crime_region", "motive"]:
            if value == "нет":
                value = "неизвестно"


        if value == "1990":
            value = "27"

        if value == "республика Татарстан":
            value = "Республика Татарстан"

        if "," in value:
            values = [v.strip() for v in value.split(",")]
            return values
        return value

for col in ['gender_accused', 'age_accused', 'alcohol', 'drugs', 'mental_disorder', 'prior_convictions', 'gender_victim', 'age_victim', 'relationship_between_accused_and_victim', 'time_of_day', 'day_of_week', 'season', 'year', 'crime_region', 'location', 'method', 'cruelty', 'motive', 'witnesses', 'precrime_argument', 'prison_term', 'intentional']:
    df_with_marking[col] = df_with_marking[col].apply(lambda x: clean_value(x, col))

nan age_accused

In [20]:
def clean_value(value, column):
    if column == 'prison_term':
        if value != "неизвестно":
            return float(value)
    if column == "year":
        if value != "неизвестно":
            return int(float(value))
for col in ['year', 'prison_term']:
    df_with_marking[col] = df_with_marking[col].apply(lambda x: clean_value(x, col))

In [21]:
for col in df_with_marking.columns:
    if col != 'preamble' and col != 'description' and col != 'sentence':
        print(df_with_marking[col].value_counts())
        print("sdfdv'd'")
        print()

id
57844     1
71745     1
41579     1
116462    1
102232    1
         ..
122495    1
79171     1
31607     1
14640     1
2220      1
Name: count, Length: 100, dtype: int64
sdfdv'd'

region
50    10
29     7
3      5
2      5
59     4
54     4
23     3
52     3
24     3
71     3
66     2
47     2
16     2
40     2
27     2
56     2
42     2
10     2
38     2
60     2
22     2
75     2
69     1
65     1
73     1
61     1
34     1
17     1
14     1
26     1
72     1
5      1
45     1
64     1
25     1
67     1
31     1
11     1
55     1
8      1
33     1
89     1
39     1
53     1
21     1
12     1
63     1
74     1
19     1
28     1
78     1
Name: count, dtype: int64
sdfdv'd'

entryDate
2015-11-20    2
2016-06-29    2
2020-02-28    2
2018-11-29    2
2022-01-31    2
             ..
2022-03-01    1
2018-12-04    1
2017-07-31    1
2016-01-11    1
2016-03-01    1
Name: count, Length: 95, dtype: int64
sdfdv'd'

names
Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч.1 УК РФ                                                                                                                                                                                1
Скворцов Евгений Владимирович - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ, Скородумов Сергей Юрьевич - ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з УК РФ    1
Матвеев Сергей Владимирович - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                            1
Шамов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                            1
                                                                                                                                                                                                                                     ..
ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ст.105 ч.1 УК РФ                                                                                                                                                                        1
Немтинов Сергей Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ                                                                                                                                                                                         1
Меликян Тарон Акопи - ст.105 ч.1 УК РФ                                                                                                                                                                                                1
Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ                                                                                                                                                                                          1
Name: count, Length: 100, dtype: int64
sdfdv'd'

judge
Хорошева Екатерина Александровна    2
Вальков Алексей Львович             2
Сапега Н.Н.                         1
Мядзелец О.А.                       1
Иванов Д.В.                         1
                                   ..
Гулевич Станислав Анатольевич       1
Сергеева Надежда Николаевна         1
Безрукова Ольга Васильевна          1
Попова Марина Николаевна            1
Токтаров Денис Витальевич           1
Name: count, Length: 98, dtype: int64
sdfdv'd'

decision
Вынесен ПРИГОВОР    100
Name: count, dtype: int64
sdfdv'd'

accused
Газизов Дмитрий Рустамович                                  1
Жмурко Юрий Геннадьевич                                     1
Скворцов Евгений Владимирович, Скородумов Сергей Юрьевич    1
Матвеев Сергей Владимирович                                 1
Шамов Сергей Викторович                                     1
                                                           ..
Тараканов Владимир Владимирович                             1
Немтинов Сергей Викторович                                  1
Баженов Дмитрий Викторович                                  1
Меликян Тарон Акопи                                         1
Мичурин Евгений Андреевич                                   1
Name: count, Length: 100, dtype: int64
sdfdv'd'

articles
ст.105 ч.1                                                                                                                                                                                                                                                                                     64
ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                                         18
ст.167 ч.1, ст.105 ч.1                                                                                                                                                                                                                                                                          1
ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з, ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4 п.п.б,в, ст.105 ч.2 п.п.а,ж,з                                                                                                                                      1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.2 п.з                                                                                                                                                                                                                                                          1
ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                                              1
ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з, ст.162 ч.4 п.в, ст.105 ч.2 п.п.ж,з                                                                                                                                                                                                                          1
ст.105 ч.2 п.а                                                                                                                                                                                                                                                                                  1
ст.161 ч.2 п.г, ст.158 ч.2 п.в, ст.158 ч.2 п.в, ст.158 ч.3 п.а, ст.105 ч.1                                                                                                                                                                                                                      1
ст.105 ч.1, ст. 30 ч.3, ст.105 ч.2 п.п.а,к                                                                                                                                                                                                                                                      1
ст. 30 ч.3, ст.158 ч.1, ст.158 ч.2 п.в, ст.158 ч.3 п.г, ст.105 ч.1                                                                                                                                                                                                                              1
ст.119 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.1, ст. 30 ч.3, ст.105 ч.1                                                                                                                                                                                                                                                              1
ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.105 ч.2 п.п.б,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.222 ч.2, ст.161 ч.2 п.п.а,г, ст.163 ч.2 п.п.а,в,г, ст.126 ч.2 п.п.а,в,г,з, ст.33 ч.3, ст.105 ч.2 п.п.б,з     1
ст.158 ч.2 п.в, ст.105 ч.1                                                                                                                                                                                                                                                                      1
ст. 30 ч.1, ст.126 ч.2 п.п.а,в,г, ст. 30 ч.1, ст.105 ч.2 п.в                                                                                                                                                                                                                                    1
ст.166 ч.1, ст.158 ч.3 п.а, ст. 30 ч.3, ст.105 ч.2 п.п.а,б,к, ст.105 ч.2 п.п.а,д                                                                                                                                                                                                                1
ст. 30 ч.3, ст.167 ч.2, ст.105 ч.2 п.а                                                                                                                                                                                                                                                          1
ст. 30 ч.3, ст.105 ч.2 п.п.в,и                                                                                                                                                                                                                                                                  1
ст.115 ч.1, ст.158 ч.1, ст.316, ст.158 ч.1, ст.222 ч.1, ст.222.1 ч.1, ст.105 ч.1                                                                                                                                                                                                                1
Name: count, dtype: int64
sdfdv'd'

link_text
http://lomonosovsky--arh.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=50375462&delo_id=1540006&new=0&text_number=1      1
http://novopokrovsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=148629400&delo_id=1540006&new=0&text_number=1    1
http://oblsud--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6598636&delo_id=1540006&new=0&text_number=1              1
http://volokolamsk--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=546713735&delo_id=1540006&new=0&text_number=1       1
http://angarsky--irk.sudrf.ru/modules.php?name=sud_delo&srv_num=2&name_op=doc&number=324517332&delo_id=1540006&new=0&text_number=1         1
                                                                                                                                          ..
http://nvs--spb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=676164658&delo_id=1540006&new=0&text_number=1              1
http://pskovsky--psk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=43570893&delo_id=1540006&new=0&text_number=1          1
http://igarka--krk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=234170582&delo_id=1540006&new=0&text_number=1           1
http://luberetzy--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=64696535&delo_id=1540006&new=0&text_number=1          1
http://chistopolsky--tat.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=205265520&delo_id=1540006&new=0&text_number=1     1
Name: count, Length: 99, dtype: int64
sdfdv'd'

gender_accused
мужчина               80
женщина               17
[мужчина, мужчина]     3
Name: count, dtype: int64
sdfdv'd'

age_accused
неизвестно                  95
[неизвестно, неизвестно]     3
45                           1
62                           1
Name: count, dtype: int64
sdfdv'd'

alcohol
да            78
нет           19
[нет, нет]     2
[да, да]       1
Name: count, dtype: int64
sdfdv'd'

drugs
нет           95
[нет, нет]     3
да             2
Name: count, dtype: int64
sdfdv'd'

mental_disorder
нет           89
да             8
[нет, нет]     3
Name: count, dtype: int64
sdfdv'd'

prior_convictions
нет           77
да            20
[нет, нет]     2
[нет, да]      1
Name: count, dtype: int64
sdfdv'd'

gender_victim
мужчина               71
женщина               23
[женщина, женщина]     2
[мужчина, мужчина]     2
[женщина, мужчина]     1
[мужчина, женщина]     1
Name: count, dtype: int64
sdfdv'd'

age_victim
неизвестно                  94
[неизвестно, неизвестно]     4
27                           1
меньше 14                    1
Name: count, dtype: int64
sdfdv'd'

relationship_between_accused_and_victim
знакомый                    45
сожитель                    17
супруг                       7
незнакомец                   6
друг                         4
родственник                  3
коллега                      3
интимные отношения           2
брат                         2
зять                         2
сосед                        2
неизвестно                   1
[неизвестно, неизвестно]     1
мать сожительницы            1
[знакомый, знакомый]         1
работник                     1
[сын, знакомый]              1
бывший супруг                1
Name: count, dtype: int64
sdfdv'd'

time_of_day
вечер            33
ночь             24
день             13
утро             12
неизвестно        6
[ночь, утро]      5
[утро, день]      3
[вечер, ночь]     2
[день, вечер]     2
Name: count, dtype: int64
sdfdv'd'

day_of_week
неизвестно                69
понедельник                6
четверг                    5
среда                      5
суббота                    5
вторник                    4
воскресенье                3
пятница                    2
[понедельник, вторник]     1
Name: count, dtype: int64
sdfdv'd'

season
неизвестно    53
весна         15
лето          13
осень         11
зима           8
Name: count, dtype: int64
sdfdv'd'

year
2016.0    11
2019.0     8
2017.0     7
2021.0     7
2020.0     6
2018.0     5
2015.0     4
2023.0     3
Name: count, dtype: int64
sdfdv'd'

crime_region
неизвестно                                             63
Архангельская областьая областьая областьая область     3
Новосибирская область                                   2
Республика Татарстан                                    2
Ямало-Ненецкий автономный округ                         2
Республика Башкортостан                                 2
Московская область                                      2
Тверская область                                        1
Республика Тыва                                         1
Ленинградская область                                   1
Владивосток                                             1
Краснодарский край                                      1
Архангельская область                                   1
Сахалинская область                                     1
Ульяновская область                                     1
Новосибирск                                             1
Саратовская область                                     1
Республика Карелия                                      1
Республика Башкоростан                                  1
Свердловская область                                    1
Нижний Новгород                                         1
Курганская область                                      1
Республика Дагестан                                     1
Хабаровский край                                        1
Тульская область                                        1
Смоленская область                                      1
Новгородская область                                    1
Чувашская Республика                                    1
Республика Хакасия                                      1
Санкт-Петербург                                         1
Псковская область                                       1
Name: count, dtype: int64
sdfdv'd'

location
квартира                56
улица                   16
дом                     13
общежитие                3
подъезд                  2
[такси, берег озера]     1
дача                     1
гараж                    1
лес                      1
безлюдная местность      1
хостел                   1
двор                     1
лестничная площадка      1
чердак                   1
база отдыха              1
Name: count, dtype: int64
sdfdv'd'

method
нож                                              55
избиение                                          6
удушение                                          5
молоток                                           4
топор                                             4
огнестрел                                         3
[руки, нож]                                       2
травматический пистолет                           1
удар предметом                                    1
[камень, электропроводной шнур, подушка]          1
ружье                                             1
[руки, ноги]                                      1
[кирпич, руки]                                    1
полено                                            1
огнестрельное оружие                              1
клинок                                            1
[избиение, удушение]                              1
[избиение, молоток]                               1
[нож, удушение]                                   1
[нож, избиение]                                   1
[удушение, избиение]                              1
[молоток, топор]                                  1
[избиение, нож]                                   1
[избиение, нож, вилка]                            1
повешение                                         1
[лопата, избиение]                                1
[нож, молоток, избиение, скидывание с высоты]     1
кирпич                                            1
Name: count, dtype: int64
sdfdv'd'

cruelty
не жестокое    53
жестокое       47
Name: count, dtype: int64
sdfdv'd'

intentional
умышленное    100
Name: count, dtype: int64
sdfdv'd'

motive
личная неприязнь                              74
ревность                                       7
[личная неприязнь, ревность]                   3
[месть, личная неприязнь]                      2
[личная неприязнь, месть]                      1
наемное убийство                               1
[личная неприязнь, скрыть первое убийство]     1
имущество                                      1
[личная неприязнь, кража]                      1
[деньги, имущество]                            1
[ревность, личная неприязнь]                   1
[месть, ограбление, наемное убийство]          1
[личная неприязнь, самооборона]                1
месть                                          1
[личная неприязнь, ограбление]                 1
самооборона                                    1
неизвестно                                     1
хулиганство                                    1
Name: count, dtype: int64
sdfdv'd'

witnesses
нет    65
да     35
Name: count, dtype: int64
sdfdv'd'

precrime_argument
была    92
нет      8
Name: count, dtype: int64
sdfdv'd'

prison_term
8.00     12
9.00     12
7.00     12
9.50      7
7.50      6
6.50      5
6.00      4
8.50      3
20.00     3
4.00      2
5.00      2
11.00     2
18.00     2
12.00     2

In [22]:
df_with_marking = df_with_marking.drop(columns=["preamble", "description", "sentence"], errors="ignore")
df_with_marking = df_with_marking.merge(df[["id", "preamble", "description", "sentence"]], on="id", how="left")
df_with_marking

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term,preamble,description,sentence
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,"[руки, нож]",жестокое,умышленное,"[личная неприязнь, месть]",да,была,6.50,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,ружье,не жестокое,умышленное,"[личная неприязнь, ревность]",да,была,8.08,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"[мужчина, мужчина]",...,"[камень, электропроводной шнур, подушка]",жестокое,умышленное,"[деньги, имущество]",нет,нет,18.00,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,травматический пистолет,не жестокое,умышленное,личная неприязнь,да,была,3.00,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,"[руки, ноги]",жестокое,умышленное,личная неприязнь,нет,была,9.25,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,4.00,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,У С Т А Н О В И Л :\nПодсудимый Тараканов В.В....,П Р И Г О В О Р И Л :\nПризнать Тараканова Вла...
96,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,мужчина,...,"[лопата, избиение]",жестокое,умышленное,личная неприязнь,нет,была,12.00,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,"УСТАНОВИЛ:\nНемтинов С.В. совершил убийство, т...",ПРИГОВОРИЛ:\nПризнать Немтинова Сергея Викторо...
97,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,8.00,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,У С Т А Н О В И Л:\nБаженов Д.В. совершил убий...,П Р И Г О В О Р И Л:\nБаженова Д.В. признать в...
98,14640,50,2016-01-11,Меликян Тарон Акопи - ст.105 ч.1 УК РФ,Попова Марина Николаевна,Вынесен ПРИГОВОР,Меликян Тарон Акопи,ст.105 ч.1,http://luberetzy--mo.sudrf.ru/modules.php?name...,мужчина,...,"[нож, молоток, избиение, скидывание с высоты]",жестокое,умышленное,ревность,да,была,8.00,Дело №\nПРИГОВОР\nименем Российской Федерации\...,"УСТАНОВИЛ:\nМеликян Т.А. совершил убийство, то...",ПРИГОВОРИЛ:\nМеликяна Т. А. признать виновным ...
99,2220,16,2016-03-01,Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ,Токтаров Денис Витальевич,Вынесен ПРИГОВОР,Мичурин Евгений Андреевич,ст.105 ч.1,http://chistopolsky--tat.sudrf.ru/modules.php?...,мужчина,...,кирпич,жестокое,умышленное,личная неприязнь,да,нет,9.50,копия\nДело №\nП Р И Г О В О Р\nи м е н е м Р ...,Установил:\nДД.ММ.ГГГГ в период времени с 10 ч...,"Приговорил:\nМичурин Е.А, признать виновным в ..."

In [23]:
for index, row in df_with_marking.iterrows():
    print(f"Строка {index}:")
    for col in ["accused", "prison_term", "preamble", "description", "sentence"]:
        print(f"{col}: {row[col]}")
    print("-" * 50)

Строка 0:
accused: Газизов Дмитрий Рустамович
prison_term: 6.5
preamble: Дело <№> (29RS0<№>-58)
ПРИГОВОР
именем Российской Федерации
<Дата>
г.Архангельск
Ломоносовский районный суд г. Архангельска в составе
председательствующего Аршинова А.А.
при секретаре Поваровой А.М.
с участием государственного обвинителя - старшего помощника прокурора г. Архангельска Брагина С.Л.,
подсудимого Г.Д.Р.,
защитника – адвоката Долгановой Е.В.,
рассмотрев в открытом судебном заседании материалы уголовного дела в отношении
Г.Д.Р., родившегося <Дата> в ..., гражданина России, в браке не состоящего, детей не имеющего, со средним профессиональным образованием, неработающего, постоянной регистрации на территории Российской Федерации не имеющего, проживающего по адресу: ..., ранее не судимого, содержащегося под стражей с <Дата>,
обвиняемого в совершении преступления, предусмотренного ч. 1 ст. 105 УК РФ,

description: УСТАНОВИЛ:
Г.Д.Р. совершил убийство при следующих обстоятельствах.
В период с <Дата> до <Дата> Г.Д.Р., находясь в состоянии алкогольного опьянения у ..., в ходе конфликта с А.В.М.о., возникшего на почве личных неприязненных отношений из-за ранее высказанных А.В.М.о. угроз и оскорблений в адрес в Г.Д.Р., с целью убийства А.В.М.о. умышленно нанес ему руками не менее двух ударов по голове, после чего с той же целью умышленно нанес ему один удар клинком ножа в левую боковую поверхность груди, один удар в левую подмышечную область и два удара в область левого бедра, причинив ему телесные повреждения:
-кровоподтек и ссадину в области спинки носа, ссадину в центральных отделах верхней губы, которые как в отдельности, так и в совокупности расцениваются как повреждения, не причинившие вред здоровью,
-колото-резаное ранение мягких тканей передней поверхности левого бедра в верхней трети, колото-резаное ранение мягких тканей наружной боковой поверхности левого бедра в средней трети, которые как в отдельности, так и в совокупности расцениваются как легкий вред здоровью по признаку кратковременного расстройства здоровья продолжительностью до трех недель,
-колото-резаное ранение левой боковой поверхности груди в средней трети, проникающее в левую плевральную полость, с повреждениями четвертого левого ребра, верхней и нижней долей левого легкого, кровоизлиянием в левую плевральную полость (700 мл.), колото-резаное ранение в центральных отделах левой подмышечной области (в левой подмышечной ямке) с повреждением левой подмышечной артерии, которые закономерно осложнились массивной кровопотерей, в совокупности по признаку опасности для жизни расцениваются как тяжкий вред здоровью и состоят в прямой причинно-следственной связи со смертью А.В.М.о., наступившей на месте происшествия спустя непродолжительное время после причинения ему указанных телесных повреждений.
В судебном заседании подсудимый Г.Д.Р. вину в инкриминируемом ему преступлении признал частично и подтвердил, что действительно во время распития спиртных напитков с А.В.М.о., Р.М.А., М.А.С. и Б.И.В. у него возник конфликт с А.В.М.о., который стал высказывать в его адрес оскорбления и угрозы убийством, демонстрируя при этом нож, однако в данный конфликт вмешался Р.М.А., после чего он ушел домой. Придя домой, полагая, что А.В.М.о. может прийти к нему домой и убить его, он вооружился кухонным ножом и решил переговорить с А. по поводу произошедшего, для чего позвонил Редько и попросил А. спуститься на улицу. Находясь на улице, А. первым попытался нанести ему удар ножом, обороняясь от которого, он также достал нож и нанес ему несколько ударов по телу А., от которых он впоследствии скончался. Настаивает, что удары он наносил А. в состоянии необходимой обороны и умысла на его убийство у него не было.
Аналогичной позиции Г.Д.Р. придерживался и на стадии предварительного следствия при его допросах в качестве подозреваемого и обвиняемого, подтверждая свои показания на месте случившегося, о чем также добровольно сообщил в правоохранительные органы в своей явке с повинной (т.1 л.д. 126-128, 133-139, 141-154, 182-185).
Несмотря на занятую подсудимым позицию, его вина в совершении инкриминируемого ему преступления полностью подтверждается совокупностью представленных стороной обвинения доказательств, исследованных и проверенных судом.
Допрошенный в судебном заседании и на стадии предварительного следствия свидетель Р.М.А., подтвердил, что в ходе распития спиртных напитков с между Г.Д.Р. и А.В.М.о. возник конфликт, в ходе которого А.В.М.о. высказал в адрес Г.Д.Р. оскорбления в грубой нецензурной форме, выгонял того из квартиры, высказывал угрозы применения насилия, а также демонстрировал ему нож, однако в результате его вмешательства данный конфликт удалось уладить, после чего Г.Д.Р. и М.А.С. покинули квартиру. Спустя некоторое время ему позвонил Г.Д.Р. и стал высказывать в адрес А.В.М.о. оскорбления в грубой неприличной форме, а также потребовал, чтобы А. вышел на улицу разобраться с ним, на что А.В.М.о., выхватив у него телефон, согласился спустился на улицу, а он остался дома. Через некоторое время с балкона он увидел, что А.В.М.о. лежит на земле возле черного автомобиля без признаков жизни (т.1 л.д. 51-55, 56-58, 59-61).
Распивавшие с Г.Д.Р. и А.В.М.о. спиртные напитки М.А.С. и Б.И.В. в судебном заседании и на стадии предварительного следствия описали развитие событий аналогичным образом (т.1 л.д. 63-66, 68-70, 91-94, 95-97).
Показания вышеуказанных свидетелей и подсудимого полностью согласуются и с показаниями прибывших по вызову сотрудников полиции Г.Е.Ф. и Л.Д.С., а также врача скорой медицинской помощи Г.А.М., которые подтвердили, что по прибытию около <Дата> к ... ими был обнаружен труп А.В.М.о. с колото-резанной раной грудной клетки слева (т.1 л.д. 99-104, 105-110, 111-114).
Помимо этого вина подсудимого также подтверждаются и письменными доказательствами, исследованными в судебном заседании в соответствии со ст. 285 УПК РФ.
Так, в ходе осмотра участка местности у ... был обнаружен труп А.В.М.о. с признаками насильственной смерти, нож-бабочка, принадлежащий погибшему, следы крови и мобильные телефоны (т.1 л.д.13-32).
Согласно заключению эксперта <№> от <Дата> при осмотре трупа А.В.М.о. у него были обнаружены следующие телесные повреждения:
-кровоподтек и ссадина в области спинки носа, ссадина в центральных отделах верхней губы, которые являются прижизненными и образовались от не менее, чем двух травмирующих воздействий твердого тупого предмета незадолго до наступления смерти А.В.М.о., при этом как в отдельности, так и в совокупности у живых лиц расцениваются как повреждения, не причинившие вреда здоровью,
-колото-резаное ранение мягких тканей передней поверхности левого бедра в верхней трети, колото-резаное ранение мягких тканей наружной боковой поверхности левого бедра в средней трети, которые являются прижизненными и образовались незадолго до наступления смерти А. в результате воздействия плоского клинкового колюще-режущего орудия и по признаку кратковременного расстройства здоровья продолжительностью до трех недель у живых лиц как в отдельности, так и в совокупности расцениваются как легкий вред здоровью,
-колото-резаное ранение левой боковой поверхности груди в средней трети, проникающее в левую плевральную полость, с повреждениями четвертого левого ребра, верхней и нижней долей левого легкого, кровоизлиянием в левую плевральную полость (700 мл.), колото-резаное ранение в центральных отделах левой подмышечной области (в левой подмышечной ямке) с повреждением левой подмышечной артерии, которые закономерно осложнились массивной кровопотерей, являются прижизненными и образовались в результате воздействия плоского клинкового колюще-режущего орудия и в совокупности по признаку опасности для жизни расцениваются как тяжкий вред здоровью и состоят в прямой причинно-следственной связи со смертью А.В.М.о. (т.2 л.д. 5-27)
При этом согласно заключению эксперта от <Дата> года <№> колото-резанные раны А.В.М.о. были причинены ножом хозяйственно-бытового назначения, выданным на стадии предварительного расследования свидетелем Ф.А.В., при осмотре которого также были обнаружены следы крови погибшего (т.1 л.д. 81-90, т.2 л.д. 43-50, 56-59).
При осмотре одежды А.В.М.о. были обнаружены сквозные повреждения в области груди слева со следами вещества, похожего на кровь, а при осмотре обнаруженных при нем мобильных телефонов были установлены факты осуществления звонков погибшего и Г.Д.Р. незадолго до случившегося (т.1 л.д. 129-135, 212-223, т.2 л.д. 78-82, 91-112).
Изъятые с места происшествия одежда погибшего и мобильные телефоны, а также нож, выданный свидетелем Ф.А.В., были осмотрены на стадии предварительного следствия и признаны по делу в качестве вещественных доказательств (т.2 л.д. 89, 113, 136).
Как следует из заключения комплексной амбулаторной психолого-психиатрической экспертизы от <Дата>, не смотря на произошедший конфликт, Г.Д.Р. в момент совершения данного преступления не находился в состоянии физиологического аффекта или ином эмоциональном состоянии, оказывающих существенное влияние на его сознание или поведение (т.2 л.д. 73-76).
Анализируя вышеизложенные доказательства, суд находит вину подсудимого в убийстве А.В.М.о. полностью доказанной.
Сам факт нанесения Г.Д.Р. ударов ножом по телу и бедру А.Д.Р. при указанных в обвинении обстоятельствах подсудимым не оспаривается и подтверждается его собственными признательными показаниями, данными в судебном заседании и на стадии предварительного следствия, показаниями многочисленных свидетелей, протоколами проведенных следственных действий и заключениями экспертных исследований и сомнений у суда не вызывает.
Указанные доказательства являются полными, подробными, противоречий не имеют, взаимно дополняют друг друга и согласуются между собой, а поскольку они получены с соблюдением требований уголовно-процессуального закона и относятся к существу предъявленного Г.Д.Р. обвинения, суд признает их относимыми, допустимыми и достоверными, а в совокупности достаточными для разрешения дела.
Как достоверно установлено в судебном заседании, во время распития спиртных напитков у Г.Д.Р. произошел конфликт с А.В.М.о., который стал высказывать в его адрес оскорбления в грубой неприличной форме и угрозы убийством, демонстрируя при этом нож, в который вмешался Редько, после чего конфликт был улажен, а Г.Д.Р. ушел домой, где, желая отомстить А. за высказанные в его адрес угрозы и оскорбления, вооружился кухонным ножом и посредством мобильной связи потребовал от А. выйти на улицу, где между ними вновь разгорелся конфликт, в ходе которого Г.Д.Р. умышленно нанес А. удары руками по лицу, а также один удар ножом в левую боковую поверхность груди, один удар ножом в левую подмышечную область, а также два удара ножом в область левого бедра, что со всей очевидностью указывает на умысел подсудимого, направленный на лишение жизни А.В.М.о.
Об этом же свидетельствует и выбор им в качестве орудия преступления ножа, обладающего повышенными травмирующими характеристиками, которым он заранее вооружился и нанес им потерпевшему целенаправленные удары в область груди слева, где располагаются жизненно важные органы, которых было достаточно для наступления смерти потерпевшего, что не оспаривается и самим подсудимым.
Согласно заключению эксперта полученные А.В.М.о. в результате нанесенных Г.Д.Р. ударов ножом в левую боковую поверхность груди и левую подмышечную область ранения по квалифицирующему признаку опасности вреда здоровью оцениваются как тяжкий вред здоровью человека и состоят в прямой причинно-следственной связи с наступлением смерти А.В.М.о. на месте происшествия.
Результаты проведенных по делу экспертиз, в том числе по установлению тяжести вреда здоровью потерпевшего, ни подсудимым, ни его защитником не оспариваются. Заключения экспертиз соответствует требованиям ст. 204 УПК РФ, имеет четкие, мотивированные, научно обоснованные ответы на поставленные вопросы и объективно подтверждается обстоятельствами дела.
Суд отвергает подсудимого о том, что он находился в состоянии необходимой обороны, поскольку конфликт, произошедший между ним и А. в квартире Р., был улажен в результате вмешательства Р., после чего Г.Д.Р. ушел домой, где его жизни и здоровью ничего не угрожало, однако он сам, предварительно вооружившись ножом, инициировал встречу с А., в ходе которой нанес ему многочисленные удары ножом, от которых последний скончался.
По смыслу закона, не признается находившимся в состоянии необходимой обороны лицо, которое спровоцировало нападение, чтобы использовать его как повод для совершения противоправных действий.
Таким образом, обстоятельств, указывающих на нахождение Г.Д.Р. в состоянии необходимой обороны, равно как и на превышение ее допустимых пределов, а также физиологического аффекта по делу не установлено, в связи с чем суд приходит к выводу, что данное преступление совершено Г.Д.Р. на почве личных неприязненных отношений из-за ранее высказанных А. угроз и оскорблений в адрес подсудимого.
При таких обстоятельствах суд квалифицирует действия Г.Д.Р. ч. 1 ст. 105 УК РФ как убийство, то есть умышленное причинение смерти другому человеку.
За содеянное Г.Д.Р. подлежит наказанию, при назначении которого суд, руководствуясь требованиями ст.ст.6, 43, 60 УК РФ, учитывает характер и степень общественной опасности совершенного им преступления, данные о его личности, обстоятельства, смягчающие и отягчающее наказание, а также влияние назначенного наказания на исправление подсудимого и на условия жизни его семьи.
Подсудимым совершено умышленное преступление против жизни, которое в соответствии с ч.5 ст. 15 УК РФ относится к категории особо тяжких.
Г.Д.Р. ранее не судим (т.2 л.д. 163), в браке не состоит, детей не имеет, нигде не работает. По месту жительства участковым уполномоченным полиции характеризуется удовлетворительно, спиртными напитками не злоупотребляет, привлекался к административной ответственности за нарушения ПДД, что объективно подтверждается сведениями, предоставленными центром по исполнению административного законодательства УМВД России по г. Архангельску и не оспаривается самим подсудимым (т.2 л.д. 170, 171-172, 175, 177).
На учете у врача психиатра Г.Д.Р. не состоит (т.2 л.д. 181, 182), какими-либо хроническими заболеваниями не страдает.
Обстоятельствами, смягчающими наказание Г.Д.Р., суд признает его явку с повинной, активное способствование раскрытию и расследованию преступления, частичное признание им своей вины, раскаяние в содеянном, а также противоправное поведение потерпевшего, выразившееся в высказывании угроз и оскорблений в адрес подсудимого, что явилось поводом для преступления.
Учитывая характер и степень общественной опасности совершенного Г.Д.Р. преступления и обстоятельства его совершения, а также сведения о личности подсудимого, который спиртным не злоупотребляет, принимая во внимание его пояснения в судебном заседании о количестве выпитого им алкоголя, суд приходит к выводу о том, что алкогольное опьянение, в котором находился Г.Д.Р. в момент совершения данного преступления, существенным образом сказалось на его поведении и ослабило его самоконтроль за поступками, что с учетом поведения потерпевшего и привело к совершению данного преступления, хотя будучи в трезвом состоянии он таких действий никогда бы не совершил, суд в соответствии с ч. 1.1 ст. 63 УК РФ признает в качестве обстоятельства, отягчающего его наказание, совершение им преступления в состоянии опьянения, вызванном употреблением алкоголя.
Иных обстоятельств, смягчающих либо отягчающих наказание подсудимого, суд не усматривает.
С учетом всех обстоятельств уголовного дела в совокупности, характера и категории тяжести совершенного Г.Д.Р. преступления, являющегося умышленным и направленным против жизни человека, а также данных о личности подсудимого, суд приходит к выводу о том, что достижение целей наказания, установленных ст.43 УК РФ, возможно только в условиях изоляции Г.Д.Р. от общества, а потому не находит законных оснований для назначения ему более мягкого наказания, чем лишение свободы.
Вместе с тем, принимая во внимание наличие по делу вышеуказанных обстоятельств, смягчающих наказание Г.Д.Р., и сведения о его личности, суд не усматривает необходимости в назначении ему дополнительного наказания в виде ограничения свободы, предусмотренного санкцией ч.1 ст. 105 УК РФ.
При определении размера наказания суд учитывает наличие по делу вышеуказанных смягчающих и отягчающего наказание обстоятельств, возраст подсудимого, а также состояние его здоровья и членов его семьи.
Принимая во внимание установленное судом обстоятельство, отягчающее наказание подсудимого, а также фактические обстоятельства совершенного Г.Д.Р. преступления и степень его общественной опасности, мотивы и цели его совершения, суд не усматривает законных оснований для изменения категории преступления на менее тяжкую в соответствии с ч.6 ст.15 УК РФ, равно как и для применения к подсудимому положений ст.64, ст.73 УК РФ, а также для освобождения его от наказания или предоставления ему отсрочки от его отбывания.
Согласно п. «в» ч. 1 ст. 58 УК РФ отбывать наказание подсудимому надлежит в исправительной колонии строгого режима.
В связи с этим в целях обеспечения исполнения приговора ранее избранная Г.Д.Р. мера пресечения в виде заключения под стражу отмене или изменению до вступления приговора в законную силу не подлежит.
При этом время содержания его под стражей в период с <Дата> по день вступления приговора в законную силу подлежит зачету в срок окончательного наказания из расчета один день содержания его под стражей за один день лишения свободы в исправительной колонии строгого режима.
Гражданский иск по делу не заявлен.
Арест на имущество не накладывался.
После вступления приговора в законную силу хранящиеся в камере хранения вещественных доказательств следственного отдела по Ломоносовскому округу г.Архангельска СУ СК РФ по Архангельской области и НАО вещественные доказательства:
– хозяйственный нож как орудие преступления подлежит уничтожению,
– нож-бабочку, шапку, куртку, спортивную куртку, кофту, брюки джинсовые, ботинки, спортивные брюки, футболку, две пары носков следует вернуть потерпевшему Г.Д.Б.о., а в случае их неистребования им в течение 6 месяцев с момента вступления приговора в законную силу уничтожить (т. 2 л.д. 113, 136),
- мобильный телефон марки <***> суд считает возможным вернуть его законному владельцу Г.Д.Р. (т. 2 л.д. 89).
На стадии предварительного расследования защиту Г.Д.Р. осуществлял адвокат по назначению следователя, которому за оказание такой помощи отдельным постановлением выплачено вознаграждение в сумме <***> (т.2 л.д. 200).
В соответствии с п. 5 ч. 2 ст. 131, ст. 132 УПК РФ указанные расходы являются процессуальными издержками, которые взыскиваются с осужденных или возмещаются за счет средств федерального бюджета.
В связи с тем, что Г.Д.Р. от услуг адвоката не отказывался, о своей имущественной несостоятельности убедительных доводов не привел, при этом он молод, здоров и полностью трудоспособен, суд не усматривает оснований для его полного или частичного освобождения от уплаты данных процессуальных издержек и считает необходимым взыскать их в полном объеме с Г.Д.Р. в федеральный бюджет.
На основании изложенного, руководствуясь ст.ст.307-309 УПК РФ,

sentence: ПРИГОВОРИЛ:
Г.Д.Р. признать виновным в совершении преступления, предусмотренного ч. 1 ст. 105 УК РФ, и назначить ему наказание в виде лишения свободы на срок 6 (шесть) лет 6 (шесть) месяцев с отбыванием наказания в исправительной колонии строгого режима.
Срок наказания исчислять с <Дата>.
Зачесть в срок отбывания наказания время содержания Г.Д.Р. под стражей в период с <Дата> по день вступления приговора в законную силу из расчета один день содержания его под стражей за один день лишения свободы в исправительной колонии строгого режима.
Меру пресечения Г.Д.Р. в виде заключения под стражу на период апелляционного обжалования приговора оставить без изменения.
Вещественные доказательства, хранящиеся в камере хранения вещественных доказательств следственного отдела по Ломоносовскому округу г.Архангельска СУ СК РФ по Архангельской области и НАО:

In [25]:
df_with_marking.shape

(100, 34)

In [26]:
df_with_marking.to_csv('df_with_marking_final.csv', index=False)

In [3]:
import pandas as pd

In [4]:
df_with_marking1 = pd.read_csv('df_with_marking_final.csv')
df_with_marking1

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term,preamble,description,sentence
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,"['руки', 'нож']",жестокое,умышленное,"['личная неприязнь', 'месть']",да,была,6.50,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,ружье,не жестокое,умышленное,"['личная неприязнь', 'ревность']",да,была,8.08,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,"['камень', 'электропроводной шнур', 'подушка']",жестокое,умышленное,"['деньги', 'имущество']",нет,нет,18.00,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,травматический пистолет,не жестокое,умышленное,личная неприязнь,да,была,3.00,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,"['руки', 'ноги']",жестокое,умышленное,личная неприязнь,нет,была,9.25,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,4.00,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,У С Т А Н О В И Л :\nПодсудимый Тараканов В.В....,П Р И Г О В О Р И Л :\nПризнать Тараканова Вла...
96,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,мужчина,...,"['лопата', 'избиение']",жестокое,умышленное,личная неприязнь,нет,была,12.00,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,"УСТАНОВИЛ:\nНемтинов С.В. совершил убийство, т...",ПРИГОВОРИЛ:\nПризнать Немтинова Сергея Викторо...
97,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,8.00,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,У С Т А Н О В И Л:\nБаженов Д.В. совершил убий...,П Р И Г О В О Р И Л:\nБаженова Д.В. признать в...
98,14640,50,2016-01-11,Меликян Тарон Акопи - ст.105 ч.1 УК РФ,Попова Марина Николаевна,Вынесен ПРИГОВОР,Меликян Тарон Акопи,ст.105 ч.1,http://luberetzy--mo.sudrf.ru/modules.php?name...,мужчина,...,"['нож', 'молоток', 'избиение', 'скидывание с в...",жестокое,умышленное,ревность,да,была,8.00,Дело №\nПРИГОВОР\nименем Российской Федерации\...,"УСТАНОВИЛ:\nМеликян Т.А. совершил убийство, то...",ПРИГОВОРИЛ:\nМеликяна Т. А. признать виновным ...
99,2220,16,2016-03-01,Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ,Токтаров Денис Витальевич,Вынесен ПРИГОВОР,Мичурин Евгений Андреевич,ст.105 ч.1,http://chistopolsky--tat.sudrf.ru/modules.php?...,мужчина,...,кирпич,жестокое,умышленное,личная неприязнь,да,нет,9.50,копия\nДело №\nП Р И Г О В О Р\nи м е н е м Р ...,Установил:\nДД.ММ.ГГГГ в период времени с 10 ч...,"Приговорил:\nМичурин Е.А, признать виновным в ..."

In [5]:
df_with_marking1['method'].value_counts()

method
нож                                                      55
избиение                                                  6
удушение                                                  5
молоток                                                   4
топор                                                     4
огнестрел                                                 3
['руки', 'нож']                                           2
травматический пистолет                                   1
удар предметом                                            1
['камень', 'электропроводной шнур', 'подушка']            1
ружье                                                     1
['руки', 'ноги']                                          1
['кирпич', 'руки']                                        1
полено                                                    1
огнестрельное оружие                                      1
клинок                                                    1
['избиение', 'удушение']                                  1
['избиение', 'молоток']                                   1
['нож', 'удушение']                                       1
['нож', 'избиение']                                       1
['удушение', 'избиение']                                  1
['молоток', 'топор']                                      1
['избиение', 'нож']                                       1
['избиение', 'нож', 'вилка']                              1
повешение                                                 1
['лопата', 'избиение']                                    1
['нож', 'молоток', 'избиение', 'скидывание с высоты']     1
кирпич                                                    1
Name: count, dtype: int64

In [8]:
def replace_values(value):
    if value in ["руки", "ноги"]:
        return "избиение"
    elif"руки" in value:
        return "избиение"
    elif "подушка" in value:
        return "удушение"
    elif value == "огнестрельное оружие":
        return "огнестрел"
    return value

df_with_marking1["method"] = df_with_marking1["method"].apply(replace_values)
print(df_with_marking1["method"].value_counts())

method
нож                                                      55
избиение                                                 10
удушение                                                  6
огнестрел                                                 4
молоток                                                   4
топор                                                     4
ружье                                                     1
удар предметом                                            1
травматический пистолет                                   1
полено                                                    1
клинок                                                    1
['избиение', 'удушение']                                  1
['избиение', 'молоток']                                   1
['нож', 'удушение']                                       1
['нож', 'избиение']                                       1
['удушение', 'избиение']                                  1
['молоток', 'топор']                                      1
['избиение', 'нож']                                       1
['избиение', 'нож', 'вилка']                              1
повешение                                                 1
['лопата', 'избиение']                                    1
['нож', 'молоток', 'избиение', 'скидывание с высоты']     1
кирпич                                                    1
Name: count, dtype: int64

In [10]:
df_with_marking1.to_csv('df_with_marking_final.csv', index=False)

In [11]:
df_with_marking1 = pd.read_csv('df_with_marking_final.csv')
df_with_marking1

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term,preamble,description,sentence
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,избиение,жестокое,умышленное,"['личная неприязнь', 'месть']",да,была,6.50,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,ружье,не жестокое,умышленное,"['личная неприязнь', 'ревность']",да,была,8.08,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,удушение,жестокое,умышленное,"['деньги', 'имущество']",нет,нет,18.00,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,травматический пистолет,не жестокое,умышленное,личная неприязнь,да,была,3.00,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,избиение,жестокое,умышленное,личная неприязнь,нет,была,9.25,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,4.00,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,У С Т А Н О В И Л :\nПодсудимый Тараканов В.В....,П Р И Г О В О Р И Л :\nПризнать Тараканова Вла...
96,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,мужчина,...,"['лопата', 'избиение']",жестокое,умышленное,личная неприязнь,нет,была,12.00,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,"УСТАНОВИЛ:\nНемтинов С.В. совершил убийство, т...",ПРИГОВОРИЛ:\nПризнать Немтинова Сергея Викторо...
97,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,мужчина,...,нож,не жестокое,умышленное,личная неприязнь,нет,была,8.00,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,У С Т А Н О В И Л:\nБаженов Д.В. совершил убий...,П Р И Г О В О Р И Л:\nБаженова Д.В. признать в...
98,14640,50,2016-01-11,Меликян Тарон Акопи - ст.105 ч.1 УК РФ,Попова Марина Николаевна,Вынесен ПРИГОВОР,Меликян Тарон Акопи,ст.105 ч.1,http://luberetzy--mo.sudrf.ru/modules.php?name...,мужчина,...,"['нож', 'молоток', 'избиение', 'скидывание с в...",жестокое,умышленное,ревность,да,была,8.00,Дело №\nПРИГОВОР\nименем Российской Федерации\...,"УСТАНОВИЛ:\nМеликян Т.А. совершил убийство, то...",ПРИГОВОРИЛ:\nМеликяна Т. А. признать виновным ...
99,2220,16,2016-03-01,Мичурин Евгений Андреевич - ст.105 ч.1 УК РФ,Токтаров Денис Витальевич,Вынесен ПРИГОВОР,Мичурин Евгений Андреевич,ст.105 ч.1,http://chistopolsky--tat.sudrf.ru/modules.php?...,мужчина,...,кирпич,жестокое,умышленное,личная неприязнь,да,нет,9.50,копия\nДело №\nП Р И Г О В О Р\nи м е н е м Р ...,Установил:\nДД.ММ.ГГГГ в период времени с 10 ч...,"Приговорил:\nМичурин Е.А, признать виновным в ..."