In [1]:
import pandas as pd

df = pd.read_csv('preprocessed_data.csv')

In [2]:
df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...

In [6]:
df = df.assign(
    gender_accused="", age_accused="", alcohol="", drugs="", mental_disorder="", prior_convictions="",
    gender_victim="", age_victim="", relationship_between_accused_and_victim="",
    time_of_day="", day_of_week="", season="", year="",
    crime_region="", location="", method="", cruelty="", intentional="", motive="",
    witnesses="", precrime_argument="", prison_term=""
)

df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,,,,,,,,,,
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,,,,,,,,,,
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,,,,,,,,,,
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,,,,,,,,,,
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,,,,,,,,,,

In [7]:
df_sample = df.sample(n=100, random_state=42)
df_sample

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
16281,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,,,,,,,,,,
22629,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,,,,,,,,,,
11306,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,,,,,,,,,,
34974,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
30211,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715,7557,28,2016-05-06,Логадырь Николай Владимирович - ст.105 ч.1 УК РФ,Едакова М.А.,Вынесен ПРИГОВОР,Логадырь Николай Владимирович,ст.105 ч.1,http://shimanovskiy--amr.sudrf.ru/modules.php?...,Дело № 1-82/2016\nП Р И Г О В О Р\nИменем Росс...,...,,,,,,,,,,
23431,92323,56,2019-11-08,Петрова Лариса Алексеевна - ст.105 ч.1 УК РФ,Топильская С.А.,Вынесен ПРИГОВОР,Петрова Лариса Алексеевна,ст.105 ч.1,http://centralny--orb.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
34075,122495,78,2022-03-01,"ТАРАКАНОВ ВЛАДИМИР ВЛАДИМИРОВИЧ - ст. 30 ч.3, ...",Гулевич Станислав Анатольевич,Вынесен ПРИГОВОР,Тараканов Владимир Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://nvs--spb.sudrf.ru/modules.php?name=sud_...,Дело № 1-589/22 (78 BS 0015-01-2022-00231414)\...,...,,,,,,,,,,
19090,79171,60,2018-12-04,Немтинов Сергей Викторович - ст.105 ч.1 УК РФ,Сергеева Надежда Николаевна,Вынесен ПРИГОВОР,Немтинов Сергей Викторович,ст.105 ч.1,http://pskovsky--psk.sudrf.ru/modules.php?name...,Дело ***\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИ...,...,,,,,,,,,,
11821,31607,24,2017-07-31,Баженов Дмитрий Викторович - ст.105 ч.1 УК РФ,Безрукова Ольга Васильевна,Вынесен ПРИГОВОР,Баженов Дмитрий Викторович,ст.105 ч.1,http://igarka--krk.sudrf.ru/modules.php?name=s...,Дело №\nП Р И Г О В О Р\nИменем Российской Фед...,...,,,,,,,,,,

In [16]:
import numpy as np

df_sample1, df_sample2, df_sample3, df_sample4 = np.array_split(df_sample, 4)

c:\Users\Zephyrus\Documents\GitHub\criminal-research\myenv\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [17]:
df_sample1.shape, df_sample2.shape, df_sample3.shape, df_sample4.shape

((25, 34), (25, 34), (25, 34), (25, 34))

In [19]:
df_sample1.to_csv('df_sample1.csv', index=False)
df_sample2.to_csv('df_sample2.csv', index=False)
df_sample3.to_csv('df_sample3.csv', index=False)
df_sample4.to_csv('df_sample4.csv', index=False)

In [ ]:
df_sample1.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,year,crime_region,location,method,cruelty,intentional,motive,witnesses,precrime_argument,prison_term
16281,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,...,,,,,,,,,,
22629,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,...,,,,,,,,,,
11306,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,...,,,,,,,,,,
34974,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,...,,,,,,,,,,
30211,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,...,,,,,,,,,,