In [1]:
import pandas as pd

df_link_notna_text_na = pd.read_csv('filtered_data.csv')
print(df_link_notna_text_na.shape)
df_link_notna_text_na = df_link_notna_text_na[df_link_notna_text_na['link_text'].notna() & df_link_notna_text_na['text'].isna()]
df_link_notna_text_na.shape

(7864, 21)

(7864, 21)

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import concurrent.futures

def get_text_(id_link):
    id_, link = id_link
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
    }
    session = requests.Session()
    session.headers = headers
    try:
        response = session.get(link, timeout=120)
        response.raise_for_status()
        bs = BeautifulSoup(response.text, 'html.parser')
        
        div = bs.find('div', id='content') 
        if not div:
            div = bs.find('div', class_='container')
        if div:
            text = div.get_text(separator="\n", strip=True)
            return [id_, link, text]
        else:
            print(f"not find text, link: {link}, status: {response.status_code}")
            return [id_, link, None]
    except requests.exceptions.RequestException as e:
        print(f"request error, link: {link}, error: {str(e)}")
        return [id_, link, None]
    except Exception as e:
        print(f"other error, link: {link}, type: {type(e)}, error: {str(e)}")
        return [id_, link, None]

def find_text(cur_df):
    links = list(zip(cur_df['id'], cur_df['link_text']))
    CONNECTIONS = 4
    out = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=CONNECTIONS) as executor:
        future_to_link = (executor.submit(get_text_, id_link) for id_link in links)
        for future in tqdm(concurrent.futures.as_completed(future_to_link), total=len(links)):
            try:
                data = future.result() 
            except Exception as exc:      
                data = str(type(exc))
            finally:
                out.append(data)
    return out

out = find_text(df_link_notna_text_na)
df_with_link_text = pd.DataFrame(out, columns=['id', 'link_text', 'text'])

  1%|          | 64/7864 [01:10<12:29:24,  5.76s/it]

not find text, link: http://baltachevsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=67024303&delo_id=1540006&new=0&text_number=1, status: 200

  1%|          | 68/7864 [01:22<6:41:17,  3.09s/it]

not find text, link: http://meleuzovsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=15743993&delo_id=1540006&new=0&text_number=1, status: 200

  2%|▏         | 143/7864 [03:16<2:05:36,  1.02it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8e574f2c-e874-410d-b202-0e0f44d2fb6c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 151/7864 [03:24<2:28:10,  1.15s/it]

not find text, link: http://gribanovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=bf8cf35d-f2a3-480b-b4ee-80d2a6adf005&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 155/7864 [03:29<2:18:14,  1.08s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=79ba9464-8136-420a-bc8f-b865ffe5623d&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 156/7864 [03:30<2:15:21,  1.05s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=13c4abd8-5664-4134-b375-a231ad70648a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 158/7864 [03:31<1:52:15,  1.14it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=fe2bb63a-d85e-4e4a-8852-51bdada9e47c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 173/7864 [03:53<2:30:09,  1.17s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a9daa1c1-3cff-41b0-a4ef-af7b3f36b51a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 182/7864 [04:04<1:59:43,  1.07it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=9ec1c3de-d500-46fd-bafc-0c8bd6e58356&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 185/7864 [04:06<1:12:15,  1.77it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=70e582ae-fd59-47c0-b6b4-130bab54dc8e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=64cf6592-f46c-4c3f-8126-d03e78557102&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 186/7864 [04:07<1:29:10,  1.43it/s]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=6ef59428-b160-4524-a86b-1ef5c3fb5209&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 189/7864 [04:08<58:13,  2.20it/s]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=eea9eef3-98f8-4b90-b218-e07093cec388&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 190/7864 [04:08<1:00:36,  2.11it/s]

not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=b80fbd2b-2578-486a-a79c-ddeebaee5d95&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  2%|▏         | 196/7864 [04:13<1:53:05,  1.13it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=d805996b-43dd-44ec-bb44-5cc106c0d66b&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 205/7864 [04:23<3:10:09,  1.49s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ba5b5bac-9de9-428e-bbfb-4c648f949036&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 207/7864 [04:26<3:01:37,  1.42s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a16e6adf-270f-4245-8aba-f16dcc5c2ad5&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 211/7864 [04:31<2:29:55,  1.18s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=5681a9e2-d5e9-43c9-9206-c3d16ad1ccf6&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 240/7864 [05:05<1:33:05,  1.36it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=6a79fa72-be69-41fb-a29f-07c0807c6e04&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 243/7864 [05:08<1:39:29,  1.28it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8e8b9275-3a39-4a2e-9145-b1ff2e33f491&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=78f6d581-040b-4c0c-b1a2-d20fd08b446f&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 246/7864 [05:10<1:37:29,  1.30it/s]

not find text, link: http://gribanovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=00ea581e-a36c-42c8-b917-8a3a99206421&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 255/7864 [05:20<2:37:42,  1.24s/it]

not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8bc488cf-4dcc-4061-bda4-ec2b1acce359&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 258/7864 [05:27<3:21:07,  1.59s/it]

not find text, link: http://otstrogozhsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=9c6d5ed6-f811-4630-a539-d36a705436ce&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  3%|▎         | 268/7864 [05:45<5:10:13,  2.45s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a177294d-86a2-447a-ac32-9e36088c8b07&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  4%|▎         | 287/7864 [06:35<6:00:25,  2.85s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=4bffd9e3-d9b9-48d1-b564-b0308dc2ca42&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  5%|▍         | 364/7864 [08:00<1:12:44,  1.72it/s]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=21bec423-5eb7-4ad1-b306-13d121e4d862&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  8%|▊         | 633/7864 [13:48<1:59:45,  1.01it/s]

not find text, link: http://oblsud--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6628124&delo_id=1540006&new=0&text_number=1, status: 200

  8%|▊         | 647/7864 [14:04<3:16:16,  1.63s/it]

request error, link: http://pervouralsky--svd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=28985618&delo_id=1540006&new=0&text_number=1, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

  9%|▉         | 709/7864 [15:43<2:20:21,  1.18s/it]

not find text, link: http://paninsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=aaf5af1f-ee9b-4bbe-92c1-ce41d63c4554&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 11%|█         | 836/7864 [18:54<1:32:42,  1.26it/s]

request error, link: http://pinegasud--arh.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=11645919&delo_id=1540006&new=0&text_number=1, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 11%|█         | 853/7864 [19:13<2:25:37,  1.25s/it]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=04500961-cbc1-4472-8dd5-f0d21d329ff2&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 12%|█▏        | 939/7864 [20:28<34:46,  3.32it/s]

not find text, link: http://intasud--komi.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=13599733&delo_id=1540006&new=0&text_number=1, status: 200

 12%|█▏        | 971/7864 [21:22<57:32,  2.00it/s]

not find text, link: http://pechora--komi.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=44901091&delo_id=1540006&new=0&text_number=1, status: 200

 13%|█▎        | 1022/7864 [22:56<1:04:44,  1.76it/s]

request error, link: http://kalininsky--nsk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=87478310&delo_id=1540006&new=0&text_number=1, error: 502 Server Error: Bad Gateway for url: https://kalininsky--nsk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=87478310&delo_id=1540006&new=0&text_number=1

 13%|█▎        | 1044/7864 [23:25<1:56:18,  1.02s/it]

not find text, link: http://liskinsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=4e89a21a-4e74-40dc-9bf6-9d2febad3a66&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 18%|█▊        | 1401/7864 [31:06<1:49:45,  1.02s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=bd1927b8-eeac-458e-9a5c-27005ed597a0&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 18%|█▊        | 1421/7864 [31:39<2:04:23,  1.16s/it]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=7640783c-3f79-4cca-a39a-9f65a62b7cbb&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 20%|██        | 1592/7864 [35:06<4:52:37,  2.80s/it]

not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8de145df-7dd3-417e-ad5f-be76b0307be4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 21%|██        | 1638/7864 [36:28<59:18,  1.75it/s]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=c129c20c-9376-4de9-ab8f-5a91b667d1b8&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 21%|██        | 1663/7864 [36:59<3:26:34,  2.00s/it]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=64602139-b40b-4a25-9eec-5c46345574a8&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 22%|██▏       | 1739/7864 [38:24<33:21,  3.06it/s]

not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=f526a1b5-976c-44cf-acdb-c0af66e6171b&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 23%|██▎       | 1801/7864 [39:17<2:02:35,  1.21s/it]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=522147fe-ad2e-419e-b8d1-9ddc3ccfd56e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 24%|██▎       | 1855/7864 [40:12<49:05,  2.04it/s]

request error, link: http://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=116336038&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=116336038&delo_id=1540006&new=0&text_number=1

 24%|██▎       | 1866/7864 [40:24<1:09:55,  1.43it/s]

not find text, link: http://kalacheevsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ada3e972-bae8-400e-a198-6d604b55913e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 24%|██▍       | 1920/7864 [41:41<1:17:14,  1.28it/s]

not find text, link: http://liskinsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=cc05c0c9-cb5f-4d5c-8aea-2755c5ec3063&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 26%|██▋       | 2069/7864 [45:38<2:56:52,  1.83s/it]

not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ee0a5c61-f6da-4946-a183-9ae2b83ab85c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 27%|██▋       | 2087/7864 [46:09<6:35:06,  4.10s/it]

request error, link: http://krasnogorsky--svd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36733933&delo_id=1540006&new=0&text_number=1, error: HTTPSConnectionPool(host='krasnogorsky--svd.sudrf.ru', port=443): Read timed out. (read timeout=120)

 29%|██▉       | 2285/7864 [48:40<52:55,  1.76it/s]

request error, link: http://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=122826035&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=122826035&delo_id=1540006&new=0&text_number=1

 30%|██▉       | 2337/7864 [50:06<3:46:46,  2.46s/it]

request error, link: http://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=3859765&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=3859765&delo_id=1540006&new=0&text_number=1

 31%|███       | 2411/7864 [51:58<1:32:54,  1.02s/it]

not find text, link: http://oktiabrsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=7589241&delo_id=1540006&new=0&text_number=1, status: 200

 34%|███▎      | 2643/7864 [55:27<44:21,  1.96it/s]

not find text, link: http://paninsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=16c5e932-eaa0-4250-b59b-6b231467d672&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 37%|███▋      | 2943/7864 [1:01:22<1:42:19,  1.25s/it]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568244&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568244&delo_id=1540006&new=0&text_number=1

 42%|████▏     | 3272/7864 [1:07:27<2:31:34,  1.98s/it]

not find text, link: http://leninsky--pnz.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=77234701&delo_id=1540006&new=0&text_number=1, status: 200

 43%|████▎     | 3363/7864 [1:09:41<2:43:21,  2.18s/it]

not find text, link: http://oktiabrsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=7590413&delo_id=1540006&new=0&text_number=1, status: 200

 43%|████▎     | 3365/7864 [1:09:48<3:36:32,  2.89s/it]

not find text, link: http://zheleznodorozhnii--pnz.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=60966358&delo_id=1540006&new=0&text_number=1, status: 200

 44%|████▍     | 3449/7864 [1:11:00<33:34,  2.19it/s]

not find text, link: http://ostashkovsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ef6ebe5b-c52b-4766-a022-51048db1b3a4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 49%|████▉     | 3841/7864 [1:18:27<54:34,  1.23it/s]

request error, link: http://vs--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=21831447&delo_id=1540006&new=0&text_number=1, error: HTTPSConnectionPool(host='vs--bkr.sudrf.ru', port=443): Read timed out. (read timeout=120)

 49%|████▉     | 3890/7864 [1:19:36<2:07:25,  1.92s/it]

request error, link: http://sharinsky--hak.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=26976897&delo_id=1540006&new=0&text_number=1, error: HTTPSConnectionPool(host='sharinsky--hak.sudrf.ru', port=443): Read timed out. (read timeout=120)

 50%|████▉     | 3921/7864 [1:19:53<22:53,  2.87it/s]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=667d9236-a609-45fe-9a43-f4e623defbfc&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 51%|█████     | 4009/7864 [1:21:26<41:40,  1.54it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568534&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568534&delo_id=1540006&new=0&text_number=1

 52%|█████▏    | 4100/7864 [1:23:20<1:21:09,  1.29s/it]

request error, link: http://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=56833764&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=56833764&delo_id=1540006&new=0&text_number=1

 55%|█████▍    | 4325/7864 [1:27:46<1:44:13,  1.77s/it]

not find text, link: http://blagovarsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=8265239&delo_id=1540006&new=0&text_number=1, status: 200

 56%|█████▌    | 4381/7864 [1:28:56<25:29,  2.28it/s]

request error, link: http://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=35775188&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=35775188&delo_id=1540006&new=0&text_number=1

 56%|█████▌    | 4400/7864 [1:29:29<3:19:26,  3.45s/it]

not find text, link: http://blagoveschensky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=15186324&delo_id=1540006&new=0&text_number=1, status: 200

 60%|█████▉    | 4694/7864 [1:35:30<1:22:45,  1.57s/it]

request error, link: http://peschanokopsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36699571&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://peschanokopsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36699571&delo_id=1540006&new=0&text_number=1

 61%|██████    | 4807/7864 [1:37:11<28:26,  1.79it/s]

request error, link: http://nagaib--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=292914249&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://nagaib--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=292914249&delo_id=1540006&new=0&text_number=1

 62%|██████▏   | 4879/7864 [1:38:16<35:48,  1.39it/s]

request error, link: http://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288297869&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288297869&delo_id=1540006&new=0&text_number=1

 62%|██████▏   | 4914/7864 [1:40:08<3:26:45,  4.21s/it]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568786&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568786&delo_id=1540006&new=0&text_number=1

 64%|██████▍   | 5029/7864 [1:42:54<34:16,  1.38it/s]

not find text, link: http://kanevskay--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147726844&delo_id=1540006&new=0&text_number=1, status: 200

 64%|██████▍   | 5058/7864 [1:43:55<2:23:55,  3.08s/it]

not find text, link: http://sochi-lazarevsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=148292446&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▍   | 5088/7864 [1:44:54<2:40:05,  3.46s/it]

not find text, link: http://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=154633357&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▍   | 5091/7864 [1:45:11<3:39:40,  4.75s/it]

not find text, link: http://ust-labinsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=241995463&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▍   | 5096/7864 [1:45:13<1:01:00,  1.32s/it]

not find text, link: http://krasnodar-sovetsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=254552029&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▍   | 5111/7864 [1:45:38<1:20:31,  1.75s/it]

not find text, link: http://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=247526498&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▌   | 5116/7864 [1:45:46<1:09:34,  1.52s/it]

not find text, link: http://krasnoarmeisk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147913185&delo_id=1540006&new=0&text_number=1, status: 200

 65%|██████▌   | 5136/7864 [1:46:07<1:46:20,  2.34s/it]

not find text, link: http://novorossisk-oktybrsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=64135628&delo_id=1540006&new=0&text_number=1, status: 200

 66%|██████▌   | 5159/7864 [1:46:38<32:40,  1.38it/s]

request error, link: http://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288469554&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288469554&delo_id=1540006&new=0&text_number=1

 66%|██████▌   | 5195/7864 [1:47:16<1:28:20,  1.99s/it]

not find text, link: http://kanevskay--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147726740&delo_id=1540006&new=0&text_number=1, status: 200

 66%|██████▋   | 5221/7864 [1:49:10<2:17:12,  3.11s/it]

not find text, link: http://dinskoy--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=44871301&delo_id=1540006&new=0&text_number=1, status: 200

 67%|██████▋   | 5240/7864 [1:50:26<1:26:18,  1.97s/it]

not find text, link: http://krasnodar-leninsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=148474278&delo_id=1540006&new=0&text_number=1, status: 200

 67%|██████▋   | 5306/7864 [1:51:43<1:11:22,  1.67s/it]

not find text, link: http://birsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=27245258&delo_id=1540006&new=0&text_number=1, status: 200

 68%|██████▊   | 5313/7864 [1:52:06<1:43:36,  2.44s/it]

not find text, link: http://krasnodar-sovetsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=155075133&delo_id=1540006&new=0&text_number=1, status: 200

 68%|██████▊   | 5335/7864 [1:52:20<12:24,  3.40it/s]

not find text, link: http://kavkazsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147652147&delo_id=1540006&new=0&text_number=1, status: 200
not find text, link: http://pervomaisky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153473934&delo_id=1540006&new=0&text_number=1, status: 200

 68%|██████▊   | 5345/7864 [1:52:31<53:17,  1.27s/it]

not find text, link: http://bruxovecky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=24813280&delo_id=1540006&new=0&text_number=1, status: 200

 68%|██████▊   | 5359/7864 [1:52:44<46:34,  1.12s/it]

not find text, link: http://oblsud--mo.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6736487&delo_id=1540006&new=0&text_number=1, status: 200

 68%|██████▊   | 5365/7864 [1:52:50<26:07,  1.59it/s]

not find text, link: http://apsheronsk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153036371&delo_id=1540006&new=0&text_number=1, status: 200

 69%|██████▊   | 5396/7864 [1:53:40<2:19:34,  3.39s/it]

not find text, link: http://oktiabrsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=7608593&delo_id=1540006&new=0&text_number=1, status: 200

 69%|██████▉   | 5413/7864 [1:54:17<33:56,  1.20it/s]

not find text, link: http://novorossisk-primorsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=46813615&delo_id=1540006&new=0&text_number=1, status: 200

 69%|██████▉   | 5420/7864 [1:54:20<19:02,  2.14it/s]

not find text, link: http://sochi-lazarevsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=223545440&delo_id=1540006&new=0&text_number=1, status: 200

 70%|██████▉   | 5490/7864 [1:55:06<1:45:51,  2.68s/it]

not find text, link: http://blagoveschensky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=31741788&delo_id=1540006&new=0&text_number=1, status: 200

 70%|██████▉   | 5499/7864 [1:55:22<1:01:04,  1.55s/it]

not find text, link: http://leninsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=19129245&delo_id=1540006&new=0&text_number=1, status: 200

 70%|███████   | 5509/7864 [1:55:25<13:48,  2.84it/s]

not find text, link: http://novokubansk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=44873330&delo_id=1540006&new=0&text_number=1, status: 200

 70%|███████   | 5527/7864 [1:55:59<1:38:27,  2.53s/it]

not find text, link: http://novorossisk-primorsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=98906115&delo_id=1540006&new=0&text_number=1, status: 200

 70%|███████   | 5536/7864 [1:56:05<28:37,  1.36it/s]

not find text, link: http://tixoreck-gor--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=155248025&delo_id=1540006&new=0&text_number=1, status: 200

 71%|███████   | 5548/7864 [1:56:27<33:50,  1.14it/s]

not find text, link: http://anapa--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=231257320&delo_id=1540006&new=0&text_number=1, status: 200

 71%|███████▏  | 5619/7864 [1:57:50<1:17:20,  2.07s/it]

not find text, link: http://krasnodar-sovetsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=158220250&delo_id=1540006&new=0&text_number=1, status: 200

 72%|███████▏  | 5663/7864 [1:58:34<1:59:38,  3.26s/it]

not find text, link: http://tbilissky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=155202516&delo_id=1540006&new=0&text_number=1, status: 200

 72%|███████▏  | 5665/7864 [1:58:35<1:05:56,  1.80s/it]

not find text, link: http://anapa-gor--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=132600828&delo_id=1540006&new=0&text_number=1, status: 200

 72%|███████▏  | 5701/7864 [1:59:41<1:08:58,  1.91s/it]

not find text, link: http://gor-kluch--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153341209&delo_id=1540006&new=0&text_number=1, status: 200

 73%|███████▎  | 5728/7864 [2:00:08<30:47,  1.16it/s]

not find text, link: http://apsheronsk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153036948&delo_id=1540006&new=0&text_number=1, status: 200

 73%|███████▎  | 5745/7864 [2:00:28<51:36,  1.46s/it]

not find text, link: http://armavir--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=47388225&delo_id=1540006&new=0&text_number=1, status: 200

 73%|███████▎  | 5768/7864 [2:01:43<2:21:43,  4.06s/it]

request error, link: http://apsheronsk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153037329&delo_id=1540006&new=0&text_number=1, error: 504 Server Error: Gateway Time-out for url: https://apsheronsk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153037329&delo_id=1540006&new=0&text_number=1

 74%|███████▍  | 5818/7864 [2:04:36<1:26:35,  2.54s/it]

request error, link: http://mostovskay--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=79479153&delo_id=1540006&new=0&text_number=1, error: 504 Server Error: Gateway Time-out for url: https://mostovskay--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=79479153&delo_id=1540006&new=0&text_number=1

 74%|███████▍  | 5846/7864 [2:05:45<1:47:06,  3.18s/it]

not find text, link: http://baimaksky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=32286203&delo_id=1540006&new=0&text_number=1, status: 200

 74%|███████▍  | 5858/7864 [2:06:22<1:13:41,  2.20s/it]

not find text, link: http://eisk-gor--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147630267&delo_id=1540006&new=0&text_number=1, status: 200

 75%|███████▌  | 5923/7864 [2:07:41<1:14:37,  2.31s/it]

request error, link: http://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=130471486&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=130471486&delo_id=1540006&new=0&text_number=1

 77%|███████▋  | 6025/7864 [2:09:53<1:52:11,  3.66s/it]

not find text, link: http://novorossisk-oktybrsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=160462618&delo_id=1540006&new=0&text_number=1, status: 200

 77%|███████▋  | 6026/7864 [2:10:01<2:30:50,  4.92s/it]

not find text, link: http://gulkevichi--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=147359242&delo_id=1540006&new=0&text_number=1, status: 200

 77%|███████▋  | 6051/7864 [2:10:30<50:18,  1.67s/it]

not find text, link: http://korenovsk--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=98786900&delo_id=1540006&new=0&text_number=1, status: 200

 77%|███████▋  | 6057/7864 [2:10:46<1:25:08,  2.83s/it]

not find text, link: http://sochi-lazarevsky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=153842329&delo_id=1540006&new=0&text_number=1, status: 200

 77%|███████▋  | 6065/7864 [2:11:10<1:07:10,  2.24s/it]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720527&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720527&delo_id=1540006&new=0&text_number=1

 78%|███████▊  | 6133/7864 [2:13:12<1:22:19,  2.85s/it]

not find text, link: http://mostovskay--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=109232077&delo_id=1540006&new=0&text_number=1, status: 200

 78%|███████▊  | 6141/7864 [2:13:40<1:30:03,  3.14s/it]

request error, link: http://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=212065394&delo_id=1540006&new=0&text_number=1, error: 504 Server Error: Gateway Time-out for url: https://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=212065394&delo_id=1540006&new=0&text_number=1

 78%|███████▊  | 6158/7864 [2:14:13<38:51,  1.37s/it]

request error, link: http://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=231510989&delo_id=1540006&new=0&text_number=1, error: 504 Server Error: Gateway Time-out for url: https://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=231510989&delo_id=1540006&new=0&text_number=1

 78%|███████▊  | 6167/7864 [2:14:38<1:19:29,  2.81s/it]

not find text, link: http://krasnodar-prikubansky--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=212065376&delo_id=1540006&new=0&text_number=1, status: 200

 78%|███████▊  | 6170/7864 [2:14:43<52:25,  1.86s/it]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=485dbe2b-048c-4605-a9d3-a79577b6a93a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 79%|███████▊  | 6180/7864 [2:14:58<1:10:52,  2.53s/it]

not find text, link: http://dinskoy--krd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=215881991&delo_id=1540006&new=0&text_number=1, status: 200

 79%|███████▊  | 6183/7864 [2:15:00<38:40,  1.38s/it]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=3ce31a12-5829-47ce-a79f-0190e2a0ba02&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 81%|████████  | 6339/7864 [2:17:20<15:21,  1.66it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720529&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720529&delo_id=1540006&new=0&text_number=1

 81%|████████  | 6370/7864 [2:17:43<23:01,  1.08it/s]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=2b94b75f-e5aa-4282-9d0a-0f9546b7504a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 83%|████████▎ | 6497/7864 [2:19:22<09:39,  2.36it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720532&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720532&delo_id=1540006&new=0&text_number=1

 88%|████████▊ | 6956/7864 [2:26:39<08:19,  1.82it/s]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8a3e779d-795a-4faf-933f-75e17274218e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 90%|████████▉ | 7076/7864 [2:28:37<22:53,  1.74s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=be9e3137-c20e-46ea-97a8-9e3553874710&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 90%|█████████ | 7095/7864 [2:28:59<10:40,  1.20it/s]

request error, link: http://orlovsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=185882185&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://orlovsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=185882185&delo_id=1540006&new=0&text_number=1

 94%|█████████▎| 7357/7864 [2:33:27<07:33,  1.12it/s]

not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=86412db5-04a4-45fe-8411-8bd31449f4f4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 94%|█████████▎| 7366/7864 [2:33:44<33:40,  4.06s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=1fbd26ba-d6d3-481f-96cc-499150342e7d&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

100%|█████████▉| 7845/7864 [2:41:22<00:43,  2.30s/it]

request error, link: http://sovetsky--mari.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=11367694&delo_id=1540006&new=0&text_number=1, error: 502 Server Error: Bad Gateway for url: https://sovetsky--mari.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=11367694&delo_id=1540006&new=0&text_number=1

100%|██████████| 7864/7864 [2:42:02<00:00,  1.24s/it]

In [3]:
print(df_with_link_text.shape)
df_with_link_text.head()

(7864, 3)

,id,link_text,text
0,102588,http://oblsud--kln.sudrf.ru/modules.php?name=s...,Решение по уголовному делу\nИнформация по делу...
1,24366,http://centr--cht.sudrf.ru/modules.php?name=su...,Решение по уголовному делу\nИнформация по делу...
2,24255,http://zabaykalsk--cht.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...
3,6258,http://pozharsky--prm.sudrf.ru/modules.php?nam...,Решение по уголовному делу
4,5018,http://leningradskay--krd.sudrf.ru/modules.php...,Решение по уголовному делу

In [4]:
df_with_link_text2 = df_with_link_text[df_with_link_text['link_text'].notna() & df_with_link_text['text'].isna()]
df_with_link_text2.shape

(129, 3)

In [5]:
out = find_text(df_with_link_text2)
df_with_link_text_new = pd.DataFrame(out, columns=['id', 'link_text', 'text'])

  2%|▏         | 2/129 [00:01<01:15,  1.68it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8e574f2c-e874-410d-b202-0e0f44d2fb6c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  4%|▍         | 5/129 [00:01<00:30,  4.07it/s]

not find text, link: http://gribanovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=bf8cf35d-f2a3-480b-b4ee-80d2a6adf005&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=79ba9464-8136-420a-bc8f-b865ffe5623d&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  5%|▍         | 6/129 [00:02<00:31,  3.85it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=13c4abd8-5664-4134-b375-a231ad70648a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  6%|▌         | 8/129 [00:02<00:27,  4.34it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=9ec1c3de-d500-46fd-bafc-0c8bd6e58356&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a9daa1c1-3cff-41b0-a4ef-af7b3f36b51a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  8%|▊         | 10/129 [00:03<00:28,  4.24it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=70e582ae-fd59-47c0-b6b4-130bab54dc8e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=64cf6592-f46c-4c3f-8126-d03e78557102&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  9%|▊         | 11/129 [00:03<00:36,  3.25it/s]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=eea9eef3-98f8-4b90-b218-e07093cec388&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

  9%|▉         | 12/129 [00:03<00:42,  2.75it/s]

not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=b80fbd2b-2578-486a-a79c-ddeebaee5d95&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 10%|█         | 13/129 [00:04<00:42,  2.73it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=d805996b-43dd-44ec-bb44-5cc106c0d66b&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 11%|█         | 14/129 [00:05<01:02,  1.83it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a16e6adf-270f-4245-8aba-f16dcc5c2ad5&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 12%|█▏        | 15/129 [00:17<07:35,  4.00s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=fe2bb63a-d85e-4e4a-8852-51bdada9e47c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 12%|█▏        | 16/129 [00:18<05:38,  3.00s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=6a79fa72-be69-41fb-a29f-07c0807c6e04&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 13%|█▎        | 17/129 [00:18<04:08,  2.22s/it]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=6ef59428-b160-4524-a86b-1ef5c3fb5209&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 14%|█▍        | 18/129 [00:19<03:12,  1.73s/it]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=78f6d581-040b-4c0c-b1a2-d20fd08b446f&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 16%|█▌        | 20/129 [00:19<01:52,  1.03s/it]

not find text, link: http://gribanovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=00ea581e-a36c-42c8-b917-8a3a99206421&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ba5b5bac-9de9-428e-bbfb-4c648f949036&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 16%|█▋        | 21/129 [00:20<01:40,  1.07it/s]

not find text, link: http://otstrogozhsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=9c6d5ed6-f811-4630-a539-d36a705436ce&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 17%|█▋        | 22/129 [00:20<01:22,  1.30it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=5681a9e2-d5e9-43c9-9206-c3d16ad1ccf6&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 18%|█▊        | 23/129 [00:21<01:04,  1.64it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=a177294d-86a2-447a-ac32-9e36088c8b07&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 19%|█▊        | 24/129 [00:21<00:58,  1.80it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=4bffd9e3-d9b9-48d1-b564-b0308dc2ca42&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 19%|█▉        | 25/129 [00:22<00:52,  2.00it/s]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=21bec423-5eb7-4ad1-b306-13d121e4d862&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 22%|██▏       | 28/129 [00:23<00:43,  2.35it/s]

not find text, link: http://paninsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=aaf5af1f-ee9b-4bbe-92c1-ce41d63c4554&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 23%|██▎       | 30/129 [00:24<00:43,  2.28it/s]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=04500961-cbc1-4472-8dd5-f0d21d329ff2&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 26%|██▌       | 33/129 [00:25<00:45,  2.13it/s]

not find text, link: http://liskinsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=4e89a21a-4e74-40dc-9bf6-9d2febad3a66&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 27%|██▋       | 35/129 [00:26<00:44,  2.13it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=bd1927b8-eeac-458e-9a5c-27005ed597a0&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8e8b9275-3a39-4a2e-9145-b1ff2e33f491&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 29%|██▉       | 38/129 [00:27<00:26,  3.48it/s]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=7640783c-3f79-4cca-a39a-9f65a62b7cbb&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8de145df-7dd3-417e-ad5f-be76b0307be4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 31%|███       | 40/129 [00:28<00:28,  3.12it/s]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=64602139-b40b-4a25-9eec-5c46345574a8&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200
not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8bc488cf-4dcc-4061-bda4-ec2b1acce359&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 32%|███▏      | 41/129 [00:29<00:46,  1.88it/s]

not find text, link: http://kashinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=522147fe-ad2e-419e-b8d1-9ddc3ccfd56e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 33%|███▎      | 42/129 [00:29<00:53,  1.62it/s]

not find text, link: http://kalacheevsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ada3e972-bae8-400e-a198-6d604b55913e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 33%|███▎      | 43/129 [00:30<00:57,  1.49it/s]

not find text, link: http://liskinsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=cc05c0c9-cb5f-4d5c-8aea-2755c5ec3063&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 34%|███▍      | 44/129 [00:31<00:56,  1.50it/s]

not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ee0a5c61-f6da-4946-a183-9ae2b83ab85c&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 36%|███▌      | 46/129 [00:36<02:31,  1.83s/it]

request error, link: http://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=122826035&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=122826035&delo_id=1540006&new=0&text_number=1

 36%|███▋      | 47/129 [00:37<01:55,  1.41s/it]

request error, link: http://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=3859765&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=3859765&delo_id=1540006&new=0&text_number=1

 38%|███▊      | 49/129 [00:38<01:30,  1.13s/it]

not find text, link: http://paninsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=16c5e932-eaa0-4250-b59b-6b231467d672&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 39%|███▉      | 50/129 [00:39<01:11,  1.10it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568244&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568244&delo_id=1540006&new=0&text_number=1

 40%|███▉      | 51/129 [00:42<02:07,  1.64s/it]

not find text, link: http://maksatihinsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=f526a1b5-976c-44cf-acdb-c0af66e6171b&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 40%|████      | 52/129 [00:43<01:36,  1.25s/it]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=c129c20c-9376-4de9-ab8f-5a91b667d1b8&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 41%|████      | 53/129 [00:43<01:19,  1.05s/it]

request error, link: http://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=116336038&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=116336038&delo_id=1540006&new=0&text_number=1

 43%|████▎     | 55/129 [00:51<02:43,  2.22s/it]

not find text, link: http://ostashkovsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=ef6ebe5b-c52b-4766-a022-51048db1b3a4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 44%|████▍     | 57/129 [00:55<02:24,  2.01s/it]

not find text, link: http://novousmansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=667d9236-a609-45fe-9a43-f4e623defbfc&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 45%|████▍     | 58/129 [00:56<01:48,  1.53s/it]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568534&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568534&delo_id=1540006&new=0&text_number=1

 47%|████▋     | 61/129 [01:00<01:26,  1.27s/it]

request error, link: http://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=35775188&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=35775188&delo_id=1540006&new=0&text_number=1

 49%|████▉     | 63/129 [01:01<01:00,  1.10it/s]

request error, link: http://peschanokopsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36699571&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://peschanokopsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36699571&delo_id=1540006&new=0&text_number=1
request error, link: http://nagaib--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=292914249&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://nagaib--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=292914249&delo_id=1540006&new=0&text_number=1

 51%|█████     | 66/129 [01:02<00:29,  2.12it/s]

request error, link: http://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288297869&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://bred--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288297869&delo_id=1540006&new=0&text_number=1
request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568786&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=63568786&delo_id=1540006&new=0&text_number=1

 55%|█████▌    | 71/129 [01:05<00:29,  1.98it/s]

request error, link: http://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=56833764&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://m-taiginskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=56833764&delo_id=1540006&new=0&text_number=1

 58%|█████▊    | 75/129 [01:08<00:29,  1.83it/s]

request error, link: http://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288469554&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://troickr--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=288469554&delo_id=1540006&new=0&text_number=1

 84%|████████▍ | 109/129 [01:34<00:09,  2.06it/s]

request error, link: http://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=130471486&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://salsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=130471486&delo_id=1540006&new=0&text_number=1

 87%|████████▋ | 112/129 [01:35<00:04,  3.57it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720527&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720527&delo_id=1540006&new=0&text_number=1

 91%|█████████▏| 118/129 [01:37<00:05,  2.15it/s]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=3ce31a12-5829-47ce-a79f-0190e2a0ba02&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 92%|█████████▏| 119/129 [01:38<00:04,  2.03it/s]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=2b94b75f-e5aa-4282-9d0a-0f9546b7504a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 93%|█████████▎| 120/129 [01:38<00:03,  2.41it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720532&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720532&delo_id=1540006&new=0&text_number=1

 94%|█████████▍| 121/129 [01:39<00:04,  1.86it/s]

not find text, link: http://rossoshansky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=8a3e779d-795a-4faf-933f-75e17274218e&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 95%|█████████▍| 122/129 [01:39<00:04,  1.73it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=be9e3137-c20e-46ea-97a8-9e3553874710&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 95%|█████████▌| 123/129 [01:42<00:07,  1.23s/it]

not find text, link: http://bezhecky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=485dbe2b-048c-4605-a9d3-a79577b6a93a&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 96%|█████████▌| 124/129 [01:43<00:05,  1.07s/it]

not find text, link: http://pavlovsky--vrn.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=86412db5-04a4-45fe-8411-8bd31449f4f4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 97%|█████████▋| 125/129 [01:44<00:03,  1.03it/s]

not find text, link: http://torzhoksky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=1fbd26ba-d6d3-481f-96cc-499150342e7d&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0, status: 200

 99%|█████████▉| 128/129 [01:45<00:00,  1.48it/s]

request error, link: http://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720529&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://todjinskiy--tva.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=53720529&delo_id=1540006&new=0&text_number=1

100%|██████████| 129/129 [01:47<00:00,  1.20it/s]

request error, link: http://orlovsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=185882185&delo_id=1540006&new=0&text_number=1, error: 404 Client Error: Not Found for url: https://orlovsky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=185882185&delo_id=1540006&new=0&text_number=1

In [6]:
print(df_with_link_text_new.shape)

df_with_link_text3 = df_with_link_text_new[df_with_link_text_new['link_text'].notna() & df_with_link_text_new['text'].isna()]
df_with_link_text3.shape

(129, 3)

(65, 3)

In [7]:
df_with_link_text_new[df_with_link_text_new['text'].notna()].head()

,id,link_text,text
0,2841,http://baltachevsky--bkr.sudrf.ru/modules.php?...,Решение по уголовному делу\nИнформация по делу...
3,3927,http://meleuzovsky--bkr.sudrf.ru/modules.php?n...,Решение по уголовному делу\nИнформация по делу...
25,61891,http://oblsud--mo.sudrf.ru/modules.php?name=su...,Решение по уголовному делу\nИнформация по делу...
26,65314,http://pervouralsky--svd.sudrf.ru/modules.php?...,Решение по уголовному делу\nИнформация по делу...
29,57880,http://pinegasud--arh.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...

In [8]:
df_merged = df_with_link_text.merge(df_with_link_text_new, on="id", how="left", suffixes=("", "_new"))
df_merged["text"] = df_merged["text"].fillna(df_merged["text_new"])
df_with_link_text_final = df_merged[["id", "link_text", "text"]]
df_with_link_text_final.head()

,id,link_text,text
0,102588,http://oblsud--kln.sudrf.ru/modules.php?name=s...,Решение по уголовному делу\nИнформация по делу...
1,24366,http://centr--cht.sudrf.ru/modules.php?name=su...,Решение по уголовному делу\nИнформация по делу...
2,24255,http://zabaykalsk--cht.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...
3,6258,http://pozharsky--prm.sudrf.ru/modules.php?nam...,Решение по уголовному делу
4,5018,http://leningradskay--krd.sudrf.ru/modules.php...,Решение по уголовному делу

In [9]:
print(df_with_link_text_final.shape)
df_with_link_text4 = df_with_link_text_final[df_with_link_text_final['link_text'].notna() & df_with_link_text_final['text'].isna()]
df_with_link_text4.shape

(7864, 3)

(65, 3)

In [10]:
df_with_link_text_final.to_csv('df_with_link_text_final.csv', index=False)