# Первоначальный анализ данных

In [1]:
import pandas as pd

df = pd.read_csv('data_full_murders_with_accused_v20240328.csv', sep=";")

In [2]:
df.head()

,id,region,year,instance,court_name,caseNumber,entryDate,names,judge,resultDate,...,endDate,consideredBy,cui,accused,hash,articles,link_meta,link_text,is_text,text
0,0,1,2016,FIRST,ВЕРХОВНЫЙ СУД РЕСПУБЛИКИ АДЫГЕЯ,2-3/2016,01.04.2016,"<Информация скрыта> - ст.132 ч.2 п.а УК РФ, <И...",Глуходед Елена Владимировна,2016-07-19,...,13.10.2016,Рассмотрено единолично судьей,01OS0000-01-2016-000064-04,<Информация скрыта>,a0538e978cd931a812452d7f38eab79a,"ст.132 ч.2 п.а, ст.132 ч.2 п.а, ст.105 ч.2 п.к",http://vs--adg.sudrf.ru/modules.php?name=sud_d...,NaN,False,NaN
1,1,1,2016,APPELLATION,ВЕРХОВНЫЙ СУД РЕСПУБЛИКИ АДЫГЕЯ,22-407/2016,03.08.2016,Абдырахманов Руслан Райкович - УК РФ: ст. 105 ...,Набокова Асланхан Мухтаровна,2016-08-23,...,NaN,NaN,NaN,Абдырахманов Руслан Райкович,37cc12034234cb3635eca42e5a9dfdc2,ст. 105 ч.2 п. ж,http://vs--adg.sudrf.ru/modules.php?name=sud_d...,NaN,False,NaN
2,2,1,2016,APPELLATION,ВЕРХОВНЫЙ СУД РЕСПУБЛИКИ АДЫГЕЯ,22-411/2016,05.08.2016,"Вовк Юлия Сергеевна - УК РФ: ст. 105 ч.1, ст. ...",Кадакоева Мариет Масхудовна,2016-08-19,...,NaN,NaN,NaN,Вовк Юлия Сергеевна,b5fc669a7146a712161a34aca31ba412,"ст. 105 ч.1, ст. 167 ч.2",http://vs--adg.sudrf.ru/modules.php?name=sud_d...,NaN,False,NaN
3,3,1,2016,APPELLATION,ВЕРХОВНЫЙ СУД РЕСПУБЛИКИ АДЫГЕЯ,22-352/2016,07.07.2016,Болдарев Алексей Николаевич - УК РФ: ст. 105 ч...,Набокова Асланхан Мухтаровна,2016-07-22,...,NaN,NaN,NaN,Болдарев Алексей Николаевич,158491aa470c8d068281643cfddda218,ст. 105 ч.1,http://vs--adg.sudrf.ru/modules.php?name=sud_d...,http://vs--adg.sudrf.ru/modules.php?name=sud_d...,True,Федеральный судья Бражников Е.Г. Дело № 22– 35...
4,4,1,2016,APPELLATION,ВЕРХОВНЫЙ СУД РЕСПУБЛИКИ АДЫГЕЯ,22-89/2016,08.02.2016,Рожков Виктор Михайлович - УК РФ: ст. 105 ч.1 ...,Певнев Сергей Викторович,2016-02-26,...,NaN,NaN,NaN,Рожков Виктор Михайлович,08e72d1e44e74386205c5bd670ac5faa,ст. 105 ч.1,http://vs--adg.sudrf.ru/modules.php?name=sud_d...,NaN,False,NaN

In [3]:
df.shape

(135149, 21)

In [4]:
df.dtypes

id               int64
region           int64
year             int64
instance        object
court_name      object
caseNumber      object
entryDate       object
names           object
judge           object
resultDate      object
decision        object
endDate         object
consideredBy    object
cui             object
accused         object
hash            object
articles        object
link_meta       object
link_text       object
is_text           bool
text            object
dtype: object

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.notna().sum()

id              135149
region          135149
year            135149
instance        135149
court_name      135149
caseNumber      135149
entryDate       135149
names           135149
judge           130919
resultDate      135149
decision        135126
endDate          59215
consideredBy     48274
cui              57269
accused         135098
hash            135098
articles        135149
link_meta       135149
link_text        72998
is_text         135149
text             71564
dtype: int64

In [11]:
df.isna().sum()

id                  0
region              0
year                0
instance            0
court_name          0
caseNumber          0
entryDate           0
names               0
judge            4230
resultDate          0
decision           23
endDate         75934
consideredBy    86875
cui             77880
accused            51
hash               51
articles            0
link_meta           0
link_text       62151
is_text             0
text            63585
dtype: int64

In [8]:
df.isnull().sum()

id                  0
region              0
year                0
instance            0
court_name          0
caseNumber          0
entryDate           0
names               0
judge            4230
resultDate          0
decision           23
endDate         75934
consideredBy    86875
cui             77880
accused            51
hash               51
articles            0
link_meta           0
link_text       62151
is_text             0
text            63585
dtype: int64

In [12]:
for col in df.columns:
    unique = df[col].unique()
    print(col, unique.size, unique)
    print("")

id 135149 [ 92093 116367  25775 ... 133199 131903 133200]

region 87 [55  5 79 42  3 65 24 14 26 38 61 16 30 72 87 78 66 50 74 47 62 17 52 11
 39 75 67 54 95 32 25 86  9 18 77 15 48 33 53 82 34  2  7 23 45 27 60 28
 22 36 92 68 89 63 49  4 70 19 69 71 56 10 46 57 41 76 29 58 21 37 51 13
 35 40 59 44 31 43 64 12 73  1  8 83 20 91  6]

year 9 [2020 2022 2016 2019 2023 2018 2017 2021 2024]

instance 2 ['FIRST' 'APPELLATION']

court_name 2231 ['Первомайский районный суд г. Омска' 'Верховный Суд Республики Дагестан'
 'Облученский районный суд Еврейской автономной области' ...
 'Ярославский гарнизонный военный суд'
 'Ставропольский гарнизонный военный суд'
 'Тульский гарнизонный военный суд']

caseNumber 74795 ['1-2/2020 (1-2/2019, 1-2/2018, 1-2/2017, 1-2/2016, 1-2/2015, 1-2/2014, 1-3/2013, 1-3/2012, 1-3/2011, 1-3/2010, 1-4/2009, 1-4/2008, 1-4/2007,)'
 '2-1/2022 (2-1/2021, 2-1/2020, 2-2/2019, 2-1/2018, 2-1/2017, 2-1/2016, 2-1/2015, 2-1/2014, 2-1/2013, 2-1/2012, 2-1/2011, 2-1/2010, 2-1/2009, 2-1/2008,)'
 '1-2/2016 (1-2/2015, 1-2/2014, 1-2/2013, 1-2/2012, 1-4/2011, 1-5/2010, 1-6/2009, 1-7/2008, 1-25/2007, 1-2/2006, 1-2/2005, 1-2/2004, 1-2/2003, 1-2/2002, 1-2/2001, 1-2/2000, 1-4/1999,)'
 ... '10К-9031/2023' '22К-9974/2023' '10К-9025/2023']

entryDate 2379 <DatetimeArray>
['1998-07-14 00:00:00', '1998-08-24 00:00:00', '1999-01-15 00:00:00',
 '2000-08-02 00:00:00', '2005-07-12 00:00:00', '2006-06-14 00:00:00',
 '2006-10-10 00:00:00', '2008-07-25 00:00:00', '2008-12-23 00:00:00',
 '2009-03-11 00:00:00',
 ...
 '2023-12-13 00:00:00', '2023-12-14 00:00:00', '2023-12-15 00:00:00',
 '2023-12-18 00:00:00', '2023-12-19 00:00:00', '2023-12-20 00:00:00',
 '2023-12-21 00:00:00', '2023-12-22 00:00:00', '2023-12-25 00:00:00',
 '2023-12-26 00:00:00']
Length: 2379, dtype: datetime64[ns]

names 123722 ['Яковлев Владимир Николаевич - ст. 116 ч.1, ст. 105 ч.1 УК РФ'
 '<Информация скрыта> - ст. 30 ч.3, ст.105 ч.2 п.з, ст.162 ч.4 п.в, ст.228 ч.1 УК РФ'
 'Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ' ...
 '<Информация скрыта> - ст.30 ч.3, ст.105 ч.1 УК РФ Суд (судебный участок) первой инстанции: Ленинский суд (г.Челябинск) Номер дела в первой инстанции: 3/1-133/2023'
 'Рублев Иван Игоревич Закрытое судебное заседание (ст. 241 УПК РФ) - ст.30 ч.3, ст.105 ч.2 п.в, ст.127 ч.2 пп.г,д УК РФ Суд (судебный участок) первой инстанции: Орджоникидзевский районный суд г. Екатеринбурга Номер дела в первой инстанции: 3/2-129/2023'
 '<Информация скрыта> - ст.105 ч.1 УК РФ Суд (судебный участок) первой инстанции: Тракторозаводский Номер дела в первой инстанции: 1-846/2023']

judge 14068 ['Толстых Артём Александрович' 'Исрафилов Закир Эфендиевич' 'Сон А.И.' ...
 'Мамаева Яна Юрьевна' 'Зиганшин Д.К.' 'Беспалов Олег Валериевич']

resultDate 2195 ['2020-12-30' '2022-12-23' '2016-10-31' ... '2024-02-07' '2024-02-13'
 '2024-01-26']

decision 62 ['Вынесен ПРИГОВОР'
 'ВОЗВРАЩЕНО ПРОКУРОРУ или РУКОВОДИТЕЛЮ СЛЕДСТВЕННОГО ОРГАНА'
 'Уголовное дело ПРЕКРАЩЕНО'
 'Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА'
 'Направлено ПО ПОДСУДНОСТИ (подведомственности)' 'Изменено'
 'Вступило в силу' 'ВЫНЕСЕНО РЕШЕНИЕ (ОПРЕДЕЛЕНИЕ)' 'Отменено' nan
 'Вынесен приговор' 'СНЯТО по ДРУГИМ ОСНОВАНИЯМ'
 'Представление (жалоба) ОТОЗВАНЫ' 'для дооформления'
 'Апелляционное (кассационное до 2013г) производство ПРЕКРАЩЕНО'
 'Вынесено определение суда апелляционной инстанции'
 'Вынесено постановление суда апелляционной инстанции'
 'Оставить определение (постановление) без изменения'
 'ВОЗВРАЩЕНО ПРОКУРОРУ' 'Возвращено' 'Возвращено без рассмотрения'
 'возвращено для дооформления' 'Прекращено'
 'Принудительные меры к невменяемым' 'Служебная проверка'
 'Дело присоединено к другому делу' 'В связи с неправильным оформлением'
 'Отозвано представление' 'Изменить определение (постановление) частично'
 'Дело снято и направлено в суд 1-й инстанции на дооформление'
 'возвращено в суд 1 инстанции без рассмотрения' 'Отозвана жалоба'
 'Отменить определение (постановление) полностью, дело вернуть на новое рассмотрение'
 'служебная проверка'
 'Приостановлено - Обвиняемый скрылся и место его пребывания неизвестно'
 'ненадлежащие оформление' 'ст.259-260 УПК' 'Обжаловано' 'Завершено'
 'Вынесено другое ПОСТАНОВЛЕНИЕ' 'Ст. 389.7 УПК РФ' 'Отменено апелляцией'
 'ОТКАЗАНО в принятии заявления к производству'
 'Отменить определение (постановление), дело прекратить'
 'Отменить определение (постановление) полностью, вынести новое решение'
 'СНЯТО с апелляционного рассмотрения'
 'Апелляционное ПРОИЗВОДСТВО ПРЕКРАЩЕНО' 'Передано по подсудности'
 'По запросу суда' 'Назначено судебное заседание на 17.11.2020 10:40'
 'Отложено до 21.12.2020 09:20 (Недоставление подсудимого)'
 'Отменено кассацией'
 'Вынесено постановление о роспуске коллегии присяжных заседателей и направлении уголовного дела на новое рассмотрение'
 'Зарегистрировано' 'Постановление приговора до 05.05.2021 15:22'
 'Назначено судебное заседание на 02.03.2021 09:30'
 'Обжаловано в кассации'
 'Назначено судебное заседание на 11.05.2021 12:15'
 'Назначено судебное заседание на 02.09.2022 11:00'
 'Назначено судебное заседание на 15.11.2021 12:00' 'Ст. 389.6 УПК РФ'
 'ст. 389.6 УПК РФ']

endDate 2504 ['04.03.2021' nan '11.11.2016' ... '14.01.2024' '29.02.2024' '27.01.2024']

consideredBy 16 ['Рассмотрено единолично судьей' nan
 'Рассмотрено с участием присяжных заседателей'
 'Рассмотрено коллегией из трех федеральных судей'
 'Номер судебного состава: 8' 'Номер судебного состава: 9'
 'Номер судебного состава: 5' 'Номер судебного состава: 6'
 'Номер судебного состава: 2' 'Номер судебного состава: 7'
 'Номер судебного состава: 4' 'Номер судебного состава: 3'
 'Номер судебного состава: 1' 'Номер судебного состава: 10'
 'Номер судебного состава: 12' 'Номер судебного состава: 11']

cui 50948 ['55RS0005-01-1998-000001-11' nan '42OS0000-01-2000-000001-76' ...
 '77RS0002-02-2023-009318-52' '77RS0013-02-2023-013331-40'
 '66RS0006-02-2023-001088-70']

accused 75702 ['Яковлев Владимир Николаевич' '<Информация скрыта>'
 'Искяндаров Джамбар Мехти Оглы' ... 'Хмельницкий Михаил Викторович'
 'Кашин Григорий Владимирович' 'Рублев Иван Игоревич Закрытое, Упк Рф']

hash 75702 ['0f1758e9ae2f4ef690d49cfc666cf44e' 'a0538e978cd931a812452d7f38eab79a'
 'aa456a98421dd7844543190b87d6ded8' ... '865f0e3296081db81969e27343009e68'
 '196159d8a93732d9129e1b70881999f2'
 '4988970860bea578753bc695e4bde6b9, 8f7400601ea3e44eceb3a7178ab6be60']

articles 19845 ['ст. 116 ч.1, ст. 105 ч.1'
 'ст. 30 ч.3, ст.105 ч.2 п.з, ст.162 ч.4 п.в, ст.228 ч.1' 'ст.105 ч.1' ...
 'ст.105 ч.2 п.ж, ст.226 ч.3 п.а, ст.105 ч.2 п.ж, ст.226 ч.3 п.а '
 'ст.33 ч.5, ст.105 ч.2 пп.а,ж,з,л '
 'ст. 241 , ст.30 ч.3, ст.105 ч.2 п.в, ст.127 ч.2 пп.г,д ']

link_meta 135149 ['http://pervomaycourt--oms.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=246722896&case_uid=5c3a32a3-e3bb-40e5-a3f7-e921e8d5b2a7&delo_id=1540006'
 'http://vs--dag.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=10154025&case_uid=8eff52d8-4126-4643-ae7a-ac1c920740db&result=1&delo_id=1540006'
 'http://obluchensky--brb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=4217637&case_uid=870b1dee-755d-4252-8909-5aa451f55d1a&delo_id=1540006'
 ...
 'http://oblsud--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=44769728&case_uid=20212b31-e523-41dd-8b56-e62c8c52c19e&delo_id=4&new=4'
 'http://oblsud--svd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=13030337&case_uid=e5b5a919-5f7a-4d92-8394-ad67836b25ba&delo_id=4&new=4'
 'http://oblsud--chel.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=case&case_id=44769686&case_uid=63ced044-b426-42b9-8071-074a3c8e4758&delo_id=4&new=4']

link_text 72999 ['http://pervomaycourt--oms.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=131515816&delo_id=1540006&new=0&text_number=1'
 nan
 'http://obluchensky--brb.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=745513&delo_id=1540006&new=0&text_number=1'
 ...
 'http://vs--krm.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=15912130&delo_id=4&new=4&text_number=1'
 'http://oblsud--brj.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=11753307&delo_id=4&new=4&text_number=1'
 'http://kraevoy--stv.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=36533388&delo_id=4&new=4&text_number=1']

is_text 2 [ True False]


In [13]:
df = df.sort_values(by="entryDate")

In [18]:
df = df[df['instance'] == 'FIRST']

In [ ]:
df = df[(df['link_text'].notna()) | (df['text'].notna())]
print(df.shape)

(43728, 21)

In [20]:
df['decision'].value_counts()

decision
Вынесен ПРИГОВОР                                              40842
Вступило в силу                                                1096
Уголовное дело ПРЕКРАЩЕНО                                       986
ВОЗВРАЩЕНО ПРОКУРОРУ или РУКОВОДИТЕЛЮ СЛЕДСТВЕННОГО ОРГАНА      276
Изменено                                                        167
Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА            127
Направлено ПО ПОДСУДНОСТИ (подведомственности)                  108
Отменено апелляцией                                              38
Отменено                                                         37
Обжаловано в кассации                                            14
Обжаловано                                                        9
Отменено кассацией                                                4
Дело присоединено к другому делу                                  3
Принудительные меры к невменяемым                                 1
Возвращено                                                        1
Передано по подсудности                                           1
Постановление приговора до 05.05.2021 15:22                       1
Назначено судебное заседание на 02.09.2022 11:00                  1
Name: count, dtype: int64

In [27]:
df2 = df[(df['link_text'].notna()) & (df['text'].isna())]
print(df2.shape)
df2['decision'].value_counts()

(8192, 21)

decision
Вынесен ПРИГОВОР                                              7859
Уголовное дело ПРЕКРАЩЕНО                                      238
ВОЗВРАЩЕНО ПРОКУРОРУ или РУКОВОДИТЕЛЮ СЛЕДСТВЕННОГО ОРГАНА      62
Направлено ПО ПОДСУДНОСТИ (подведомственности)                  24
Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА             6
Дело присоединено к другому делу                                 1
Name: count, dtype: int64

In [31]:
df1 = df[df['decision'] == 'Уголовное дело ПРЕКРАЩЕНО']
print(df1['link_text'].to_numpy()[:5])

['http://kozul--krk.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=25714630&delo_id=1540006&new=0&text_number=1'
 'http://olov--cht.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=8927979&delo_id=1540006&new=0&text_number=1'
 'http://gusinoozersky--bur.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=209795781&delo_id=1540006&new=0&text_number=1'
 'http://borzya--cht.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=11692039&delo_id=1540006&new=0&text_number=1'
 'http://zheleznodorozhny--hbr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=3161326&delo_id=1540006&new=0&text_number=1']

In [36]:
df1 = df[df['decision'] == 'Вступило в силу']
print(df1['text'].to_numpy()[:5])

['PAGE21Дело № 1-25-2016-17П Р И Г О В О РИменем Российской Федерацииг.Москва18 января 2016 годаЛюблинский районный суд г.Москвы в составе председательствующего судьи Маслова А.В.\nпри секретаре Охановой А.В., Утяцкой Н.Ю., Эльдяевой А.И.\nс участием государственного обвинителя- помощника Люблинского межрайонного прокурора г.Москвы Дребезова М.В., Шнахова В.К.\nподсудимого Футорянского А.Б.\nзащитников Прошкина Л.Г., Прошкина Г.Л., Лебедева В.Ю. представивших удостоверения №№№ и ордера №№№,потерпевшего ФИО.\nрассмотрев в открытом судебном заседании материалы уголовного дела в отношении:\nФуторянского А.Б., иные данные обвиняемого в совершении преступления, предусмотренногоч.1 ст.105 УК РФ,У С Т А Н О В И Л :Футорянский А.Б. виновен в том, что совершил убийство, то есть умышленное причинение смерти другому человеку.\nПреступления совершены при следующих обстоятельствах.Так он, 14 января 2014 года в период с 00 часов\n30 минут по 06 часов 00 минут, более точное время следствием не установлено, находясь в квартире по месту своего фактического проживания по адресу: адрес, будучи в состоянии агрессии, обусловленной алкогольным опьянением и личными неприязненными отношениями, возникшими в процессе совместного проживания со своей матерью ФИО1 решил совершить убийство последней.\nВо исполнение своего преступного умысла, направленного на убийство ФИО1, Футорянский А.Б. осознавая противоправный характер своих действий и желая этого подверг потерпевшую избиению, нанеся ей не менее 8 ударов руками по лицу и конечностям, после чего подобрал на месте происшествия петлю из неустановленного материала, которую умышленно, с целью убийства обмотал вокруг шеи ФИО1 и совершил удушение путем затягивания петли на шее последней.\nВ результате преступных действий Футорянского А.Б. потерпевшей ФИО1 были причинены следующие телесные повреждения: овальные ссадины в лобной области, на спинке и левом крыле носа, полосовидные кровоподтеки на верхнем веке правого глаза и в правой щечной области, округлые и овальные кровоподтеки (3) по нижнему краю левой ключицы, на задней поверхности правого предплечья в нижней трети и в области запястья, 2,3 и 4 пальцах правой кисти, не являющиеся опасными для жизни и не расценивающиеся как вред здоровью, одиночная замкнутая горизонтально расположенная на границе средней и нижней трети шеи равномерно вдавленная странгуляционная борозда, разветвляющаяся на передней поверхности шеи с образованием перекреста у нижнего края щитовидного хряща, полосовидные поперечные и косопоперечные линейные, а также множественные мелкие ссадины на передней и боковой поверхностях шеи и на подбородке, обширные кровоизлияния в толще кожи, подкожной жировой клетчатке и мышцах на уровне, выше и ниже странгуляционной борозды, полные переломы обоих верхних рогов щитовидного хряща, возникших в результате неоднократных сдавлений шеи одиночной полумягкой тонкой петлей, затянутой посторонней рукой на передней поверхности шеи, в сочетании со смещениями петли верх и вниз, повлекшие за собой развитие асфиксии, причинившие тяжкий вред здоровью опасный для жизни и состоящее в прямой причинно-следственной связи с наступлением смерти, последовавшей на месте происшествия в результате механической асфиксии вследствие сдавления шеи петлей.После убийства ФИО1, желая сокрыть следы совершенного им преступления и уклониться от уголовной ответственности за содеянное, Футорянский А.Б. вынес труп ФИО1 на лестничную клетку 4 этажа по вышеуказанному адресу.\nДопрошенный в судебном заседании подсудимый Футорянский А.Б. вину в предъявленном обвинениине признал и показал, что к убийству ФИО1 он не причастен, указал, что убийство совершила его бывшая жена –ФИО2 По существу показал, что между его мамой и женой отношения были плохие. Отношения у них ухудшались после рождения старшего сына в 2010 году. У жены были приступы, до свадьбы они тоже случались, она лечилась у психиатра, а после рождения второго сына у бывшей жены приступы стали чаще. Мама ему жаловалась, что его жена не дает ей общаться с внуками. Они искали варианты для покупки квартиры в адрес. В октябре или ноябре маме потребовалась операция, и прекратили поиски квартиры. По этому поводу случился скандал. 13 января 2014 года с 19 часов до 23 часов оннаходился на семинаре, уехал из дома в 16 часов с начала на собеседование, а потом на семинар.На семинаре был до 22 часов 30 минут. Свою мать до отъезда из дома он видел. Жена ему позвонила и спрашивала когда он приедет, отправляла СМС, оннаписал, что будет в течение часа. Примерно в 00 часов 30 минут приехал домой,разделся и пошел в комнату, где его ждала жена. Жена рассказала про детей,потом переоделась и легла. Когда мы с ней разговаривали, он увидел у нее на руках ссадины.Он спросил, что это, она сказала, что расчесала.Жена потом пошла к детям, а он пошел на кухню поесть, потом пошел на балкон читать, находясь набалконе, он услышал хлопок. После чегозашел в квартиру, входная дверь была открыта, он закрыл ее,вернулся в комнату и лег спать. Это было где-тов 02 -2.30 часа ночи. На следующий день 14 января 2014 годапроснулся часов в 10. Женаспросила, не уезжаю ликуда-нибудь, поскольку надо посидеть с младшим сыном, которогоона положила спать. Сама ушла со старшим сыном в поликлинику. Он открыл дверь в комнату, чтобы было слышно. Через некоторое время они вернулись.Старший сын пришел к нему в комнату слушать музыку, а жена взяла стала убираться у входной двери.Старший сын спросил, где бабушка, жена сказала, что она у врача. После чего старший сын пошел спать, а жена с младшим сыном пришла и села на диван, стала плакать, он спросил, что случилось, она сказала, что ее надо спасти. Он подумал, что у жены начался приступ, и сел на пол перед ней. Она сказала, что подралась с мамой и убила ее. Он спросил, где она подралась, она сказала, что на кухне. Он спросил, гдеона, на что жена ответила, что она ее вынесла к лифту. В этот моменту жены случилась истерика. Он взял младшего сына, а жена пошла успокаиваться. Сынаположил спать и сел за компьютер.К лифту он не пошел, через некоторое времязашла жена и попросила выйти в коридор, на пороге квартиры он увидел сотрудников полиции. На площадке была женщина. Он вышел на лестницу и увидел свою маму. Ему сказали принести документы, но в квартире он не нашел сумку, где могли быть документы, о чемсказал сотрудникам полиции. Он стал звонить на мобильный телефон маме, но звонок не услышал. Прошел в комнатумамы и увидел сумку у стены высоко, я посмотрел, чтобы найти телефон и паспорт. Сотрудники полиции сказали взять свои документы и проехать с ними.Кровать мамы была застелена, а ночная ее рубашка была расстелена на кровати. Мама не могла застелить кровать покрывалом. В отделе полиции его обыскали, поднялись на 4 этаж, одели наручники и требовали признаться. Показания у него брали ночью, без разрешения взяли отпечатки пальцев со стола в коридоре. Когда велся допрос бывшей жены, она предположила, что маму убил маньяк, когда она выносила мусор. В отделе полиции всю ночь не выводили в туалет, а утром на следующий день одели наручники,и отвезли в следственный комитет. В следственном комитете в коридоре он общался с адвокатом Лебедевым, но свидетеля ФИО3 он не видел.\nНесмотря на позицию подсудимого его вина подтверждается следующими доказательствами:\nПоказаниями допрошенного в судебном заседании потерпевшего ФИО. из которых следует, что он является двоюроднымбратом ФИО1, очевидцем событий не был. О том, что произошло, он узнал от другого двоюродного брата. Знал, что между подсудимым и его мамой были конфликты, и у него не имеется сомнений о том, что убийство ФИО2 Елизаветы совершил подсудимый.Показаниями допрошенного в судебном заседании свидетеля ФИО2,из которых следует, что подсудимый является ее бывшем мужем. После переезда в Москву, проживали в адрес, проживали вместе с его мамой, конфликтов не было, помогали друг другу. Подсудимый был достаточно агрессивным как к ней, так и к своей матери- ФИО1всегда использовал нецензурную речь. Во время проживания в квартире ФИО1жила в одной комнате, она с детьми в другой, а Футорянский А.Б. в третьей комнате. 13 января 2014 года был обычный день, Футорянский А.Б. около 16 часов уехал на семинар, но перед отъездом у него с его мамой был конфликт, который она не слышала, но разговор был на повышенных тонах. В тот же день она примерно в 23 часа разговаривала с Футорянским А.Б. по телефону, домой он вернулся около 00 часов 30 минут 14 января 2014 года и от него исходил запах алкоголя, также пояснила, что он употреблял наркотические вещества- курил траву. Когда Футорянский А.Б. пришел домой она зашла к нему в комнату и попыталась поговорить, но он былне в настроении, на вопросы он ни чего не ответил, поговорили о детях, вступила в интимную связь, а затем пошла в комнату к детям спать. Через некоторое время услышала, что из комнаты вышла ФИО1и слышала ее разговор с Футорянским А.Б., она поняла, что его мама обратилась к нему с просьбой, но он ей резко ответил и хлопнула дверь, разговор прервался, потом она опять услышала, что ФИО1хотела поговорить с Футорянским А.Б., но он опять ее оборвал нецензурной бранью и услышала как громко хлопает межкомнатная дверь, но в какую комнату она не поняла, затем услышала еще стук, поняла. Что это был стук шкафа в комнате ФИО1и услышала как она крикнула: « Саша остановись, перестань», она из комнаты не вышла, так как проснулся ребенок. Затем услышала, что Футорянский вышел из комнаты и открылась входная дверь из квартиры и Футорянский ушел, вернулся минут через 10, но входную дверь не закрыл, услышала как закрывается межкомнатная дверь, также услышала тяжелые и медленные шаги, снова открылась входная дверь, а затем закрылась. Через некоторое время услышала, что дверь закрылась на замки и Футорянский ходил по квартире, затем уснула. 14 января 2014 года она проснулась около 08 часов, записала ребенка к врачу, зашла к Футорянскому в комнату и попросила посидеть его с младшим ребенком, так как со старшим собиралась идти к врачу. Затем старший ребенок забежал к ФИО1в комнату и спросил где бабушка, она сказала, что она ушла в поликлинику, но сама понимала, что это ни так, так как ночью поняла, что она умерла. О том, что произошло ночью, она у Футорянского не спрашивала. Затем ушла в поликлинику, вернувшись, хотела идти гулять с младшим ребенком, но домой пришла полиция и спросили все ли дома, она сказала, что дома нет бабушки. Сотрудники спросили чья мама, она ответила мама мужа и они попросили чтобы вышел муж. Футорянский А.Б. вышел из квартиры, а она осталась дома, через 10 минут Футорянский вернулся с криком: «Юля, нашу маму убили, где ее вещи», и побежал к ней в комнату. Следом зашли полицейские и сказали, что им необходимо проехать с ними и она поняла, что ей ранее казалось стало реальностью. Видела, что труп находился на лестничной площадке, а дверь на лестничную площадку всегда закрыта. После позвонила своей маме в г.Тверь и попросила ее приехать и посидеть с детьми. Затем были допросы в полиции и следственном комитете. ФИО1она сама видела 13 января 2014 года в 20 часов 30 минут, когда она выносила мусор, а она в это время мыла ребенка в ванной.Из оглашенных в порядке ст.281 УПК РФ показаний свидетеля ФИО2 данных в ходе предварительного следствия следует, что фактически проживает по адресу: адрес, совместно с мужем Футорянским А.Б., сыновьями ФИО6и ФИО7, а также со свекровью ФИО1 С Футорянским А.Б. она познакомилась в декабре 2008 года. Футорянский А.Б. рос со своей матерью. Родители развелись, когда он был маленьким. Муж был единственным ребенком в семье. Воспитанием сына занималась ФИО1, а также дедушка и бабушка Футорянского А.Б. Какое-то время Футорянский А.Б. работал в Государственной Думе РФ, после чего работал в 3-4 различных коммерческих компаниях финансистом. За достаточно короткий срок смог заработать большие деньги. Семью полностью обеспечивал муж. После рождения первого сына, муж ушел с работы. Практически все время он сидел дома. В настоящее время он зарабатывает на жизнь, торгуя на бирже. Кроме того, он посещает курсы по повышению квалификации в сфере торговли на бирже. Футорянского А.Б. может охарактеризовать как импульсивного, вспыльчивого человека. Не может назвать его агрессивным, но он может с легкостью оскорбить человека. Футорянский А.Б. властный человек. Она привыкла к тому, что он может оскорбить ее, отругать и уйти, но она привыкла к этому. Физическое насилие к ней и к детям, Футорянский А.Б. никогда не применял. С ФИО1 у нее были нормальные отношения. Последняя никогда не вмешивалась в отношения с мужем либо в ведение совместного хозяйства. Была спокойной, мягкой, неконфликтной. Ссор у них никогда не было. У ФИО1 и Футорянского А.Б. отношения были нормальными. Но в силу своего характера, он мог спокойно накричать на нее, высказать свое недовольство. В силу своего возраста ФИО1 стала занудным человеком, что сильно раздражало мужа. В настоящий момент у нее имеются проблемы с ногами, поэтому она из дома практически не выходит. Дома она помогала им с детьми и с работой по дому, в силу своих возможностей и возраста.Квартира в которой они проживают принадлежит ФИО1, однако у мужа есть своя двухкомнатная квартира в адрес. Туда они периодически приезжают, когда встречаются с его друзьями. Футорянский А.Б. периодически выпивает, но алкоголем никогда не злоупотреблял. Иногда Футорянский А.Б. курит марихуану, травм головы либо иных серьезных заболеваний у него не было.\n13.01.2014 она весь день находилась дома с детьми, только один раз выходила на улицу с детьми. Дома также находилась свекровь и муж. У Футорянского А.Б. в этот день было запланировано собеседование и курсы, связанные с торговлей на бирже. В этот день днем между мужем и свекровью произошел конфликт. Свекровь пришла к мужу и хотела решить какой-то вопрос, что именно она хотела от него, ей не известно. Муж в грубой форме послал ФИО1 после чего они стали ругаться. Так как она и дети находились возле них, то посчитала нужным увести детей из кухни. Пройдя в комнату, они не выходили, пока не ушел муж. В связи с тем, что у них маленькие дети, она сними спит в одной комнате, а Футорянский А.Б. – в другой, чтобы дети не мешали ему спать.\nПримерно в 20 часов 00 минут она написала мужу смс, что ужин готов и она ждет его. Далее примерно в 23 часа 00 минут она уложила детей спать. Сама легла спать примерно в 23 часа 40 минут. Затем примерно в 00 часов 30 минут 14.01.2014 она проснулась от того, что хлопнула входная дверь. Тогда она поняла, что домой пришел муж. Она встала и направилась в комнату к мужу. Стала расспрашивать, что было у него интересного на курсах. Муж неохотно разговаривал с ней, отчего она поняла, что он в плохом настроении. Тогда она стала рассказывать ему про свой день и про детей. Обычно муж любит слушать ее истории, но в этот раз он не захотел. Кроме того, она спросила у мужа, по поводу чего он ссорился с матерью, но он сказал, что это не ее дело. Она попрощалась с ним и ушла к себе. Зайдя в комнату, она услышала как в это время из своей комнаты выходит ФИО1 Она же не стала останавливаться, а зашла к себе и закрыла дверь. В этот момент из своей комнаты выходил муж и в коридоре встретился с матерью. Она вновь стала что-то расспрашивать у него, она хотела решить какой-то вопрос, однако муж в грубой форме сказал, что это тема закрыта. Затем она пошла в туалет, а муж пошел на кухню. Она же все время находилась в комнате и не выходила, она слышала и ориентировалась в том, что происходит только по звукам. Когда они вновь пересеклись в коридоре, они стали ругаться. Потом они оба зашли в какую-то из комнат и закрыли дверь. Спустя несколько секунд она услышала крик ФИО1: «Саш, что ты делаешь, прекрати!». В ответ была тишина. Спустя еще несколько секунд открылась дверь комнаты, откуда, судя по шагам вышел муж. Он стал одеваться, после чего открыл входную дверь и вышел из квартиры, он закрыл ее за собой, но на ключ не запирал. Она подумала, что он мог выйти покурить в коридор. Муж вернулся очень быстро. Прошел в комнату, какую точно сказать не может. После чего она услышала тяжелые шаги мужа и звук, как - будто, что-то волокут тяжелое. Она поняла, что муж что-то сделал с ФИО1 и выносит ее тело. Судя по звукам тело вынесли из квартиры, но муж достаточно быстро вернулся обратно к себе, прошел в комнату и скорее всего лег спать. Она же лежала у себя в холодном поту и не выходила, так как боялась увидеть это, а также боялась за детей, которые могут также это увидеть. Она больше всего боялась, что муж может что-то сделать с собой, так как у него в комнате было ружье. Проснувшись утром, она решила позвонить ФИО1 на мобильный телефон, однако звонка она не услышала. Она понимала, что ее уже нет в живых, но все равно хотела позвонить. Затем проснулись дети и она пошла их кормить. Старший сын пошел к бабушке, так как каждое утро он ее будит. Убедившись, что бабушки нет, сын стал спрашивать, где бабушка, она же сказала, что она у врача. Когда они проснулись, муж спал. Примерно в 11 часов она пошла к мужу, чтобы разбудить его и спросить, будет ли он дома, так как ей нужно было уйти в поликлинику с сыном, а второго не с кем оставить. Муж сказал, что он будет дома и никуда не уйдет. Примерно в 14 часов 00 минут она вернулась от врача. Футорянский А.Б. был дома, сидел за компьютером. Так как она сильно была напугана, она не о чем не стала спрашивать у мужа. Около 17 часов 00 минут приехали сотрудники полиции и стали расспрашивать кто дома. Она сказала, что дома нет мамы мужа. Затем они пригласили мужа в подъезд. Спустя какое-то время муж вбежал в квартиру с криком, что нашу маму кто-то задушил. Она прекрасно понимала, что муж убил ФИО1, однако до последнего надеялась, что его никто не заподозрит.В ходе дополнительного допроса свидетель показал, что 14 января 2014 года, телефон ФИО1 типа «раскладушка» марки «Motorola» достал из сумки ФИО1, которая находилась в ее комнате, ее бывший муж Футорянский А.Б. и передал его ей, а она его передала по просьбе полицейских одному из сотрудников полиции, которые проверяли контакты ФИО1 и обзванивали лиц из записной книжки ФИО1 Потом полицейский, кто именно не помнит, попросил взять у нее данный телефон для проведения каких-то оперативных мероприятий и собирался ей его позже вернуть. Следователем в ходе данного допроса ей на обозрение предоставлен мобильный телефон марки «Motorola» темно-синего цвета, она отчетливо рассмотрела данный телефон и опознает его как телефон, который принадлежит ФИО2 А.Б., и которым она пользовалась по день смерти. Данный телефон достал лично из сумки ФИО1, находящейся в ее комнате, поэтому последний точно знал и должен знать, что данный телефон у ФИО1 никто не украл и не отобрал. Также она добавила, что у нее на левой руке имеется шрам от ожога, который она получила днем 14 января 2014 года, когда на кухне в квартире, где она тогда проживала с детьми, она наливала воду из только что вскипевшего чайника, а рядом был ребенок, и толи она неосторожным движением тогда, толи ее тронул ребенок, но она выплеснула воду из чайника себе на левую руку и ее «ошпарила», в связи с чем у нее образовался тогда ожог. Но это именно был ожог, а не кровоподтек или ссадина. Еще раз отметила, что шрам от ожога до сих пор остался на левой руке. 14 января 2014 года о полученном ожоге Футорянскому А.Б. она не рассказывала. Других телесных повреждений на руках и других частях тела у нее тогда не было и быть не могло. Мог ли быть между Футорянским А.Б. и ФИО1 конфликт на почве долга в ночь с 13 января 2014 года на 14 января 2014 года, она не знает.(т. 1 л.д.83-87, 89-93, 99-104,114-116, 218-229). Данные показания свидетель подтвердил в суде и пояснил, что данные показания она давала добровольно без воздействия какого-либо. Показания данные в части того, что Футорянский А.Б. и она убийство ФИО1 не совершали, и что ни чего не слышала не подтвердила, так как данные показания просили давать знакомые подсудимого и его защитник.Показаниями допрошенного в судебном заседании свидетеля ФИО3 из которых следует, что в составе комиссии экспертов проводил комиссионную экспертизу т

In [39]:
df1 = df[df['decision'] == 'Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА']
print(df1['link_text'].to_numpy()[:5])
print(df1['text'].to_numpy()[:5])

['http://kimrsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=2b73750d-8ba8-40a4-b1b9-3e4fd8169657&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=1&_hideJudge=0'
 'http://moskovsky--twr.sudrf.ru/modules.php?name=sud_delo&name_op=case&_uid=f68b764c-cac1-46ab-bda5-fe4a8ef347e4&_deloId=1540006&_caseType=0&_new=0&_doc=1&srv_num=3&_hideJudge=0'
 nan nan nan]

In [46]:
df = df[df['decision'].isin(['Вынесен ПРИГОВОР', 'Вступило в силу', 'Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА'])]
print(df.shape)
df['decision'].value_counts()

(42065, 21)

decision
Вынесен ПРИГОВОР                                        40842
Вступило в силу                                          1096
Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА      127
Name: count, dtype: int64

In [47]:
df.notna().sum()

id              42065
region          42065
year            42065
instance        42065
court_name      42065
caseNumber      42065
entryDate       42065
names           42065
judge           42059
resultDate      42065
decision        42065
endDate         40933
consideredBy    29794
cui             30844
accused         42054
hash            42054
articles        42065
link_meta       42065
link_text       40507
is_text         42065
text            34200
dtype: int64

In [48]:
cui_instances = df.groupby('cui')['instance'].apply(lambda x: '; '.join(x)).reset_index()
cui_instances['instance'].value_counts()

instance
FIRST                  30622
FIRST; FIRST             108
FIRST; FIRST; FIRST        2
Name: count, dtype: int64

In [49]:
cui_instances[cui_instances['instance'] == 'FIRST; FIRST; FIRST']

                              cui             instance
22496  61RS0041-01-2017-000171-75  FIRST; FIRST; FIRST
24191  66RS0022-01-2020-000616-58  FIRST; FIRST; FIRST

In [50]:
df_cui1 = df[df['cui'] == '61RS0041-01-2017-000171-75']
print(df_cui1['link_text'].unique())

df_cui2 = df[df['cui'] == '66RS0022-01-2020-000616-58']
print(df_cui2['link_text'].unique())
print(df_cui2['text'].unique())

['http://mkurgansky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=131791052&delo_id=1540006&new=0&text_number=1'
 'http://mkurgansky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=131794067&delo_id=1540006&new=0&text_number=1'
 'http://mkurgansky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=131800660&delo_id=1540006&new=0&text_number=1']
[nan
 'http://berezovsky--svd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=207191123&delo_id=1540006&new=0&text_number=1'
 'http://berezovsky--svd.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=363144226&delo_id=1540006&new=0&text_number=1']

In [51]:
cui_instances[cui_instances['instance'] == 'FIRST; FIRST']

                              cui      instance
437    03RS0007-01-2019-001236-67  FIRST; FIRST
986    03RS0037-01-2016-002206-78  FIRST; FIRST
1037   03RS0043-01-2021-001590-39  FIRST; FIRST
2015   04RS0018-01-2019-003671-11  FIRST; FIRST
2090   04RS0020-01-2017-000025-44  FIRST; FIRST
...                           ...           ...
30316  89RS0009-01-2021-000428-73  FIRST; FIRST
30333  91OS0000-01-2016-000088-10  FIRST; FIRST
30549  91RS0018-01-2017-000002-81  FIRST; FIRST
30663  92OS0000-01-2020-000007-98  FIRST; FIRST
30703  92RS0003-01-2020-000181-71  FIRST; FIRST

[108 rows x 2 columns]

In [52]:
df_cui1 = df[df['cui'] == '03RS0007-01-2019-001236-67']
print(df_cui1['link_text'].unique())
df_cui1 = df[df['cui'] == '03RS0037-01-2016-002206-78']
print(df_cui1['link_text'].unique())

['http://sovetsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=6588855&delo_id=1540006&new=0&text_number=1'
 'http://sovetsky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=125408036&delo_id=1540006&new=0&text_number=1']
['http://gafuriysky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=8275886&delo_id=1540006&new=0&text_number=1'
 'http://gafuriysky--bkr.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=8317045&delo_id=1540006&new=0&text_number=1']

In [53]:
df_cui_processed = df[df['cui'].notna()].groupby('cui', as_index=False).first()
df = pd.concat([df_cui_processed, df[df['cui'].isna()]], axis=0)
df = df.sort_values(by="entryDate")

In [55]:
cui_instances_filtered = df.groupby('cui')['instance'].apply(lambda x: '; '.join(x)).reset_index()
print(cui_instances_filtered['instance'].value_counts())

instance
FIRST    30732
Name: count, dtype: int64

In [56]:
df_cui1 = df[df['cui'] == '61RS0041-01-2017-000171-75']
print(df_cui1['link_text'].unique())

['http://mkurgansky--ros.sudrf.ru/modules.php?name=sud_delo&srv_num=1&name_op=doc&number=131791052&delo_id=1540006&new=0&text_number=1']

In [57]:
df.shape

(41953, 21)

In [58]:
df.notna().sum()

cui             30732
id              41953
region          41953
year            41953
instance        41953
court_name      41953
caseNumber      41953
entryDate       41953
names           41953
judge           41947
resultDate      41953
decision        41953
endDate         40838
consideredBy    29696
accused         41942
hash            41942
articles        41953
link_meta       41953
link_text       40431
is_text         41953
text            34089
dtype: int64

In [59]:
df_link_na_text_na = df[df['link_text'].isna() & df['text'].isna()]
print(df_link_na_text_na.shape)
df_link_notna_text_na = df[df['link_text'].notna() & df['text'].isna()]
print(df_link_notna_text_na.shape)
df_link_na_text_not_na = df[df['link_text'].isna() & df['text'].notna()]
print(df_link_na_text_not_na.shape)

(0, 21)
(7864, 21)
(1522, 21)

# Парсинг

In [60]:
df_link_notna_text_na.to_csv('filtered_data.csv', index=False)

In [61]:
df_with_link_text_final = pd.read_csv('df_with_link_text_final.csv')
print(df_with_link_text_final.shape)
df_with_link_text4 = df_with_link_text_final[df_with_link_text_final['link_text'].notna() & df_with_link_text_final['text'].isna()]
df_with_link_text4.shape

(7864, 3)

(65, 3)

In [62]:
df_merged = df.merge(df_with_link_text_final, on="id", how="left", suffixes=("", "_new"))
df_merged["text"] = df_merged["text"].fillna(df_merged["text_new"])
df = df_merged.drop(columns=['link_text_new', 'text_new'])

df_link_na_text_na1 = df[df['link_text'].isna() & df['text'].isna()]
print(df_link_na_text_na1.shape)
df_link_notna_text_na1 = df[df['link_text'].notna() & df['text'].isna()]
print(df_link_notna_text_na1.shape)
df_link_na_text_not_na1 = df[df['link_text'].isna() & df['text'].notna()]
print(df_link_na_text_not_na1.shape)

(0, 21)
(65, 21)
(1522, 21)

In [63]:
df.shape

(41953, 21)

In [64]:
df.notna().sum()

cui             30732
id              41953
region          41953
year            41953
instance        41953
court_name      41953
caseNumber      41953
entryDate       41953
names           41953
judge           41947
resultDate      41953
decision        41953
endDate         40838
consideredBy    29696
accused         41942
hash            41942
articles        41953
link_meta       41953
link_text       40431
is_text         41953
text            41888
dtype: int64

In [68]:
df = df[df['text'].notna()]

In [69]:
df.head()

,cui,id,region,year,instance,court_name,caseNumber,entryDate,names,judge,...,decision,endDate,consideredBy,accused,hash,articles,link_meta,link_text,is_text,text
0,55RS0005-01-1998-000001-11,92093,55,2020,FIRST,Первомайский районный суд г. Омска,"1-2/2020 (1-2/2019, 1-2/2018, 1-2/2017, 1-2/20...",1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,...,Вынесен ПРИГОВОР,04.03.2021,Рассмотрено единолично судьей,Яковлев Владимир Николаевич,0f1758e9ae2f4ef690d49cfc666cf44e,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,http://pervomaycourt--oms.sudrf.ru/modules.php...,True,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...
1,NaN,25775,79,2016,FIRST,Облученский районный суд Еврейской автономной ...,"1-2/2016 (1-2/2015, 1-2/2014, 1-2/2013, 1-2/20...",1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,...,Вынесен ПРИГОВОР,11.11.2016,Рассмотрено единолично судьей,Искяндаров Джамбар Мехти Оглы,aa456a98421dd7844543190b87d6ded8,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,http://obluchensky--brb.sudrf.ru/modules.php?n...,True,Решение вступило в законную силу: 11.11.2016 г...
2,42OS0000-01-2000-000001-76,75488,42,2019,FIRST,Кемеровский областной суд,"2-1/2019 (2-1/2018, 2-1/2017, 2-1/2016, 2-1/20...",2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,...,Вынесен ПРИГОВОР,22.01.2020,Рассмотрено единолично судьей,Кузнецов Вячеслав Иванович,4e1a125e57ea2d00c925d9f66c36497f,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,http://oblsud--kmr.sudrf.ru/modules.php?name=s...,True,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...
3,04OS0000-01-2005-000001-39,126184,3,2023,FIRST,Верховный суд Республики Бурятия,"1-1/2023 (1-1/2022, 1-1/2021, 1-1/2020, 1-1/20...",2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,...,Вынесен ПРИГОВОР,21.06.2023,Рассмотрено единолично судьей,Скворцова Ольга Анатольевна,611e9a1fa8ee32d99519a6c8d2c3d7c8,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,http://vs--bur.sudrf.ru/modules.php?name=sud_d...,True,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...
4,38OS0000-01-2009-000001-29,102316,38,2021,FIRST,Иркутский областной суд,"2-1/2021 (2-1/2020, 2-1/2019, 2-1/2018, 2-1/20...",2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,...,Вынесен ПРИГОВОР,24.12.2021,Рассмотрено единолично судьей,Голованов Виктор Павлович,3f1d419fbe0dfec707d756b66d0898ec,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,http://oblsud--irk.sudrf.ru/modules.php?name=s...,True,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...

In [70]:
df['decision'].value_counts()

decision
Вынесен ПРИГОВОР                                        40681
Вступило в силу                                          1082
Применены ПРИНУДИТЕЛЬНЫЕ МЕРЫ МЕДИЦИНСКОГО ХАРАКТЕРА      125
Name: count, dtype: int64

In [71]:
df.to_csv('parsed_data.csv', index=False)

# Оставляем нужное

In [1]:
import pandas as pd

df = pd.read_csv('parsed_data.csv')

In [2]:
df.shape

(41888, 21)

In [3]:
df = df[['id', 'region', 'entryDate', 'names', 'judge', 'decision', 'accused', 'articles', 'link_text', 'text']]
df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,text
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...

In [4]:
df["entryDate"]

0        1998-07-14
1        1999-01-15
2        2000-08-02
3        2005-07-12
4        2009-03-11
            ...
41883    2023-12-01
41884    2023-12-01
41885    2023-12-04
41886    2023-12-04
41887    2023-12-07
Name: entryDate, Length: 41888, dtype: object

In [5]:
df.isna().sum()

id              0
region          0
entryDate       0
names           0
judge           6
decision        0
accused        11
articles        0
link_text    1522
text            0
dtype: int64

In [6]:
df.loc[:, "judge"] = df["judge"].fillna("Неизвестно")
df.loc[:, "accused"] = df["accused"].fillna("Неизвестно")

In [7]:
df.isna().sum()

id              0
region          0
entryDate       0
names           0
judge           0
decision        0
accused         0
articles        0
link_text    1522
text            0
dtype: int64

In [8]:
import re

pattern_established = r"у\s*с\s*т\s*а\s*н\s*о\s*в\s*и\s*л"
pattern_sentenced = r"п\s*р\s*и\s*г\s*о\s*в\s*о\s*р\s*и\s*л"

df = df[df['text'].str.contains(pattern_established, regex=True, flags=re.IGNORECASE) & 
        df['text'].str.contains(pattern_sentenced, regex=True, flags=re.IGNORECASE)]

print(df.shape)

(40084, 10)

In [9]:
def split_text(row):
    text = row["text"]

    established_match = re.search(pattern_established, text, re.IGNORECASE)
    established_i = established_match.start()
    sentenced_match= re.search(pattern_sentenced, text, re.IGNORECASE)
    sentenced_i = sentenced_match.start()

    part1 = text[:established_i]
    part2 = text[established_i:sentenced_i]
    part3 = text[sentenced_i:]

    return pd.Series([part1, part2, part3])

df[["preamble", "description", "sentence"]] = df.apply(split_text, axis=1)

In [10]:
df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,text,preamble,description,sentence
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...

In [12]:
df = df.drop(columns='text')
df.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...

In [13]:
df1 = df[df['articles'].str.contains('105')]
df1.shape

(40084, 12)

In [14]:
df.to_csv('preprocessed_data.csv', index=False)