In [ ]:
import pandas as pd

In [258]:
file_path4 = 'verdicts_with_c.csv'
dfac = pd.read_csv(file_path4, on_bad_lines='warn')

ИТООООООГ - ПОЛ ПРЕСТ + НАЛИЧИЕ СУДИМ + СРОК ПРИГОВОРА

In [528]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast
import numpy as np


client = OpenAI(api_key='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')

df_eval = dfac.iloc[0:].copy() 

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_eval["combined_text"] = df_eval["preamble"].str.cat(df_eval["sentence"], sep=" ").apply(clean_text)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее по статье 105 УК РФ.
3. Финальный срок лишения свободы.

**Правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ. Если статья 105 и 111 не упоминается для обвиняемого, не возвращай никаких данных для него (ни пол, ни судимости, ни срок).
- Если обвиняемых несколько, возвращай значения для каждого в порядке их упоминания в тексте, разделяя запятыми.
- Количество значений для пола, судимостей и сроков должно совпадать: если обвиняемый не связан со статьей 105 или 111, он исключается из всех трех признаков.
- Если статья 105 и 111 не упоминается в тексте вообще, верни пустые строки для пола и судимостей, и nan для срока.

**Правила для пола:**
- Если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она", "обвиняемый"/"обвиняемая"), укажи "мужчина" или "женщина".
- Если информации нет, укажи "неизвестно".
- Для нескольких обвиняемых возвращай список: [<мужчина/женщина/неизвестно>, ...].

**Правила для судимостей:**
- Если есть явное указание, что обвиняемый ранее судим по статье 105 УК РФ (например, "ранее судим по статье 105", "имеет судимость по статье 105"), укажи "да".
- Если указано отсутствие судимостей или судимости были по другим статьям (например, "ранее судим по статье 158", "не судим по статье 105"), укажи "нет".
- Если информации о судимостях по статье 105 нет, укажи "нет".
- Если информации нет, укажи "нет".
- Для нескольких обвиняемых возвращай список: [<да/нет>, ...].

**Правила для срока лишения свободы:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан, не может быть определен (например, вместо конкретных чисел написано "<данные изъяты>"), или наказание не связано с лишением свободы (например, штраф), верни nan для этого обвиняемого.
- Если для нескольких обвиняемых есть сроки, включай только тех, у кого срок больше 0 и не nan, в порядке упоминания.
- Если информация о сроке отсутствует для всех обвиняемых, верни nan (по количеству обвиняемых).
- Для нескольких обвиняемых возвращай список: [<срок_1, срок_2, ...>] только для ненулевых сроков.

**Формат ответа:**
```
пол: <мужчина/женщина/неизвестно или [мужчина/женщина/неизвестно, ...] или пустая строка>
судимости: <да/нет или [да/нет, ...] или пустая строка>
срок: <число или [число, ...] или nan>
```

**Примеры:**
- Текст: Иванов, ранее судимый по статье 105 УК РФ, приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: да
  срок: 4.83
  ```
- Текст: Обвиняемый получил штраф по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: nan
  ```
- Текст: Иванов и Петрова, ранее судимые по статье 158 УК РФ, <данные изъяты> по статье 105 УК РФ.
  Ответ:
  ```
  пол: [мужчина, женщина]
  судимости: [нет, нет]
  срок: nan, nan
  ```
- Текст: Петров получил 3 года по статье 105 УК РФ, Сидоров — 3 года по статье 158 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: 3.00
  ```
- Текст: Иванов, ранее судимый по статье 159 УК РФ, приговорен к 5 годам по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: 5.00
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {"gender": "", "prior_convictions": "", "prison_term": "nan"}

def normalize_prediction(text):
    result = {"gender": "", "prior_convictions": "", "prison_term": "nan"}
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("пол:"):
                gender_part = line.replace("пол:", "").strip()
                if gender_part.startswith("[") and gender_part.endswith("]"):
                    gender_values = [v.strip() for v in gender_part[1:-1].split(",") if v.strip()]
                    result["gender"] = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
                else:
                    result["gender"] = gender_part if gender_part in ["мужчина", "женщина", "неизвестно", ""] else "неизвестно"
                    
            elif line.startswith("судимости:"):
                convictions_part = line.replace("судимости:", "").strip()
                if convictions_part.startswith("[") and convictions_part.endswith("]"):
                    convictions_values = [v.strip() for v in convictions_part[1:-1].split(",") if v.strip()]
                    result["prior_convictions"] = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
                else:
                    result["prior_convictions"] = convictions_part if convictions_part in ["да", "нет", ""] else "нет"
                    
            elif line.startswith("срок:"):
                prison_term_part = line.replace("срок:", "").strip()
                if prison_term_part == "nan":
                    result["prison_term"] = "nan"
                elif prison_term_part.startswith("[") and prison_term_part.endswith("]"):
                    terms = [v.strip() for v in prison_term_part[1:-1].split(",") if v.strip()]
                    normalized_terms = []
                    for term in terms:
                        try:
                            value = float(term)
                            if value > 0:
                                normalized_terms.append(f"{value:.2f}")
                        except ValueError:
                            continue  # Пропускаем nan или нечисловые значения
                    result["prison_term"] = normalized_terms if normalized_terms else "nan"
                else:
                    try:
                        value = float(prison_term_part)
                        if value > 0:
                            result["prison_term"] = f"{value:.2f}"
                        else:
                            result["prison_term"] = "nan"
                    except ValueError:
                        result["prison_term"] = "nan"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["predictions"] = df_eval["combined_text"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [02:06<00:00,  1.26s/it]

In [529]:
df_eval["predicted_gender"] = df_eval["predictions"].apply(lambda x: ", ".join(x["gender"]) if isinstance(x["gender"], list) else x["gender"])
df_eval["predicted_prior_convictions"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prior_convictions"]) if isinstance(x["prior_convictions"], list) else x["prior_convictions"])
df_eval["predicted_prison_term"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prison_term"]) if isinstance(x["prison_term"], list) else x["prison_term"])

In [547]:
df_eval.loc[9, "prison_term"] = '[20, 18]'
df_eval.loc[12, "prison_term"] = '20.0'
df_eval.loc[16, "prison_term"] = '14.0'
df_eval.loc[25, "prison_term"] = '15.0'
df_eval.loc[26, "prison_term"] = '9.0' 
df_eval.loc[28, "prison_term"] = '7.0' 
df_eval.loc[41, "prison_term"] = '[18.0, 19.08]'
df_eval.loc[45, "prison_term"] = '10.67'
df_eval.loc[53, "prison_term"] = '8.0'
df_eval.loc[59, "prison_term"] = '8.5'
df_eval.loc[65, "prison_term"] = '11'
df_eval.loc[71, "prison_term"] = '9.08'
df_eval.loc[74, "prison_term"] = '6.5'
df_eval.loc[84, "prison_term"] = '7.25'
df_eval.loc[85, "prison_term"] = '6.58'
df_eval.loc[91, "prison_term"] = '10'
df_eval.loc[92, "prison_term"] = '9' 
df_eval.loc[96, "prison_term"] = '13'
df_eval.loc[97, "prison_term"] = '9'

df_eval.loc[60, "gender_accused"] = 'женщина'

In [ ]:
def format_gender(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["мужчина", "женщина", "неизвестно"]]
            return ', '.join(formatted) if formatted else 'неизвестно'
        except:
            return 'неизвестно'
    else:
        return str(value) if str(value) in ["мужчина", "женщина", "неизвестно"] else 'неизвестно'

def format_prior_convictions(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["да", "нет"]]
            return ', '.join(formatted) if formatted else 'нет'
        except:
            return 'нет'
    else:
        return str(value) if str(value) in ["да", "нет"] else 'нет'

def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)
            formatted = [f"{float(x):.2f}" for x in numbers if float(x) > 0]
            return ', '.join(formatted) if formatted else 'nan'
        except:
            return 'nan'
    else:
        try:
            value = float(value)
            return f"{value:.2f}" if value > 0 else 'nan'
        except:
            return 'nan'

df_eval['gender_formatted'] = df_eval['gender_accused'].apply(format_gender)
df_eval['prior_convictions_formatted'] = df_eval['prior_convictions'].apply(format_prior_convictions)
df_eval['prison_term_formatted'] = df_eval['prison_term'].apply(format_prison_term)

y_true_gender = df_eval["gender_formatted"]
y_pred_gender = df_eval["predicted_gender"]
y_true_convictions = df_eval["prior_convictions_formatted"]
y_pred_convictions = df_eval["predicted_prior_convictions"]
y_true_prison_term = df_eval["prison_term_formatted"]
y_pred_prison_term = df_eval["predicted_prison_term"]

gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

prison_term_accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
prison_term_precision, prison_term_recall, prison_term_f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {prison_term_accuracy:.4f}")
print(f"Precision: {prison_term_precision:.4f}")
print(f"Recall:    {prison_term_recall:.4f}")
print(f"F1-score:  {prison_term_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_formatted", "predicted_gender", "prior_convictions_formatted", "predicted_prior_convictions", "prison_term_formatted", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9900
Precision: 0.9905
Recall:    0.9900
F1-score:  0.9901

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8700
Precision: 0.8749
Recall:    0.8700
F1-score:  0.8672

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.9600
Precision: 0.9725
Recall:    0.9600
F1-score:  0.9647

Пример предсказаний:
   gender_formatted  predicted_gender prior_convictions_formatted  \
0           мужчина           мужчина                         нет
1           мужчина           мужчина                         нет
2  мужчина, мужчина  мужчина, мужчина                    нет, нет
3           мужчина           мужчина                         нет
4           мужчина           мужчина                         нет

  predicted_prior_convictions prison_term_formatted predicted_prison_term
0                         нет                  6.50                  6.50
1                         нет                  8.08                  8.08
2                    нет, нет          18.00, 20.00          18.00, 20.00
3                         нет                  3.00                  3.00
4                         нет                  9.25                  9.25

тоже самое, но с учетом кол преступников

In [633]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast
import numpy as np


client = OpenAI(api_key='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')

df_eval = dfac.iloc[0:].copy()

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_eval["combined_text"] = df_eval["preamble"].str.cat(df_eval["sentence"], sep=" ").apply(clean_text)

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ или 111 УК РФ:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее по статье 105 УК РФ.
3. Финальный срок лишения свободы.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ. Если эти статьи не упоминаются для обвиняемого, не возвращай никаких данных для него (ни пол, ни судимости, ни срок).
- Количество значений для пола, судимостей и сроков должно равняться числу обвиняемых, указанному в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если обвиняемых меньше, чем killer_count, заполни недостающие значения: "неизвестно" для пола, "нет" для судимостей, "nan" для срока.
- Если обвиняемых больше, чем killer_count, верни данные только для первых killer_count обвиняемых.
- Если статьи 105 и 111 не упоминаются в тексте вообще, верни списки длиной killer_count: ["неизвестно", ...] для пола, ["нет", ...] для судимостей, ["nan", ...] для срока.

**Правила для пола:**
- Если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она", "обвиняемый"/"обвиняемая"), укажи "мужчина" или "женщина".
- Если информации нет, укажи "неизвестно".
- Формат: "пол: [<мужчина/женщина/неизвестно>, ...]".

**Правила для судимостей:**
- Если есть явное указание, что обвиняемый ранее судим по статье 105 УК РФ (например, "ранее судим по статье 105", "имеет судимость по статье 105"), укажи "да".
- Если указано отсутствие судимостей или судимости были по другим статьям (например, "ранее судим по статье 158", "не судим по статье 105"), укажи "нет".
- Если информации о судимостях по статье 105 нет, укажи "нет".
- Формат: "судимости: [<да/нет>, ...]".

**Правила для срока лишения свободы:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан, не может быть определен (например, вместо конкретных чисел написано "<данные изъяты>"), или наказание не связано с лишением свободы (например, штраф), верни "nan" для этого обвиняемого.
- Формат: "срок: [<число или nan>, ...]".

**Формат ответа:**
```
пол: [<мужчина/женщина/неизвестно>, ...]
судимости: [<да/нет>, ...]
срок: [<число или nan>, ...]
```

**Примеры:**
- Текст: Иванов, ранее судимый по статье 105 УК РФ, приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [да]
  срок: [4.83]
  ```
- Текст: Обвиняемый получил штраф по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [нет]
  срок: [nan]
  ```
- Текст: Иванов и Петрова, ранее судимые по статье 158 УК РФ, <данные изъяты> по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  пол: [мужчина, женщина]
  судимости: [нет, нет]
  срок: [nan, nan]
  ```
- Текст: Петров получил 3 года по статье 105 УК РФ, Сидоров — 3 года по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  пол: [мужчина, неизвестно]
  судимости: [нет, нет]
  срок: [3.00, nan]
  ```
- Текст: Иванов, ранее судимый по статье 159 УК РФ, приговорен к 5 годам по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [нет]
  срок: [5.00]
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [неизвестно]
  судимости: [нет]
  срок: [nan]
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["combined_text"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "gender": ["неизвестно"] * killer_count,
        "prior_convictions": ["нет"] * killer_count,
        "prison_term": ["nan"] * killer_count
    }

def normalize_prediction(text, killer_count):
    result = {
        "gender": ["неизвестно"] * killer_count,
        "prior_convictions": ["нет"] * killer_count,
        "prison_term": ["nan"] * killer_count
    }
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("пол:"):
                gender_part = line.replace("пол:", "").strip()
                if gender_part.startswith("[") and gender_part.endswith("]"):
                    gender_values = [v.strip() for v in gender_part[1:-1].split(",") if v.strip()]
                    gender_values = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
                    result["gender"] = gender_values[:killer_count] + ["неизвестно"] * (killer_count - len(gender_values))
                else:
                    gender_value = gender_part if gender_part in ["мужчина", "женщина", "неизвестно"] else "неизвестно"
                    result["gender"] = [gender_value] + ["неизвестно"] * (killer_count - 1)
                    
            elif line.startswith("судимости:"):
                convictions_part = line.replace("судимости:", "").strip()
                if convictions_part.startswith("[") and convictions_part.endswith("]"):
                    convictions_values = [v.strip() for v in convictions_part[1:-1].split(",") if v.strip()]
                    convictions_values = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
                    result["prior_convictions"] = convictions_values[:killer_count] + ["нет"] * (killer_count - len(convictions_values))
                else:
                    convictions_value = convictions_part if convictions_part in ["да", "нет"] else "нет"
                    result["prior_convictions"] = [convictions_value] + ["нет"] * (killer_count - 1)
                    
            elif line.startswith("срок:"):
                prison_term_part = line.replace("срок:", "").strip()
                if prison_term_part == "nan":
                    result["prison_term"] = ["nan"] * killer_count
                elif prison_term_part.startswith("[") and prison_term_part.endswith("]"):
                    terms = [v.strip() for v in prison_term_part[1:-1].split(",") if v.strip()]
                    normalized_terms = []
                    for term in terms:
                        try:
                            value = float(term)
                            if value > 0:
                                normalized_terms.append(f"{value:.2f}")
                            else:
                                normalized_terms.append("nan")
                        except ValueError:
                            normalized_terms.append("nan")
                    result["prison_term"] = normalized_terms[:killer_count] + ["nan"] * (killer_count - len(normalized_terms))
                else:
                    try:
                        value = float(prison_term_part)
                        if value > 0:
                            result["prison_term"] = [f"{value:.2f}"] + ["nan"] * (killer_count - 1)
                        else:
                            result["prison_term"] = ["nan"] * killer_count
                    except ValueError:
                        result["prison_term"] = ["nan"] * killer_count
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["predictions"] = df_eval[["combined_text", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

df_eval["predicted_gender"] = df_eval["predictions"].apply(lambda x: ", ".join(x["gender"]) if x["gender"] else "")
df_eval["predicted_prior_convictions"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prior_convictions"]) if x["prior_convictions"] else "")
df_eval["predicted_prison_term"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prison_term"]) if x["prison_term"] else "")

100%|██████████| 100/100 [02:21<00:00,  1.42s/it]

In [634]:
df_eval.loc[9, "prison_term"] = '[20, 18]'
df_eval.loc[12, "prison_term"] = '20.0'
df_eval.loc[16, "prison_term"] = '14.0'
df_eval.loc[25, "prison_term"] = '15.0'
df_eval.loc[26, "prison_term"] = '9.0' 
df_eval.loc[28, "prison_term"] = '7.0' 
df_eval.loc[41, "prison_term"] = '[18.0, 19.08]'
df_eval.loc[45, "prison_term"] = '10.67'
df_eval.loc[53, "prison_term"] = '8.0'
df_eval.loc[59, "prison_term"] = '8.5'
df_eval.loc[65, "prison_term"] = '11'
df_eval.loc[71, "prison_term"] = '9.08'
df_eval.loc[74, "prison_term"] = '6.5'
df_eval.loc[84, "prison_term"] = '7.25'
df_eval.loc[85, "prison_term"] = '6.58'
df_eval.loc[91, "prison_term"] = '10'
df_eval.loc[92, "prison_term"] = '9' 
df_eval.loc[96, "prison_term"] = '13'
df_eval.loc[97, "prison_term"] = '9'

df_eval.loc[60, "gender_accused"] = 'женщина'

In [ ]:
def format_gender(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["мужчина", "женщина", "неизвестно"]]
            return ', '.join(formatted) if formatted else 'неизвестно'
        except:
            return 'неизвестно'
    else:
        return str(value) if str(value) in ["мужчина", "женщина", "неизвестно"] else 'неизвестно'

def format_prior_convictions(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["да", "нет"]]
            return ', '.join(formatted) if formatted else 'нет'
        except:
            return 'нет'
    else:
        return str(value) if str(value) in ["да", "нет"] else 'нет'

def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)
            formatted = [f"{float(x):.2f}" for x in numbers if float(x) > 0]
            return ', '.join(formatted) if formatted else 'nan'
        except:
            return 'nan'
    else:
        try:
            value = float(value)
            return f"{value:.2f}" if value > 0 else 'nan'
        except:
            return 'nan'

df_eval['gender_formatted'] = df_eval['gender_accused'].apply(format_gender)
df_eval['prior_convictions_formatted'] = df_eval['prior_convictions'].apply(format_prior_convictions)
df_eval['prison_term_formatted'] = df_eval['prison_term'].apply(format_prison_term)

y_true_gender = df_eval["gender_formatted"]
y_pred_gender = df_eval["predicted_gender"]
y_true_convictions = df_eval["prior_convictions_formatted"]
y_pred_convictions = df_eval["predicted_prior_convictions"]
y_true_prison_term = df_eval["prison_term_formatted"]
y_pred_prison_term = df_eval["predicted_prison_term"]

gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

prison_term_accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
prison_term_precision, prison_term_recall, prison_term_f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {prison_term_accuracy:.4f}")
print(f"Precision: {prison_term_precision:.4f}")
print(f"Recall:    {prison_term_recall:.4f}")
print(f"F1-score:  {prison_term_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_formatted", "predicted_gender", "prior_convictions_formatted", "predicted_prior_convictions", "prison_term_formatted", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9900
Precision: 0.9905
Recall:    0.9900
F1-score:  0.9901

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8400
Precision: 0.8276
Recall:    0.8400
F1-score:  0.8274

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.9600
Precision: 0.9700
Recall:    0.9600
F1-score:  0.9647

Пример предсказаний:
   gender_formatted  predicted_gender prior_convictions_formatted  \
0           мужчина           мужчина                         нет
1           мужчина           мужчина                         нет
2  мужчина, мужчина  мужчина, мужчина                    нет, нет
3           мужчина           мужчина                         нет
4           мужчина           мужчина                         нет

  predicted_prior_convictions prison_term_formatted predicted_prison_term
0                         нет                  6.50                  6.50
1                         нет                  8.08                  8.08
2                    нет, нет          18.00, 20.00          18.50, 20.50
3                         нет                  3.00                  3.00
4                         нет                  9.25                  9.25

In [553]:
file_path5 = 'nemogy.csv'
dfa = pd.read_csv(file_path5, on_bad_lines='warn')
dfa.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,preamble,description,sentence,victim_count,killer_count,extracted_prison_term,prison_term_re,num_victims,has_woman_victim,has_man_victim
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...,1,1,NaN,6.0,1,0,1
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...,1,1,NaN,8.0,1,0,1
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...,2,2,NaN,2017.0,2,1,0
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...,1,1,NaN,3.0,1,0,1
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...,1,1,9.25,9.0,1,0,1

ИТОГ - alcohol + relationship_between_accused_and_victim + motive + precrime_argument + has_woman_victim + has_man_victim

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
import ast

client = OpenAI(api_key='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')

df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

# df_eval["combined_text"] = df_eval["preamble"].str.cat(df_eval["sentence"], sep=" ").apply(clean_text)

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ или 111 УК РФ или 30 УК РФ:
1. Находился ли обвиняемый в состоянии алкогольного опьянения в момент совершения преступления.
2. Была ли ссора между преступником и жертвой перед преступлением.
3. Мотив преступления (мульти-лейбл).
4. Связь между преступником и жертвой. 
5. Наличие жертвы женского пола.
6. Наличие жертвы мужского пола.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ или 30 УК РФ. Если статья 105 и 111 и 30 не упоминается для обвиняемого, не возвращай никаких данных для него.
- Количество ответов для признаков 1, 2 и 4 должно совпадать с числом обвиняемых, указанным в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если статья 105 и 111 и 30 не упоминается в тексте вообще, верни пустые списки для признаков 1, 2, 4, "неизвестно" для мотива, и 0 для признаков 5 и 6.
- Если killer_count больше числа упомянутых обвиняемых, заполни недостающие значения для признаков 1, 2, 4 значениями по умолчанию ("нет" для 1 и 2, "неизвестно" для 4).

**Правила для признаков:**

1. **Алкогольное опьянение**:
   - Если есть явное указание (например, "был пьян", "в состоянии опьянения"), укажи "да".
   - Если указано отсутствие (например, "не употреблял алкоголь"), укажи "нет".
   - Если информации нет, укажи "нет".
   - Формат: "алкоголь: [<да/нет>, ...]", где значения для каждого обвиняемого указаны в порядке их упоминания в тексте.

2. **Ссора перед преступлением (precrime_argument)**:
   - Если есть указание на ссору (например, "в ходе конфликта", "после спора"), укажи "была".
   - Если указано отсутствие ссоры или информации нет, укажи "нет".
   - Формат: "ссора: [<была/нет>, ...]".

3. **Мотив преступления**:
   - Укажи мотивы в начальной форме единственного числа (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство).
   - Если мотивов несколько, перечисли через запятую.
   - Если мотив не указан, верни "неизвестно".
   - Извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь").
   - Формат: "мотив: <мотив1, мотив2, ... или неизвестно>".

4. **Связь между преступником и жертвой**:
   - Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник, сожитель, друг, сосед, коллега, работник, незнакомец).
   - Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. 
   - Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец. 
   - Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг").
   - Если связь не указана, верни "неизвестно".
   - Формат: "связь: [<связь1>, <связь2>, ...]".
Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно".

5. **Наличие жертвы женского пола**:
   - Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("она") или явные указания ("женщина").
   - Формат: "жертва_женщина: <1/0>".

6. **Наличие жертвы мужского пола**:
   - Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("он") или явные указания ("мужчина").
   - Формат: "жертва_мужчина: <1/0>".

**Примеры:**
- Текст: Иванов, будучи пьяным, после ссоры убил свою жену по мотивам ревности по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: [да]
  ссора: [была]
  мотив: ревность
  связь: [супруг]
  жертва_женщина: 1
  жертва_мужчина: 0
  ```
- Текст: Петров и Сидоров, трезвые, убили знакомого в ходе драки по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет, нет]
  ссора: [была, была]
  мотив: личная неприязнь
  связь: [знакомый, знакомый]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Иванов убил незнакомца ради кражи по статье 105 УК РФ, Сидоров украл деньги по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет]
  ссора: [нет]
  мотив: ограбление
  связь: [незнакомец]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: []
  ссора: []
  мотив: неизвестно
  связь: []
  жертва_женщина: 0
  жертва_мужчина: 0
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["description"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }

def normalize_prediction(text, killer_count):
    result = {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("алкоголь:"):
                alcohol_part = line.replace("алкоголь:", "").strip()
                if alcohol_part.startswith("[") and alcohol_part.endswith("]"):
                    values = [v.strip() for v in alcohol_part[1:-1].split(",") if v.strip()]
                    result["alcohol"] = [v if v in ["да", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["alcohol"] = [alcohol_part if alcohol_part in ["да", "нет"] else "нет"][:killer_count]
                result["alcohol"] += ["нет"] * (killer_count - len(result["alcohol"]))
                
            elif line.startswith("ссора:"):
                argument_part = line.replace("ссора:", "").strip()
                if argument_part.startswith("[") and argument_part.endswith("]"):
                    values = [v.strip() for v in argument_part[1:-1].split(",") if v.strip()]
                    result["precrime_argument"] = [v if v in ["была", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["precrime_argument"] = [argument_part if argument_part in ["была", "нет"] else "нет"][:killer_count]
                result["precrime_argument"] += ["нет"] * (killer_count - len(result["precrime_argument"]))
                
            elif line.startswith("мотив:"):
                motive_part = line.replace("мотив:", "").strip()
                motives = [m.strip() for m in motive_part.split(",") if m.strip()]
                result["motive"] = ", ".join(motives) if motives else "неизвестно"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                if rel_part.startswith("[") and rel_part.endswith("]"):
                    values = [v.strip() for v in rel_part[1:-1].split(",") if v.strip()]
                    result["relationship"] = values[:killer_count]
                else:
                    result["relationship"] = [rel_part][:killer_count]
                result["relationship"] += ["неизвестно"] * (killer_count - len(result["relationship"]))
                
            elif line.startswith("жертва_женщина:"):
                woman_part = line.replace("жертва_женщина:", "").strip()
                result["has_woman_victim"] = woman_part if woman_part in ["0", "1"] else "0"
                
            elif line.startswith("жертва_мужчина:"):
                man_part = line.replace("жертва_мужчина:", "").strip()
                result["has_man_victim"] = man_part if man_part in ["0", "1"] else "0"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["predictions"] = df_eval[["description", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

df_eval["predicted_alcohol"] = df_eval["predictions"].apply(lambda x: ", ".join(x["alcohol"]))
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: ", ".join(x["precrime_argument"]))
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])
df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: ", ".join(x["relationship"]))
df_eval["predicted_has_woman_victim"] = df_eval["predictions"].apply(lambda x: x["has_woman_victim"])
df_eval["predicted_has_man_victim"] = df_eval["predictions"].apply(lambda x: x["has_man_victim"])

100%|██████████| 100/100 [05:35<00:00,  3.35s/it]

In [592]:
def format_list(value, valid_values, default):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in valid_values]
            return ', '.join(formatted) if formatted else default
        except:
            return default
    else:
        return str(value) if str(value) in valid_values else default
    
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)

mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))

df_eval["alcohol_formatted"] = df_eval["alcohol"].apply(lambda x: format_list(x, ["да", "нет"], "нет"))
df_eval["precrime_argument_formatted"] = df_eval["precrime_argument"].apply(lambda x: format_list(x, ["была", "нет"], "нет"))
df_eval["relationship_formatted"] = df_eval["relationship_between_accused_and_victim"].apply(lambda x: format_list(x, [
    "знакомый", "зять", "супруг", "родственник", "сожитель", "друг", "сосед", "коллега", "работник", "незнакомец", "неизвестно"
], "неизвестно"))
df_eval["has_woman_victim_formatted"] = df_eval["has_woman_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")
df_eval["has_man_victim_formatted"] = df_eval["has_man_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")

y_true_alcohol = df_eval["alcohol_formatted"]
y_pred_alcohol = df_eval["predicted_alcohol"]
y_true_precrime_argument = df_eval["precrime_argument_formatted"]
y_pred_precrime_argument = df_eval["predicted_precrime_argument"]
y_true_relationship = df_eval["relationship_formatted"]
y_pred_relationship = df_eval["predicted_relationship"]
y_true_has_woman_victim = df_eval["has_woman_victim_formatted"]
y_pred_has_woman_victim = df_eval["predicted_has_woman_victim"]
y_true_has_man_victim = df_eval["has_man_victim_formatted"]
y_pred_has_man_victim = df_eval["predicted_has_man_victim"]


alcohol_accuracy = accuracy_score(y_true_alcohol, y_pred_alcohol)
alcohol_precision, alcohol_recall, alcohol_f1, _ = precision_recall_fscore_support(
    y_true_alcohol, y_pred_alcohol, average="weighted", zero_division=0
)

precrime_argument_accuracy = accuracy_score(y_true_precrime_argument, y_pred_precrime_argument)
precrime_argument_precision, precrime_argument_recall, precrime_argument_f1, _ = precision_recall_fscore_support(
    y_true_precrime_argument, y_pred_precrime_argument, average="weighted", zero_division=0
)

motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)
motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

has_woman_victim_accuracy = accuracy_score(y_true_has_woman_victim, y_pred_has_woman_victim)
has_woman_victim_precision, has_woman_victim_recall, has_woman_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_woman_victim, y_pred_has_woman_victim, average="weighted", zero_division=0
)

has_man_victim_accuracy = accuracy_score(y_true_has_man_victim, y_pred_has_man_victim)
has_man_victim_precision, has_man_victim_recall, has_man_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_man_victim, y_pred_has_man_victim, average="weighted", zero_division=0
)


print("\nОЦЕНКА GPT-4o-mini (Алкогольное опьянение):")
print(f"Accuracy:  {alcohol_accuracy:.4f}")
print(f"Precision: {alcohol_precision:.4f}")
print(f"Recall:    {alcohol_recall:.4f}")
print(f"F1-score:  {alcohol_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ссора перед преступлением):")
print(f"Accuracy:  {precrime_argument_accuracy:.4f}")
print(f"Precision: {precrime_argument_precision:.4f}")
print(f"Recall:    {precrime_argument_recall:.4f}")
print(f"F1-score:  {precrime_argument_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Accuracy:  {motive_accuracy:.4f}")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Связь с жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва женского пола):")
print(f"Accuracy:  {has_woman_victim_accuracy:.4f}")
print(f"Precision: {has_woman_victim_precision:.4f}")
print(f"Recall:    {has_woman_victim_recall:.4f}")
print(f"F1-score:  {has_woman_victim_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва мужского пола):")
print(f"Accuracy:  {has_man_victim_accuracy:.4f}")
print(f"Precision: {has_man_victim_precision:.4f}")
print(f"Recall:    {has_man_victim_recall:.4f}")
print(f"F1-score:  {has_man_victim_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "alcohol_formatted", "predicted_alcohol",
    "precrime_argument_formatted", "predicted_precrime_argument",
    "motive2", "predicted_motive",
    "relationship_formatted", "predicted_relationship",
    "has_woman_victim_formatted", "predicted_has_woman_victim",
    "has_man_victim_formatted", "predicted_has_man_victim"
]].head())

ОЦЕНКА GPT-4o-mini (Алкогольное опьянение):
Accuracy:  0.8600
Precision: 0.8636
Recall:    0.8600
F1-score:  0.8590

ОЦЕНКА GPT-4o-mini (Ссора перед преступлением):
Accuracy:  0.9400
Precision: 0.9706
Recall:    0.9400
F1-score:  0.9439

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Accuracy:  0.8000
Precision: 0.9159
Recall:    0.8596
F1-score:  0.8869

ОЦЕНКА GPT-4o-mini (Связь с жертвой):
Accuracy:  0.4300
Precision: 0.4912
Recall:    0.4300
F1-score:  0.4302

ОЦЕНКА GPT-4o-mini (Жертва женского пола):
Accuracy:  0.8500
Precision: 0.8933
Recall:    0.8500
F1-score:  0.8572

ОЦЕНКА GPT-4o-mini (Жертва мужского пола):
Accuracy:  0.9600
Precision: 0.9599
Recall:    0.9600
F1-score:  0.9594

Пример предсказаний:
  alcohol_formatted predicted_alcohol precrime_argument_formatted  \
0                да                да                        была
1                да                да                        была
2          нет, нет          нет, нет                         нет
3                да                да                        была
4                да                да                        была

  predicted_precrime_argument                     motive2  \
0                        была     личная неприязнь, месть
1                        была  личная неприязнь, ревность
2                    нет, нет           деньги, имущество
3                        была            личная неприязнь
4                        была            личная неприязнь

             predicted_motive  relationship_formatted  predicted_relationship  \
0     месть, личная неприязнь                знакомый              незнакомец
1  ревность, личная неприязнь                знакомый                  супруг
2                   имущество  неизвестно, неизвестно  незнакомец, незнакомец
3   личная неприязнь, корысть                работник                знакомый
4            личная неприязнь                знакомый              незнакомец

  has_woman_victim_formatted predicted_has_woman_victim  \
0                          0                          0
1                          0                          1
2                          1                          1
3                          0                          0
4                          0                          0

  has_man_victim_formatted predicted_has_man_victim
0                        1                        1
1                        1                        1
2                        0                        0
3                        1                        1
4                        1                        1

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['аморальное поведение', 'вымогательство', 'защита', 'корысть', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

ИТОГ - ВРЕМЯ + МЕСТО + МЕТОД + СВЯЗЬ

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast

client = OpenAI(api_key='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')

df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                unique_locs = []
                for loc in loc_list:
                    loc_cat = location_map.get(loc, 'другое')
                    if loc_cat not in unique_locs:
                        unique_locs.append(loc_cat)
                return ', '.join(unique_locs)
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                unique_methods = sorted(set([method_map.get(meth, 'другое') for meth in meth_list]))
                return ', '.join(unique_methods)
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'

df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Время суток**: Определи, в какое время суток произошло преступление (утро, день, вечер, ночь). Правила:
   - 04:00–11:59 → утро
   - 12:00–15:59 → день
   - 16:00–22:59 → вечер
   - 23:00–03:59 → ночь
   Если в тексте нет чёткого указания на время, выбери наиболее вероятное. Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта. Формат: "время: <утро, день, вечер, ночь или комбинация через запятую>".
2. **Место преступления**: Укажи место преступления в начальной форме в единственном числе (например, "квартира", "улица"). Если мест несколько, перечисли уникальные категории через запятую. Классифицируй место по категориям: жилое помещение (квартира, дом, дача, общежитие, хостел), уличное пространство (улица, двор, лес, берег озера, безлюдная местность), общественный транспорт (такси, автобус, поезд), общественное место (магазин, кафе, бар, рынок), подъезд и прилегающие зоны (подъезд, лестничная площадка, чердак), рабочая зона (гараж, база отдыха, склад, офис), другое. Верни название категории. Не повторяй одинаковые категории.
3. **Метод преступления**: Укажи метод преступления в начальной форме в единственном числе (например, "нож", "избиение"). Если методов несколько, перечисли уникальные категории через запятую. Классифицируй метод по категориям: физическое воздействие (избиение, удар предметом, скидывание с высоты), холодное оружие (нож, клинок, вилка, лопата, топор), тяжелые предметы (молоток, кирпич, полено), огнестрельное оружие (ружье, травматический пистолет, огнестрел), удушение (удушение, повешение), другое. Верни название категории.
4. **Связь между преступником и жертвой**: Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник). Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец. Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг"). Если связь не указана, верни "неизвестно".
  

**Правила:**
- Для времени суток: опирайся на явные указания (например, "в 5 утра") или контекст (например, "после полуночи" → ночь). Если время неясно, выбери наиболее вероятное.
- Для места: опирайся на явные указания (например, "в квартире") и классифицируй по указанным категориям. Если место неясно, укажи "другое". Убедись, что одинаковые категории не повторяются.
- Для метода: опирайся на явные указания (например, "зарезал ножом") и классифицируй по указанным категориям. Если метод неясен, укажи "другое". Сортируй категории для игнорирования порядка.
- Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно".
- Ответ должен быть в формате:
  ```
  время: <утро, день, вечер, ночь или комбинация через запятую>
  место: <категория_1, категория_2, ... или другое>
  метод: <категория_1, категория_2, ... или другое>
  связь: <связь_1, связь_2, ... или неизвестно>
  ```

**Примеры:**
- Текст: Иванов зарезал свою жену в квартире в 5 утра из ревности.
  Ответ:
  ```
  время: утро
  место: жилое помещение
  метод: холодное оружие
  связь: супруг
  ```
- Текст: Двое обвиняемых избили незнакомца на улице в 15:00 ради кражи.
  Ответ:
  ```
  время: день
  место: уличное пространство
  метод: физическое воздействие
  связь: незнакомец, незнакомец
  ```
- Текст: Сидоров ударил молотком коллегу в гараже в 20:00 из личной неприязни.
  Ответ:
  ```
  время: вечер
  место: рабочая зона
  метод: тяжелые предметы
  связь: коллега
  ```
- Текст: Петров задушил сожительницу в подъезде после полуночи из мести.
  Ответ:
  ```
  время: ночь
  место: подъезд и прилегающие зоны
  метод: удушение
  связь: сожитель
  ```
- Текст: Двое обвиняемых напали на прохожего в такси и на улице в 11:00–13:00, используя нож и кулаки.
  Ответ:
  ```
  время: утро, день
  место: общественный транспорт, уличное пространство
  метод: холодное оружие, физическое воздействие
  связь: незнакомец, незнакомец
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "time_of_day": "неизвестно",
        "location": "другое",
        "method": "другое",
        "relationship": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "time_of_day": "неизвестно",
        "location": "другое",
        "method": "другое",
        "relationship": "неизвестно"
    }
    
    try:
        lines = text.split("\n")
        valid_times = ["утро", "день", "вечер", "ночь"]
        valid_locations = [
            "жилое помещение", "уличное пространство", "общественный транспорт",
            "общественное место", "подъезд и прилегающие зоны", "рабочая зона", "другое"
        ]
        valid_methods = [
            "физическое воздействие", "холодное оружие", "тяжелые предметы",
            "огнестрельное оружие", "удушение", "другое"
        ]
        valid_relationships = [
            "родственник", "супруг", "зять", "сожитель", "бывший супруг",
            "друг", "знакомый", "сосед", "коллега", "работник", "незнакомец",
            "брат", "отец", "сын", "дядя", "племянник", "неизвестно"
        ]
        
        for line in lines:
            line = line.strip()
            if line.startswith("время:"):
                time_part = line.replace("время:", "").strip()
                times = [t.strip() for t in time_part.split(",") if t.strip()]
                result["time_of_day"] = ", ".join([t if t in valid_times else "неизвестно" for t in times][:2]) or "неизвестно"
                
            elif line.startswith("место:"):
                loc_part = line.replace("место:", "").strip()
                locations = [loc.strip() for loc in loc_part.split(",") if loc.strip()]
                unique_locations = []
                for loc in locations:
                    loc = loc if loc in valid_locations else "другое"
                    if loc not in unique_locations:
                        unique_locations.append(loc)
                result["location"] = ", ".join(unique_locations) or "другое"
                
            elif line.startswith("метод:"):
                meth_part = line.replace("метод:", "").strip()
                methods = [meth.strip() for meth in meth_part.split(",") if meth.strip()]
                unique_methods = sorted(set([meth if meth in valid_methods else "другое" for meth in methods]))
                result["method"] = ", ".join(unique_methods) or "другое"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                relationships = [r.strip() for r in rel_part.split(",") if r.strip()]
                result["relationship"] = ", ".join([r if r in valid_relationships else "неизвестно" for r in relationships]) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

df_eval["predicted_time_of_day"] = df_eval["predictions"].apply(lambda x: x["time_of_day"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: x["relationship"])

100%|██████████| 100/100 [05:26<00:00,  3.26s/it]

In [ ]:
def format_time_of_day(value):
    valid_times = ["утро", "день", "вечер", "ночь"]
    if isinstance(value, str):
        times = [t.strip() for t in value.split(",") if t.strip()]
        formatted = [t for t in times if t in valid_times][:2]
        return ", ".join(formatted) if formatted else "неизвестно"
    return "неизвестно"

df_eval["time_of_day_formatted"] = df_eval["time_of_day"].apply(format_time_of_day)
df_eval["location_formatted"] = df_eval["location2"]
df_eval["method_formatted"] = df_eval["method2"]
# df_eval["relationship_formatted"] = df_eval["relationship2"]

y_true_time = df_eval["time_of_day_formatted"]
y_pred_time = df_eval["predicted_time_of_day"]
y_true_location = df_eval["location_formatted"]
y_pred_location = df_eval["predicted_location"]
y_true_method = df_eval["method_formatted"]
y_pred_method = df_eval["predicted_method"]
y_true_relationship = df_eval["relationship_between_accused_and_victim"]
y_pred_relationship = df_eval["predicted_relationship"]

time_accuracy = accuracy_score(y_true_time, y_pred_time)
time_precision, time_recall, time_f1, _ = precision_recall_fscore_support(
    y_true_time, y_pred_time, average="weighted", zero_division=0
)

location_accuracy = accuracy_score(y_true_location, y_pred_location)
location_precision, location_recall, location_f1, _ = precision_recall_fscore_support(
    y_true_location, y_pred_location, average="weighted", zero_division=0
)

method_accuracy = accuracy_score(y_true_method, y_pred_method)
method_precision, method_recall, method_f1, _ = precision_recall_fscore_support(
    y_true_method, y_pred_method, average="weighted", zero_division=0
)

relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Время суток):")
print(f"Accuracy:  {time_accuracy:.4f}")
print(f"Precision: {time_precision:.4f}")
print(f"Recall:    {time_recall:.4f}")
print(f"F1-score:  {time_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Место преступления):")
print(f"Accuracy:  {location_accuracy:.4f}")
print(f"Precision: {location_precision:.4f}")
print(f"Recall:    {location_recall:.4f}")
print(f"F1-score:  {location_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Метод преступления):")
print(f"Accuracy:  {method_accuracy:.4f}")
print(f"Precision: {method_precision:.4f}")
print(f"Recall:    {method_recall:.4f}")
print(f"F1-score:  {method_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Связь с жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "time_of_day_formatted", "predicted_time_of_day",
    "location_formatted", "predicted_location",
    "method_formatted", "predicted_method",
    "relationship_between_accused_and_victim", "predicted_relationship"
]].head())

ОЦЕНКА GPT-4o-mini (Время суток):
Accuracy:  0.6500
Precision: 0.7344
Recall:    0.6500
F1-score:  0.6538

ОЦЕНКА GPT-4o-mini (Место преступления):
Accuracy:  0.8200
Precision: 0.9691
Recall:    0.8200
F1-score:  0.8821

ОЦЕНКА GPT-4o-mini (Метод преступления):
Accuracy:  0.6600
Precision: 0.9141
Recall:    0.6600
F1-score:  0.7304

ОЦЕНКА GPT-4o-mini (Связь с жертвой):
Accuracy:  0.5800
Precision: 0.5640
Recall:    0.5800
F1-score:  0.5601

Пример предсказаний:
  time_of_day_formatted predicted_time_of_day    location_formatted  \
0            неизвестно            неизвестно  уличное пространство
1                  ночь                  ночь  уличное пространство
2            неизвестно            неизвестно       жилое помещение
3                 вечер                 вечер       жилое помещение
4                  утро                  утро  уличное пространство

             predicted_location        method_formatted  \
0          уличное пространство  физическое воздействие
1          уличное пространство    огнестрельное оружие
2               жилое помещение                удушение
3               жилое помещение    огнестрельное оружие
4  уличное пространство, другое  физическое воздействие

                                    predicted_method  \
0            физическое воздействие, холодное оружие
1       огнестрельное оружие, физическое воздействие
2  удушение, физическое воздействие, холодное оружие
3                               огнестрельное оружие
4                             физическое воздействие

  relationship_between_accused_and_victim predicted_relationship
0                                знакомый               знакомый
1                                знакомый               знакомый
2            ['неизвестно', 'неизвестно']     знакомый, знакомый
3                                работник               знакомый
4                                знакомый               знакомый

ФИНАЛ НА 3К

In [611]:
file_path_3k = 'sampled_killer1_3000.csv'
df_3k = pd.read_csv(file_path_3k, on_bad_lines='warn')
df_3k.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,prior_convictions,predicted_killer_gender,predicted_victim_gender,gender_accused,gender_victim
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,У С Т А Н О В И Л:\nВласова Н.А. совершила уби...,П Р И Г О В О Р И Л:\nВласову Н.А. признать ви...,1,нет,неизвестно,неизвестно,женщина,мужчина
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,УСТАНОВИЛ:\n<дата> около 22 часов 30 минут П.Д...,ПРИГОВОРИЛ:\nПРОСКУРНОВА Д.В. признать виновны...,1,нет,мужчина,мужчина,мужчина,мужчина
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,у с т а н о в и л :\nМингазов\nА.Д. совершил у...,п р и г о в о р и л :\nПризнать\nвиновным в со...,1,да,мужчина,мужчина,мужчина,мужчина
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,"УСТАНОВИЛ:\nБлинов А.А. совершил убийство, то ...",ПРИГОВОРИЛ:\nБлинова Александра Анатольевича п...,1,нет,мужчина,мужчина,мужчина,мужчина
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,У С Т А Н О В И Л:\nГрехнев А.Н. совершил убий...,П Р И Г О В О Р И Л:\nГрехнева А. Н. признать ...,1,нет,мужчина,неизвестно,мужчина,неизвестно

In [617]:
df_3k_my = df_3k[["id", "region", "entryDate", "names", "judge", "decision", "accused", "articles", "link_text", "preamble", "description", "sentence", "killer_count"]].copy()  
df_3k_my.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,У С Т А Н О В И Л:\nВласова Н.А. совершила уби...,П Р И Г О В О Р И Л:\nВласову Н.А. признать ви...,1
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,УСТАНОВИЛ:\n<дата> около 22 часов 30 минут П.Д...,ПРИГОВОРИЛ:\nПРОСКУРНОВА Д.В. признать виновны...,1
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,у с т а н о в и л :\nМингазов\nА.Д. совершил у...,п р и г о в о р и л :\nПризнать\nвиновным в со...,1
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,"УСТАНОВИЛ:\nБлинов А.А. совершил убийство, то ...",ПРИГОВОРИЛ:\nБлинова Александра Анатольевича п...,1
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,У С Т А Н О В И Л:\nГрехнев А.Н. совершил убий...,П Р И Г О В О Р И Л:\nГрехнева А. Н. признать ...,1

1)

In [618]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast
import numpy as np


client = OpenAI(api_key='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')

# df_eval = dfac.iloc[0:].copy() 

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_3k_my["combined_text"] = df_3k_my["preamble"].str.cat(df_3k_my["sentence"], sep=" ").apply(clean_text)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее по статье 105 УК РФ.
3. Финальный срок лишения свободы.

**Правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ. Если статья 105 и 111 не упоминается для обвиняемого, не возвращай никаких данных для него (ни пол, ни судимости, ни срок).
- Если обвиняемых несколько, возвращай значения для каждого в порядке их упоминания в тексте, разделяя запятыми.
- Количество значений для пола, судимостей и сроков должно совпадать: если обвиняемый не связан со статьей 105 или 111, он исключается из всех трех признаков.
- Если статья 105 и 111 не упоминается в тексте вообще, верни пустые строки для пола и судимостей, и nan для срока.

**Правила для пола:**
- Если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она", "обвиняемый"/"обвиняемая"), укажи "мужчина" или "женщина".
- Если информации нет, укажи "неизвестно".
- Для нескольких обвиняемых возвращай список: [<мужчина/женщина/неизвестно>, ...].

**Правила для судимостей:**
- Если есть явное указание, что обвиняемый ранее судим по статье 105 УК РФ (например, "ранее судим по статье 105", "имеет судимость по статье 105"), укажи "да".
- Если указано отсутствие судимостей или судимости были по другим статьям (например, "ранее судим по статье 158", "не судим по статье 105"), укажи "нет".
- Если информации о судимостях по статье 105 нет, укажи "нет".
- Если информации нет, укажи "нет".
- Для нескольких обвиняемых возвращай список: [<да/нет>, ...].

**Правила для срока лишения свободы:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан, не может быть определен (например, вместо конкретных чисел написано "<данные изъяты>"), или наказание не связано с лишением свободы (например, штраф), верни nan для этого обвиняемого.
- Если для нескольких обвиняемых есть сроки, включай только тех, у кого срок больше 0 и не nan, в порядке упоминания.
- Если информация о сроке отсутствует для всех обвиняемых, верни nan (по количеству обвиняемых).
- Для нескольких обвиняемых возвращай список: [<срок_1, срок_2, ...>] только для ненулевых сроков.

**Формат ответа:**
```
пол: <мужчина/женщина/неизвестно или [мужчина/женщина/неизвестно, ...] или пустая строка>
судимости: <да/нет или [да/нет, ...] или пустая строка>
срок: <число или [число, ...] или nan>
```

**Примеры:**
- Текст: Иванов, ранее судимый по статье 105 УК РФ, приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: да
  срок: 4.83
  ```
- Текст: Обвиняемый получил штраф по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: nan
  ```
- Текст: Иванов и Петрова, ранее судимые по статье 158 УК РФ, <данные изъяты> по статье 105 УК РФ.
  Ответ:
  ```
  пол: [мужчина, женщина]
  судимости: [нет, нет]
  срок: nan, nan
  ```
- Текст: Петров получил 3 года по статье 105 УК РФ, Сидоров — 3 года по статье 158 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: 3.00
  ```
- Текст: Иванов, ранее судимый по статье 159 УК РФ, приговорен к 5 годам по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: 5.00
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {"gender": "", "prior_convictions": "", "prison_term": "nan"}

def normalize_prediction(text):
    result = {"gender": "", "prior_convictions": "", "prison_term": "nan"}
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("пол:"):
                gender_part = line.replace("пол:", "").strip()
                if gender_part.startswith("[") and gender_part.endswith("]"):
                    gender_values = [v.strip() for v in gender_part[1:-1].split(",") if v.strip()]
                    result["gender"] = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
                else:
                    result["gender"] = gender_part if gender_part in ["мужчина", "женщина", "неизвестно", ""] else "неизвестно"
                    
            elif line.startswith("судимости:"):
                convictions_part = line.replace("судимости:", "").strip()
                if convictions_part.startswith("[") and convictions_part.endswith("]"):
                    convictions_values = [v.strip() for v in convictions_part[1:-1].split(",") if v.strip()]
                    result["prior_convictions"] = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
                else:
                    result["prior_convictions"] = convictions_part if convictions_part in ["да", "нет", ""] else "нет"
                    
            elif line.startswith("срок:"):
                prison_term_part = line.replace("срок:", "").strip()
                if prison_term_part == "nan":
                    result["prison_term"] = "nan"
                elif prison_term_part.startswith("[") and prison_term_part.endswith("]"):
                    terms = [v.strip() for v in prison_term_part[1:-1].split(",") if v.strip()]
                    normalized_terms = []
                    for term in terms:
                        try:
                            value = float(term)
                            if value > 0:
                                normalized_terms.append(f"{value:.2f}")
                        except ValueError:
                            continue  
                    result["prison_term"] = normalized_terms if normalized_terms else "nan"
                else:
                    try:
                        value = float(prison_term_part)
                        if value > 0:
                            result["prison_term"] = f"{value:.2f}"
                        else:
                            result["prison_term"] = "nan"
                    except ValueError:
                        result["prison_term"] = "nan"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_3k_my["predictions"] = df_3k_my["combined_text"].progress_apply(classify_with_gpt4)

100%|██████████| 3000/3000 [1:04:46<00:00,  1.30s/it]

In [620]:
df_3k_my["predicted_gender"] = df_3k_my["predictions"].apply(lambda x: ", ".join(x["gender"]) if isinstance(x["gender"], list) else x["gender"])
df_3k_my["predicted_prior_convictions"] = df_3k_my["predictions"].apply(lambda x: ", ".join(x["prior_convictions"]) if isinstance(x["prior_convictions"], list) else x["prior_convictions"])
df_3k_my["predicted_prison_term"] = df_3k_my["predictions"].apply(lambda x: ", ".join(x["prison_term"]) if isinstance(x["prison_term"], list) else x["prison_term"])

In [621]:
df_3k_my.to_csv("3k_1.csv", index=False, encoding='utf-8')

In [622]:
df_3k_my.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,combined_text,predictions,predicted_gender,predicted_prior_convictions,predicted_prison_term
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,У С Т А Н О В И Л:\nВласова Н.А. совершила уби...,П Р И Г О В О Р И Л:\nВласову Н.А. признать ви...,1,Дело № 1-208/12-2018 П Р И Г О В О Р именем Ро...,"{'gender': 'женщина', 'prior_convictions': 'не...",женщина,нет,8.00
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,УСТАНОВИЛ:\n<дата> около 22 часов 30 минут П.Д...,ПРИГОВОРИЛ:\nПРОСКУРНОВА Д.В. признать виновны...,1,Дело № ПРИГОВОР Именем Российской Федерации г....,"{'gender': 'мужчина', 'prior_convictions': 'не...",мужчина,нет,6.00
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,у с т а н о в и л :\nМингазов\nА.Д. совершил у...,п р и г о в о р и л :\nПризнать\nвиновным в со...,1,Решение по уголовному делу Информация по делу ...,"{'gender': 'мужчина', 'prior_convictions': 'не...",мужчина,нет,13.08
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,"УСТАНОВИЛ:\nБлинов А.А. совершил убийство, то ...",ПРИГОВОРИЛ:\nБлинова Александра Анатольевича п...,1,ПРИГОВОР ИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ г.Белово ...,"{'gender': 'мужчина', 'prior_convictions': 'не...",мужчина,нет,7.00
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,У С Т А Н О В И Л:\nГрехнев А.Н. совершил убий...,П Р И Г О В О Р И Л:\nГрехнева А. Н. признать ...,1,Дело № 1-0220/2018 (11702330002030403) П р и г...,"{'gender': 'мужчина', 'prior_convictions': 'не...",мужчина,нет,9.83

2)

In [625]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
import ast

client = OpenAI(api_key='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')

# df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ или 111 УК РФ или 30 УК РФ:
1. Находился ли обвиняемый в состоянии алкогольного опьянения в момент совершения преступления.
2. Была ли ссора между преступником и жертвой перед преступлением.
3. Мотив преступления (мульти-лейбл).
4. Связь между преступником и жертвой. 
5. Наличие жертвы женского пола.
6. Наличие жертвы мужского пола.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ или 30 УК РФ. Если статья 105 и 111 и 30 не упоминается для обвиняемого, не возвращай никаких данных для него.
- Количество ответов для признаков 1, 2 и 4 должно совпадать с числом обвиняемых, указанным в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если статья 105 и 111 и 30 не упоминается в тексте вообще, верни пустые списки для признаков 1, 2, 4, "неизвестно" для мотива, и 0 для признаков 5 и 6.
- Если killer_count больше числа упомянутых обвиняемых, заполни недостающие значения для признаков 1, 2, 4 значениями по умолчанию ("нет" для 1 и 2, "неизвестно" для 4).

**Правила для признаков:**

1. **Алкогольное опьянение**:
   - Если есть явное указание (например, "был пьян", "в состоянии опьянения"), укажи "да".
   - Если указано отсутствие (например, "не употреблял алкоголь"), укажи "нет".
   - Если информации нет, укажи "нет".
   - Формат: "алкоголь: [<да/нет>, ...]", где значения для каждого обвиняемого указаны в порядке их упоминания в тексте.

2. **Ссора перед преступлением (precrime_argument)**:
   - Если есть указание на ссору (например, "в ходе конфликта", "после спора"), укажи "была".
   - Если указано отсутствие ссоры или информации нет, укажи "нет".
   - Формат: "ссора: [<была/нет>, ...]".

3. **Мотив преступления**:
   - Укажи мотивы в начальной форме единственного числа (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство).
   - Если мотивов несколько, перечисли через запятую.
   - Если мотив не указан, верни "неизвестно".
   - Извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь").
   - Формат: "мотив: <мотив1, мотив2, ... или неизвестно>".

4. **Связь между преступником и жертвой**:
   - Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник, сожитель, друг, сосед, коллега, работник, незнакомец).
   - Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. 
   - Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец. 
   - Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг").
   - Если связь не указана, верни "неизвестно".
   - Формат: "связь: [<связь1>, <связь2>, ...]".
Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно".

5. **Наличие жертвы женского пола**:
   - Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("она") или явные указания ("женщина").
   - Формат: "жертва_женщина: <1/0>".

6. **Наличие жертвы мужского пола**:
   - Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("он") или явные указания ("мужчина").
   - Формат: "жертва_мужчина: <1/0>".

**Примеры:**
- Текст: Иванов, будучи пьяным, после ссоры убил свою жену по мотивам ревности по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: [да]
  ссора: [была]
  мотив: ревность
  связь: [супруг]
  жертва_женщина: 1
  жертва_мужчина: 0
  ```
- Текст: Петров и Сидоров, трезвые, убили знакомого в ходе драки по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет, нет]
  ссора: [была, была]
  мотив: личная неприязнь
  связь: [знакомый, знакомый]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Иванов убил незнакомца ради кражи по статье 105 УК РФ, Сидоров украл деньги по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет]
  ссора: [нет]
  мотив: ограбление
  связь: [незнакомец]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: []
  ссора: []
  мотив: неизвестно
  связь: []
  жертва_женщина: 0
  жертва_мужчина: 0
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["description"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }

def normalize_prediction(text, killer_count):
    result = {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("алкоголь:"):
                alcohol_part = line.replace("алкоголь:", "").strip()
                if alcohol_part.startswith("[") and alcohol_part.endswith("]"):
                    values = [v.strip() for v in alcohol_part[1:-1].split(",") if v.strip()]
                    result["alcohol"] = [v if v in ["да", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["alcohol"] = [alcohol_part if alcohol_part in ["да", "нет"] else "нет"][:killer_count]
                # Заполняем недостающие значения
                result["alcohol"] += ["нет"] * (killer_count - len(result["alcohol"]))
                
            elif line.startswith("ссора:"):
                argument_part = line.replace("ссора:", "").strip()
                if argument_part.startswith("[") and argument_part.endswith("]"):
                    values = [v.strip() for v in argument_part[1:-1].split(",") if v.strip()]
                    result["precrime_argument"] = [v if v in ["была", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["precrime_argument"] = [argument_part if argument_part in ["была", "нет"] else "нет"][:killer_count]
                result["precrime_argument"] += ["нет"] * (killer_count - len(result["precrime_argument"]))
                
            elif line.startswith("мотив:"):
                motive_part = line.replace("мотив:", "").strip()
                motives = [m.strip() for m in motive_part.split(",") if m.strip()]
                result["motive"] = ", ".join(motives) if motives else "неизвестно"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                if rel_part.startswith("[") and rel_part.endswith("]"):
                    values = [v.strip() for v in rel_part[1:-1].split(",") if v.strip()]
                    result["relationship"] = values[:killer_count]
                else:
                    result["relationship"] = [rel_part][:killer_count]
                result["relationship"] += ["неизвестно"] * (killer_count - len(result["relationship"]))
                
            elif line.startswith("жертва_женщина:"):
                woman_part = line.replace("жертва_женщина:", "").strip()
                result["has_woman_victim"] = woman_part if woman_part in ["0", "1"] else "0"
                
            elif line.startswith("жертва_мужчина:"):
                man_part = line.replace("жертва_мужчина:", "").strip()
                result["has_man_victim"] = man_part if man_part in ["0", "1"] else "0"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_3k_my["predictions2"] = df_3k_my[["description", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

100%|██████████| 3000/3000 [3:19:54<00:00,  4.00s/it]

In [626]:
df_3k_my["predicted_alcohol"] = df_3k_my["predictions2"].apply(lambda x: ", ".join(x["alcohol"]))
df_3k_my["predicted_precrime_argument"] = df_3k_my["predictions2"].apply(lambda x: ", ".join(x["precrime_argument"]))
df_3k_my["predicted_motive"] = df_3k_my["predictions2"].apply(lambda x: x["motive"])
df_3k_my["predicted_relationship"] = df_3k_my["predictions2"].apply(lambda x: ", ".join(x["relationship"]))
df_3k_my["predicted_has_woman_victim"] = df_3k_my["predictions2"].apply(lambda x: x["has_woman_victim"])
df_3k_my["predicted_has_man_victim"] = df_3k_my["predictions2"].apply(lambda x: x["has_man_victim"])

In [627]:
df_3k_my.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,predicted_gender,predicted_prior_convictions,predicted_prison_term,predictions2,predicted_alcohol,predicted_precrime_argument,predicted_motive,predicted_relationship,predicted_has_woman_victim,predicted_has_man_victim
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,...,женщина,нет,8.00,"{'alcohol': ['да'], 'precrime_argument': ['был...",да,была,личная неприязнь,супруг,0,1
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,...,мужчина,нет,6.00,"{'alcohol': ['да'], 'precrime_argument': ['был...",да,была,личная неприязнь,знакомый,0,1
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,...,мужчина,нет,13.08,"{'alcohol': ['да'], 'precrime_argument': ['был...",да,была,личная неприязнь,брат,0,1
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,...,мужчина,нет,7.00,"{'alcohol': ['да'], 'precrime_argument': ['был...",да,была,личная неприязнь,знакомый,0,1
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,...,мужчина,нет,9.83,"{'alcohol': ['да'], 'precrime_argument': ['был...",да,была,личная неприязнь,сожитель,1,0

In [628]:
df_3k_my.to_csv("3k_2.csv", index=False, encoding='utf-8')

3)

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast

client = OpenAI(api_key='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')

# df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                unique_locs = []
                for loc in loc_list:
                    loc_cat = location_map.get(loc, 'другое')
                    if loc_cat not in unique_locs:
                        unique_locs.append(loc_cat)
                return ', '.join(unique_locs)
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                unique_methods = sorted(set([method_map.get(meth, 'другое') for meth in meth_list]))
                return ', '.join(unique_methods)
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'

df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Время суток**: Определи, в какое время суток произошло преступление (утро, день, вечер, ночь). Правила:
   - 04:00–11:59 → утро
   - 12:00–15:59 → день
   - 16:00–22:59 → вечер
   - 23:00–03:59 → ночь
   Если в тексте нет чёткого указания на время, выбери наиболее вероятное. Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта. Формат: "время: <утро, день, вечер, ночь или комбинация через запятую>".
2. **Место преступления**: Укажи место преступления в начальной форме в единственном числе (например, "квартира", "улица"). Если мест несколько, перечисли уникальные категории через запятую. Классифицируй место по категориям: жилое помещение (квартира, дом, дача, общежитие, хостел), уличное пространство (улица, двор, лес, берег озера, безлюдная местность), общественный транспорт (такси, автобус, поезд), общественное место (магазин, кафе, бар, рынок), подъезд и прилегающие зоны (подъезд, лестничная площадка, чердак), рабочая зона (гараж, база отдыха, склад, офис), другое. Верни название категории. Не повторяй одинаковые категории.
3. **Метод преступления**: Укажи метод преступления в начальной форме в единственном числе (например, "нож", "избиение"). Если методов несколько, перечисли уникальные категории через запятую. Классифицируй метод по категориям: физическое воздействие (избиение, удар предметом, скидывание с высоты), холодное оружие (нож, клинок, вилка, лопата, топор), тяжелые предметы (молоток, кирпич, полено), огнестрельное оружие (ружье, травматический пистолет, огнестрел), удушение (удушение, повешение), другое. Верни название категории.
4. **Связь между преступником и жертвой**: Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник). Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец. Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг"). Если связь не указана, верни "неизвестно".
  

**Правила:**
- Для времени суток: опирайся на явные указания (например, "в 5 утра") или контекст (например, "после полуночи" → ночь). Если время неясно, выбери наиболее вероятное.
- Для места: опирайся на явные указания (например, "в квартире") и классифицируй по указанным категориям. Если место неясно, укажи "другое". Убедись, что одинаковые категории не повторяются.
- Для метода: опирайся на явные указания (например, "зарезал ножом") и классифицируй по указанным категориям. Если метод неясен, укажи "другое". Сортируй категории для игнорирования порядка.
- Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно".
- Ответ должен быть в формате:
  ```
  время: <утро, день, вечер, ночь или комбинация через запятую>
  место: <категория_1, категория_2, ... или другое>
  метод: <категория_1, категория_2, ... или другое>
  связь: <связь_1, связь_2, ... или неизвестно>
  ```

**Примеры:**
- Текст: Иванов зарезал свою жену в квартире в 5 утра из ревности.
  Ответ:
  ```
  время: утро
  место: жилое помещение
  метод: холодное оружие
  связь: супруг
  ```
- Текст: Двое обвиняемых избили незнакомца на улице в 15:00 ради кражи.
  Ответ:
  ```
  время: день
  место: уличное пространство
  метод: физическое воздействие
  связь: незнакомец, незнакомец
  ```
- Текст: Сидоров ударил молотком коллегу в гараже в 20:00 из личной неприязни.
  Ответ:
  ```
  время: вечер
  место: рабочая зона
  метод: тяжелые предметы
  связь: коллега
  ```
- Текст: Петров задушил сожительницу в подъезде после полуночи из мести.
  Ответ:
  ```
  время: ночь
  место: подъезд и прилегающие зоны
  метод: удушение
  связь: сожитель
  ```
- Текст: Двое обвиняемых напали на прохожего в такси и на улице в 11:00–13:00, используя нож и кулаки.
  Ответ:
  ```
  время: утро, день
  место: общественный транспорт, уличное пространство
  метод: холодное оружие, физическое воздействие
  связь: незнакомец, незнакомец
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "time_of_day": "неизвестно",
        "location": "другое",
        "method": "другое",
        "relationship": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "time_of_day": "неизвестно",
        "location": "другое",
        "method": "другое",
        "relationship": "неизвестно"
    }
    
    try:
        lines = text.split("\n")
        valid_times = ["утро", "день", "вечер", "ночь"]
        valid_locations = [
            "жилое помещение", "уличное пространство", "общественный транспорт",
            "общественное место", "подъезд и прилегающие зоны", "рабочая зона", "другое"
        ]
        valid_methods = [
            "физическое воздействие", "холодное оружие", "тяжелые предметы",
            "огнестрельное оружие", "удушение", "другое"
        ]
        valid_relationships = [
            "родственник", "супруг", "зять", "сожитель", "бывший супруг",
            "друг", "знакомый", "сосед", "коллега", "работник", "незнакомец",
            "брат", "отец", "сын", "дядя", "племянник", "неизвестно"
        ]
        
        for line in lines:
            line = line.strip()
            if line.startswith("время:"):
                time_part = line.replace("время:", "").strip()
                times = [t.strip() for t in time_part.split(",") if t.strip()]
                result["time_of_day"] = ", ".join([t if t in valid_times else "неизвестно" for t in times][:2]) or "неизвестно"
                
            elif line.startswith("место:"):
                loc_part = line.replace("место:", "").strip()
                locations = [loc.strip() for loc in loc_part.split(",") if loc.strip()]
                unique_locations = []
                for loc in locations:
                    loc = loc if loc in valid_locations else "другое"
                    if loc not in unique_locations:
                        unique_locations.append(loc)
                result["location"] = ", ".join(unique_locations) or "другое"
                
            elif line.startswith("метод:"):
                meth_part = line.replace("метод:", "").strip()
                methods = [meth.strip() for meth in meth_part.split(",") if meth.strip()]
                unique_methods = sorted(set([meth if meth in valid_methods else "другое" for meth in methods]))
                result["method"] = ", ".join(unique_methods) or "другое"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                relationships = [r.strip() for r in rel_part.split(",") if r.strip()]
                result["relationship"] = ", ".join([r if r in valid_relationships else "неизвестно" for r in relationships]) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_3k_my["clean_description3"] = df_3k_my["description"].apply(clean_text)
df_3k_my["predictions3"] = df_3k_my["clean_description3"].progress_apply(classify_with_gpt4)

100%|██████████| 3000/3000 [3:11:30<00:00,  3.83s/it]

In [630]:
df_3k_my["predicted_time_of_day"] = df_3k_my["predictions3"].apply(lambda x: x["time_of_day"])
df_3k_my["predicted_location"] = df_3k_my["predictions3"].apply(lambda x: x["location"])
df_3k_my["predicted_method"] = df_3k_my["predictions3"].apply(lambda x: x["method"])
df_3k_my["predicted_relationship3"] = df_3k_my["predictions3"].apply(lambda x: x["relationship"])

In [631]:
df_3k_my

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,predicted_motive,predicted_relationship,predicted_has_woman_victim,predicted_has_man_victim,clean_description3,predictions3,predicted_time_of_day,predicted_location,predicted_method,predicted_relationship3
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,...,личная неприязнь,супруг,0,1,У С Т А Н О В И Л: Власова Н.А. совершила убий...,"{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,"физическое воздействие, холодное оружие",супруг
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,...,личная неприязнь,знакомый,0,1,"УСТАНОВИЛ: около 22 часов 30 минут П.Д.В., нах...","{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,холодное оружие,знакомый
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,...,личная неприязнь,брат,0,1,у с т а н о в и л : Мингазов А.Д. совершил умы...,"{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,"физическое воздействие, холодное оружие","брат, брат, знакомый"
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,...,личная неприязнь,знакомый,0,1,"УСТАНОВИЛ: Блинов А.А. совершил убийство, то е...","{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,холодное оружие,знакомый
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,...,личная неприязнь,сожитель,1,0,У С Т А Н О В И Л: Грехнев А.Н. совершил убийс...,"{'time_of_day': 'вечер, ночь', 'location': 'жи...","вечер, ночь",жилое помещение,холодное оружие,сожитель
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,6580,26,2016-06-23,Панченко Юрий Васильевич - ст.105 ч.1 УК РФ,Кривцанова Галина Петровна,Вынесен ПРИГОВОР,Панченко Юрий Васильевич,ст.105 ч.1,http://blagodarnensky--stv.sudrf.ru/modules.ph...,Дело №1-99/2016\nПРИГОВОР\nИменем Российской Ф...,...,личная неприязнь,брат,0,1,У С Т А Н О В И Л: Панченко Ю.В. совершил убий...,"{'time_of_day': 'ночь', 'location': 'жилое пом...",ночь,жилое помещение,холодное оружие,брат
2996,62712,52,2018-03-23,Прутков Кирилл Игоревич - ст.105 ч.1 УК РФ,Егоров Андрей Владимирович,Вынесен ПРИГОВОР,Прутков Кирилл Игоревич,ст.105 ч.1,http://prioksky--nnov.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,"личная неприязнь, ревность",сожитель,1,0,УСТАНОВИЛ: около 01 часа 00 минут в квартире в...,"{'time_of_day': 'ночь', 'location': 'жилое пом...",ночь,жилое помещение,холодное оружие,сожитель
2997,54534,16,2018-10-12,"Аверкин Алексей Ринатович - ст.115 ч.2 п.в, ст...",Семенов Олег Владимирович,Вынесен ПРИГОВОР,Аверкин Алексей Ринатович,"ст.115 ч.2 п.в, ст. 30 ч.3, ст.105 ч.1",http://zelenodolsky--tat.sudrf.ru/modules.php?...,Дело №1-399/2018\nПРИГОВОР\nименем Российской ...,...,ревность,сожитель,1,1,УСТАНОВИЛ: Аверкин А.Р. совершил преступления ...,"{'time_of_day': 'утро, день', 'location': 'жил...","утро, день",жилое помещение,"физическое воздействие, холодное оружие","сожитель, сожитель"
2998,47517,66,2017-09-22,"Утюмов Вячеслав Гумарович - ст.105 ч.2 п.п.а,к...",Ладин Александр Максимович,Вынесен ПРИГОВОР,Утюмов Вячеслав Гумарович,"ст.105 ч.2 п.п.а,к",http://oblsud--svd.sudrf.ru/modules.php?name=s...,Дело № 2-40/2017\nИменем Российской Федерации\...,...,личная неприязнь,супруг,1,1,У С Т А Н О В И Л: Утюмов В.Г. совершил убийст...,"{'time_of_day': 'вечер, ночь', 'location': 'жи...","вечер, ночь",жилое помещение,"физическое воздействие, холодное оружие","знакомый, неизвестно"
2999,61493,49,2018-06-20,Трофимченко Евгений Михайлович - ст.105 ч.1 УК РФ,Сидорова Марина Александровна,Вынесен ПРИГОВОР,Трофимченко Евгений Михайлович,ст.105 ч.1,http://magadansky--mag.sudrf.ru/modules.php?na...,Дело № 1-298/2018 (11802440002000038)\nП Р И Г...,...,личная неприязнь,супруг,1,1,у с т а н о в и л : Трофимченко Е.М. совершил ...,"{'time_of_day': 'ночь', 'location': 'уличное п...",ночь,уличное пространство,"физическое воздействие, холодное оружие",знакомый

In [632]:
df_3k_my.to_csv("3k_3.csv", index=False, encoding='utf-8')

Размечаем еще 36к

In [651]:
import pandas as pd
import numpy as np
import zipfile

zip_path = "preprocessed_data1.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("preprocessed_data1.csv") as f:
        prep_df = pd.read_csv(f)

print(prep_df.shape)

(39119, 12)

In [652]:
prep_df.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...

In [653]:
import re

def count_killers(names_text: str) -> int:
    text = names_text.replace('\n', ' ').replace('\r', ' ').strip()

    people = re.split(r'\s*,\s*(?=[^,]*?\s*-\s*ст\.)', text)

    count = 0
    for person in people:
        if '105' in person:
            count += 1
    return count

prep_df['killer_count'] = prep_df['names'].apply(count_killers)

In [654]:
prep_df.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...,1
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...,1
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...,1
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...,1
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...,1

In [661]:
(prep_df['killer_count'] == 2).sum()

1027

In [662]:
prep_df2 = prep_df[
    ~prep_df['id'].isin(df_3k_my['id']) & 
    ~prep_df['id'].isin(dfff['id'])
].copy()

In [663]:
print(prep_df2.shape)

(36019, 13)

достаем 3 признака - пол прест + была ли судимость + срок заключ

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast
import numpy as np


client = OpenAI(api_key='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')

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

prep_df2["combined_text"] = prep_df2["preamble"].str.cat(prep_df2["sentence"], sep=" ").apply(clean_text)

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ или 111 УК РФ:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее по статье 105 УК РФ.
3. Финальный срок лишения свободы.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ. Если эти статьи не упоминаются для обвиняемого, не возвращай никаких данных для него (ни пол, ни судимости, ни срок).
- Количество значений для пола, судимостей и сроков должно равняться числу обвиняемых, указанному в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если обвиняемых меньше, чем killer_count, заполни недостающие значения: "неизвестно" для пола, "нет" для судимостей, "nan" для срока.
- Если обвиняемых больше, чем killer_count, верни данные только для первых killer_count обвиняемых.
- Если статьи 105 и 111 не упоминаются в тексте вообще, верни списки длиной killer_count: ["неизвестно", ...] для пола, ["нет", ...] для судимостей, ["nan", ...] для срока.

**Правила для пола:**
- Если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она", "обвиняемый"/"обвиняемая"), укажи "мужчина" или "женщина".
- Если информации нет, укажи "неизвестно".
- Формат: "пол: [<мужчина/женщина/неизвестно>, ...]".

**Правила для судимостей:**
- Если есть явное указание, что обвиняемый ранее судим по статье 105 УК РФ (например, "ранее судим по статье 105", "имеет судимость по статье 105"), укажи "да".
- Если указано отсутствие судимостей или судимости были по другим статьям (например, "ранее судим по статье 158", "не судим по статье 105"), укажи "нет".
- Если информации о судимостях по статье 105 нет, укажи "нет".
- Формат: "судимости: [<да/нет>, ...]".

**Правила для срока лишения свободы:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан, не может быть определен (например, вместо конкретных чисел написано "<данные изъяты>"), или наказание не связано с лишением свободы (например, штраф), верни "nan" для этого обвиняемого.
- Формат: "срок: [<число или nan>, ...]".

**Формат ответа:**
```
пол: [<мужчина/женщина/неизвестно>, ...]
судимости: [<да/нет>, ...]
срок: [<число или nan>, ...]
```

**Примеры:**
- Текст: Иванов, ранее судимый по статье 105 УК РФ, приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [да]
  срок: [4.83]
  ```
- Текст: Обвиняемый получил штраф по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [нет]
  срок: [nan]
  ```
- Текст: Иванов и Петрова, ранее судимые по статье 158 УК РФ, <данные изъяты> по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  пол: [мужчина, женщина]
  судимости: [нет, нет]
  срок: [nan, nan]
  ```
- Текст: Петров получил 3 года по статье 105 УК РФ, Сидоров — 3 года по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  пол: [мужчина, неизвестно]
  судимости: [нет, нет]
  срок: [3.00, nan]
  ```
- Текст: Иванов, ранее судимый по статье 159 УК РФ, приговорен к 5 годам по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [мужчина]
  судимости: [нет]
  срок: [5.00]
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  пол: [неизвестно]
  судимости: [нет]
  срок: [nan]
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["combined_text"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "gender": ["неизвестно"] * killer_count,
        "prior_convictions": ["нет"] * killer_count,
        "prison_term": ["nan"] * killer_count
    }

def normalize_prediction(text, killer_count):
    result = {
        "gender": ["неизвестно"] * killer_count,
        "prior_convictions": ["нет"] * killer_count,
        "prison_term": ["nan"] * killer_count
    }
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("пол:"):
                gender_part = line.replace("пол:", "").strip()
                if gender_part.startswith("[") and gender_part.endswith("]"):
                    gender_values = [v.strip() for v in gender_part[1:-1].split(",") if v.strip()]
                    gender_values = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
                    result["gender"] = gender_values[:killer_count] + ["неизвестно"] * (killer_count - len(gender_values))
                else:
                    gender_value = gender_part if gender_part in ["мужчина", "женщина", "неизвестно"] else "неизвестно"
                    result["gender"] = [gender_value] + ["неизвестно"] * (killer_count - 1)
                    
            elif line.startswith("судимости:"):
                convictions_part = line.replace("судимости:", "").strip()
                if convictions_part.startswith("[") and convictions_part.endswith("]"):
                    convictions_values = [v.strip() for v in convictions_part[1:-1].split(",") if v.strip()]
                    convictions_values = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
                    result["prior_convictions"] = convictions_values[:killer_count] + ["нет"] * (killer_count - len(convictions_values))
                else:
                    convictions_value = convictions_part if convictions_part in ["да", "нет"] else "нет"
                    result["prior_convictions"] = [convictions_value] + ["нет"] * (killer_count - 1)
                    
            elif line.startswith("срок:"):
                prison_term_part = line.replace("срок:", "").strip()
                if prison_term_part == "nan":
                    result["prison_term"] = ["nan"] * killer_count
                elif prison_term_part.startswith("[") and prison_term_part.endswith("]"):
                    terms = [v.strip() for v in prison_term_part[1:-1].split(",") if v.strip()]
                    normalized_terms = []
                    for term in terms:
                        try:
                            value = float(term)
                            if value > 0:
                                normalized_terms.append(f"{value:.2f}")
                            else:
                                normalized_terms.append("nan")
                        except ValueError:
                            normalized_terms.append("nan")
                    result["prison_term"] = normalized_terms[:killer_count] + ["nan"] * (killer_count - len(normalized_terms))
                else:
                    try:
                        value = float(prison_term_part)
                        if value > 0:
                            result["prison_term"] = [f"{value:.2f}"] + ["nan"] * (killer_count - 1)
                        else:
                            result["prison_term"] = ["nan"] * killer_count
                    except ValueError:
                        result["prison_term"] = ["nan"] * killer_count
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

prep_df2["predictions"] = prep_df2[["combined_text", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

In [665]:
prep_df2["predicted_gender"] = prep_df2["predictions"].apply(lambda x: ", ".join(x["gender"]) if x["gender"] else "")
prep_df2["predicted_prior_convictions"] = prep_df2["predictions"].apply(lambda x: ", ".join(x["prior_convictions"]) if x["prior_convictions"] else "")
prep_df2["predicted_prison_term"] = prep_df2["predictions"].apply(lambda x: ", ".join(x["prison_term"]) if x["prison_term"] else "")

In [667]:
prep_df2.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,combined_text,predictions,predicted_gender,predicted_prior_convictions,predicted_prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,УСТАНОВИЛ:\nЯковлев В.Н. умышлено причинил тяж...,ПРИГОВОРИЛ:\nЯковлева В. Н. признать виновным ...,1,Дело № 1-2/2020 55RS0005-01-1998-000001-11 ПРИ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,9.00
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,У С Т А Н О В И Л:\nИскяндаров Д.М.о. совершил...,П Р И Г О В О Р И Л\nИскяндарова Д.М. признать...,1,Решение вступило в законную силу: 11.11.2016 г...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,"УСТАНОВИЛ:\n12 сентября 1998 г., в вечернее вр...",ПРИГОВОРИЛ:\nПризнать Кузнецова Вячеслава Иван...,1,Дело №2-1/2019 244527 УИД 42OS0000-01-2000-000...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,13.00
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,У С Т А Н О В И Л:\nВ период совместного прожи...,П Р И Г О В О Р И Л:\nПризнать Скворцову О.А. ...,1,ПРИГОВОР Именем Российской Федерации г. Улан-У...,"{'gender': ['женщина'], 'prior_convictions': [...",женщина,нет,13.00
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,У С Т А Н О В И Л:\nПодсудимый Голованов В.П. ...,П Р И Г О В О Р И Л:\nПризнать Голованова Викт...,1,П Р И Г О В О Р ИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ г....,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,nan

In [686]:
prep_df2[18637:]

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,combined_text,predictions,predicted_gender,predicted_prior_convictions,predicted_prison_term
20244,83899,86,2019-03-29,Новикова Елена Анатольевна - ст.105 ч.1 УК РФ,Куклев Вячеслав Валерьевич,Вынесен ПРИГОВОР,Новикова Елена Анатольевна,ст.105 ч.1,http://kogalym--hmao.sudrf.ru/modules.php?name...,КОПИЯ\nдело № 1-47/2019\nУИД 86RS0008-01-2019-...,У С Т А Н О В И Л:\nФИО2 умышленно причинила т...,П Р И Г О В О Р И Л:\nФИО2 признать виновной в...,1,КОПИЯ дело № 1-47/2019 УИД 86RS0008-01-2019-00...,"{'gender': ['женщина'], 'prior_convictions': [...",женщина,нет,7.50
20245,72993,27,2019-04-01,Ерохина Валерия Евгеньевна - ст.105 ч.1 УК РФ,Гладун Денис Валерьевич,Вынесен ПРИГОВОР,Ерохина Валерия Евгеньевна,ст.105 ч.1,http://habarovskyr--hbr.sudrf.ru/modules.php?n...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,У С Т А Н О В И Л:\nОрганом предварительного с...,ПРИГОВОРИЛ:\nОправдать Ерохину Валерию Евгенье...,1,Дело № ПРИГОВОР Именем Российской Федерации г....,"{'gender': ['женщина'], 'prior_convictions': [...",женщина,нет,nan
20246,75896,43,2019-04-01,Трефилов Андрей Александрович - ст.105 ч.1 УК РФ,Махнев Владимир Валерьевич,Вынесен ПРИГОВОР,Трефилов Андрей Александрович,ст.105 ч.1,http://omutninsky--kir.sudrf.ru/modules.php?na...,№ 1-78/2019\nУИД 43 RS0026-01-2019-000388-22\n...,"УСТАНОВИЛ:\nТрефилов А.А. совершил убийство, т...",ПРИГОВОРИЛ:\nПризнать ТРЕФИЛОВА АНДРЕЯ АЛЕКСАН...,1,№ 1-78/2019 УИД 43 RS0026-01-2019-000388-22 П ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,9.50
20247,77813,52,2019-04-01,Кожирнов Сергей Александрович - ст.105 ч.1 УК РФ,Кащук Дмитрий Анатольевич,Вынесен ПРИГОВОР,Кожирнов Сергей Александрович,ст.105 ч.1,http://sormovsky--nnov.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,У С Т А Н О В И Л:\nПодсудимый\nсовершил убийс...,П Р И Г О В О Р И Л :\nПризнать\nвиновным в со...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,9.50
20248,81566,74,2019-04-01,Сарычев Сергей Владимирович - ст.105 ч.1 УК РФ,Свиридова Наталья Вениаминовна,Вынесен ПРИГОВОР,Сарычев Сергей Владимирович,ст.105 ч.1,http://zlatoust--chel.sudrf.ru/modules.php?nam...,Дело № 1-223/2019\nП Р И Г О В О Р\nИменем Рос...,У с т а н о в и л:\n29 января 2019 года в пери...,П р и г о в о р и л:\nПризнать Сарычева Сергея...,1,Дело № 1-223/2019 П Р И Г О В О Р Именем Росси...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,7.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,130207,58,2023-12-01,Илюхин Алексей Юрьевич - ст.105 ч.1 УК РФ,Угрушева Юлия Александровна,Вынесен ПРИГОВОР,Илюхин Алексей Юрьевич,ст.105 ч.1,http://zemetchinsky--pnz.sudrf.ru/modules.php?...,дело №1-37/(2023)\nПРИГОВОР\nИменем Российской...,УСТАНОВИЛ:\nИлюхин А.Ю. совершил убийство ФИО1...,ПРИГОВОРИЛ:\nпризнать Илюхина Алексея Юрьевича...,1,дело №1-37/(2023) ПРИГОВОР Именем Российской Ф...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan
39115,124747,22,2023-12-01,Коновальцев Алексей Иванович - ст.105 ч.1 УК РФ,Мамаева Яна Юрьевна,Вынесен ПРИГОВОР,Коновальцев Алексей Иванович,ст.105 ч.1,http://talmensky--alt.sudrf.ru/modules.php?nam...,Уникальный идентификатор дела: 22RS0051-01-202...,У С Т А Н О В И Л:\nКоновальцев А.И. совершил ...,П Р И Г О В О Р И Л:\nКоновальцева А.И. призна...,1,Уникальный идентификатор дела: 22RS0051-01-202...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan
39116,129083,50,2023-12-04,Исаев Илья Сергеевич - ст.105 ч.1 УК РФ,Сидоров П.А.,Вынесен ПРИГОВОР,Исаев Илья Сергеевич,ст.105 ч.1,http://ramenskoe--mo.sudrf.ru/modules.php?name...,50RS0039-01-2023-014621-76 Дело № 1-801/23\nПР...,"УСТАНОВИЛ:\nИсаев И.С. совершил убийство, то е...",ПРИГОВОРИЛ:\nПризнать Исаева И. С. виновным в ...,1,50RS0039-01-2023-014621-76 Дело № 1-801/23 ПРИ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan
39117,124382,2,2023-12-04,Файзрахманов Данил Ильдарович - ст.105 ч.1 УК РФ,Шаймухаметов Р.Р.,Вынесен ПРИГОВОР,Файзрахманов Данил Ильдарович,ст.105 ч.1,http://kirovsky--bkr.sudrf.ru/modules.php?name...,Дело №1-610/2023\nУИД 03RS0003-01-2023-013502\...,установил:\nФайзрахманов Д.И. совершил убийств...,приговорил:\nПодсудимого Файзрахманова Данила ...,1,Дело №1-610/2023 УИД 03RS0003-01-2023-013502 П...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan
39118,126271,3,2023-12-07,Молчанова Мария Михайловна - ст.105 ч.1 УК РФ,Очирова Арюна Владимировна,Вынесен ПРИГОВОР,Молчанова Мария Михайловна,ст.105 ч.1,http://zheleznodorozhniy--bur.sudrf.ru/modules...,Уголовное дело № 1-910/2023\nПРИГОВОР\nИМЕНЕМ ...,УСТАНОВИЛ:\n18.09.2023 около 18 часов Молчанов...,ПРИГОВОРИЛ:\nПризнать Малчанову М.М. виновной ...,1,Уголовное дело № 1-910/2023 ПРИГОВОР ИМЕНЕМ РО...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,nan

In [666]:
prep_df2.to_csv("36k.csv", index=False, encoding='utf-8')

In [697]:
df_new = prep_df2[prep_df2['predicted_prison_term'] == "nan"]
df_new.shape

(6995, 18)

собираем вместе

In [718]:
zip_path = "df_labeled_all.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("df_labeled_all.csv") as f:
        df_labeled_all = pd.read_csv(f)

df_labeled_all.shape

(34765, 23)

In [719]:
df_labeled_all.head()

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,gender_accused,prior_convictions,alcohol,precrime_argument,has_woman_victim,has_man_victim,method,motive,location,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,мужчина,нет,да,была,0,1.0,тяжелые предметы,личная неприязнь,"рабочая зона, уличное пространство",8.191830
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,"общественное место, уличное пространство",7.986857
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие","корысть, личная неприязнь",жилое помещение,10.631853
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,женщина,нет,нет,была,0,1.0,огнестрельное оружие,"корысть, личная неприязнь",уличное пространство,9.172660
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,мужчина,нет,да,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.311355

In [720]:
df_labeled_all['id'].nunique()

34765

In [700]:
file_path = 'prep_df3.csv'
df3 = pd.read_csv(file_path, on_bad_lines='warn')

In [703]:
df3

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,combined_text,predictions,predicted_gender,predicted_prior_convictions,predicted_prison_term
0,115151,40,2022-05-31,"Шевченко Юрий Александрович - ст.158 ч.1, ст.1...",Музюкин Алексей Владимирович,Вынесен ПРИГОВОР,Шевченко Юрий Александрович,"ст.158 ч.1, ст.158 ч.1, ст.158 ч.1, ст. 30 ч.3...",http://obninsky--klg.sudrf.ru/modules.php?name...,Дело № 1-149/2022 40RS0026-01-2022-001427-35\n...,У С Т А Н О В И Л:\nПодсудимый Шевченко Ю.А. с...,П Р И Г О В О Р И Л:\nПризнать Шевченко Юрия А...,1,Дело № 1-149/2022 40RS0026-01-2022-001427-35 П...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,NaN
1,115942,46,2022-04-25,Манешин Виктор Викторович - ст.105 ч.1 УК РФ,Адамова Ирина Борисовна,Вынесен ПРИГОВОР,Манешин Виктор Викторович,ст.105 ч.1,http://lgovsky--krs.sudrf.ru/modules.php?name=...,Решение по уголовному делу\nИнформация по делу...,У С Т А Н О В И Л:\nМанешин В.В. совершил убий...,П Р И Г О В О Р И Л:\nПризнать Манешина\nФИО62...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,NaN
2,123924,16,2023-02-06,Яриков Андрей Александрович - ст.105 ч.1 УК РФ,Хакимов Рустам Назифович,Вынесен ПРИГОВОР,Яриков Андрей Александрович,ст.105 ч.1,http://naberezhno-chelninsky--tat.sudrf.ru/mod...,Решение по уголовному делу\nИнформация по делу...,У С Т А Н О В И Л:\n10 ноября 2022 года в пери...,П Р И Г О В О Р И Л:\nЯрикова Андрея Александр...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,10.0
3,133492,76,2022-12-08,"Филиппов Виленин Виленинович - ст.222 ч.1, ст....",Гасюков Андрей Иванович,Вынесен ПРИГОВОР,Филиппов Виленин Виленинович,"ст.222 ч.1, ст.105 ч.1",http://kirovsky--jrs.sudrf.ru/modules.php?name...,Решение по уголовному делу\nИнформация по делу...,У С Т А Н О В И Л:\nВердиктом коллегии присяжн...,П Р И Г О В О Р И Л:\nПризнать Филиппова Вилен...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,8.5
4,114859,38,2022-03-23,Копылова Наталья Валерьевна - ст.105 ч.1 УК РФ,Суховеркина Татьяна Владимировна,Вынесен ПРИГОВОР,Копылова Наталья Валерьевна,ст.105 ч.1,http://sayansky--irk.sudrf.ru/modules.php?name...,ПРИГОВОР\nименем Российской Федерации\nДД.ММ.Г...,"установил :\nКопылова Н.В. совершила убийство,...",приговорил :\nПризнать Копылову Н. В. виновной...,1,ПРИГОВОР именем Российской Федерации ДД.ММ.ГГГ...,"{'gender': ['женщина'], 'prior_convictions': [...",женщина,нет,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,133494,76,2023-02-28,Козлов Владимир Васильевич - ст.105 ч.1 УК РФ,Сергеева Елена Анатольевна,Вынесен ПРИГОВОР,Козлов Владимир Васильевич,ст.105 ч.1,http://kirovsky--jrs.sudrf.ru/modules.php?name...,Дело № 1-87/2023\nУИД: 76:RS0014-02-2023-00011...,У С Т А Н О В И Л:\nКозлов В.В. виновен в убий...,П Р И Г О В О Р И Л:\nПризнать Козлова Владими...,1,Дело № 1-87/2023 УИД: 76:RS0014-02-2023-000113...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
2996,113227,3,2022-03-11,Пантелеев Владимир Владимирович - ст.105 ч.1 У...,Куликова Алёна Леонидовна,Вынесен ПРИГОВОР,Пантелеев Владимир Владимирович,ст.105 ч.1,http://bichursky--bur.sudrf.ru/modules.php?nam...,Дело № 1-27/2022\nУИД 04RS0003-01-2022-000228-...,"УСТАНОВИЛ:\nПантелеев В.В. совершил убийство, ...",ПРИГОВОРИЛ:\nПризнать Пантелеева В.В. виновным...,1,Дело № 1-27/2022 УИД 04RS0003-01-2022-000228-2...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
2997,97669,10,2021-02-01,"Любарец Олег Петрович - ст. 30 ч.3, ст.105 ч.1...",Маковский Михаил Анатольевич,Вынесен ПРИГОВОР,Любарец Олег Петрович,"ст. 30 ч.3, ст.105 ч.1",http://belomorsky--kar.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,"у с т а н о в и л:\nЛюбарец О.П., в период с 2...",п р и г о в о р и л:\nпризнать виновным в сове...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
2998,133532,76,2023-07-03,"Каюров Владимир Александрович - ст.119 ч.1, ст...",Балаев Евгений Александрович,Вынесен ПРИГОВОР,Каюров Владимир Александрович,"ст.119 ч.1, ст. 30 ч.3, ст.105 ч.2 п.а, ст.158...",http://oblsud--jrs.sudrf.ru/modules.php?name=s...,Дело-№ 2-17/2023 год\nУИД 760S0000-01-2023-000...,установил:\nКаюров В.А. совершил следующие пре...,приговорил:\nПризнать Каюрова В.А. виновным в ...,1,Дело-№ 2-17/2023 год УИД 760S0000-01-2023-0000...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
2999,60624,42,2018-01-23,Петров Сергей Александрович - ст.105 ч.1 УК РФ,Невирович В.С.,Вынесен ПРИГОВОР,Петров Сергей Александрович,ст.105 ч.1,http://kirovsky--kmr.sudrf.ru/modules.php?name...,Дело № 1-35-18\nП Р И Г О В О Р\nИменем Россий...,У С Т А Н О В И Л:\nПетров С.А. совершил убийс...,ПРИГОВОРИЛ:\nПризнать виновным Петрова С.А. в ...,1,Дело № 1-35-18 П Р И Г О В О Р Именем Российск...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN

In [705]:
file_path = 'prep_df3.2.csv'
df32 = pd.read_csv(file_path, on_bad_lines='warn')

In [706]:
df32

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,description,sentence,killer_count,combined_text,predictions,predicted_gender,predicted_prior_convictions,predicted_prison_term
0,129155,50,2023-05-10,Козельский Владимир Сергеевич - ст.105 ч.1 УК РФ,Кузнецова Надежда Александровна,Вынесен ПРИГОВОР,Козельский Владимир Сергеевич,ст.105 ч.1,http://shelkovo--mo.sudrf.ru/modules.php?name=...,№ УИД №\nПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ...,"УСТАНОВИЛ:\nКозельский В.С. совершил убийство,...",ПРИГОВОРИЛ:\nКозельский В.С. признать виновным...,1,№ УИД № ПРИГОВОР ИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ Д...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,6.00
1,123271,1,2022-10-03,"Савченко Лидия Владимировна - ст. 30 ч.3, ст.1...",Сташ Бэлла Юрьевна,Вынесен ПРИГОВОР,Савченко Лидия Владимировна,"ст. 30 ч.3, ст.105 ч.1",http://maikopsky--adg.sudrf.ru/modules.php?nam...,К делу №\nП Р И Г О В О Р\nИменем Российской Ф...,У С Т А Н О В И Л :\nФИО1 совершила умышленное...,П Р И Г О В О Р И Л :\nПризнать ФИО1 виновной ...,1,К делу № П Р И Г О В О Р Именем Российской Фед...,"{'gender': ['женщина'], 'prior_convictions': [...",женщина,нет,3.00
2,51057,76,2016-09-15,Воробьев Андрей Иванович - ст.105 ч.1 УК РФ,Яшин Е.В.,Вынесен ПРИГОВОР,Воробьев Андрей Иванович,ст.105 ч.1,http://pereslavsky--jrs.sudrf.ru/modules.php?n...,Дело № 1-4/2017\nП Р И Г О В О Р\nИМЕНЕМ РОССИ...,У С Т А Н О В И Л:\nВоробьев А.И. обвиняется в...,П Р И Г О В О Р И Л:\nВоробьева Андрея Иванови...,1,Дело № 1-4/2017 П Р И Г О В О Р ИМЕНЕМ РОССИЙС...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,NaN
3,109770,11,2022-07-29,"Заболоцкий Стефан Маркович - ст.115 ч.2 п.в, с...",Нечаева Екатерина Андреевна,Вынесен ПРИГОВОР,Заболоцкий Стефан Маркович,"ст.115 ч.2 п.в, ст.105 ч.1",http://syktsud--komi.sudrf.ru/modules.php?name...,УИД 11RS0001-01-2022-012042-19 Дело №1-955/202...,УСТАНОВИЛ:\nЗаболоцкий С.М. совершил умышленно...,ПРИГОВОРИЛ:\nПризнать Заболоцкого Стефана Марк...,1,УИД 11RS0001-01-2022-012042-19 Дело №1-955/202...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,нет,10.17
4,92557,59,2019-11-26,Белорусцев Станислав Николаевич - ст.105 ч.1 У...,Кротов Иван Иванович,Вынесен ПРИГОВОР,Белорусцев Станислав Николаевич,ст.105 ч.1,http://krasnokam--perm.sudrf.ru/modules.php?na...,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nБелорусцев С.Н.\nсовершил убийство...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['мужчина'], 'prior_convictions': [...",мужчина,да,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,134947,89,2023-04-04,Карычев Гельман Гималетдинович - ст.105 ч.1 УК РФ,Яковлев Данил Валерьевич,Вынесен ПРИГОВОР,Карычев Гельман Гималетдинович,ст.105 ч.1,http://salehardsky--ynao.sudrf.ru/modules.php?...,Решение по уголовному делу\nИнформация по делу...,У С Т А Н О В И Л:\nКарычев Г. Г. совершил уби...,П Р И Г О В О Р И Л:\nПризнать КАРЫЧЕВА\nГ.Г.\...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
1996,129671,54,2023-07-26,Сорокин Александр Владимирович - ст.105 ч.1 УК РФ,Криницына Анастасия Сергеевна,Вынесен ПРИГОВОР,Сорокин Александр Владимирович,ст.105 ч.1,http://zaelcovsky--nsk.sudrf.ru/modules.php?na...,Уникальный идентификатор дела __\nДело __\nПос...,установил:\nСорокин А.В. совершил убийство Пот...,приговорил:\nСорокина А. В. признать виновным ...,1,Уникальный идентификатор дела __ Дело __ Посту...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
1997,132638,72,2023-03-29,Монин Иван Иванович - ст.105 ч.1 УК РФ,Перминов Станислав Геннадьевич,Вынесен ПРИГОВОР,Монин Иван Иванович,ст.105 ч.1,http://leninsky--tum.sudrf.ru/modules.php?name...,№ 1-812/2023\nП Р И Г О В О Р\nИменем Российск...,у с т а н о в и л:\n06.01.2023 в период времен...,П Р И Г О В О Р И Л:\nМонина И.И. признать вин...,1,№ 1-812/2023 П Р И Г О В О Р Именем Российской...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
1998,79847,64,2019-10-31,Бодров Александр Александрович - ст.105 ч.2 п....,Бодров О.Ю.,Вынесен ПРИГОВОР,Бодров Александр Александрович,ст.105 ч.2 п.а,http://oblsud--sar.sudrf.ru/modules.php?name=s...,Решение по уголовному делу\nИнформация по делу...,у с т а н о в и л:\nПодсудимый Бодров А.А. сов...,п р и г о в о р и л:\nпризнать виновным в сове...,1,Решение по уголовному делу Информация по делу ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN
1999,76228,47,2019-03-28,Крюков Игорь Владимирович - ст.105 ч.1 УК РФ,Осипов Николай Владимирович,Вынесен ПРИГОВОР,Крюков Игорь Владимирович,ст.105 ч.1,http://kingisepp--lo.sudrf.ru/modules.php?name...,№ 1-98/2019\nП Р И Г О В О Р\nИМЕНЕМ РОССИЙСКО...,У С Т А Н О В И Л:\nКрюков Игорь Владимирович ...,П Р И Г О В О Р И Л:\nКрюкова Игоря Владимиров...,1,№ 1-98/2019 П Р И Г О В О Р ИМЕНЕМ РОССИЙСКОЙ ...,"{'gender': ['неизвестно'], 'prior_convictions'...",неизвестно,нет,NaN

In [708]:
zip_path = "36k.csv.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("36k.csv") as f:
        df_all = pd.read_csv(f)

df_all.shape

(36019, 18)

In [709]:
combined_df = pd.concat([df3, df32, df_all], ignore_index=True)

In [710]:
combined_df.shape

(41019, 18)

In [711]:
combined_df = combined_df.dropna(subset=['predicted_prison_term'])

In [712]:
combined_df = combined_df[combined_df['killer_count'] < 2]

In [713]:
combined_df.shape

(28723, 18)

In [714]:
combined_df['id'].nunique()

28723

In [721]:
id_to_predicted = combined_df.set_index('id')['predicted_prison_term'].to_dict()

df_labeled_all['prison_term'] = df_labeled_all.apply(
    lambda row: id_to_predicted.get(row['id'], row['prison_term']),
    axis=1
)

In [722]:
df_labeled_all

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,gender_accused,prior_convictions,alcohol,precrime_argument,has_woman_victim,has_man_victim,method,motive,location,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,мужчина,нет,да,была,0,1.0,тяжелые предметы,личная неприязнь,"рабочая зона, уличное пространство",9.00
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,"общественное место, уличное пространство",7.986857
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие","корысть, личная неприязнь",жилое помещение,13.00
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,женщина,нет,нет,была,0,1.0,огнестрельное оружие,"корысть, личная неприязнь",уличное пространство,13.00
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,мужчина,нет,да,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.311355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34760,130207,58,2023-12-01,Илюхин Алексей Юрьевич - ст.105 ч.1 УК РФ,Угрушева Юлия Александровна,Вынесен ПРИГОВОР,Илюхин Алексей Юрьевич,ст.105 ч.1,http://zemetchinsky--pnz.sudrf.ru/modules.php?...,дело №1-37/(2023)\nПРИГОВОР\nИменем Российской...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,другое,7.173814
34761,124747,22,2023-12-01,Коновальцев Алексей Иванович - ст.105 ч.1 УК РФ,Мамаева Яна Юрьевна,Вынесен ПРИГОВОР,Коновальцев Алексей Иванович,ст.105 ч.1,http://talmensky--alt.sudrf.ru/modules.php?nam...,Уникальный идентификатор дела: 22RS0051-01-202...,...,мужчина,да,да,была,1,1.0,"удушение, физическое воздействие",личная неприязнь,жилое помещение,8.322342
34762,129083,50,2023-12-04,Исаев Илья Сергеевич - ст.105 ч.1 УК РФ,Сидоров П.А.,Вынесен ПРИГОВОР,Исаев Илья Сергеевич,ст.105 ч.1,http://ramenskoe--mo.sudrf.ru/modules.php?name...,50RS0039-01-2023-014621-76 Дело № 1-801/23\nПР...,...,мужчина,нет,нет,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.810283
34763,124382,2,2023-12-04,Файзрахманов Данил Ильдарович - ст.105 ч.1 УК РФ,Шаймухаметов Р.Р.,Вынесен ПРИГОВОР,Файзрахманов Данил Ильдарович,ст.105 ч.1,http://kirovsky--bkr.sudrf.ru/modules.php?name...,Дело №1-610/2023\nУИД 03RS0003-01-2023-013502\...,...,мужчина,нет,да,была,0,1.0,физическое воздействие,личная неприязнь,уличное пространство,8.415129
34764,126271,3,2023-12-07,Молчанова Мария Михайловна - ст.105 ч.1 УК РФ,Очирова Арюна Владимировна,Вынесен ПРИГОВОР,Молчанова Мария Михайловна,ст.105 ч.1,http://zheleznodorozhniy--bur.sudrf.ru/modules...,Уголовное дело № 1-910/2023\nПРИГОВОР\nИМЕНЕМ ...,...,женщина,да,да,была,0,1.0,холодное оружие,личная неприязнь,уличное пространство,7.699321

In [723]:
id_to_predicted = combined_df.set_index('id')['predicted_prior_convictions'].to_dict()

df_labeled_all['prior_convictions'] = df_labeled_all.apply(
    lambda row: id_to_predicted.get(row['id'], row['prior_convictions']),
    axis=1
)

In [724]:
df_labeled_all

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,gender_accused,prior_convictions,alcohol,precrime_argument,has_woman_victim,has_man_victim,method,motive,location,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,мужчина,нет,да,была,0,1.0,тяжелые предметы,личная неприязнь,"рабочая зона, уличное пространство",9.00
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,"общественное место, уличное пространство",7.986857
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие","корысть, личная неприязнь",жилое помещение,13.00
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,женщина,нет,нет,была,0,1.0,огнестрельное оружие,"корысть, личная неприязнь",уличное пространство,13.00
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,мужчина,нет,да,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.311355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34760,130207,58,2023-12-01,Илюхин Алексей Юрьевич - ст.105 ч.1 УК РФ,Угрушева Юлия Александровна,Вынесен ПРИГОВОР,Илюхин Алексей Юрьевич,ст.105 ч.1,http://zemetchinsky--pnz.sudrf.ru/modules.php?...,дело №1-37/(2023)\nПРИГОВОР\nИменем Российской...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,другое,7.173814
34761,124747,22,2023-12-01,Коновальцев Алексей Иванович - ст.105 ч.1 УК РФ,Мамаева Яна Юрьевна,Вынесен ПРИГОВОР,Коновальцев Алексей Иванович,ст.105 ч.1,http://talmensky--alt.sudrf.ru/modules.php?nam...,Уникальный идентификатор дела: 22RS0051-01-202...,...,мужчина,да,да,была,1,1.0,"удушение, физическое воздействие",личная неприязнь,жилое помещение,8.322342
34762,129083,50,2023-12-04,Исаев Илья Сергеевич - ст.105 ч.1 УК РФ,Сидоров П.А.,Вынесен ПРИГОВОР,Исаев Илья Сергеевич,ст.105 ч.1,http://ramenskoe--mo.sudrf.ru/modules.php?name...,50RS0039-01-2023-014621-76 Дело № 1-801/23\nПР...,...,мужчина,нет,нет,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.810283
34763,124382,2,2023-12-04,Файзрахманов Данил Ильдарович - ст.105 ч.1 УК РФ,Шаймухаметов Р.Р.,Вынесен ПРИГОВОР,Файзрахманов Данил Ильдарович,ст.105 ч.1,http://kirovsky--bkr.sudrf.ru/modules.php?name...,Дело №1-610/2023\nУИД 03RS0003-01-2023-013502\...,...,мужчина,нет,да,была,0,1.0,физическое воздействие,личная неприязнь,уличное пространство,8.415129
34764,126271,3,2023-12-07,Молчанова Мария Михайловна - ст.105 ч.1 УК РФ,Очирова Арюна Владимировна,Вынесен ПРИГОВОР,Молчанова Мария Михайловна,ст.105 ч.1,http://zheleznodorozhniy--bur.sudrf.ru/modules...,Уголовное дело № 1-910/2023\nПРИГОВОР\nИМЕНЕМ ...,...,женщина,да,да,была,0,1.0,холодное оружие,личная неприязнь,уличное пространство,7.699321

In [726]:
zip_path = "3k_3.csv.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("3k_3.csv") as f:
        df_3k = pd.read_csv(f)

df_3k.shape

(3000, 31)

In [739]:
df_3k = df_3k[~df_3k['predicted_prison_term'].astype(str).str.contains(',')]

In [740]:
df_3k

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,predicted_motive,predicted_relationship,predicted_has_woman_victim,predicted_has_man_victim,clean_description3,predictions3,predicted_time_of_day,predicted_location,predicted_method,predicted_relationship3
0,53674,10,2018-02-28,Власова Наталья Александровна - ст.105 ч.1 УК РФ,Грабчук Олег Владимирович,Вынесен ПРИГОВОР,Власова Наталья Александровна,ст.105 ч.1,http://petrozavodsky--kar.sudrf.ru/modules.php...,Дело № 1-208/12-2018\nП Р И Г О В О Р\nименем ...,...,личная неприязнь,супруг,0,1,У С Т А Н О В И Л: Власова Н.А. совершила убий...,"{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,"физическое воздействие, холодное оружие",супруг
1,18351,61,2015-08-13,"Проскурнов Дмитрий Владимирович - ст. 30 ч.3, ...",Егоров Николай Петрович,Вынесен ПРИГОВОР,Проскурнов Дмитрий Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://novocherkassky--ros.sudrf.ru/modules.ph...,Дело №\nПРИГОВОР\nИменем Российской Федерации\...,...,личная неприязнь,знакомый,0,1,"УСТАНОВИЛ: около 22 часов 30 минут П.Д.В., нах...","{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,холодное оружие,знакомый
2,85412,18,2019-12-13,Мингазов Александр Дамирович - ст.105 ч.1 УК РФ,Танаев Алексей Юрьевич,Вынесен ПРИГОВОР,Мингазов Александр Дамирович,ст.105 ч.1,http://malopurginskiy--udm.sudrf.ru/modules.ph...,Решение по уголовному делу\nИнформация по делу...,...,личная неприязнь,брат,0,1,у с т а н о в и л : Мингазов А.Д. совершил умы...,"{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,"физическое воздействие, холодное оружие","брат, брат, знакомый"
3,60373,42,2018-05-11,Блинов Александр Анатольевич - ст.105 ч.1 УК РФ,Баженов А.А.,Вынесен ПРИГОВОР,Блинов Александр Анатольевич,ст.105 ч.1,http://belovskygor--kmr.sudrf.ru/modules.php?n...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Белов...,...,личная неприязнь,знакомый,0,1,"УСТАНОВИЛ: Блинов А.А. совершил убийство, то е...","{'time_of_day': 'вечер', 'location': 'жилое по...",вечер,жилое помещение,холодное оружие,знакомый
4,60835,43,2018-03-12,Грехнев Алексей Николаевич - ст.105 ч.1 УК РФ,Зайцев К.Г.,Вынесен ПРИГОВОР,Грехнев Алексей Николаевич,ст.105 ч.1,http://leninsky--kir.sudrf.ru/modules.php?name...,Дело № 1-0220/2018 (11702330002030403)\nП р и ...,...,личная неприязнь,сожитель,1,0,У С Т А Н О В И Л: Грехнев А.Н. совершил убийс...,"{'time_of_day': 'вечер, ночь', 'location': 'жи...","вечер, ночь",жилое помещение,холодное оружие,сожитель
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,6580,26,2016-06-23,Панченко Юрий Васильевич - ст.105 ч.1 УК РФ,Кривцанова Галина Петровна,Вынесен ПРИГОВОР,Панченко Юрий Васильевич,ст.105 ч.1,http://blagodarnensky--stv.sudrf.ru/modules.ph...,Дело №1-99/2016\nПРИГОВОР\nИменем Российской Ф...,...,личная неприязнь,брат,0,1,У С Т А Н О В И Л: Панченко Ю.В. совершил убий...,"{'time_of_day': 'ночь', 'location': 'жилое пом...",ночь,жилое помещение,холодное оружие,брат
2996,62712,52,2018-03-23,Прутков Кирилл Игоревич - ст.105 ч.1 УК РФ,Егоров Андрей Владимирович,Вынесен ПРИГОВОР,Прутков Кирилл Игоревич,ст.105 ч.1,http://prioksky--nnov.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,"личная неприязнь, ревность",сожитель,1,0,УСТАНОВИЛ: около 01 часа 00 минут в квартире в...,"{'time_of_day': 'ночь', 'location': 'жилое пом...",ночь,жилое помещение,холодное оружие,сожитель
2997,54534,16,2018-10-12,"Аверкин Алексей Ринатович - ст.115 ч.2 п.в, ст...",Семенов Олег Владимирович,Вынесен ПРИГОВОР,Аверкин Алексей Ринатович,"ст.115 ч.2 п.в, ст. 30 ч.3, ст.105 ч.1",http://zelenodolsky--tat.sudrf.ru/modules.php?...,Дело №1-399/2018\nПРИГОВОР\nименем Российской ...,...,ревность,сожитель,1,1,УСТАНОВИЛ: Аверкин А.Р. совершил преступления ...,"{'time_of_day': 'утро, день', 'location': 'жил...","утро, день",жилое помещение,"физическое воздействие, холодное оружие","сожитель, сожитель"
2998,47517,66,2017-09-22,"Утюмов Вячеслав Гумарович - ст.105 ч.2 п.п.а,к...",Ладин Александр Максимович,Вынесен ПРИГОВОР,Утюмов Вячеслав Гумарович,"ст.105 ч.2 п.п.а,к",http://oblsud--svd.sudrf.ru/modules.php?name=s...,Дело № 2-40/2017\nИменем Российской Федерации\...,...,личная неприязнь,супруг,1,1,У С Т А Н О В И Л: Утюмов В.Г. совершил убийст...,"{'time_of_day': 'вечер, ночь', 'location': 'жи...","вечер, ночь",жилое помещение,"физическое воздействие, холодное оружие","знакомый, неизвестно"
2999,61493,49,2018-06-20,Трофимченко Евгений Михайлович - ст.105 ч.1 УК РФ,Сидорова Марина Александровна,Вынесен ПРИГОВОР,Трофимченко Евгений Михайлович,ст.105 ч.1,http://magadansky--mag.sudrf.ru/modules.php?na...,Дело № 1-298/2018 (11802440002000038)\nП Р И Г...,...,личная неприязнь,супруг,1,1,у с т а н о в и л : Трофимченко Е.М. совершил ...,"{'time_of_day': 'ночь', 'location': 'уличное п...",ночь,уличное пространство,"физическое воздействие, холодное оружие",знакомый

In [749]:
c = 0
for v,k in df_3k['predicted_prison_term'].value_counts().items():
    if ',' in v:
        c+=k
    print(v, k)

9.00 345
8.00 342
7.00 267
6.00 196
10.00 182
9.50 120
8.50 104
11.00 102
7.50 90
6.50 88
12.00 87
5.00 60
13.00 55
4.00 52
3.00 39
15.00 38
14.00 33
17.00 32
10.50 29
16.00 25
9.83 22
18.00 21
4.50 19
11.50 19
5.50 18
3.50 17
19.00 15
6.08 12
2.00 12
12.50 12
9.08 12
13.50 11
1.50 11
20.00 10
6.17 10
2.50 10
1.00 9
6.75 9
8.83 8
7.25 8
9.25 8
14.50 7
6.25 6
1.83 5
9.75 5
7.08 5
9.17 5
7.83 5
7.67 5
9.92 5
9.58 4
10.17 4
8.08 4
6.83 4
8.75 4
7.17 4
10.08 4
4.83 4
24.00 4
9.03 3
5.08 3
6.58 3
10.33 3
3.67 3
16.50 3
6.33 3
10.25 3
1.25 3
15.50 3
22.00 3
1.08 3
2.17 3
10.92 3
9.42 3
11.25 3
9.67 3
8.17 3
8.42 3
8.67 3
23.00 3
7.75 2
18.08 2
8.92 2
12.08 2
7.42 2
7.58 2
0.50 2
9.33 2
11.83 2
18.50 2
3.83 2
12.67 2
14.75 2
5.25 2
6.67 2
11.08 2
12.17 2
11.33 2
10.03 2
8.33 2
6.42 2
17.08 2
2.67 2
1.67 1
9999.00 1
13.17 1
12.75 1
2.92 1
7.92 1
7.03 1
9.54 1
7.01 1
6.62 1
23.50 1
1.17 1
16.01 1
9.19 1
5.58 1
10.83 1
12.58 1
25.00 1
12.92 1
17.17 1
1.75 1
1.92 1
16.08 1
13.08 1
11.58 1
17.03 1
3.33 1
15.83 1
27.50 1
1.14 1
9.20 1
18.25 1
9.55 1
3.42 1
6.52 1
11.17 1
10.58 1
12.42 1
17.25 1
12.25 1
19.08 1
8.52 1
14.04 1
14.33 1
8.55 1
12.33 1
7.33 1
10.75 1
20.50 1
10.67 1
7.06 1
18.67 1
20.03 1
7.14 1
2.25 1
5.17 1
0.83 1
8.25 1
10.42 1
6.03 1
19.50 1
4.17 1
4.67 1
20.08 1
11.92 1
21.08 1
17.83 1
21.00 1

In [728]:
df_3k.columns

Index(['id', 'region', 'entryDate', 'names', 'judge', 'decision', 'accused',
       'articles', 'link_text', 'preamble', 'description', 'sentence',
       'killer_count', 'combined_text', 'predictions', 'predicted_gender',
       'predicted_prior_convictions', 'predicted_prison_term', 'predictions2',
       'predicted_alcohol', 'predicted_precrime_argument', 'predicted_motive',
       'predicted_relationship', 'predicted_has_woman_victim',
       'predicted_has_man_victim', 'clean_description3', 'predictions3',
       'predicted_time_of_day', 'predicted_location', 'predicted_method',
       'predicted_relationship3'],
      dtype='object')

In [750]:
df_3k = df_3k.drop(columns=[
    'combined_text',
    'predictions',
    'predictions2',
    'predicted_time_of_day',
    'predicted_relationship',
    'clean_description3',
    'predictions3',
    'predicted_time_of_day',
    'predicted_relationship3'
])

In [751]:
df_3k.columns

Index(['id', 'region', 'entryDate', 'names', 'judge', 'decision', 'accused',
       'articles', 'link_text', 'preamble', 'description', 'sentence',
       'killer_count', 'predicted_gender', 'predicted_prior_convictions',
       'predicted_prison_term', 'predicted_alcohol',
       'predicted_precrime_argument', 'predicted_motive',
       'predicted_has_woman_victim', 'predicted_has_man_victim',
       'predicted_location', 'predicted_method'],
      dtype='object')

In [752]:
df_3k = df_3k.rename(columns={
    'predicted_prison_term': 'prison_term',
    'predicted_gender': 'gender_accused',
    'predicted_prior_convictions' : 'prior_convictions',
    'predicted_prison_term' : 'prison_term',
    'predicted_alcohol' : 'alcohol',
    'predicted_precrime_argument' : 'precrime_argument',
    'predicted_motive' : 'motive', 
    'predicted_has_woman_victim' : 'has_woman_victim',
    'predicted_has_man_victim' : 'has_man_victim',
    'predicted_location' : 'location',
    'predicted_method' : 'method'
})

In [753]:
df_3k.columns

Index(['id', 'region', 'entryDate', 'names', 'judge', 'decision', 'accused',
       'articles', 'link_text', 'preamble', 'description', 'sentence',
       'killer_count', 'gender_accused', 'prior_convictions', 'prison_term',
       'alcohol', 'precrime_argument', 'motive', 'has_woman_victim',
       'has_man_victim', 'location', 'method'],
      dtype='object')

In [729]:
df_labeled_all.columns

Index(['id', 'region', 'entryDate', 'names', 'judge', 'decision', 'accused',
       'articles', 'link_text', 'preamble', 'description', 'sentence',
       'killer_count', 'gender_accused', 'prior_convictions', 'alcohol',
       'precrime_argument', 'has_woman_victim', 'has_man_victim', 'method',
       'motive', 'location', 'prison_term'],
      dtype='object')

In [756]:
df_3k_reordered = df_3k[df_labeled_all.columns]
df_combined = pd.concat([df_labeled_all, df_3k_reordered], ignore_index=True)

In [757]:
df_combined

,id,region,entryDate,names,judge,decision,accused,articles,link_text,preamble,...,gender_accused,prior_convictions,alcohol,precrime_argument,has_woman_victim,has_man_victim,method,motive,location,prison_term
0,92093,55,1998-07-14,"Яковлев Владимир Николаевич - ст. 116 ч.1, ст....",Толстых Артём Александрович,Вынесен ПРИГОВОР,Яковлев Владимир Николаевич,"ст. 116 ч.1, ст. 105 ч.1",http://pervomaycourt--oms.sudrf.ru/modules.php...,Дело № 1-2/2020\n55RS0005-01-1998-000001-11\nП...,...,мужчина,нет,да,была,0,1.0,тяжелые предметы,личная неприязнь,"рабочая зона, уличное пространство",9.00
1,25775,79,1999-01-15,Искяндаров Джамбар Мехти Оглы - ст.105 ч.1 УК РФ,Сон А.И.,Вынесен ПРИГОВОР,Искяндаров Джамбар Мехти Оглы,ст.105 ч.1,http://obluchensky--brb.sudrf.ru/modules.php?n...,Решение вступило в законную силу: 11.11.2016 г...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,"общественное место, уличное пространство",7.986857
2,75488,42,2000-08-02,"Кузнецов Вячеслав Иванович - ст.162 ч.2 п.п.а,...",Акимова Юна Юрьевна,Вынесен ПРИГОВОР,Кузнецов Вячеслав Иванович,"ст.162 ч.2 п.п.а,в,г, ст. 30 ч.3, ст.105 ч.2 п...",http://oblsud--kmr.sudrf.ru/modules.php?name=s...,Дело №2-1/2019\n244527\nУИД 42OS0000-01-2000-0...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие","корысть, личная неприязнь",жилое помещение,13.00
3,126184,3,2005-07-12,Скворцова Ольга Анатольевна - ст.33 ч.3-ст.105...,Цыренов Тимур Будажапович,Вынесен ПРИГОВОР,Скворцова Ольга Анатольевна,"ст.33 ч.3, ст.105 ч.2 п.п.ж,з",http://vs--bur.sudrf.ru/modules.php?name=sud_d...,ПРИГОВОР\nИменем Российской Федерации\nг. Улан...,...,женщина,нет,нет,была,0,1.0,огнестрельное оружие,"корысть, личная неприязнь",уличное пространство,13.00
4,102316,38,2009-03-11,Голованов Виктор Павлович - ст.105 ч.2 п.а УК РФ,Ляховецкий Олег Павлович,Вынесен ПРИГОВОР,Голованов Виктор Павлович,ст.105 ч.2 п.а,http://oblsud--irk.sudrf.ru/modules.php?name=s...,П Р И Г О В О Р\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n...,...,мужчина,нет,да,была,1,0.0,удушение,личная неприязнь,жилое помещение,8.311355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37750,6580,26,2016-06-23,Панченко Юрий Васильевич - ст.105 ч.1 УК РФ,Кривцанова Галина Петровна,Вынесен ПРИГОВОР,Панченко Юрий Васильевич,ст.105 ч.1,http://blagodarnensky--stv.sudrf.ru/modules.ph...,Дело №1-99/2016\nПРИГОВОР\nИменем Российской Ф...,...,мужчина,нет,да,была,0,1.0,холодное оружие,личная неприязнь,жилое помещение,9.00
37751,62712,52,2018-03-23,Прутков Кирилл Игоревич - ст.105 ч.1 УК РФ,Егоров Андрей Владимирович,Вынесен ПРИГОВОР,Прутков Кирилл Игоревич,ст.105 ч.1,http://prioksky--nnov.sudrf.ru/modules.php?nam...,Решение по уголовному делу\nИнформация по делу...,...,мужчина,нет,да,была,1,0.0,холодное оружие,"личная неприязнь, ревность",жилое помещение,9.00
37752,54534,16,2018-10-12,"Аверкин Алексей Ринатович - ст.115 ч.2 п.в, ст...",Семенов Олег Владимирович,Вынесен ПРИГОВОР,Аверкин Алексей Ринатович,"ст.115 ч.2 п.в, ст. 30 ч.3, ст.105 ч.1",http://zelenodolsky--tat.sudrf.ru/modules.php?...,Дело №1-399/2018\nПРИГОВОР\nименем Российской ...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие",ревность,жилое помещение,3.83
37753,47517,66,2017-09-22,"Утюмов Вячеслав Гумарович - ст.105 ч.2 п.п.а,к...",Ладин Александр Максимович,Вынесен ПРИГОВОР,Утюмов Вячеслав Гумарович,"ст.105 ч.2 п.п.а,к",http://oblsud--svd.sudrf.ru/modules.php?name=s...,Дело № 2-40/2017\nИменем Российской Федерации\...,...,мужчина,нет,да,была,1,1.0,"физическое воздействие, холодное оружие",личная неприязнь,жилое помещение,21.00
37754,61493,49,2018-06-20,Трофимченко Евгений Михайлович - ст.105 ч.1 УК РФ,Сидорова Марина Александровна,Вынесен ПРИГОВОР,Трофимченко Евгений Михайлович,ст.105 ч.1,http://magadansky--mag.sudrf.ru/modules.php?na...,Дело № 1-298/2018 (11802440002000038)\nП Р И Г...,...,мужчина,да,да,была,1,1.0,"физическое воздействие, холодное оружие",личная неприязнь,уличное пространство,10.00

In [758]:
df_combined['id'].nunique()

37755

In [759]:
df_combined.to_csv("df_combined.csv", index=False, encoding='utf-8')