In [2]:
import pandas as pd

In [23]:
!pip install -U "g4f[all]"

Collecting g4f[all]
  Downloading g4f-0.5.0.4-py3-none-any.whl.metadata (54 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (2.32.3)
Requirement already satisfied: aiohttp in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (3.9.1)
Collecting brotli (from g4f[all])
  Downloading Brotli-1.1.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (5.5 kB)
Collecting pycryptodome (from g4f[all])
  Downloading pycryptodome-3.22.0-cp37-abi3-macosx_10_9_universal2.whl.metadata (3.4 kB)
Requirement already satisfied: nest_asyncio in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (1.6.0)
Collecting curl_cffi>=0.6.2 (from g4f[all])
  Downloading curl_cffi-0.10.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (12 kB)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (2025.1.31)
Collecting browser_cookie3 (from g4f[all])
  Downloading browser_cookie3-0.20.1-py3-none-any.whl.metadata (713 bytes)
Collecting duckduckgo-search>=5.0 (from g4f[all])
  Downloading duckduckgo_search-8.0.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (4.12.3)
Requirement already satisfied: platformdirs in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (4.3.6)
Collecting aiohttp_socks (from g4f[all])
  Downloading aiohttp_socks-0.10.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (10.2.0)
Collecting cairosvg (from g4f[all])
  Downloading CairoSVG-2.7.1-py3-none-any.whl.metadata (2.7 kB)
Collecting werkzeug (from g4f[all])
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting flask (from g4f[all])
  Downloading flask-3.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting fastapi (from g4f[all])
  Downloading fastapi-0.115.12-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn (from g4f[all])
  Downloading uvicorn-0.34.1-py3-none-any.whl.metadata (6.5 kB)
Collecting nodriver (from g4f[all])
  Downloading nodriver-0.45.1-py3-none-any.whl.metadata (48 kB)
Collecting python-multipart (from g4f[all])
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Collecting pywebview (from g4f[all])
  Downloading pywebview-5.4-py3-none-any.whl.metadata (4.5 kB)
Collecting plyer (from g4f[all])
  Downloading plyer-2.1.0-py2.py3-none-any.whl.metadata (61 kB)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from g4f[all]) (69.0.2)
Collecting pypdf2 (from g4f[all])
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Collecting python-docx (from g4f[all])
  Downloading python_docx-1.1.2-py3-none-any.whl.metadata (2.0 kB)
Collecting odfpy (from g4f[all])
  Downloading odfpy-1.4.1.tar.gz (717 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.0/717.0 kB 22.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ebooklib (from g4f[all])
  Downloading EbookLib-0.18.tar.gz (115 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting openpyxl (from g4f[all])
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: cffi>=1.12.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from curl_cffi>=0.6.2->g4f[all]) (1.16.0)
Requirement already satisfied: click>=8.1.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from duckduckgo-search>=5.0->g4f[all]) (8.1.8)
Collecting primp>=0.14.0 (from duckduckgo-search>=5.0->g4f[all])
  Downloading primp-0.14.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting lxml>=5.3.0 (from duckduckgo-search>=5.0->g4f[all])
  Downloading lxml-5.3.2-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.6 kB)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp->g4f[all]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp->g4f[all]) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp->g4f[all]) (1.9.3)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp->g4f[all]) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from aiohttp->g4f[all]) (1.3.1)
Collecting aiohttp (from g4f[all])
  Downloading aiohttp-3.11.16-cp312-cp312-macosx_11_0_arm64.whl.metadata (7.7 kB)
Collecting python-socks<3.0.0,>=2.4.3 (from python-socks[asyncio]<3.0.0,>=2.4.3->aiohttp_socks->g4f[all])
  Downloading python_socks-2.7.1-py3-none-any.whl.metadata (8.0 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->g4f[all])
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting propcache>=0.2.0 (from aiohttp->g4f[all])
  Downloading propcache-0.3.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (10 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->g4f[all])
  Downloading yarl-1.19.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (71 kB)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from beautifulsoup4->g4f[all]) (2.6)
Collecting lz4 (from browser_cookie3->g4f[all])
  Downloading lz4-4.4.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting pycryptodomex (from browser_cookie3->g4f[all])
  Downloading pycryptodomex-3.22.0-cp37-abi3-macosx_10_9_universal2.whl.metadata (3.4 kB)
Collecting cairocffi (from cairosvg->g4f[all])
  Downloading cairocffi-1.7.1-py3-none-any.whl.metadata (3.3 kB)
Collecting cssselect2 (from cairosvg->g4f[all])
  Downloading cssselect2-0.8.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cairosvg->g4f[all]) (0.7.1)
Requirement already satisfied: tinycss2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cairosvg->g4f[all]) (1.4.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ebooklib->g4f[all]) (1.17.0)
Collecting starlette<0.47.0,>=0.40.0 (from fastapi->g4f[all])
  Downloading starlette-0.46.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from fastapi->g4f[all]) (2.5.2)
Requirement already satisfied: typing-extensions>=4.8.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from fastapi->g4f[all]) (4.13.1)
Requirement already satisfied: Jinja2>=3.1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from flask->g4f[all]) (3.1.4)
Collecting itsdangerous>=2.2 (from flask->g4f[all])
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting blinker>=1.9 (from flask->g4f[all])
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from werkzeug->g4f[all]) (3.0.2)
Collecting mss (from nodriver->g4f[all])
  Downloading mss-10.0.0-py3-none-any.whl.metadata (6.1 kB)
Collecting websockets>=14 (from nodriver->g4f[all])
  Downloading websockets-15.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting deprecated (from nodriver->g4f[all])
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting et-xmlfile (from openpyxl->g4f[all])
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting pyobjc-core (from pywebview->g4f[all])
  Downloading pyobjc_core-11.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (2.5 kB)
Collecting pyobjc-framework-Cocoa (from pywebview->g4f[all])
  Downloading pyobjc_framework_Cocoa-11.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (2.3 kB)
Collecting pyobjc-framework-Quartz (from pywebview->g4f[all])
  Downloading pyobjc_framework_Quartz-11.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (3.3 kB)
Collecting pyobjc-framework-WebKit (from pywebview->g4f[all])
  Downloading pyobjc_framework_WebKit-11.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (2.4 kB)
Collecting pyobjc-framework-security (from pywebview->g4f[all])
  Downloading pyobjc_framework_Security-11.0-cp312-cp312-macosx_10_13_universal2.whl.metadata (2.2 kB)
Collecting proxy_tools (from pywebview->g4f[all])
  Downloading proxy_tools-0.1.0.tar.gz (3.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bottle (from pywebview->g4f[all])
  Downloading bottle-0.13.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->g4f[all]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->g4f[all]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests->g4f[all]) (2.3.0)
Requirement already satisfied: h11>=0.8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from uvicorn->g4f[all]) (0.14.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cffi>=1.12.0->curl_cffi>=0.6.2->g4f[all]) (2.21)
Requirement already satisfied: annotated-types>=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->g4f[all]) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi->g4f[all]) (2.14.5)
Requirement already satisfied: anyio<5,>=3.6.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from starlette<0.47.0,>=0.40.0->fastapi->g4f[all]) (4.6.2.post1)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cssselect2->cairosvg->g4f[all]) (0.5.1)
Collecting wrapt<2,>=1.10 (from deprecated->nodriver->g4f[all])
  Downloading wrapt-1.17.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.4 kB)
Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi->g4f[all]) (1.3.0)
Downloading curl_cffi-0.10.0-cp39-abi3-macosx_11_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 45.5 MB/s eta 0:00:00
Downloading duckduckgo_search-8.0.0-py3-none-any.whl (18 kB)
Downloading aiohttp_socks-0.10.1-py3-none-any.whl (10 kB)
Downloading aiohttp-3.11.16-cp312-cp312-macosx_11_0_arm64.whl (456 kB)
Downloading Brotli-1.1.0-cp312-cp312-macosx_10_13_universal2.whl (815 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 815.7/815.7 kB 36.0 MB/s eta 0:00:00
Downloading browser_cookie3-0.20.1-py3-none-any.whl (17 kB)
Downloading CairoSVG-2.7.1-py3-none-any.whl (43 kB)
Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)
Downloading flask-3.1.0-py3-none-any.whl (102 kB)
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
Downloading g4f-0.5.0.4-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 40.8 MB/s eta 0:00:00
Downloading nodriver-0.45.1-py3-none-any.whl (357 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading plyer-2.1.0-py2.py3-none-any.whl (142 kB)
Downloading pycryptodome-3.22.0-cp37-abi3-macosx_10_9_universal2.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 47.8 MB/s eta 0:00:00
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
Downloading python_docx-1.1.2-py3-none-any.whl (244 kB)
Downloading python_multipart-0.0.20-py3-none-any.whl (24 kB)
Downloading pywebview-5.4-py3-none-any.whl (475 kB)
Downloading uvicorn-0.34.1-py3-none-any.whl (62 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading lxml-5.3.2-cp312-cp312-macosx_10_9_universal2.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 30.8 MB/s eta 0:00:00a 0:00:01
Downloading primp-0.14.0-cp38-abi3-macosx_11_0_arm64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 44.9 MB/s eta 0:00:00
Downloading propcache-0.3.1-cp312-cp312-macosx_11_0_arm64.whl (46 kB)
Downloading python_socks-2.7.1-py3-none-any.whl (54 kB)
Downloading starlette-0.46.2-py3-none-any.whl (72 kB)
Downloading websockets-15.0.1-cp312-cp312-macosx_11_0_arm64.whl (173 kB)
Downloading yarl-1.19.0-cp312-cp312-macosx_11_0_arm64.whl (95 kB)
Downloading bottle-0.13.2-py2.py3-none-any.whl (104 kB)
Downloading cairocffi-1.7.1-py3-none-any.whl (75 kB)
Downloading cssselect2-0.8.0-py3-none-any.whl (15 kB)
Downloading Deprecated-1.2.18-py2.py3-none-any.whl (10.0 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading lz4-4.4.4-cp312-cp312-macosx_11_0_arm64.whl (189 kB)
Downloading mss-10.0.0-py3-none-any.whl (24 kB)
Downloading pycryptodomex-3.22.0-cp37-abi3-macosx_10_9_universal2.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 45.2 MB/s eta 0:00:00
Downloading pyobjc_core-11.0-cp312-cp312-macosx_10_13_universal2.whl (739 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.8/739.8 kB 28.5 MB/s eta 0:00:00
Downloading pyobjc_framework_Cocoa-11.0-cp312-cp312-macosx_10_13_universal2.whl (385 kB)
Downloading pyobjc_framework_Quartz-11.0-cp312-cp312-macosx_10_13_universal2.whl (212 kB)
Downloading pyobjc_framework_Security-11.0-cp312-cp312-macosx_10_13_universal2.whl (41 kB)
Downloading pyobjc_framework_WebKit-11.0-cp312-cp312-macosx_10_13_universal2.whl (44 kB)
Downloading wrapt-1.17.2-cp312-cp312-macosx_11_0_arm64.whl (38 kB)
Building wheels for collected packages: ebooklib, odfpy, proxy_tools
  Building wheel for ebooklib (pyproject.toml) ... done
  Created wheel for ebooklib: filename=ebooklib-0.18-py3-none-any.whl size=38881 sha256=70c165904ab986b65e689084b7b4a89d04942ef6c72de4853bd31508b660357b
  Stored in directory: /Users/vera/Library/Caches/pip/wheels/c9/95/88/28e51b74669d4e3df4e72e2a031ea6c211a93a5008284d6c67
  Building wheel for odfpy (pyproject.toml) ... done
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=137363 sha256=cf2356c570903faa1f2c4df02a0b2f94ae284129a6554e33835d4b5b9cf53257
  Stored in directory: /Users/vera/Library/Caches/pip/wheels/36/5d/63/8243a7ee78fff0f944d638fd0e66d7278888f5e2285d7346b6
  Building wheel for proxy_tools (pyproject.toml) ... done
  Created wheel for proxy_tools: filename=proxy_tools-0.1.0-py3-none-any.whl size=2936 sha256=edecac45d0202993b074efc014dc4d2b2be78451f73d74a212732f14bb5b4b98
  Stored in directory: /Users/vera/Library/Caches/pip/wheels/07/37/12/f3390260c831aa68c3835d6ec2e10d8da094b5fc0ac32feb14
Successfully built ebooklib odfpy proxy_tools
Installing collected packages: proxy_tools, plyer, brotli, bottle, wrapt, werkzeug, websockets, uvicorn, python-socks, python-multipart, pypdf2, pyobjc-core, pycryptodomex, pycryptodome, propcache, primp, odfpy, mss, lz4, lxml, itsdangerous, et-xmlfile, blinker, aiohappyeyeballs, yarl, starlette, python-docx, pyobjc-framework-Cocoa, openpyxl, flask, ebooklib, duckduckgo-search, deprecated, curl_cffi, cssselect2, cairocffi, browser_cookie3, pyobjc-framework-WebKit, pyobjc-framework-security, pyobjc-framework-Quartz, nodriver, fastapi, cairosvg, aiohttp, pywebview, g4f, aiohttp_socks
  Attempting uninstall: lxml
    Found existing installation: lxml 4.9.3
    Uninstalling lxml-4.9.3:
      Successfully uninstalled lxml-4.9.3
  Attempting uninstall: yarl
    Found existing installation: yarl 1.9.3
    Uninstalling yarl-1.9.3:
      Successfully uninstalled yarl-1.9.3
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.9.1
    Uninstalling aiohttp-3.9.1:
      Successfully uninstalled aiohttp-3.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiogram 3.2.0 requires aiohttp~=3.9.0, but you have aiohttp 3.11.16 which is incompatible.
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.11.16 aiohttp_socks-0.10.1 blinker-1.9.0 bottle-0.13.2 brotli-1.1.0 browser_cookie3-0.20.1 cairocffi-1.7.1 cairosvg-2.7.1 cssselect2-0.8.0 curl_cffi-0.10.0 deprecated-1.2.18 duckduckgo-search-8.0.0 ebooklib-0.18 et-xmlfile-2.0.0 fastapi-0.115.12 flask-3.1.0 g4f-0.5.0.4 itsdangerous-2.2.0 lxml-5.3.2 lz4-4.4.4 mss-10.0.0 nodriver-0.45.1 odfpy-1.4.1 openpyxl-3.1.5 plyer-2.1.0 primp-0.14.0 propcache-0.3.1 proxy_tools-0.1.0 pycryptodome-3.22.0 pycryptodomex-3.22.0 pyobjc-core-11.0 pyobjc-framework-Cocoa-11.0 pyobjc-framework-Quartz-11.0 pyobjc-framework-WebKit-11.0 pyobjc-framework-security-11.0 pypdf2-3.0.1 python-docx-1.1.2 python-multipart-0.0.20 python-socks-2.7.1 pywebview-5.4 starlette-0.46.2 uvicorn-0.34.1 websockets-15.0.1 werkzeug-3.1.3 wrapt-1.17.2 yarl-1.19.0

In [24]:
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{"role": "user", "content": "Hello"}],
    web_search=False
)
print(response.choices[0].message.content)

Hey there! How’s it going?

In [27]:
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[{"role": "user", "content": "Hello"}],
    web_search=False
)
print(response.choices[0].message.content)

You have reached your request limit for the hour

In [28]:
from g4f.client import Client

client = Client()
response = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Hello"}],
    web_search=False
)
print(response.choices[0].message.content)

Hi there! How’s your day going so far? Anything on your mind you'd like to dive into?

In [29]:
models = client.models
models

In [31]:
def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)  # убрать лишние пробелы
    text = text.strip()
    return text

import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re

client = Client()

df_eval = merged_df.iloc[0:].copy() 

tqdm.pandas()


def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить, в какое время суток (из четырёх вариантов) произошло преступление.

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь

Если в тексте нет чёткого указания на время, выбери наиболее вероятное.
Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта.

Ответ должен состоять **только** из одного или двух слов из списка:
**утро, день, вечер, ночь**. Без пояснений и комментариев.

Примеры:
Текст: Преступление произошло в 5 утра, на автобусной остановке.
Ответ: утро
Текст: В 15:00 обвиняемый выстрелил в жертву
Ответ: день"

Описание:
{text}

Ответ:""".strip()


def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False

            )
            reply = response.choices[0].message.content.strip().lower()
            # return normalize_prediction(reply)
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"


# df_eval["clean_text"] = df_eval["text"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["sum_text"].progress_apply(classify_with_gpt4)

y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]


accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)


print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [10:39:07<00:00, 383.48s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.4000
Precision: 0.3939
Recall:    0.4000
F1-score:  0.3627

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно                  день
1               ночь                  ночь
2         неизвестно                 вечер
3              вечер                 вечер
4               утро                  день
..               ...                   ...
95             вечер                 вечер
96             вечер                 вечер
97  ['утро', 'день']            утро, день
98              утро                  ночь
99              утро                  утро

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [109]:
file_path_fin = 'df_with_marking_final.csv'
dfff = pd.read_csv(file_path_fin, on_bad_lines='warn')
dfff.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,preamble,description,sentence,victim_count,killer_count,extracted_prison_term,prison_term_re,num_victims,has_woman_victim,has_man_victim
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...,1,1,NaN,6.0,1,0,1
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...,1,1,NaN,8.0,1,0,1
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...,2,2,NaN,2017.0,2,1,0
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...,1,1,NaN,3.0,1,0,1
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...,1,1,9.25,9.0,1,0,1

In [ ]:
file_path = 'df_with_marking_final (1).csv'
df = pd.read_csv(file_path, on_bad_lines='warn')
df.head()

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = Client()

df_eval = df.iloc[0:].copy()

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — определить для каждого упомянутого обвиняемого:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее.

Правила:
- Для пола: если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она"), укажи "мужчина" или "женщина". Если информации нет, укажи "неизвестно".
- Для судимостей: если есть явное указание (например, "ранее судим", "имеет судимость"), укажи "да". Если указано отсутствие (например, "не судим"), укажи "нет". Если информации нет, укажи "нет".
- Формат ответа:
  - Если обвиняемый один, возвращай строки: "пол: <мужчина/женщина/неизвестно>, судимости: <да/нет>".
  - Если обвиняемых несколько, возвращай списки: "пол: [<мужчина/женщина/неизвестно>, ...], судимости: [<да/нет>, ...]".
- Значения для каждого обвиняемого указаны в порядке их упоминания в тексте.
- Убедись, что порядок значений строго соответствует порядку упоминания обвиняемых.
- **Возвращай только указанный формат ответа. Не добавляй объяснения, комментарии или дополнительный текст.**

Примеры:
Текст: Обвиняемый Иванов А.А., ранее судимый, совершил кражу.
Ответ: пол: мужчина, судимости: да
Текст: Обвиняемая Петрова Е.В., не судимая, совершила мошенничество.
Ответ: пол: женщина, судимости: нет
Текст: Подсудимые Скородумов С.Ю. и Скворцова Е.В. совершили убийство, ранее не судимые.
Ответ: пол: [мужчина, женщина], судимости: [нет, нет]
Текст: Обвиняемый совершил преступление в 15:00.
Ответ: пол: неизвестно, судимости: нет
Текст: Иванов А.А. и Петрова Е.В., ранее судимые, совершили кражу.
Ответ: пол: [мужчина, женщина], судимости: [да, да]
Текст: гражданина России, ранее не судимого
Ответ: пол: мужчина, судимости: нет
Текст: уроженца, неработающего, судимого
Ответ: пол: мужчина, судимости: да
Текст: обвиняемой в совершении преступления
Ответ: пол: женщина, судимости: нет

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return {"gender": "неизвестно", "prior_convictions": "нет"}

def normalize_prediction(text):
    gender = "неизвестно"
    prior_convictions = "нет"
    
    try:
        pattern = r'пол:\s*(\[.*?\]|\w+)\s*,\s*судимости:\s*(\[.*?\]|\w+)'
        match = re.search(pattern, text.strip())
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        gender_part = match.group(1).strip()
        convictions_part = match.group(2).strip()
        
        gender_match = re.match(r'\[(.*?)\]', gender_part)
        convictions_match = re.match(r'\[(.*?)\]', convictions_part)
        
        if gender_match:
            gender_values = [v.strip() for v in gender_match.group(1).split(",") if v.strip()]
            gender = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
        else:
            gender = gender_part if gender_part in ["мужчина", "женщина", "неизвестно"] else "неизвестно"
            
        if convictions_match:
            convictions_values = [v.strip() for v in convictions_match.group(1).split(",") if v.strip()]
            prior_convictions = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
        else:
            prior_convictions = convictions_part if convictions_part in ["да", "нет"] else "нет"
            
    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, match: {match.groups() if match else None}, defaulting to 'неизвестно' for gender, 'нет' for convictions")
    
    return {"gender": gender, "prior_convictions": prior_convictions}

df_eval["predictions"] = df_eval["preamble"].progress_apply(classify_with_gpt4)

def format_prediction(row, key):
    prediction = row["predictions"][key]
    killer_count = row["killer_count"] if pd.notnull(row["killer_count"]) else 1
    if killer_count >= 2 and isinstance(prediction, list):
        return prediction
    elif killer_count == 1 and isinstance(prediction, list) and len(prediction) == 1:
        return prediction[0]
    return prediction

df_eval["predicted_gender"] = df_eval.apply(lambda x: format_prediction(x, "gender"), axis=1)
df_eval["predicted_prior_convictions"] = df_eval.apply(lambda x: format_prediction(x, "prior_convictions"), axis=1)

# def normalize_true_label(label):
#     if isinstance(label, str) and ", " in label:
#         return [x.strip() for x in label.split(", ")]
#     elif isinstance(label, str):
#         return label
#     elif isinstance(label, list):
#         return label
#     return "неизвестно" if "gender" in str(label) else "нет"

# df_eval["true_gender"] = df_eval["gender_accused"].apply(normalize_true_label)
# df_eval["true_prior_convictions"] = df_eval["prior_convictions"].apply(normalize_true_label)

 38%|███▊      | 38/100 [33:49<44:57, 43.50s/it]

Parsing error in response: , error: Response does not match expected format: , match: None, defaulting to 'неизвестно' for gender, 'нет' for convictions

100%|██████████| 100/100 [1:34:45<00:00, 56.86s/it]

In [112]:
y_true_gender = df_eval["gender_accused"]
y_pred_gender = df_eval["predicted_gender"].astype(str)
y_true_convictions = df_eval["prior_convictions"]
y_pred_convictions = df_eval["predicted_prior_convictions"].astype(str)

gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_accused", "predicted_gender", "prior_convictions", "predicted_prior_convictions"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9600
Precision: 0.9806
Recall:    0.9600
F1-score:  0.9699

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8100
Precision: 0.8425
Recall:    0.8100
F1-score:  0.8228

Пример предсказаний:
           gender_accused    predicted_gender prior_convictions  \
0                 мужчина             мужчина               нет
1                 мужчина             мужчина               нет
2  ['мужчина', 'мужчина']  [мужчина, мужчина]    ['нет', 'нет']
3                 мужчина             мужчина               нет
4                 мужчина             мужчина               нет

  predicted_prior_convictions
0                         нет
1                         нет
2                  [нет, нет]
3                         нет
4                         нет

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = Client()

df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — определить:
1. Время суток, когда произошло преступление (time_of_day).
2. Место, где произошло преступление (location).
3. Способ совершения преступления (method).
4. Была ли ссора между преступником и жертвой перед преступлением (precrime_argument).

Правила:
- **Время суток (time_of_day)**:- **Время суток (time_of_day)**:
  - 04:00–11:59 → утро
  - 12:00–15:59 → день
  - 16:00–22:59 → вечер
  - 23:00–03:59 → ночь
  - Если нет точного времени, но указан промежуток (например, ночь или утро), возвращай список из двух значений (например, ['ночь', 'утро']). Если время неизвестно, укажи "неизвестно".
- **Место (location)**:
  - Укажи конкретное место (например, "квартира", "улица", "подъезд", "лес", "автомобиль"). Если место не указано, возвращай "неизвестно".
- **Способ (method)**:
  - Укажи способ убийства или покушения (например, "нож", "огнестрел", "удушение", "избиение", "отравление", "утопление", "поджог", "автотравма"). Если способ неизвестен, укажи "неизвестно".
  - Если жертв несколько и способы разные, возвращай список строк (например, ['нож', 'удушение']). Если способ одинаковый, возвращай строку (например, "огнестрел"). Если одну жертву убивали несколькими способами, перечисли их в списке (например, ['нож', 'избиение']).
- **Ссора (precrime_argument)**:
  - Если есть указание на ссору, укажи "была". Если указано отсутствие ссоры, укажи "не была". Если информации нет, укажи "неизвестно".
- Формат ответа:
  - Возвращай: "время: <значение>, место: <значение>, способ: <значение>, ссора: <значение>".
  - Для множественных значений (время или способ) используй списки: например, "время: ['ночь', 'утро']" или "способ: ['нож', 'удушение']".
- **Возвращай только указанный формат ответа!!! Не добавляй объяснения, комментарии или дополнительный текст. все существительные должны быть в Именительном падеже - то есть писать НЕ 'ножом', а просто 'нож', НЕ 'выстрел из травматического пистолета', а просто 'пистолет'**

Примеры:
Текст: В 15:00 обвиняемый убил жертву ножом в квартире после ссоры.
Ответ: время: день, место: квартира, способ: нож, ссора: была
Текст: Ночью в лесу жертва была задушена, ссоры не было.
Ответ: время: ночь, место: лес, способ: удушение, ссора: нет
Текст: Преступление произошло в подъезде, жертвы убиты огнестрелом и ножом.
Ответ: время: неизвестно, место: подъезд, способ: ['огнестрел', 'нож'], ссора: неизвестно
Текст: Вечером на улице обвиняемый избил жертву, ссоры не упомянуты.
Ответ: время: вечер, место: улица, способ: избиение, ссора: неизвестно
Текст: Жертва была отравлена и утоплена в автомобиле в 2:00.
Ответ: время: ночь, место: автомобиль, способ: ['отравление', 'утопление'], ссора: неизвестно
Текст: Преступление произошло около полуночи или утром в заброшенном здании, способ неизвестен.
Ответ: время: ['ночь', 'утро'], место: заброшенное здание, способ: неизвестно, ссора: неизвестно

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "нет"
    }
    
    try:
        pattern = r'время:\s*(\[.*?\]|\w+)\s*,\s*место:\s*([^\,]+)\s*,\s*способ:\s*(\[.*?\]|\w+)\s*,\s*ссора:\s*(\w+)'
        match = re.search(pattern, text.strip())
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        time_part = match.group(1).strip()
        location_part = match.group(2).strip()
        method_part = match.group(3).strip()
        argument_part = match.group(4).strip()
        
        time_match = re.match(r'\[(.*?)\]', time_part)
        if time_match:
            time_values = [v.strip() for v in time_match.group(1).split(",") if v.strip()]
            result["time_of_day"] = [v for v in time_values if v in ["утро", "день", "вечер", "ночь"]]
        else:
            result["time_of_day"] = time_part if time_part in ["утро", "день", "вечер", "ночь", "неизвестно"] else "неизвестно"
        
        valid_locations = ["квартира", "улица", "подъезд", "лес", "заброшенное здание", "автомобиль", "неизвестно"]
        result["location"] = location_part if location_part in valid_locations or location_part != "" else "неизвестно"
        
        method_match = re.match(r'\[(.*?)\]', method_part)
        valid_methods = ["нож", "огнестрел", "удушение", "отравление", "избиение", "утопление", "поджог", "автотравма", "неизвестно"]
        if method_match:
            method_values = [v.strip() for v in method_match.group(1).split(",") if v.strip()]
            result["method"] = [v for v in method_values if v in valid_methods]
        else:
            result["method"] = method_part if method_part in valid_methods else "неизвестно"
        
        result["precrime_argument"] = argument_part if argument_part in ["была", "не была", "неизвестно"] else "неизвестно"

    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, match: {match.groups() if match else None}, defaulting to 'неизвестно' for all fields")
    
    return result

# df_eval["clean_description"] = df_eval["description"].apply(clean_text)
# df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)
df_eval["predictions"] = df_eval["description"].progress_apply(classify_with_gpt4)

df_eval["predicted_time_of_day"] = df_eval["predictions"].apply(lambda x: x["time_of_day"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: x["precrime_argument"])

# def normalize_true_label(label, field):
#     if isinstance(label, str) and ", " in label:
#         return [x.strip() for x in label.split(", ")]
#     elif isinstance(label, str):
#         return label
#     elif isinstance(label, list):
#         return label
#     return "неизвестно"

# df_eval["true_time_of_day"] = df_eval["time_of_day"].apply(lambda x: normalize_true_label(x, "time_of_day"))
# df_eval["true_location"] = df_eval["location"].apply(lambda x: normalize_true_label(x, "location"))
# df_eval["true_method"] = df_eval["method"].apply(lambda x: normalize_true_label(x, "method"))
# df_eval["true_precrime_argument"] = df_eval["precrime_argument"].apply(lambda x: normalize_true_label(x, "precrime_argument"))

 37%|███▋      | 37/100 [32:11<58:18, 55.53s/it]

Parsing error in response: время: 17:00, место: возле магазина «кит», способ: избиение, ссора: неизвестно, error: Response does not match expected format: время: 17:00, место: возле магазина «кит», способ: избиение, ссора: неизвестно, match: None, defaulting to 'неизвестно' for all fields

 68%|██████▊   | 68/100 [1:05:29<43:53, 82.31s/it]

Parsing error in response: время: 13:13-14:05, место: дом, способ: нож, ссора: была, error: Response does not match expected format: время: 13:13-14:05, место: дом, способ: нож, ссора: была, match: None, defaulting to 'неизвестно' for all fields

100%|██████████| 100/100 [1:26:03<00:00, 51.63s/it]

In [ ]:
def calculate_metrics(y_true, y_pred, label_name):
    y_true_flat = []
    y_pred_flat = []
    
    for t, p in zip(y_true, y_pred):
        if isinstance(t, list) and isinstance(p, list):
            y_true_flat.extend(t)
            y_pred_flat.extend(p)
        else:
            y_true_flat.append(str(t))
            y_pred_flat.append(str(p))
    
    accuracy = accuracy_score(y_true_flat, y_pred_flat)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_flat, y_pred_flat, average="weighted", zero_division=0
    )
    
    print(f"\nОЦЕНКА GPT-4o-mini ({label_name}):")
    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")

try:
    calculate_metrics(df_eval["time_of_day"], df_eval["predicted_time_of_day"], "Время суток")
    calculate_metrics(df_eval["location"], df_eval["predicted_location"], "Место")
    calculate_metrics(df_eval["method"], df_eval["predicted_method"], "Способ")
    calculate_metrics(df_eval["precrime_argument"], df_eval["predicted_precrime_argument"], "Ссора")
except KeyError as e:
    print(f"\nTrue labels missing: {e}. Metrics skipped.")

print("\nПример предсказаний:")
print(df_eval[["preamble", "time_of_day", "predicted_time_of_day", 
               "location", "predicted_location", 
               "method", "predicted_method", 
               "precrime_argument", "predicted_precrime_argument"]].head())

ОЦЕНКА GPT-4o-mini (Время суток):
Accuracy:  0.2300
Precision: 0.5640
Recall:    0.2300
F1-score:  0.3072

ОЦЕНКА GPT-4o-mini (Место):
Accuracy:  0.5000
Precision: 0.7336
Recall:    0.5000
F1-score:  0.5552

ОЦЕНКА GPT-4o-mini (Способ):
Accuracy:  0.4500
Precision: 0.6025
Recall:    0.4500
F1-score:  0.5027

ОЦЕНКА GPT-4o-mini (Ссора):
Accuracy:  0.8400
Precision: 0.8883
Recall:    0.8400
F1-score:  0.8635

Пример предсказаний:
                                            preamble time_of_day  \
0  Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...  неизвестно
1  К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...        ночь
2  ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...  неизвестно
3  Решение по уголовному делу\nИнформация по делу...       вечер
4  ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...        утро

  predicted_time_of_day  location predicted_location                   method  \
0            неизвестно     улица              улица                 избиение
1                    []     улица         неизвестно                    ружье
2            неизвестно  квартира                дом                 удушение
3                    []       дом                дом  травматический пистолет
4                    []     улица                лес                 избиение

  predicted_method precrime_argument predicted_precrime_argument
0               []              была                        была
1        огнестрел              была                        была
2               []               нет                  неизвестно
3               []              была                        была
4               []              была                        была

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = Client()

df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — определить:
1. Время суток, когда произошло преступление (time_of_day).
2. Место, где произошло преступление (location).
3. Способ совершения преступления (method).
4. Была ли ссора между преступником и жертвой перед преступлением (precrime_argument).

Правила:
- **Время суток (time_of_day)**:
  - 04:00–11:59 → утро
  - 12:00–15:59 → день
  - 16:00–22:59 → вечер
  - 23:00–03:59 → ночь
  - Если нет точного времени, но указан промежуток (например, "около полуночи или утром", "00:00–06:00"), возвращай список из двух значений (например, ['ночь', 'утро']). Если время неизвестно, укажи "неизвестно".
  - Возвращай только одно или два слова из списка: утро, день, вечер, ночь.
- **Место (location)**:
  - Укажи конкретное место в именительном падеже (например, "квартира", "улица", "подъезд", "лес", "автомобиль"). Если место не указано, возвращай "неизвестно".
  - Не добавляй уточняющих деталей (например, для "возле магазина «Кит»" пиши "улица").
- **Способ (method)**:
  - Укажи способ убийства или покушения (например, "нож", "огнестрел", "удушение", "избиение", "отравление", "утопление", "поджог", "автотравма"). Если способ неизвестен, укажи "неизвестно".
  - Если жертв несколько и способы разные, возвращай список строк (например, ['нож', 'удушение']). Если способ одинаковый, возвращай строку (например, "огнестрел"). Если одну жертву убивали несколькими способами, перечисли их в списке (например, ['нож', 'избиение']).
- **Ссора (precrime_argument)**:
  - Если есть указание на ссору, укажи "была". Если указано отсутствие ссоры или информации нет, укажи "нет".
- Формат ответа:
  - Возвращай: "время: <значение>, место: <значение>, способ: <значение>, ссора: <значение>".
  - Для множественных значений (время или способ) используй списки: например, "время: ['ночь', 'утро']" или "способ: ['нож', 'удушение']".
- **Возвращай только указанный формат ответа. Не добавляй объяснения, комментарии или дополнительный текст. Все существительные должны быть в именительном падеже (например, "нож", а не "ножом"; "пистолет", а не "выстрел из пистолета").**

Примеры:
Текст: В 15:00 обвиняемый убил жертву ножом в квартире после ссоры.
Ответ: время: день, место: квартира, способ: нож, ссора: была
Текст: Ночью в лесу жертва была задушена, ссоры не было.
Ответ: время: ночь, место: лес, способ: удушение, ссора: нет
Текст: Преступление произошло в подъезде, жертвы убиты огнестрелом и ножом.
Ответ: время: неизвестно, место: подъезд, способ: ['огнестрел', 'нож'], ссора: нет
Текст: Вечером на улице обвиняемый избил жертву, ссоры не упомянуты.
Ответ: время: вечер, место: улица, способ: избиение, ссора: нет
Текст: Жертва была отравлена и утоплена в автомобиле в 2:00.
Ответ: время: ночь, место: автомобиль, способ: ['отравление', 'утопление'], ссора: нет
Текст: Преступление произошло около полуночи или утром в заброшенном здании, способ неизвестен.
Ответ: время: ['ночь', 'утро'], место: заброшенное здание, способ: неизвестно, ссора: нет
Текст: В ходе конфликта с А.В.М.о., возникшего на почве личных неприязненных отношений, Г.Д.Р. умышленно нанес удары по голове.
Ответ: время: неизвестно, место: неизвестно, способ: избиение, ссора: была
Текст: В 00:00–06:00 в подъезде жертва была убита топором.
Ответ: время: ['ночь', 'утро'], место: подъезд, способ: топор, ссора: нет

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "нет"
    }

def normalize_prediction(text):
    result = {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "нет"
    }
    
    try:
        pattern = r'время:\s*(\[.*?\]|\w+)\s*,\s*место:\s*([^\,]+?)\s*,\s*способ:\s*(\[.*?\]|\w+)\s*,\s*ссора:\s*(\w+)'
        match = re.search(pattern, text.strip())
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        time_part = match.group(1).strip()
        location_part = match.group(2).strip()
        method_part = match.group(3).strip()
        argument_part = match.group(4).strip()
        
        time_match = re.match(r'\[(.*?)\]', time_part)
        valid_times = ["утро", "день", "вечер", "ночь"]
        if time_match:
            time_values = [v.strip() for v in time_match.group(1).split(",") if v.strip()]
            filtered_times = [v for v in time_values if v in valid_times]
            result["time_of_day"] = filtered_times if filtered_times else "неизвестно"
        else:
            result["time_of_day"] = time_part if time_part in valid_times + ["неизвестно"] else "неизвестно"
        
        valid_locations = [
            "квартира", "улица", "подъезд", "лес", "заброшенное здание", "автомобиль",
            "дом", "дача", "гараж", "общежитие", "безлюдная местность", "хостел",
            "двор", "лестничная площадка", "чердак", "база отдыха", "неизвестно"
        ]
        result["location"] = location_part if location_part in valid_locations else "неизвестно"
        
        method_match = re.match(r'\[(.*?)\]', method_part)
        valid_methods = [
            "нож", "огнестрел", "удушение", "отравление", "избиение", "утопление",
            "поджог", "автотравма", "ружье", "травматический пистолет", "удар предметом",
            "молоток", "полено", "топор", "клинок", "неизвестно"
        ]
        if method_match:
            method_values = [v.strip() for v in method_match.group(1).split(",") if v.strip()]
            filtered_methods = [v for v in method_values if v in valid_methods]
            result["method"] = filtered_methods if filtered_methods else "неизвестно"
        else:
            result["method"] = method_part if method_part in valid_methods else "неизвестно"
        
        result["precrime_argument"] = argument_part if argument_part in ["была", "нет"] else "нет"
        
    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, match: {match.groups() if match else None}, defaulting to 'неизвестно' for all fields")
    
    return result

df_eval["predictions"] = df_eval["description"].progress_apply(classify_with_gpt4)

df_eval["predicted_time_of_day"] = df_eval["predictions"].apply(lambda x: x["time_of_day"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: x["precrime_argument"])

equivalence_mappings = {
    "location": {
        "дом": ["квартира", "дом"],
        "квартира": ["квартира", "дом"],
        "улица": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "пешеходный мост": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "электрическая подстанция": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "двор": ["улица", "пешеходный мост", "электрическая подстанция", "двор"]
    },
    "method": {
        "огнестрел": ["огнестрел", "ружье", "травматический пистолет"],
        "ружье": ["огнестрел", "ружье", "травматический пистолет"],
        "травматический пистолет": ["огнестрел", "ружье", "травматический пистолет"],
        "избиение": ["избиение", "удар предметом"],
        "удар предметом": ["избиение", "удар предметом"]
    }
}

 11%|█         | 11/100 [11:04<2:40:40, 108.32s/it]

Parsing error in response: время: 15:00–18:09, место: берег озера, способ: нож, ссора: нет, error: Response does not match expected format: время: 15:00–18:09, место: берег озера, способ: нож, ссора: нет, match: None, defaulting to 'неизвестно' for all fields

 43%|████▎     | 43/100 [40:50<32:02, 33.72s/it]

Parsing error in response: время: утро, место: дом, способ: выстрелы из самодельного ружья, ссора: нет, error: Response does not match expected format: время: утро, место: дом, способ: выстрелы из самодельного ружья, ссора: нет, match: None, defaulting to 'неизвестно' for all fields

 65%|██████▌   | 65/100 [1:04:11<20:01, 34.34s/it]

Parsing error in response: время: ['вечер'], место: квартира, способ: молоток и топор, ссора: была, error: Response does not match expected format: время: ['вечер'], место: квартира, способ: молоток и топор, ссора: была, match: None, defaulting to 'неизвестно' for all fields

 73%|███████▎  | 73/100 [1:07:08<11:12, 24.93s/it]

Parsing error in response: время: 18 часов, место: квартира, способ: нож, ссора: была, error: Response does not match expected format: время: 18 часов, место: квартира, способ: нож, ссора: была, match: None, defaulting to 'неизвестно' for all fields

 98%|█████████▊| 98/100 [1:35:18<02:16, 68.23s/it]

Parsing error in response: время: вечер, место: участок местности около электрической подстанции, способ: удар руками, лопатой и иным твердым предметом, ссора: была, error: Response does not match expected format: время: вечер, место: участок местности около электрической подстанции, способ: удар руками, лопатой и иным твердым предметом, ссора: была, match: None, defaulting to 'неизвестно' for all fields

100%|██████████| 100/100 [1:38:51<00:00, 59.32s/it]

Parsing error in response: время: ['утро'], место: пешеходный мост, способ: осколок кирпича, ссора: нет, error: Response does not match expected format: время: ['утро'], место: пешеходный мост, способ: осколок кирпича, ссора: нет, match: None, defaulting to 'неизвестно' for all fields

In [ ]:
def calculate_metrics(y_true, y_pred, label_name, field):
    y_true_flat = []
    y_pred_flat = []
    partial_matches = 0
    total_items = 0
    
    for t, p in zip(y_true, y_pred):
        t = t if isinstance(t, list) else [t]
        p = p if isinstance(p, list) else [p]
        
        # Convert to sets for partial matching
        t_set = set(t)
        p_set = set(p)
        
        # Apply equivalence mappings
        if field in equivalence_mappings:
            t_mapped = set()
            p_mapped = set()
            for item in t_set:
                for key, equivalents in equivalence_mappings[field].items():
                    if item in equivalents:
                        t_mapped.add(key)
                        break
                else:
                    t_mapped.add(item)
            for item in p_set:
                for key, equivalents in equivalence_mappings[field].items():
                    if item in equivalents:
                        p_mapped.add(key)
                        break
                else:
                    p_mapped.add(item)
            t_set = t_mapped
            p_set = p_mapped
        
      
        if t_set == p_set:
            y_true_flat.extend(t)
            y_pred_flat.extend(p)
        else:
           
            if t_set & p_set:  
                partial_matches += len(t_set & p_set)
                for item in t:
                    if item in p_set or any(item in equivalence_mappings[field].get(pred, []) for pred in p_set if field in equivalence_mappings):
                        y_true_flat.append(item)
                        y_pred_flat.append(item)  
                    else:
                        y_true_flat.append(item)
                        y_pred_flat.append("неизвестно")
            else:
                y_true_flat.extend(t)
                y_pred_flat.extend(["неизвестно"] * len(t))
        
        total_items += len(t)
    
    accuracy = accuracy_score(y_true_flat, y_pred_flat)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_flat, y_pred_flat, average="weighted", zero_division=0
    )
    
    partial_accuracy = partial_matches / total_items if total_items > 0 else 0
    
    print(f"\nОЦЕНКА GPT-4o-mini ({label_name}):")
    print(f"Accuracy (exact):  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")
    print(f"Partial Accuracy: {partial_accuracy:.4f}")


try:
    calculate_metrics(df_eval["time_of_day"], df_eval["predicted_time_of_day"], "Время суток", "time_of_day")
    calculate_metrics(df_eval["location"], df_eval["predicted_location"], "Место", "location")
    calculate_metrics(df_eval["method"], df_eval["predicted_method"], "Способ", "method")
    calculate_metrics(df_eval["precrime_argument"], df_eval["predicted_precrime_argument"], "Ссора", "precrime_argument")
except KeyError as e:
    print(f"\nTrue labels missing: {e}. Metrics skipped.")


print("\nПример предсказаний:")
print(df_eval[["description", "time_of_day", "predicted_time_of_day", 
               "location", "predicted_location", 
               "method", "predicted_method", 
               "precrime_argument", "predicted_precrime_argument"]].head())

ОЦЕНКА GPT-4o-mini (Время суток):
Accuracy (exact):  0.2300
Precision: 0.7043
Recall:    0.2300
F1-score:  0.2777
Partial Accuracy: 0.0000

ОЦЕНКА GPT-4o-mini (Место):
Accuracy (exact):  0.4700
Precision: 0.7859
Recall:    0.4700
F1-score:  0.5630
Partial Accuracy: 0.0000

ОЦЕНКА GPT-4o-mini (Способ):
Accuracy (exact):  0.4800
Precision: 0.7667
Recall:    0.4800
F1-score:  0.5684
Partial Accuracy: 0.0000

ОЦЕНКА GPT-4o-mini (Ссора):
Accuracy (exact):  0.9000
Precision: 1.0000
Recall:    0.9000
F1-score:  0.9452
Partial Accuracy: 0.0000

Пример предсказаний:
                                         description time_of_day  \
0  УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...  неизвестно
1  УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...        ночь
2  УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...  неизвестно
3  УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...       вечер
4  У С Т А Н О В И Л:\nНа основании вердикта колл...        утро

  predicted_time_of_day  location predicted_location                   method  \
0            неизвестно     улица              улица                 избиение
1            неизвестно     улица         неизвестно                    ружье
2            неизвестно  квартира                дом                 удушение
3            неизвестно       дом               дача  травматический пистолет
4            неизвестно     улица                лес                 избиение

  predicted_method precrime_argument predicted_precrime_argument
0       неизвестно              была                        была
1        огнестрел              была                        была
2       неизвестно               нет                         нет
3       неизвестно              была                        была
4         избиение              была                        была

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = Client()

df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения времени суток из описания преступления.

Твоя задача — определить, в какое время суток произошло преступление (time_of_day).

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь
- Если время указано точно (например, "в 14:00"), возвращай одно значение (например, "день").
- Если время неоднозначное (например, "около полуночи или утром", "00:00–06:00"), возвращай список из двух значений (например, ['ночь', 'утро']).
- Если время не указано или неясно (например, "в течение дня"), возвращай "неизвестно".
- Используй только значения: утро, день, вечер, ночь, неизвестно.
- Формат ответа:
  - Для одного значения: "время: <значение>"
  - Для двух значений: "время: [<значение1>, <значение2>]"
  - Для неизвестного: "время: неизвестно"
- Возвращай только указанный формат ответа. Не добавляй пояснения, комментарии или дополнительный текст.

Примеры:
Текст: В 15:00 обвиняемый совершил преступление.
Ответ: время: день
Текст: Ночью в лесу произошло убийство.
Ответ: время: ночь
Текст: Преступление произошло около полуночи или утром.
Ответ: время: ['ночь', 'утро']
Текст: В 2:00 жертва была убита.
Ответ: время: ночь
Текст: Утром или в обед обвиняемый совершил кражу.
Ответ: время: ['утро', 'день']
Текст: Вечером в 18:00 произошло нападение.
Ответ: время: вечер
Текст: Преступление произошло в подъезде, время не указано.
Ответ: время: неизвестно
Текст: В 00:00–06:00 произошло ограбление.
Ответ: время: ['ночь', 'утро']
Текст: Рано утром в 5:00 было совершено преступление.
Ответ: время: утро
Текст: В полночь произошло убийство.
Ответ: время: ночь

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return "неизвестно"

def normalize_prediction(text):
    valid_times = ["утро", "день", "вечер", "ночь", "неизвестно"]
    try:
        pattern = r'время:\s*(\[.*?\]|\w+)'
        match = re.search(pattern, text)
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        time_part = match.group(1).strip()
        
        list_match = re.match(r'\[(.*?)\]', time_part)
        if list_match:
            time_values = [v.strip() for v in list_match.group(1).split(",") if v.strip()]
            filtered_times = [v for v in time_values if v in valid_times]
            return filtered_times if filtered_times else "неизвестно"
        else:
            return time_part if time_part in valid_times else "неизвестно"
            
    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, defaulting to 'неизвестно'")
        return "неизвестно"

df_eval["predicted_time_of_day"] = df_eval["description"].progress_apply(classify_with_gpt4)

# def normalize_true_label(label):
#     if isinstance(label, str) and ", " in label:
#         return [x.strip() for x in label.split(", ")]
#     elif isinstance(label, str):
#         return label
#     elif isinstance(label, list):
#         return label
#     return "неизвестно"

# df_eval["true_time_of_day"] = df_eval["time_of_day"].apply(normalize_true_label)

100%|██████████| 100/100 [1:25:32<00:00, 51.32s/it]

In [ ]:
def calculate_metrics(y_true, y_pred):
    y_true_flat = []
    y_pred_flat = []
    partial_matches = 0
    total_items = 0
    
    for t, p in zip(y_true, y_pred):
        t = t if isinstance(t, list) else [t]
        p = p if isinstance(p, list) else [p]
        
        t_set = set(t)
        p_set = set(p)
        
        if t_set == p_set:
            y_true_flat.extend(t)
            y_pred_flat.extend(p)
        else:
            overlap = t_set & p_set
            if overlap:
                partial_matches += len(overlap)
                for item in t:
                    if item in p_set:
                        y_true_flat.append(item)
                        y_pred_flat.append(item)
                    else:
                        y_true_flat.append(item)
                        y_pred_flat.append("неизвестно")
            else:
                y_true_flat.extend(t)
                y_pred_flat.extend(["неизвестно"] * len(t))
        
        total_items += len(t)
    
    accuracy = accuracy_score(y_true_flat, y_pred_flat)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_flat, y_pred_flat, average="weighted", zero_division=0
    )
    
    partial_accuracy = partial_matches / total_items if total_items > 0 else 0
    
    print("\nОЦЕНКА GPT-4o-mini (Время суток):")
    print(f"Accuracy (exact):  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")
    print(f"Partial Accuracy: {partial_accuracy:.4f}")

try:
    calculate_metrics(df_eval["time_of_day"], df_eval["predicted_time_of_day"])
except KeyError as e:
    print(f"\nTrue labels missing: {e}. Metrics skipped.")

print("\nПример предсказаний:")
print(df_eval[["description", "time_of_day", "predicted_time_of_day"]].head())

ОЦЕНКА GPT-4o-mini (Время суток):
Accuracy (exact):  0.3000
Precision: 0.8247
Recall:    0.3000
F1-score:  0.3703
Partial Accuracy: 0.0000

Пример предсказаний:
                                         description time_of_day  \
0  УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...  неизвестно
1  УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...        ночь
2  УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...  неизвестно
3  УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...       вечер
4  У С Т А Н О В И Л:\nНа основании вердикта колл...        утро

  predicted_time_of_day
0            неизвестно
1            неизвестно
2            неизвестно
3                 вечер
4            неизвестно

In [ ]:
# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)  # убрать лишние пробелы
#     text = text.strip()
#     return text

import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re

client = Client()

df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель для извлечения времени суток из описания преступления.

Твоя задача — определить, в какое время суток произошло преступление (time_of_day).

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь
- Если время указано точно (например, "в 14:00"), возвращай одно значение (например, "день").
- Если время неоднозначное (например, "около полуночи или утром", "00:00–06:00"), возвращай список из двух значений (например, ['ночь', 'утро']).
- Если время не указано или неясно (например, "в течение дня"), возвращай "неизвестно".
- Используй только значения: утро, день, вечер, ночь, неизвестно.
- Формат ответа:
  - Для одного значения: "время: <значение>"
  - Для двух значений: "время: [<значение1>, <значение2>]"
  - Для неизвестного: "время: неизвестно"
- Возвращай только указанный формат ответа. Не добавляй пояснения, комментарии или дополнительный текст.

Примеры:
Текст: В 15:00 обвиняемый совершил преступление.
Ответ: время: день
Текст: Ночью в лесу произошло убийство.
Ответ: время: ночь
Текст: Преступление произошло около полуночи или утром.
Ответ: время: ['ночь', 'утро']
Текст: В 2:00 жертва была убита.
Ответ: время: ночь
Текст: Утром или в обед обвиняемый совершил кражу.
Ответ: время: ['утро', 'день']
Текст: Вечером в 18:00 произошло нападение.
Ответ: время: вечер
Текст: Преступление произошло в подъезде, время не указано.
Ответ: время: неизвестно
Текст: В 00:00–06:00 произошло ограбление.
Ответ: время: ['ночь', 'утро']
Текст: Рано утром в 5:00 было совершено преступление.
Ответ: время: утро
Текст: В полночь произошло убийство.
Ответ: время: ночь

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False

            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"

df_eval["predicted_time_of_day"] = df_eval["description"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [1:13:23<00:00, 44.03s/it]

In [ ]:
y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

ОЦЕНКА GPT-4:
Accuracy:  0.3100
Precision: 0.6043
Recall:    0.3100
F1-score:  0.3834

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно            неизвестно
1               ночь            утро, ночь
2         неизвестно            неизвестно
3              вечер           вечер, ночь
4               утро                  утро
..               ...                   ...
95             вечер           вечер, ночь
96             вечер           вечер, ночь
97  ['утро', 'день']            утро, день
98              утро            неизвестно
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score
import numpy as np

def to_list(value):
    if isinstance(value, list):
        return value
    elif isinstance(value, str):
        if value == 'неизвестно':
            return ['неизвестно']
        return [v.strip() for v in value.split(',') if v.strip()]
    return []

def is_correct_prediction(true, pred):
    true_list = to_list(true)
    pred_list = to_list(pred)
    
    if not true_list:
        return not pred_list
    
    return all(item in pred_list for item in true_list)

y_true = df_eval['time_of_day']
y_pred = df_eval['predicted_time_of_day']

correct_predictions = [is_correct_prediction(true, pred) for true, pred in zip(y_true, y_pred)]
accuracy = np.mean(correct_predictions)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy: {accuracy:.4f}")

df_eval['is_correct'] = correct_predictions

print("\nПример предсказаний:")
print(df_eval[['time_of_day', 'predicted_time_of_day', 'is_correct']])

ОЦЕНКА GPT-4:
Accuracy: 0.6600

Пример предсказаний:
         time_of_day predicted_time_of_day  is_correct
0         неизвестно            неизвестно        True
1               ночь            утро, ночь        True
2         неизвестно            неизвестно        True
3              вечер           вечер, ночь        True
4               утро                  утро        True
..               ...                   ...         ...
95             вечер           вечер, ночь        True
96             вечер           вечер, ночь        True
97  ['утро', 'день']            утро, день       False
98              утро            неизвестно       False
99              утро            утро, день        True

[100 rows x 3 columns]

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
model.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=4, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re
import torch  


device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
print(f"Using device: {device}") 


client = Client()


df_eval = dfff.iloc[0:].copy() 


tqdm.pandas()


def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить, в какое время суток (из четырёх вариантов) произошло преступление.

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь

Если в тексте нет чёткого указания на время, выбери наиболее вероятное.
Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта.

Ответ должен состоять **только** из одного или двух слов из списка:
**утро, день, вечер, ночь**. Без пояснений и комментариев.

Примеры:
Текст: Преступление произошло в 5 утра, на автобусной остановке.
Ответ: утро
Текст: В 15:00 обвиняемый выстрелил в жертву
Ответ: день

Описание:
{text}

Ответ:""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                web_search=False
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"


def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)  
    text = text.strip()
    return text

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)


y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]


accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)


print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")


print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

Using device: mps

100%|██████████| 100/100 [1:54:35<00:00, 68.75s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.3500
Precision: 0.5050
Recall:    0.3500
F1-score:  0.3707

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно            неизвестно
1               ночь            неизвестно
2         неизвестно            неизвестно
3              вечер                 вечер
4               утро            неизвестно
..               ...                   ...
95             вечер                 вечер
96             вечер                 вечер
97  ['утро', 'день']            неизвестно
98              утро            неизвестно
99              утро                  утро

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = OpenAI(api_key='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')

df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — определить для каждого упомянутого обвиняемого:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее.

Правила:
- Для пола: если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она"), укажи "мужчина" или "женщина". Если информации нет, укажи "неизвестно".
- Для судимостей: если есть явное указание (например, "ранее судим", "имеет судимость"), укажи "да". Если указано отсутствие (например, "не судим"), укажи "нет". Если информации нет, укажи "нет".
- Формат ответа:
  - Если обвиняемый один, возвращай строки: "пол: <мужчина/женщина/неизвестно>, судимости: <да/нет>".
  - Если обвиняемых несколько, возвращай списки: "пол: [<мужчина/женщина/неизвестно>, ...], судимости: [<да/нет>, ...]".
- Значения для каждого обвиняемого указаны в порядке их упоминания в тексте.
- Убедись, что порядок значений строго соответствует порядку упоминания обвиняемых.

Примеры:
Текст: Обвиняемый Иванов А.А., ранее судимый, совершил кражу.
Ответ: пол: мужчина, судимости: да
Текст: Обвиняемая Петрова Е.В., не судимая, совершила мошенничество.
Ответ: пол: женщина, судимости: нет
Текст: Подсудимые Скородумов С.Ю. и Скворцова Е.В. совершили убийство, ранее не судимые.
Ответ: пол: [мужчина, женщина], судимости: [нет, нет]
Текст: Обвиняемый совершил преступление в 15:00.
Ответ: пол: неизвестно, судимости: нет
Текст: Иванов А.А. и Петрова Е.В., ранее судимые, совершили кражу.
Ответ: пол: [мужчина, женщина], судимости: [да, да]
Текст: гражданина России, ранее не судимого
Ответ: пол: мужчина, судимости: нет
Текст: уроженца, неработающего, судимого
Ответ: пол: мужчина, судимости: да
Текст: обвиняемой в совершении преступления
Ответ: пол: женщина, судимости: нет

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return {"gender": "неизвестно", "prior_convictions": "нет"}

def normalize_prediction(text):
    gender = "неизвестно"
    prior_convictions = "нет"
    
    try:
       
        pattern = r'(пол:\s*(\[.*?\]|\w+))\s*,\s*(судимости:\s*(\[.*?\]|\w+))'
        match = re.match(pattern, text.strip())
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        gender_part = match.group(2).strip()
        convictions_part = match.group(4).strip()
        
        gender_match = re.match(r'\[(.*?)\]', gender_part)
        convictions_match = re.match(r'\[(.*?)\]', convictions_part)
        
        if gender_match:
            gender_values = [v.strip() for v in gender_match.group(1).split(",") if v.strip()]
            gender = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
        else:
            gender = gender_part if gender_part in ["мужчина", "женщина", "неизвестно"] else "неизвестно"
            
        if convictions_match:
            convictions_values = [v.strip() for v in convictions_match.group(1).split(",") if v.strip()]
            prior_convictions = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
        else:
            prior_convictions = convictions_part if convictions_part in ["да", "нет"] else "нет"
            
    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, match: {match.groups() if match else None}, defaulting to 'неизвестно' for gender, 'нет' for convictions")
    
    return {"gender": gender, "prior_convictions": prior_convictions}

df_eval["clean_preamble"] = df_eval["preamble"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_preamble"].progress_apply(classify_with_gpt4)

df_eval["predicted_gender"] = df_eval["predictions"].apply(lambda x: x["gender"])
df_eval["predicted_prior_convictions"] = df_eval["predictions"].apply(lambda x: x["prior_convictions"])

100%|██████████| 100/100 [01:32<00:00,  1.08it/s]

In [ ]:
y_true_gender = df_eval["gender_accused"]
y_pred_gender = df_eval["predicted_gender"].astype(str)
y_true_convictions = df_eval["prior_convictions"]
y_pred_convictions = df_eval["predicted_prior_convictions"].astype(str)


gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_accused", "predicted_gender", "prior_convictions", "predicted_prior_convictions"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9600
Precision: 0.9806
Recall:    0.9600
F1-score:  0.9699

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8400
Precision: 0.8677
Recall:    0.8400
F1-score:  0.8510

Пример предсказаний:
           gender_accused    predicted_gender prior_convictions  \
0                 мужчина             мужчина               нет
1                 мужчина             мужчина               нет
2  ['мужчина', 'мужчина']  [мужчина, мужчина]    ['нет', 'нет']
3                 мужчина             мужчина               нет
4                 мужчина             мужчина               нет

  predicted_prior_convictions
0                         нет
1                         нет
2                  [нет, нет]
3                         нет
4                         нет

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — определить:
1. Время суток, когда произошло преступление (time_of_day).
2. Место, где произошло преступление (location).
3. Способ совершения преступления (method).
4. Была ли ссора между преступником и жертвой перед преступлением (precrime_argument).

Правила:
- **Время суток (time_of_day)**:
  - 04:00–11:59 → утро
  - 12:00–15:59 → день
  - 16:00–22:59 → вечер
  - 23:00–03:59 → ночь
  - Если нет точного времени, но указан промежуток (например, "около полуночи или утром", "00:00–06:00"), возвращай список из двух значений (например, ['ночь', 'утро']). Если время неизвестно, укажи "неизвестно".
  - Возвращай только одно или два слова из списка: утро, день, вечер, ночь.
- **Место (location)**:
  - Укажи конкретное место в именительном падеже (например, "квартира", "улица", "подъезд", "лес", "автомобиль"). Если место не указано, возвращай "неизвестно".
  - Не добавляй уточняющих деталей (например, для "возле магазина «Кит»" пиши "улица").
- **Способ (method)**:
  - Укажи способ убийства или покушения (например, "нож", "огнестрел", "удушение", "избиение", "отравление", "утопление", "поджог", "автотравма"). Если способ неизвестен, укажи "неизвестно".
  - Если жертв несколько и способы разные, возвращай список строк (например, ['нож', 'удушение']). Если способ одинаковый, возвращай строку (например, "огнестрел"). Если одну жертву убивали несколькими способами, перечисли их в списке (например, ['нож', 'избиение']).
- **Ссора (precrime_argument)**:
  - Если есть указание на ссору, укажи "была". Если указано отсутствие ссоры или информации нет, укажи "нет".
- Формат ответа:
  - Возвращай: "время: <значение>, место: <значение>, способ: <значение>, ссора: <значение>".
  - Для множественных значений (время или способ) используй списки: например, "время: ['ночь', 'утро']" или "способ: ['нож', 'удушение']".
- **Возвращай только указанный формат ответа. Не добавляй объяснения, комментарии или дополнительный текст. Все существительные должны быть в именительном падеже (например, "нож", а не "ножом"; "пистолет", а не "выстрел из пистолета").**

Примеры:
Текст: В 15:00 обвиняемый убил жертву ножом в квартире после ссоры.
Ответ: время: день, место: квартира, способ: нож, ссора: была
Текст: Ночью в лесу жертва была задушена, ссоры не было.
Ответ: время: ночь, место: лес, способ: удушение, ссора: нет
Текст: Преступление произошло в подъезде, жертвы убиты огнестрелом и ножом.
Ответ: время: неизвестно, место: подъезд, способ: ['огнестрел', 'нож'], ссора: нет
Текст: Вечером на улице обвиняемый избил жертву, ссоры не упомянуты.
Ответ: время: вечер, место: улица, способ: избиение, ссора: нет
Текст: Жертва была отравлена и утоплена в автомобиле в 2:00.
Ответ: время: ночь, место: автомобиль, способ: ['отравление', 'утопление'], ссора: нет
Текст: Преступление произошло около полуночи или утром в заброшенном здании, способ неизвестен.
Ответ: время: ['ночь', 'утро'], место: заброшенное здание, способ: неизвестно, ссора: нет
Текст: В ходе конфликта с А.В.М.о., возникшего на почве личных неприязненных отношений, Г.Д.Р. умышленно нанес удары по голове.
Ответ: время: неизвестно, место: неизвестно, способ: избиение, ссора: была
Текст: В 00:00–06:00 в подъезде жертва была убита топором.
Ответ: время: ['ночь', 'утро'], место: подъезд, способ: топор, ссора: нет

Описание:
{text}

Ответ:
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Error processing text: {e}")
            continue
    return {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "нет"
    }

def normalize_prediction(text):
    result = {
        "time_of_day": "неизвестно",
        "location": "неизвестно",
        "method": "неизвестно",
        "precrime_argument": "нет"
    }
    
    try:
        
        pattern = r'время:\s*(\[.*?\]|\w+)\s*,\s*место:\s*([^\,]+?)\s*,\s*способ:\s*(\[.*?\]|\w+)\s*,\s*ссора:\s*(\w+)'
        match = re.search(pattern, text.strip())
        if not match:
            raise ValueError(f"Response does not match expected format: {text}")
        
        time_part = match.group(1).strip()
        location_part = match.group(2).strip()
        method_part = match.group(3).strip()
        argument_part = match.group(4).strip()
        
        
        time_match = re.match(r'\[(.*?)\]', time_part)
        valid_times = ["утро", "день", "вечер", "ночь"]
        if time_match:
            time_values = [v.strip() for v in time_match.group(1).split(",") if v.strip()]
            filtered_times = [v for v in time_values if v in valid_times]
            result["time_of_day"] = filtered_times if filtered_times else "неизвестно"
        else:
            result["time_of_day"] = time_part if time_part in valid_times + ["неизвестно"] else "неизвестно"
        
       
        valid_locations = [
            "квартира", "улица", "подъезд", "лес", "заброшенное здание", "автомобиль",
            "дом", "дача", "гараж", "общежитие", "безлюдная местность", "хостел",
            "двор", "лестничная площадка", "чердак", "база отдыха", "неизвестно"
        ]
        result["location"] = location_part if location_part in valid_locations else "неизвестно"
        
       
        method_match = re.match(r'\[(.*?)\]', method_part)
        valid_methods = [
            "нож", "огнестрел", "удушение", "отравление", "избиение", "утопление",
            "поджог", "автотравма", "ружье", "травматический пистолет", "удар предметом",
            "молоток", "полено", "топор", "клинок", "неизвестно"
        ]
        if method_match:
            method_values = [v.strip() for v in method_match.group(1).split(",") if v.strip()]
            filtered_methods = [v for v in method_values if v in valid_methods]
            result["method"] = filtered_methods if filtered_methods else "неизвестно"
        else:
            result["method"] = method_part if method_part in valid_methods else "неизвестно"
        
        
        result["precrime_argument"] = argument_part if argument_part in ["была", "нет"] else "нет"
        
    except Exception as e:
        print(f"Parsing error in response: {text}, error: {str(e)}, match: {match.groups() if match else None}, defaulting to 'неизвестно' for all fields")
    
    return result

df_eval["predictions"] = df_eval["description"].progress_apply(classify_with_gpt4)

df_eval["predicted_time_of_day"] = df_eval["predictions"].apply(lambda x: x["time_of_day"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: x["precrime_argument"])

 98%|█████████▊| 98/100 [05:01<00:10,  5.00s/it]

Parsing error in response: время: ['вечер', 'ночь'], место: ['участок местности', 'автодорога'], способ: ['удар', 'лопата'], ссора: была, error: Response does not match expected format: время: ['вечер', 'ночь'], место: ['участок местности', 'автодорога'], способ: ['удар', 'лопата'], ссора: была, match: None, defaulting to 'неизвестно' for all fields

100%|██████████| 100/100 [05:14<00:00,  3.14s/it]

In [ ]:
equivalence_mappings = {
    "location": {
        "дом": ["квартира", "дом"],
        "квартира": ["квартира", "дом"],
        "улица": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "пешеходный мост": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "электрическая подстанция": ["улица", "пешеходный мост", "электрическая подстанция", "двор"],
        "двор": ["улица", "пешеходный мост", "электрическая подстанция", "двор"]
    },
    "method": {
        "огнестрел": ["огнестрел", "ружье", "травматический пистолет"],
        "ружье": ["огнестрел", "ружье", "травматический пистолет"],
        "травматический пистолет": ["огнестрел", "ружье", "травматический пистолет"],
        "избиение": ["избиение", "удар предметом"],
        "удар предметом": ["избиение", "удар предметом"]
    }
}


def calculate_metrics(y_true, y_pred, label_name, field):
    y_true_flat = []
    y_pred_flat = []
    partial_matches = 0
    total_items = 0
    
    for t, p in zip(y_true, y_pred):
        t = t if isinstance(t, list) else [t]
        p = p if isinstance(p, list) else [p]
        
       
        t_set = set(t)
        p_set = set(p)
        
       
        if field in equivalence_mappings:
            t_mapped = set()
            p_mapped = set()
            for item in t_set:
                for key, equivalents in equivalence_mappings[field].items():
                    if item in equivalents:
                        t_mapped.add(key)
                        break
                else:
                    t_mapped.add(item)
            for item in p_set:
                for key, equivalents in equivalence_mappings[field].items():
                    if item in equivalents:
                        p_mapped.add(key)
                        break
                else:
                    p_mapped.add(item)
            t_set = t_mapped
            p_set = p_mapped
        
       
        if t_set == p_set:
            y_true_flat.extend(t)
            y_pred_flat.extend(p)
        else:
           
            if t_set & p_set:  
                partial_matches += len(t_set & p_set)
                for item in t:
                    if item in p_set or any(item in equivalence_mappings[field].get(pred, []) for pred in p_set if field in equivalence_mappings):
                        y_true_flat.append(item)
                        y_pred_flat.append(item)  
                    else:
                        y_true_flat.append(item)
                        y_pred_flat.append("неизвестно")
            else:
                y_true_flat.extend(t)
                y_pred_flat.extend(["неизвестно"] * len(t))
        
        total_items += len(t)
    
    accuracy = accuracy_score(y_true_flat, y_pred_flat)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true_flat, y_pred_flat, average="weighted", zero_division=0
    )
    
    partial_accuracy = partial_matches / total_items if total_items > 0 else 0
    
    print(f"\nОЦЕНКА GPT-4o-mini ({label_name}):")
    print(f"Accuracy (exact):  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")
    print(f"Partial Accuracy: {partial_accuracy:.4f}")

try:
    
    calculate_metrics(df_eval["location"], df_eval["predicted_location"], "Место", "location")
    calculate_metrics(df_eval["method"], df_eval["predicted_method"], "Способ", "method")
    calculate_metrics(df_eval["precrime_argument"], df_eval["predicted_precrime_argument"], "Ссора", "precrime_argument")
except KeyError as e:
    print(f"\nTrue labels missing: {e}. Metrics skipped.")

print("\nПример предсказаний:")
print(df_eval[["description", "time_of_day", "predicted_time_of_day", 
               "location", "predicted_location", 
               "method", "predicted_method", 
               "precrime_argument", "predicted_precrime_argument"]].head())

ОЦЕНКА GPT-4o-mini (Место):
Accuracy (exact):  0.5100
Precision: 0.7878
Recall:    0.5100
F1-score:  0.5971
Partial Accuracy: 0.0000

ОЦЕНКА GPT-4o-mini (Способ):
Accuracy (exact):  0.3900
Precision: 0.7700
Recall:    0.3900
F1-score:  0.4967
Partial Accuracy: 0.0000

ОЦЕНКА GPT-4o-mini (Ссора):
Accuracy (exact):  0.9300
Precision: 1.0000
Recall:    0.9300
F1-score:  0.9535
Partial Accuracy: 0.0000

Пример предсказаний:
                                         description time_of_day  \
0  УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...  неизвестно
1  УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...        ночь
2  УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...  неизвестно
3  УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...       вечер
4  У С Т А Н О В И Л:\nНа основании вердикта колл...        утро

  predicted_time_of_day  location predicted_location                   method  \
0            неизвестно     улица              улица                 избиение
1            неизвестно     улица         неизвестно                    ружье
2            неизвестно  квартира                дом                 удушение
3            неизвестно       дом               дача  травматический пистолет
4            неизвестно     улица                лес                 избиение

  predicted_method precrime_argument predicted_precrime_argument
0       неизвестно              была                        была
1        огнестрел              была                        была
2       неизвестно               нет                         нет
3       неизвестно              была                        была
4         избиение              была                        была

In [ ]:
import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re
import torch 

client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить:
Время суток, когда произошло преступление (time_of_day).

- **Время суток (time_of_day)**:
  - 04:00–11:59 → утро
  - 12:00–15:59 → день
  - 16:00–22:59 → вечер
  - 23:00–03:59 → ночь
  - Если время указано точно (например, "в 14:00"), возвращай одно значение (например, "день").
  - Если нет точного времени (время неоднозначное), но указан промежуток (например, "около полуночи или утром", "00:00–06:00"), возвращай список из двух значений (например, ['ночь', 'утро']  — максимум два варианта). 
  - Если время не указано или неясно (например, "в течение дня"), возвращай "неизвестно".
  - Возвращай только одно или два слова из списка: утро, день, вечер, ночь.
  - Используй только значения: утро, день, вечер, ночь, неизвестно.

Ответ должен состоять **только** из одного или двух слов из списка:
**утро, день, вечер, ночь**. Без пояснений и комментариев.

- Формат ответа:
  - Для одного значения: "<значение>"
  - Для двух значений: ["<значение1>", "<значение2>"]
  - Для неизвестного: "неизвестно"
- Возвращай только указанный формат ответа. Не добавляй пояснения, комментарии или дополнительный текст.

Примеры:
Текст: В 15:00 обвиняемый совершил преступление.
Ответ: время: день
Текст: Ночью в лесу произошло убийство.
Ответ: время: ночь
Текст: Преступление произошло около полуночи или утром.
Ответ: время: ['ночь', 'утро']
Текст: В 2:00 жертва была убита.
Ответ: время: ночь
Текст: Утром или в обед обвиняемый совершил кражу.
Ответ: время: ['утро', 'день']
Текст: Вечером в 18:00 произошло нападение.
Ответ: время: вечер
Текст: Преступление произошло в подъезде, время не указано.
Ответ: время: неизвестно
Текст: В 00:00–06:00 произошло ограбление.
Ответ: время: ['ночь', 'утро']
Текст: Рано утром в 5:00 было совершено преступление.
Ответ: время: утро
Текст: В полночь произошло убийство.
Ответ: время: ночь

Описание:
{text}

Ответ:""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [04:58<00:00,  2.98s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.1500
Precision: 0.7213
Recall:    0.1500
F1-score:  0.2121

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно            неизвестно
1               ночь            утро, ночь
2         неизвестно            неизвестно
3              вечер           вечер, ночь
4               утро            утро, день
..               ...                   ...
95             вечер           вечер, ночь
96             вечер           вечер, ночь
97  ['утро', 'день']            утро, день
98              утро            неизвестно
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import ast

def format_time_of_day(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            
            parsed_list = ast.literal_eval(value)
            
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                
                return ", ".join(parsed_list)
        
        return value
    except (ValueError, SyntaxError):
        
        return value

df_eval["time_of_day2"] = df_eval["time_of_day"].apply(format_time_of_day)
df_eval["time_of_day2"]

0     неизвестно
1           ночь
2     неизвестно
3          вечер
4           утро
         ...
95         вечер
96         вечер
97    утро, день
98          утро
99          утро
Name: time_of_day2, Length: 100, dtype: object

In [ ]:
import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re
import torch 

client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить:
Время суток, когда произошло преступление (time_of_day).

- **Время суток (time_of_day)**:
  - 04:00–11:59 → утро
  - 12:00–15:59 → день
  - 16:00–22:59 → вечер
  - 23:00–03:59 → ночь
  - Если время указано точно (например, "в 14:00"), возвращай одно значение (например, "день").
  - Если в тексте нет чёткого указания на время, выбери наиболее вероятное.
  - Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта. 
  - Если время не указано или неясно (например, "в течение дня"), возвращай "неизвестно".
  - Используй только значения: утро, день, вечер, ночь, неизвестно.

Ответ должен состоять **только** из одного или двух слов (максимум) из списка:
**утро, день, вечер, ночь**. Без пояснений и комментариев.

- Формат ответа:
  - Для одного значения: "<значение>"
  - Для двух значений: ["<значение1>", "<значение2>"]
  - Для неизвестного: "неизвестно"
- Возвращай только указанный формат ответа. Не добавляй пояснения, комментарии или дополнительный текст.

Примеры:
Текст: В 15:00 обвиняемый совершил преступление.
Ответ: время: день
Текст: Ночью в лесу произошло убийство.
Ответ: время: ночь
Текст: Преступление произошло около полуночи или утром.
Ответ: время: ['ночь', 'утро']
Текст: В 2:00 жертва была убита.
Ответ: время: ночь
Текст: Утром или в обед обвиняемый совершил кражу.
Ответ: время: ['утро', 'день']
Текст: Вечером в 18:00 произошло нападение.
Ответ: время: вечер
Текст: Преступление произошло в подъезде, время не указано.
Ответ: время: неизвестно
Текст: В 00:00–06:00 произошло ограбление.
Ответ: время: ['ночь', 'утро']
Текст: Рано утром в 5:00 было совершено преступление.
Ответ: время: утро
Текст: В полночь произошло убийство.
Ответ: время: ночь
Текст: в период времени с 10 часов 30 минут до 11 часов 30 минут, более точное время не установлено,
Ответ: время: утро 
Текст: в период с 01 ч. 00 м. по 01 ч. 30 м., более точное время не установлено,
Ответ: время: ночь

Описание:
{text}

Ответ:""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

def format_time_of_day(value):
    try:
        
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            
            parsed_list = ast.literal_eval(value)
            
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                
                return ", ".join(parsed_list)
        
        return value
    except (ValueError, SyntaxError):
        
        return value

df_eval["time_of_day2"] = df_eval["time_of_day"].apply(format_time_of_day)
df_eval["time_of_day2"]

y_true = df_eval["time_of_day2"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [06:15<00:00,  3.76s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.2200
Precision: 0.7928
Recall:    0.2200
F1-score:  0.2536

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно            неизвестно
1               ночь            утро, ночь
2         неизвестно            неизвестно
3              вечер           вечер, ночь
4               утро            утро, день
..               ...                   ...
95             вечер           вечер, ночь
96             вечер           вечер, ночь
97  ['утро', 'день']            утро, день
98              утро            неизвестно
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [196]:
y_true = df_eval["time_of_day2"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day2", "predicted_time_of_day"]])

ОЦЕНКА GPT-4:
Accuracy:  0.3300
Precision: 0.7267
Recall:    0.3300
F1-score:  0.3907

Пример предсказаний:
   time_of_day2 predicted_time_of_day
0    неизвестно            неизвестно
1          ночь                  ночь
2    неизвестно            неизвестно
3         вечер           вечер, ночь
4          утро            утро, день
..          ...                   ...
95        вечер                 вечер
96        вечер           вечер, ночь
97   утро, день            утро, день
98         утро            неизвестно
99         утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)  
    text = text.strip()
    return text

import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re


client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить, в какое время суток (из четырёх вариантов) произошло преступление.

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь

Если в тексте нет чёткого указания на время, выбери наиболее вероятное.
Если упоминается промежуток времени между двумя периодами (например, 11:00–13:00), укажи оба — максимум два варианта.

Ответ должен состоять **только** из одного или двух слов из списка:
**утро, день, вечер, ночь**. Без пояснений и комментариев.

Примеры:
Текст: Преступление произошло в 5 утра, на автобусной остановке.
Ответ: утро
Текст: В 15:00 обвиняемый выстрелил в жертву
Ответ: день"

Описание:
{text}

Ответ:""".strip()


def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [04:45<00:00,  2.85s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.6900
Precision: 0.6047
Recall:    0.6900
F1-score:  0.6409

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно                  ночь
1               ночь                  ночь
2         неизвестно                  день
3              вечер                 вечер
4               утро                  утро
..               ...                   ...
95             вечер                 вечер
96             вечер                 вечер
97  ['утро', 'день']            утро, день
98              утро                  ночь
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def format_time_of_day(value):
    try:
        
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            
            parsed_list = ast.literal_eval(value)
            
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                
                return ", ".join(parsed_list)
       
        return value
    except (ValueError, SyntaxError):
        
        return value

df_eval["time_of_day2"] = df_eval["time_of_day"].apply(format_time_of_day)

y_true = df_eval["time_of_day2"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day2", "predicted_time_of_day"]])

ОЦЕНКА GPT-4:
Accuracy:  0.7200
Precision: 0.6347
Recall:    0.7200
F1-score:  0.6709

Пример предсказаний:
   time_of_day2 predicted_time_of_day
0    неизвестно                  ночь
1          ночь                  ночь
2    неизвестно                  день
3         вечер                 вечер
4          утро                  утро
..          ...                   ...
95        вечер                 вечер
96        вечер                 вечер
97   утро, день            утро, день
98         утро                  ночь
99         утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)  
    text = text.strip()
    return text

import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re


client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить, в какое время суток (из четырёх вариантов) произошло преступление.

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь

- Если в тексте есть явное указание времени (например, "в 15:00", "утром"), используй его.
- Если указан промежуток времени, пересекающий два периода (например, "с 11:00 до 13:00"), укажи оба периода (например, "утро, день") — максимум два варианта..
- Если времени нет, сделай обоснованное предположение на основе контекста:
  - Кражи в жилых помещениях чаще происходят ночью.
  - Уличные преступления (грабежи, драки) чаще происходят вечером.
  - Мошенничества и преступления в общественных местах чаще происходят днём.
  - Если контекст неясен, верни "неизвестно".
- Ответ должен содержать **только одно или два слова** из списка: утро, день, вечер, ночь, разделённые запятой и пробелом (например, "утро, день"). Без пояснений и комментариев.

Примеры:
Текст: Преступление произошло в 5 утра, на автобусной остановке.
Ответ: утро
Текст: В 15:00 обвиняемый выстрелил в жертву
Ответ: день
Текст: Кража в квартире, обнаруженная утром.
Ответ: ночь
Текст: Грабеж на улице около 20:00.
Ответ: вечер
Текст: Мошенничество в магазине, без указания времени.
Ответ: день
Текст: Нападение на прохожего, без времени.
Ответ: вечер
Текст: Преступление произошло с 11:00 до 14:00.
Ответ: утро, день
Текст: Обвиняемый совершил преступление, без деталей.
Ответ: неизвестно

Описание:
{text}

Ответ:""".strip()


def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"


df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [04:53<00:00,  2.94s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.5700
Precision: 0.6981
Recall:    0.5700
F1-score:  0.6053

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно           вечер, ночь
1               ночь                  ночь
2         неизвестно            неизвестно
3              вечер                 вечер
4               утро                  утро
..               ...                   ...
95             вечер                 вечер
96             вечер           вечер, ночь
97  ['утро', 'день']            утро, день
98              утро                  ночь
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def format_time_of_day(value):
    try:
        
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            
            parsed_list = ast.literal_eval(value)
            
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                
                return ", ".join(parsed_list)
        
        return value
    except (ValueError, SyntaxError):
       
        return value

df_eval["time_of_day2"] = df_eval["time_of_day"].apply(format_time_of_day)

y_true = df_eval["time_of_day2"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day2", "predicted_time_of_day"]])

ОЦЕНКА GPT-4:
Accuracy:  0.6100
Precision: 0.7219
Recall:    0.6100
F1-score:  0.6317

Пример предсказаний:
   time_of_day2 predicted_time_of_day
0    неизвестно           вечер, ночь
1          ночь                  ночь
2    неизвестно            неизвестно
3         вечер                 вечер
4          утро                  утро
..          ...                   ...
95        вечер                 вечер
96        вечер           вечер, ночь
97   утро, день            утро, день
98         утро                  ночь
99         утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)  
    text = text.strip()
    return text

import pandas as pd
from tqdm import tqdm
from g4f.client import Client
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import re


client = OpenAI(api_key='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')


df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель классификации времени суток по описанию преступления.

Твоя задача — определить, в какое время суток (из четырёх вариантов) произошло преступление.

Правила:
- 04:00–11:59 → утро
- 12:00–15:59 → день
- 16:00–22:59 → вечер
- 23:00–03:59 → ночь

- Если в тексте есть явное указание времени (например, "в 15:00", "утром"), используй его.
- Если указан промежуток времени, пересекающий два периода (например, "с 11:00 до 13:00"), укажи оба периода (например, "утро, день") — максимум два варианта..
- Если времени нет, сделай обоснованное предположение на основе контекста:
- Если контекст неясен, верни "неизвестно".
- Ответ должен содержать **только одно или два слова** из списка: утро, день, вечер, ночь, разделённые запятой и пробелом (например, "утро, день"). Без пояснений и комментариев.

Примеры:
Текст: Преступление произошло в 5 утра, на автобусной остановке.
Ответ: утро
Текст: В 15:00 обвиняемый выстрелил в жертву
Ответ: день
Текст: в период времени с 10 часов 30 минут до 11 часов 30 минут, более точное время не установлено
Ответ: утро 
Текст: Кража в квартире, обнаруженная утром.
Ответ: ночь
Текст: смерть ФИО наступила в период времени около 4-6 часов.
Ответ: утро
Текст: Грабеж на улице около 20:00.
Ответ: вечер
Текст: Мошенничество в магазине, без указания времени.
Ответ: неизвестно
Текст: Нападение на прохожего, без времени.
Ответ: неизвестно
Текст: Преступление произошло с 11:00 до 14:00.
Ответ: утро, день
Текст: Обвиняемый совершил преступление, без деталей.
Ответ: неизвестно

Описание:
{text}

Ответ:""".strip()


def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for _ in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            
            return normalize_prediction(reply)
        except Exception as e:
            continue
    return "ошибка"

def normalize_prediction(text):
    options = ["утро", "день", "вечер", "ночь"]
    found = [opt for opt in options if opt in text]
    return ", ".join(found) if found else "неизвестно"



df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predicted_time_of_day"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)


y_true = df_eval["time_of_day"]
y_pred = df_eval["predicted_time_of_day"]


accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")


print("\nПример предсказаний:")
print(df_eval[["time_of_day", "predicted_time_of_day"]])

100%|██████████| 100/100 [04:52<00:00,  2.93s/it]

ОЦЕНКА GPT-4:
Accuracy:  0.5800
Precision: 0.7055
Recall:    0.5800
F1-score:  0.6287

Пример предсказаний:
         time_of_day predicted_time_of_day
0         неизвестно            неизвестно
1               ночь                  ночь
2         неизвестно            неизвестно
3              вечер                 вечер
4               утро                  утро
..               ...                   ...
95             вечер                 вечер
96             вечер           вечер, ночь
97  ['утро', 'день']            утро, день
98              утро                  ночь
99              утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
def format_time_of_day(value):
    try:
        
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            
            parsed_list = ast.literal_eval(value)
            
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                
                return ", ".join(parsed_list)
        
        return value
    except (ValueError, SyntaxError):
       
        return value

df_eval["time_of_day2"] = df_eval["time_of_day"].apply(format_time_of_day)

y_true = df_eval["time_of_day2"]
y_pred = df_eval["predicted_time_of_day"]

accuracy = accuracy_score(y_true, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true, y_pred, average="weighted"
)

print("\nОЦЕНКА GPT-4:")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["time_of_day2", "predicted_time_of_day"]])

ОЦЕНКА GPT-4:
Accuracy:  0.6400
Precision: 0.7280
Recall:    0.6400
F1-score:  0.6585

Пример предсказаний:
   time_of_day2 predicted_time_of_day
0    неизвестно            неизвестно
1          ночь                  ночь
2    неизвестно            неизвестно
3         вечер                 вечер
4          утро                  утро
..          ...                   ...
95        вечер                 вечер
96        вечер           вечер, ночь
97   утро, день            утро, день
98         утро                  ночь
99         утро            утро, день

[100 rows x 2 columns]

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer

client = OpenAI(api_key='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')

df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()


def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Связь между преступником и жертвой**: Укажи связь для каждой жертвы (например, знакомый, зять, супруг, родственник, незнакомец). Если жертв несколько, перечисли связи через запятую. Если связь не указана, верни "неизвестно".
2. **Мотив преступления**: Укажи мотивы (например, личная неприязнь, месть, ревность, имущество, ограбление). Если мотивов несколько, перечисли через запятую. Если мотив не указан, верни "неизвестно".
3. **Наличие жертвы женского пола**: Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
4. **Наличие жертвы мужского пола**: Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".

**Правила:**
- Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена или местоимения). Если информация отсутствует, укажи "неизвестно".
- Для мотива: извлеки мотивы на основе явных указаний или контекста (например, "ограбление" для кражи). Если мотив неясен, укажи "неизвестно".
- Для пола жертв: опирайся на имена, местоимения ("он", "она") или явные указания ("мужчина", "женщина"). Если пол не указан, не считай жертву для этой категории.
- Ответ должен быть в формате:
  ```
  связь: <связь_1, связь_2, ... или неизвестно>
  мотив: <мотив_1, мотив_2, ... или неизвестно>
  женщина_жертва: <1 или 0>
  мужчина_жертва: <1 или 0>
  ```
- Убедись, что порядок связей соответствует порядку упоминания жертв в тексте.

**Примеры:**
- Текст: Обвиняемый убил свою жену из-за ревности.
  Ответ:
  ```
  связь: супруга
  мотив: ревность
  женщина_жертва: 1
  мужчина_жертва: 0
  ```
- Текст: Обвиняемый ограбил двух незнакомых мужчин на улице.
  Ответ:
  ```
  связь: незнакомец, незнакомец
  мотив: ограбление
  женщина_жертва: 0
  мужчина_жертва: 1
  ```
- Текст: Иванов избил знакомого и его сестру из личной неприязни.
  Ответ:
  ```
  связь: знакомый, родственница
  мотив: личная неприязнь
  женщина_жертва: 1
  мужчина_жертва: 1
  ```
- Текст: Кража в магазине, без указания жертв.
  Ответ:
  ```
  связь: неизвестно
  мотив: имущество
  женщина_жертва: 0
  мужчина_жертва: 0
  ```
- Текст: Нападение на прохожего, без деталей.
  Ответ:
  ```
  связь: незнакомец
  мотив: неизвестно
  женщина_жертва: 0
  мужчина_жертва: 1
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "relationship": "неизвестно",
        "motive": "неизвестно",
        "woman_victim": "0",
        "man_victim": "0"
    }


def normalize_prediction(text):
    result = {
        "relationship": "неизвестно",
        "motive": "неизвестно",
        "woman_victim": "0",
        "man_victim": "0"
    }
    
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("связь:"):
                result["relationship"] = line.replace("связь:", "").strip()
            elif line.startswith("мотив:"):
                result["motive"] = line.replace("мотив:", "").strip()
            elif line.startswith("женщина_жертва:"):
                result["woman_victim"] = line.replace("женщина_жертва:", "").strip()
            elif line.startswith("мужчина_жертва:"):
                result["man_victim"] = line.replace("мужчина_жертва:", "").strip()
        
       
        if result["woman_victim"] not in ["0", "1"]:
            result["woman_victim"] = "0"
        if result["man_victim"] not in ["0", "1"]:
            result["man_victim"] = "0"
        
       
        motives = [m.strip() for m in result["motive"].split(",") if m.strip()]
        valid_motives = ["личная неприязнь", "месть", "ревность", "имущество", "ограбление", "неизвестно"]
        result["motive"] = ", ".join([m for m in motives if m in valid_motives]) or "неизвестно"
        
       
        relationships = [r.strip() for r in result["relationship"].split(",") if r.strip()]
        valid_relationships = ["знакомый", "зять", "супруг", "супруга", "родственник", "родственница", "незнакомец", "неизвестно"]
        result["relationship"] = ", ".join([r for r in relationships if r in valid_relationships]) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)

df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: x["relationship"])
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])
df_eval["predicted_woman_victim"] = df_eval["predictions"].apply(lambda x: x["woman_victim"])
df_eval["predicted_man_victim"] = df_eval["predictions"].apply(lambda x: x["man_victim"])

100%|██████████| 100/100 [09:07<00:00,  5.47s/it]

In [ ]:
mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))

y_true_relationship = df_eval["relationship_between_accused_and_victim"]
y_pred_relationship = df_eval["predicted_relationship"]
relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)

y_true_woman_victim = df_eval["has_woman_victim"].astype(str)
y_pred_woman_victim = df_eval["predicted_woman_victim"]
woman_victim_accuracy = accuracy_score(y_true_woman_victim, y_pred_woman_victim)
woman_victim_precision, woman_victim_recall, woman_victim_f1, _ = precision_recall_fscore_support(
    y_true_woman_victim, y_pred_woman_victim, average="weighted", zero_division=0
)

y_true_man_victim = df_eval["has_man_victim"].astype(str)
y_pred_man_victim = df_eval["predicted_man_victim"]
man_victim_accuracy = accuracy_score(y_true_man_victim, y_pred_man_victim)
man_victim_precision, man_victim_recall, man_victim_f1, _ = precision_recall_fscore_support(
    y_true_man_victim, y_pred_man_victim, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Наличие женщины-жертвы):")
print(f"Accuracy:  {woman_victim_accuracy:.4f}")
print(f"Precision: {woman_victim_precision:.4f}")
print(f"Recall:    {woman_victim_recall:.4f}")
print(f"F1-score:  {woman_victim_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Наличие мужчины-жертвы):")
print(f"Accuracy:  {man_victim_accuracy:.4f}")
print(f"Precision: {man_victim_precision:.4f}")
print(f"Recall:    {man_victim_recall:.4f}")
print(f"F1-score:  {man_victim_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "relationship_between_accused_and_victim", "predicted_relationship",
    "motive", "predicted_motive",
    "has_woman_victim", "predicted_woman_victim",
    "has_man_victim", "predicted_man_victim"
]].head())

ОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):
Accuracy:  0.3400
Precision: 0.3565
Recall:    0.3400
F1-score:  0.3371

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.6991
Recall:    0.6930
F1-score:  0.6960

ОЦЕНКА GPT-4o-mini (Наличие женщины-жертвы):
Accuracy:  0.8100
Precision: 0.8765
Recall:    0.8100
F1-score:  0.8202

ОЦЕНКА GPT-4o-mini (Наличие мужчины-жертвы):
Accuracy:  0.9100
Precision: 0.9129
Recall:    0.9100
F1-score:  0.9047

Пример предсказаний:
  relationship_between_accused_and_victim  predicted_relationship  \
0                                знакомый                знакомый
1                                знакомый      знакомый, знакомый
2            ['неизвестно', 'неизвестно']  неизвестно, неизвестно
3                                работник                знакомый
4                                знакомый                знакомый

                             motive             predicted_motive  \
0     ['личная неприязнь', 'месть']             личная неприязнь
1  ['личная неприязнь', 'ревность']   личная неприязнь, ревность
2           ['деньги', 'имущество']                    имущество
3                  личная неприязнь  личная неприязнь, имущество
4                  личная неприязнь             личная неприязнь

   has_woman_victim predicted_woman_victim  has_man_victim  \
0                 0                      0               1
1                 0                      0               1
2                 1                      1               0
3                 0                      0               1
4                 0                      0               1

  predicted_man_victim
0                    1
1                    1
2                    0
3                    1
4                    1

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['ограбление'] will be ignored
  warnings.warn(

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer

client = OpenAI(api_key='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')

df_eval = dfff.iloc[0:].copy()  


tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                return ', '.join([location_map.get(loc, 'другое') for loc in loc_list])
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                return ', '.join([method_map.get(meth, 'другое') for meth in meth_list])
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'

import ast
df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Связь между преступником и жертвой**: Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник). Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец. Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг"). Если связь не указана, верни "неизвестно".
2. **Место преступления**: Укажи место преступления в начальной форме в единственном числе (например, "квартира", "улица"). Если мест несколько, перечисли через запятую. Классифицируй место по категориям: жилое помещение (квартира, дом, дача, общежитие, хостел), уличное пространство (улица, двор, лес, берег озера, безлюдная местность), общественный транспорт (такси, автобус, поезд), общественное место (магазин, кафе, бар, рынок), подъезд и прилегающие зоны (подъезд, лестничная площадка, чердак), рабочая зона (гараж, база отдыха, склад, офис), другое. Верни название категории.
3. **Метод преступления**: Укажи метод преступления в начальной форме в единственном числе (например, "нож", "избиение"). Если методов несколько, перечисли через запятую. Классифицируй метод по категориям: физическое воздействие (избиение, удар предметом, скидывание с высоты), холодное оружие (нож, клинок, вилка, лопата, топор), тяжелые предметы (молоток, кирпич, полено), огнестрельное оружие (ружье, травматический пистолет, огнестрел), удушение (удушение, повешение), другое. Верни название категории.
4. **Мотив преступления**: Укажи мотивы (например, личная неприязнь, месть, ревность, имущество, ограбление). Если мотивов несколько, перечисли через запятую. Если мотив не указан, верни "неизвестно".

**Правила:**
- Для связи: опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно".
- Для места: опирайся на явные указания (например, "в квартире") и классифицируй по указанным категориям. Если место неясно, укажи "другое".
- Для метода: опирайся на явные указания (например, "зарезал ножом") и классифицируй по указанным категориям. Если метод неясен, укажи "другое".
- Для мотива: извлеки мотивы на основе явных указаний или контекста (например, "ограбление" для кражи). Если мотив неясен, укажи "неизвестно".
- Ответ должен быть в формате:
  ```
  связь: <связь_1, связь_2, ... или неизвестно>
  место: <категория_1, категория_2, ... или другое>
  метод: <категория_1, категория_2, ... или другое>
  мотив: <мотив_1, мотив_2, ... или неизвестно>
  ```

**Примеры:**
- Текст: Иванов зарезал свою жену и её брата в квартире из ревности.
  Ответ:
  ```
  связь: супруг, родственник
  место: жилое помещение
  метод: холодное оружие
  мотив: ревность
  ```
- Текст: Двое обвиняемых избили незнакомца на улице ради кражи.
  Ответ:
  ```
  связь: незнакомец, незнакомец
  место: уличное пространство
  метод: физическое воздействие
  мотив: ограбление
  ```
- Текст: Сидоров ударил молотком коллегу в гараже из личной неприязни.
  Ответ:
  ```
  связь: коллега
  место: рабочая зона
  метод: тяжелые предметы
  мотив: личная неприязнь
  ```
- Текст: Кража в магазине, без указания жертв.
  Ответ:
  ```
  связь: неизвестно
  место: общественное место
  метод: другое
  мотив: имущество
  ```
- Текст: Петров задушил сожительницу и её подругу в подъезде из мести.
  Ответ:
  ```
  связь: сожитель, знакомый
  место: подъезд и прилегающие зоны
  метод: удушение
  мотив: месть
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }
    
    try:

        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("связь:"):
                result["relationship"] = line.replace("связь:", "").strip()
            elif line.startswith("место:"):
                result["location"] = line.replace("место:", "").strip()
            elif line.startswith("метод:"):
                result["method"] = line.replace("метод:", "").strip()
            elif line.startswith("мотив:"):
                result["motive"] = line.replace("мотив:", "").strip()
        

        valid_relationships = [
            "родственник", "супруг", "зять", "сожитель", "бывший супруг",
            "друг", "знакомый", "сосед", "коллега", "работник", "незнакомец",
            "брат", "отец", "сын", "дядя", "племянник", "неизвестно"
        ]
        relationships = [r.strip() for r in result["relationship"].split(",") if r.strip()]
        result["relationship"] = ", ".join([r if r in valid_relationships else "неизвестно" for r in relationships]) or "неизвестно"
        
       
        valid_locations = [
            "жилое помещение", "уличное пространство", "общественный транспорт",
            "общественное место", "подъезд и прилегающие зоны", "рабочая зона", "другое"
        ]
        locations = [loc.strip() for loc in result["location"].split(",") if loc.strip()]
        result["location"] = ", ".join([loc if loc in valid_locations else "другое" for loc in locations]) or "другое"
        
       
        valid_methods = [
            "физическое воздействие", "холодное оружие", "тяжелые предметы",
            "огнестрельное оружие", "удушение", "другое"
        ]
        methods = [meth.strip() for meth in result["method"].split(",") if meth.strip()]
        result["method"] = ", ".join([meth if meth in valid_methods else "другое" for meth in methods]) or "другое"
        
        
        valid_motives = ["личная неприязнь", "месть", "ревность", "имущество", "ограбление", "неизвестно"]
        motives = [m.strip() for m in result["motive"].split(",") if m.strip()]
        result["motive"] = ", ".join([m if m in valid_motives else "неизвестно" for m in motives]) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)


df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: x["relationship"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])

100%|██████████| 100/100 [05:18<00:00,  3.19s/it]

In [ ]:
mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


y_true_relationship = df_eval["relationship_between_accused_and_victim"]
y_pred_relationship = df_eval["predicted_relationship"]
relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)


y_true_location = df_eval["location2"]
y_pred_location = df_eval["predicted_location"]
location_accuracy = accuracy_score(y_true_location, y_pred_location)
location_precision, location_recall, location_f1, _ = precision_recall_fscore_support(
    y_true_location, y_pred_location, average="weighted", zero_division=0
)


y_true_method = df_eval["method2"]
y_pred_method = df_eval["predicted_method"]
method_accuracy = accuracy_score(y_true_method, y_pred_method)
method_precision, method_recall, method_f1, _ = precision_recall_fscore_support(
    y_true_method, y_pred_method, average="weighted", zero_division=0
)


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)


print("\nОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Место преступления):")
print(f"Accuracy:  {location_accuracy:.4f}")
print(f"Precision: {location_precision:.4f}")
print(f"Recall:    {location_recall:.4f}")
print(f"F1-score:  {location_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Метод преступления):")
print(f"Accuracy:  {method_accuracy:.4f}")
print(f"Precision: {method_precision:.4f}")
print(f"Recall:    {method_recall:.4f}")
print(f"F1-score:  {method_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")


print("\nПример предсказаний:")
print(df_eval[[
    "relationship_between_accused_and_victim", "predicted_relationship",
    "location2", "predicted_location",
    "method2", "predicted_method",
    "motive", "predicted_motive"
]].head())

ОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):
Accuracy:  0.5700
Precision: 0.5291
Recall:    0.5700
F1-score:  0.5457

ОЦЕНКА GPT-4o-mini (Место преступления):
Accuracy:  0.8900
Precision: 0.8907
Recall:    0.8900
F1-score:  0.8861

ОЦЕНКА GPT-4o-mini (Метод преступления):
Accuracy:  0.7500
Precision: 0.8170
Recall:    0.7500
F1-score:  0.7637

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.7692
Recall:    0.7018
F1-score:  0.7339

Пример предсказаний:
  relationship_between_accused_and_victim    predicted_relationship  \
0                                знакомый                  знакомый
1                                знакомый                  знакомый
2            ['неизвестно', 'неизвестно']  родственник, родственник
3                                работник                  работник
4                                знакомый                  знакомый

              location2                          predicted_location  \
0  уличное пространство                        уличное пространство
1  уличное пространство                        уличное пространство
2       жилое помещение                             жилое помещение
3       жилое помещение                             жилое помещение
4  уличное пространство  уличное пространство, уличное пространство

                  method2            predicted_method  \
0  физическое воздействие             холодное оружие
1    огнестрельное оружие        огнестрельное оружие
2                удушение  тяжелые предметы, удушение
3    огнестрельное оружие        огнестрельное оружие
4  физическое воздействие      физическое воздействие

                             motive  predicted_motive
0     ['личная неприязнь', 'месть']  личная неприязнь
1  ['личная неприязнь', 'ревность']          ревность
2           ['деньги', 'имущество']         имущество
3                  личная неприязнь  личная неприязнь
4                  личная неприязнь  личная неприязнь

In [ ]:
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)


mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "motive", "predicted_motive"
]].head())

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.8942
Recall:    0.8158
F1-score:  0.8532

Пример предсказаний:
                             motive  predicted_motive
0     ['личная неприязнь', 'месть']  личная неприязнь
1  ['личная неприязнь', 'ревность']          ревность
2           ['деньги', 'имущество']         имущество
3                  личная неприязнь  личная неприязнь
4                  личная неприязнь  личная неприязнь

In [ ]:
def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                return ', '.join([location_map.get(loc, 'другое') for loc in loc_list])
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                return ', '.join([method_map.get(meth, 'другое') for meth in meth_list])
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'

import ast
df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import ast

client = OpenAI(api_key='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')

df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()


def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                return ', '.join([location_map.get(loc, 'другое') for loc in loc_list])
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                return ', '.join(sorted([method_map.get(meth, 'другое') for meth in meth_list]))
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'


df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)


def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Связь между преступником и жертвой**: Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник, интимные отношения, сожитель). Если преступников несколько, перечисли связи для каждого преступника в порядке их упоминания, разделяя запятыми. Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > интимные отношения > незнакомец > неизвестно. Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг"). Если связь не указана, верни "неизвестно". Учти, что связь может быть любой, указанной в тексте.
2. **Место преступления**: Укажи место преступления в начальной форме в единственном числе (например, "квартира", "улица"). Если мест несколько, перечисли уникальные категории через запятую. Классифицируй место по категориям: жилое помещение (квартира, дом, дача, общежитие, хостел), уличное пространство (улица, двор, лес, берег озера, безлюдная местность), общественный транспорт (такси, автобус, поезд), общественное место (магазин, кафе, бар, рынок), подъезд и прилегающие зоны (подъезд, лестничная площадка, чердак), рабочая зона (гараж, база отдыха, склад, офис), другое. Верни название категории. Не повторяй одинаковые категории.
3. **Метод преступления**: Укажи метод преступления в начальной форме в единственном числе (например, "нож", "избиение"). Если методов несколько, перечисли уникальные категории через запятую. Классифицируй метод по категориям: физическое воздействие (например - избиение, удар предметом, скидывание с высоты), холодное оружие (например - нож, клинок, вилка, лопата, топор), тяжелые предметы (например - молоток, кирпич, полено), огнестрельное оружие (например - ружье, травматический пистолет, огнестрел), удушение (например - удушение, повешение), другое. Верни название категории.
4. **Мотив преступления**: Укажи мотивы (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство). Если мотивов несколько, перечисли через запятую. Если мотив не указан, верни "неизвестно". Учти, что мотивы могут быть любыми, указанными в тексте.

**Правила:**
- Для связи: опирайся на явные указания (например, "супруг", "знакомый", "интимные отношения") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Если связь неясна, укажи "неизвестно". Допускаются любые связи, упомянутые в тексте.
- Для места: опирайся на явные указания (например, "в квартире") и классифицируй по указанным категориям. Если место неясно, укажи "другое". Убедись, что одинаковые категории не повторяются.
- Для метода: опирайся на явные указания (например, "зарезал ножом") и классифицируй по указанным категориям. Если метод неясен, укажи "другое".
- Для мотива: извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь"). Если мотив неясен, укажи "неизвестно". Допускаются любые мотивы, упомянутые в тексте.
- Ответ должен быть в формате:
  ```
  связь: <связь_1, связь_2, ... или неизвестно>
  место: <категория_1, категория_2, ... или другое>
  метод: <категория_1, категория_2, ... или другое>
  мотив: <мотив_1, мотив_2, ... или неизвестно>
  ```

**Примеры:**
- Текст: Иванов зарезал свою жену и её брата в квартире из ревности.
  Ответ:
  ```
  связь: супруг, родственник
  место: жилое помещение
  метод: холодное оружие
  мотив: ревность
  ```
- Текст: Двое обвиняемых избили незнакомца на улице ради кражи.
  Ответ:
  ```
  связь: незнакомец, незнакомец
  место: уличное пространство
  метод: физическое воздействие
  мотив: ограбление
  ```
- Текст: Сидоров ударил молотком коллегу в гараже из личной неприязни.
  Ответ:
  ```
  связь: коллега
  место: рабочая зона
  метод: тяжелые предметы
  мотив: личная неприязнь
  ```
- Текст: Кража в магазине, без указания жертв.
  Ответ:
  ```
  связь: неизвестно
  место: общественное место
  метод: другое
  мотив: имущество
  ```
- Текст: Петров задушил сожительницу и её подругу в подъезде из мести.
  Ответ:
  ```
  связь: сожитель, знакомый
  место: подъезд и прилегающие зоны
  метод: удушение
  мотив: месть
  ```
- Текст: Обвиняемый избил человека, с которым у него были интимные отношения, на почве ссоры.
  Ответ:
  ```
  связь: интимные отношения
  место: другое
  метод: физическое воздействие
  мотив: личная неприязнь
  ```
- Текст: Двое обвиняемых напали на прохожего в такси и на улице, используя нож и кулаки.
  Ответ:
  ```
  связь: незнакомец, незнакомец
  место: общественный транспорт, уличное пространство
  метод: холодное оружие, физическое воздействие
  мотив: ограбление
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }
    
    try:
     
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("связь:"):
                result["relationship"] = line.replace("связь:", "").strip()
            elif line.startswith("место:"):
                result["location"] = line.replace("место:", "").strip()
            elif line.startswith("метод:"):
                result["method"] = line.replace("метод:", "").strip()
            elif line.startswith("мотив:"):
                result["motive"] = line.replace("мотив:", "").strip()
        
        
        relationships = [r.strip() for r in result["relationship"].split(",") if r.strip()]
        normalized_relationships = []
        for r in relationships:
            if r in ["супруга", "жена"]:
                r = "супруг"
            elif r in ["родственница", "сестра"]:
                r = "родственник"
            normalized_relationships.append(r)
        result["relationship"] = ", ".join(normalized_relationships) or "неизвестно"
        
        
        valid_locations = [
            "жилое помещение", "уличное пространство", "общественный транспорт",
            "общественное место", "подъезд и прилегающие зоны", "рабочая зона", "другое"
        ]
        locations = [loc.strip() for loc in result["location"].split(",") if loc.strip()]
        unique_locations = []
        for loc in locations:
            loc = loc if loc in valid_locations else "другое"
            if loc not in unique_locations:
                unique_locations.append(loc)
        result["location"] = ", ".join(unique_locations) or "другое"
        
        
        valid_methods = [
            "физическое воздействие", "холодное оружие", "тяжелые предметы",
            "огнестрельное оружие", "удушение", "другое"
        ]
        methods = [meth.strip() for meth in result["method"].split(",") if meth.strip()]
        normalized_methods = sorted([meth if meth in valid_methods else "другое" for meth in methods])
        result["method"] = ", ".join(normalized_methods) or "другое"
        
        
        motives = [m.strip() for m in result["motive"].split(",") if m.strip()]
        result["motive"] = ", ".join(motives) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)


df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: x["relationship"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])

100%|██████████| 100/100 [05:28<00:00,  3.29s/it]

In [ ]:
mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


df_eval["method2"] = df_eval["method"].apply(lambda x: ', '.join(sorted(categorize_method(x).split(', '))))


y_true_relationship = df_eval["relationship_between_accused_and_victim"]
y_pred_relationship = df_eval["predicted_relationship"]
relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)


y_true_location = df_eval["location2"]
y_pred_location = df_eval["predicted_location"]
location_accuracy = accuracy_score(y_true_location, y_pred_location)
location_precision, location_recall, location_f1, _ = precision_recall_fscore_support(
    y_true_location, y_pred_location, average="weighted", zero_division=0
)

y_true_method = df_eval["method2"]
y_pred_method = df_eval["predicted_method"]
method_accuracy = accuracy_score(y_true_method, y_pred_method)
method_precision, method_recall, method_f1, _ = precision_recall_fscore_support(
    y_true_method, y_pred_method, average="weighted", zero_division=0
)


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)


print("\nОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Место преступления):")
print(f"Accuracy:  {location_accuracy:.4f}")
print(f"Precision: {location_precision:.4f}")
print(f"Recall:    {location_recall:.4f}")
print(f"F1-score:  {location_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Метод преступления):")
print(f"Accuracy:  {method_accuracy:.4f}")
print(f"Precision: {method_precision:.4f}")
print(f"Recall:    {method_recall:.4f}")
print(f"F1-score:  {method_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "relationship_between_accused_and_victim", "predicted_relationship",
    "location2", "predicted_location",
    "method2", "predicted_method",
    "motive", "predicted_motive"
]].head())

ОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой):
Accuracy:  0.5300
Precision: 0.5551
Recall:    0.5300
F1-score:  0.5347

ОЦЕНКА GPT-4o-mini (Место преступления):
Accuracy:  0.8400
Precision: 0.9064
Recall:    0.8400
F1-score:  0.8664

ОЦЕНКА GPT-4o-mini (Метод преступления):
Accuracy:  0.7900
Precision: 0.8945
Recall:    0.7900
F1-score:  0.8229

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.8020
Recall:    0.7105
F1-score:  0.7535

Пример предсказаний:
  relationship_between_accused_and_victim    predicted_relationship  \
0                                знакомый                  знакомый
1                                знакомый                  сожитель
2            ['неизвестно', 'неизвестно']  родственник, родственник
3                                работник                  работник
4                                знакомый                  знакомый

              location2    predicted_location                 method2  \
0  уличное пространство  уличное пространство  физическое воздействие
1  уличное пространство  уличное пространство    огнестрельное оружие
2       жилое помещение       жилое помещение                удушение
3       жилое помещение       жилое помещение    огнестрельное оружие
4  уличное пространство  уличное пространство  физическое воздействие

                          predicted_method                            motive  \
0  физическое воздействие, холодное оружие     ['личная неприязнь', 'месть']
1                     огнестрельное оружие  ['личная неприязнь', 'ревность']
2               тяжелые предметы, удушение           ['деньги', 'имущество']
3                     огнестрельное оружие                  личная неприязнь
4                   физическое воздействие                  личная неприязнь

   predicted_motive
0  личная неприязнь
1          ревность
2         имущество
3  личная неприязнь
4  личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['корысть', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [ ]:
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)


mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "motive", "predicted_motive"
]].head())

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.9307
Recall:    0.8246
F1-score:  0.8744

Пример предсказаний:
                             motive  predicted_motive
0     ['личная неприязнь', 'месть']  личная неприязнь
1  ['личная неприязнь', 'ревность']          ревность
2           ['деньги', 'имущество']         имущество
3                  личная неприязнь  личная неприязнь
4                  личная неприязнь  личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['корысть', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import ast

client = OpenAI(api_key='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')

df_eval = dfff.iloc[0:].copy()  

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"Статья \d+ УК РФ", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def categorize_relationship(relationships):
    relationship_map = {
        'родственник': 'семейные', 'супруг': 'семейные', 'зять': 'семейные',
        'брат': 'семейные', 'отец': 'семейные', 'сын': 'семейные',
        'дядя': 'семейные', 'племянник': 'семейные', 'сестра': 'семейные',
        'супруга': 'семейные', 'родственница': 'семейные',
        'сожитель': 'близкие', 'бывший супруг': 'близкие', 'друг': 'близкие',
        'интимные отношения': 'близкие',
        'коллега': 'профессиональные', 'работник': 'профессиональные',
        'начальник': 'профессиональные', 'подчиненный': 'профессиональные',
        'сосед': 'соседские',
        'знакомый': 'случайные', 'незнакомец': 'случайные',
        'неизвестно': 'неизвестно'
    }
    if isinstance(relationships, str):
        if relationships.startswith('[') and relationships.endswith(']'):
            try:
                rel_list = ast.literal_eval(relationships)
                return ', '.join([relationship_map.get(rel, 'неизвестно') for rel in rel_list])
            except:
                return relationship_map.get(relationships, 'неизвестно')
        return relationship_map.get(relationships, 'неизвестно')
    return 'неизвестно'


def categorize_location(locations):
    location_map = {
        'квартира': 'жилое помещение', 'дом': 'жилое помещение', 'дача': 'жилое помещение',
        'общежитие': 'жилое помещение', 'хостел': 'жилое помещение',
        'улица': 'уличное пространство', 'двор': 'уличное пространство',
        'безлюдная местность': 'уличное пространство', 'берег озера': 'уличное пространство',
        'лес': 'уличное пространство',
        'такси': 'общественный транспорт', 'автобус': 'общественный транспорт',
        'поезд': 'общественный транспорт',
        'магазин': 'общественное место', 'кафе': 'общественное место',
        'бар': 'общественное место', 'рынок': 'общественное место',
        'подъезд': 'подъезд и прилегающие зоны', 'лестничная площадка': 'подъезд и прилегающие зоны',
        'чердак': 'подъезд и прилегающие зоны',
        'гараж': 'рабочая зона', 'база отдыха': 'рабочая зона', 'склад': 'рабочая зона',
        'офис': 'рабочая зона'
    }
    if isinstance(locations, str):
        if locations.startswith('[') and locations.endswith(']'):
            try:
                loc_list = ast.literal_eval(locations)
                return ', '.join([location_map.get(loc, 'другое') for loc in loc_list])
            except:
                return location_map.get(locations, 'другое')
        return location_map.get(locations, 'другое')
    return 'другое'

def categorize_method(methods):
    method_map = {
        'избиение': 'физическое воздействие', 'удар предметом': 'физическое воздействие',
        'скидывание с высоты': 'физическое воздействие',
        'нож': 'холодное оружие', 'клинок': 'холодное оружие', 'вилка': 'холодное оружие',
        'лопата': 'холодное оружие', 'топор': 'холодное оружие',
        'молоток': 'тяжелые предметы', 'кирпич': 'тяжелые предметы', 'полено': 'тяжелые предметы',
        'ружье': 'огнестрельное оружие', 'травматический пистолет': 'огнестрельное оружие',
        'огнестрел': 'огнестрельное оружие',
        'удушение': 'удушение', 'повешение': 'удушение'
    }
    if isinstance(methods, str):
        if methods.startswith('[') and methods.endswith(']'):
            try:
                meth_list = ast.literal_eval(methods)
                return ', '.join(sorted([method_map.get(meth, 'другое') for meth in meth_list]))
            except:
                return method_map.get(methods, 'другое')
        return method_map.get(methods, 'другое')
    return 'другое'

df_eval['location2'] = df_eval['location'].apply(categorize_location)
df_eval['method2'] = df_eval['method'].apply(categorize_method)
df_eval['relationship_between_accused_and_victim2'] = df_eval['relationship_between_accused_and_victim'].apply(categorize_relationship)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию:
1. **Связь между преступником и жертвой**: Укажи категорию связи для каждого преступника в порядке их упоминания, разделяя запятыми. Категории: семейные (родственник, супруг, зять, брат, отец, сын, дядя, племянник, сестра, супруга), близкие (сожитель, бывший супруг, друг, интимные отношения), профессиональные (коллега, работник, начальник, подчиненный), соседские (сосед), случайные (знакомый, незнакомец), неизвестно. Если у преступника несколько жертв, выбери наиболее значимую категорию по приоритету: семейные > близкие > профессиональные > соседские > случайные > неизвестно. Если связь не указана, верни "неизвестно".
2. **Место преступления**: Укажи место преступления в начальной форме в единственном числе (например, "квартира", "улица"). Если мест несколько, перечисли уникальные категории через запятую. Классифицируй место по категориям: жилое помещение (квартира, дом, дача, общежитие, хhostел), уличное пространство (улица, двор, лес, берег озера, безлюдная местность), общественный транспорт (такси, автобус, поезд), общественное место (магазин, кафе, бар, рынок), подъезд и прилегающие зоны (подъезд, лестничная площадка, чердак), рабочая зона (гараж, база отдыха, склад, офис), другое. Верни название категории. Не повторяй одинаковые категории.
3. **Метод преступления**: Укажи метод преступления в начальной форме в единственном числе (например, "нож", "избиение"). Если методов несколько, перечисли уникальные категории через запятую. Классифицируй метод по категориям: физическое воздействие (избиение, удар предметом, скидывание с высоты), холодное оружие (нож, клинок, вилка, лопата, топор), тяжелые предметы (молоток, кирпич, полено), огнестрельное оружие (ружье, травматический пистолет, огнестрел), удушение (удушение, повешение), другое. Верни название категории.
4. **Мотив преступления**: Укажи мотивы (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство). Если мотивов несколько, перечисли через запятую. Если мотив не указан, верни "неизвестно". Допускаются любые мотивы, упомянутые в тексте.

**Правила:**
- Для связи: опирайся на явные указания (например, "супруг", "знакомый", "интимные отношения") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников. Возвращай категорию связи, а не конкретное значение.
- Для места: опирайся на явные указания (например, "в квартире") и классифицируй по указанным категориям. Если место неясно, укажи "другое". Убедись, что одинаковые категории не повторяются.
- Для метода: опирайся на явные указания (например, "зарезал ножом") и классифицируй по указанным категориям. Если метод неясен, укажи "другое".
- Для мотива: извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь"). Если мотив неясен, укажи "неизвестно".
- Ответ должен быть в формате:
  ```
  связь: <категория_1, категория_2, ... или неизвестно>
  место: <категория_1, категория_2, ... или другое>
  метод: <категория_1, категория_2, ... или другое>
  мотив: <мотив_1, мотив_2, ... или неизвестно>
  ```

**Примеры:**
- Текст: Иванов зарезал свою жену и её брата в квартире из ревности.
  Ответ:
  ```
  связь: семейные
  место: жилое помещение
  метод: холодное оружие
  мотив: ревность
  ```
- Текст: Двое обвиняемых избили незнакомца на улице ради кражи.
  Ответ:
  ```
  связь: случайные, случайные
  место: уличное пространство
  метод: физическое воздействие
  мотив: ограбление
  ```
- Текст: Сидоров ударил молотком коллегу в гараже из личной неприязни.
  Ответ:
  ```
  связь: профессиональные
  место: рабочая зона
  метод: тяжелые предметы
  мотив: личная неприязнь
  ```
- Текст: Кража в магазине, без указания жертв.
  Ответ:
  ```
  связь: неизвестно
  место: общественное место
  метод: другое
  мотив: имущество
  ```
- Текст: Петров задушил сожительницу и её подругу в подъезде из мести.
  Ответ:
  ```
  связь: близкие, случайные
  место: подъезд и прилегающие зоны
  метод: удушение
  мотив: месть
  ```
- Текст: Обвиняемый избил человека, с которым у него были интимные отношения, на почве ссоры.
  Ответ:
  ```
  связь: близкие
  место: другое
  метод: физическое воздействие
  мотив: личная неприязнь
  ```
- Текст: Двое обвиняемых напали на прохожего в такси и на улице, используя нож и кулаки.
  Ответ:
  ```
  связь: случайные, случайные
  место: общественный транспорт, уличное пространство
  метод: холодное оружие, физическое воздействие
  мотив: ограбление
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0,
                max_tokens=150
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }

def normalize_prediction(text):
    result = {
        "relationship": "неизвестно",
        "location": "другое",
        "method": "другое",
        "motive": "неизвестно"
    }
    
    try:

        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("связь:"):
                result["relationship"] = line.replace("связь:", "").strip()
            elif line.startswith("место:"):
                result["location"] = line.replace("место:", "").strip()
            elif line.startswith("метод:"):
                result["method"] = line.replace("метод:", "").strip()
            elif line.startswith("мотив:"):
                result["motive"] = line.replace("мотив:", "").strip()
        
       
        valid_relationships = [
            "семейные", "близкие", "профессиональные", "соседские", "случайные", "неизвестно"
        ]
        relationships = [r.strip() for r in result["relationship"].split(",") if r.strip()]
        result["relationship"] = ", ".join([r if r in valid_relationships else "неизвестно" for r in relationships]) or "неизвестно"
        
        
        valid_locations = [
            "жилое помещение", "уличное пространство", "общественный транспорт",
            "общественное место", "подъезд и прилегающие зоны", "рабочая зона", "другое"
        ]
        locations = [loc.strip() for loc in result["location"].split(",") if loc.strip()]
        unique_locations = []
        for loc in locations:
            loc = loc if loc in valid_locations else "другое"
            if loc not in unique_locations:
                unique_locations.append(loc)
        result["location"] = ", ".join(unique_locations) or "другое"
        
       
        valid_methods = [
            "физическое воздействие", "холодное оружие", "тяжелые предметы",
            "огнестрельное оружие", "удушение", "другое"
        ]
        methods = [meth.strip() for meth in result["method"].split(",") if meth.strip()]
        normalized_methods = sorted([meth if meth in valid_methods else "другое" for meth in methods])
        result["method"] = ", ".join(normalized_methods) or "другое"
        
        
        motives = [m.strip() for m in result["motive"].split(",") if m.strip()]
        result["motive"] = ", ".join(motives) or "неизвестно"
        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["clean_description"] = df_eval["description"].apply(clean_text)
df_eval["predictions"] = df_eval["clean_description"].progress_apply(classify_with_gpt4)


df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: x["relationship"])
df_eval["predicted_location"] = df_eval["predictions"].apply(lambda x: x["location"])
df_eval["predicted_method"] = df_eval["predictions"].apply(lambda x: x["method"])
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])

100%|██████████| 100/100 [05:22<00:00,  3.23s/it]

In [ ]:

mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))

df_eval["method2"] = df_eval["method"].apply(lambda x: ', '.join(sorted(categorize_method(x).split(', '))))


y_true_relationship = df_eval["relationship_between_accused_and_victim2"]
y_pred_relationship = df_eval["predicted_relationship"]
relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)


y_true_location = df_eval["location2"]
y_pred_location = df_eval["predicted_location"]
location_accuracy = accuracy_score(y_true_location, y_pred_location)
location_precision, location_recall, location_f1, _ = precision_recall_fscore_support(
    y_true_location, y_pred_location, average="weighted", zero_division=0
)


y_true_method = df_eval["method2"]
y_pred_method = df_eval["predicted_method"]
method_accuracy = accuracy_score(y_true_method, y_pred_method)
method_precision, method_recall, method_f1, _ = precision_recall_fscore_support(
    y_true_method, y_pred_method, average="weighted", zero_division=0
)

motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)


print("\nОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой, категории):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Место преступления):")
print(f"Accuracy:  {location_accuracy:.4f}")
print(f"Precision: {location_precision:.4f}")
print(f"Recall:    {location_recall:.4f}")
print(f"F1-score:  {location_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Метод преступления):")
print(f"Accuracy:  {method_accuracy:.4f}")
print(f"Precision: {method_precision:.4f}")
print(f"Recall:    {method_recall:.4f}")
print(f"F1-score:  {method_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "relationship_between_accused_and_victim2", "predicted_relationship",
    "location2", "predicted_location",
    "method2", "predicted_method",
    "motive", "predicted_motive"
]].head())

ОЦЕНКА GPT-4o-mini (Связь между преступником и жертвой, категории):
Accuracy:  0.4000
Precision: 0.6689
Recall:    0.4000
F1-score:  0.3753

ОЦЕНКА GPT-4o-mini (Место преступления):
Accuracy:  0.8400
Precision: 0.9064
Recall:    0.8400
F1-score:  0.8664

ОЦЕНКА GPT-4o-mini (Метод преступления):
Accuracy:  0.7900
Precision: 0.9229
Recall:    0.7900
F1-score:  0.8229

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Precision: 0.7757
Recall:    0.7281
F1-score:  0.7511

Пример предсказаний:
  relationship_between_accused_and_victim2  predicted_relationship  \
0                                случайные                 близкие
1                                случайные                 близкие
2                   неизвестно, неизвестно  неизвестно, неизвестно
3                         профессиональные        профессиональные
4                                случайные                 близкие

              location2            predicted_location                 method2  \
0  уличное пространство          уличное пространство  физическое воздействие
1  уличное пространство          уличное пространство    огнестрельное оружие
2       жилое помещение               жилое помещение                удушение
3       жилое помещение               жилое помещение    огнестрельное оружие
4  уличное пространство  уличное пространство, другое  физическое воздействие

                          predicted_method                            motive  \
0  физическое воздействие, холодное оружие     ['личная неприязнь', 'месть']
1                     огнестрельное оружие  ['личная неприязнь', 'ревность']
2               тяжелые предметы, удушение           ['деньги', 'имущество']
3                     огнестрельное оружие                  личная неприязнь
4                   физическое воздействие                  личная неприязнь

              predicted_motive
0             личная неприязнь
1                     ревность
2                    имущество
3  личная неприязнь, имущество
4             личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['корысть', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [254]:
file_path3 = 'df_with_marking_final_new.csv'
dfsrok = pd.read_csv(file_path3, on_bad_lines='warn')
dfsrok.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,preamble,description,sentence,victim_count,killer_count,extracted_prison_term,prison_term_re,num_victims,has_woman_victim,has_man_victim
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...,1,1,NaN,6.0,1,0,1
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...,1,1,NaN,8.0,1,0,1
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...,2,2,NaN,2017.0,2,1,0
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...,1,1,NaN,3.0,1,0,1
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...,1,1,9.25,9.0,1,0,1

In [258]:
file_path4 = 'verdicts_with_c.csv'
dfac = pd.read_csv(file_path4, on_bad_lines='warn')

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support


client = OpenAI(api_key='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')

df_eval2 = dfac.iloc[0:].copy()  

tqdm.pandas()

# Очистка текста
# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации о сроке заключения из описания преступления.

Твоя задача — извлечь из текста финальный срок лишения свободы для каждого преступника в порядке их упоминания. 

**Правила:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Если преступников несколько, перечисли сроки через запятую в порядке упоминания преступников.
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан или наказание не связано с лишением свободы (например, штраф), верни 0.0 для этого преступника.
- Если в тексте нет информации о сроке, верни 0.0 для каждого преступника.
- Ответ должен быть в формате:
  ```
  срок: <срок_1, срок_2, ... или 0.0>
  ```

**Примеры:**
- Текст: Иванов был приговорен к 4 годам 10 месяцам лишения свободы.
  Ответ:
  ```
  срок: 4.83
  ```
- Текст: Петров и Сидоров получили 3 года и 5 лет 6 месяцев соответственно.
  Ответ:
  ```
  срок: 3.00, 5.50
  ```
- Текст: Обвиняемый получил штраф.
  Ответ:
  ```
  срок: 0.0
  ```
- Текст: Двое обвиняемых напали на прохожего, но срок не указан.
  Ответ:
  ```
  срок: 0.0, 0.0
  ```
- Текст: Суд приговорил Иванова к 7 годам, но после апелляции срок сократили до 5 лет.
  Ответ:
  ```
  срок: 5.00
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return "0.0"


def normalize_prediction(text):
    try:
        
        match = re.search(r"срок:\s*(.+)", text)
        if not match:
            return "0.0"
        
        terms = match.group(1).strip().split(",")
        normalized_terms = []
        for term in terms:
            term = term.strip()
            try:
                
                value = float(term)
                
                normalized_terms.append(f"{value:.2f}")
            except ValueError:
                normalized_terms.append("0.0")
        
        return ", ".join(normalized_terms) or "0.0"
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
        return "0.0"


df_eval2["predicted_prison_term"] = df_eval2["sentence"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [01:44<00:00,  1.04s/it]

In [ ]:
import pandas as pd
import ast  

def format_prison_term(value):
    
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)  
            return ', '.join([f"{float(x):.2f}" for x in numbers])
        except:
            return value
    
    else:
        try:
            return f"{float(value):.2f}"
        except:
            return value

df_eval2['prison_term2'] = df_eval2['prison_term'].apply(format_prison_term)


print(df_eval2['prison_term2'].head())

0            6.50
1            8.08
2    18.00, 20.00
3            3.00
4            9.25
Name: prison_term2, dtype: object

In [ ]:
y_true_prison_term = df_eval2["prison_term2"]
y_pred_prison_term = df_eval2["predicted_prison_term"]

accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval2[["prison_term2", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.7600
Precision: 0.8124
Recall:    0.7600
F1-score:  0.7760

Пример предсказаний:
   prison_term2 predicted_prison_term
0          6.50                  6.50
1          8.08                  8.08
2  18.00, 20.00          18.00, 20.00
3          3.00                  3.00
4          9.25                  9.25

In [418]:
df_eval2.loc[9, "prison_term"] = '[20, 18]'
df_eval2.loc[12, "prison_term"] = '20.0'
df_eval2.loc[16, "prison_term"] = '14.0'
df_eval2.loc[25, "prison_term"] = '15.0'
df_eval2.loc[26, "prison_term"] = '9.0' # тут почему-то еще 0 у меня
df_eval2.loc[28, "prison_term"] = '7.0' 
df_eval2.loc[41, "prison_term"] = '[18.0, 19.08]'
# 41 убрать 3 чела не по 105
# 44 и 69 81 у меня 0 а надо нан - там данные изьяты
# 79 у меня 10 месяцев а не дней
# 86 вопрос точности сколько 3 идет после 8 для 1 месяца
df_eval2.loc[45, "prison_term"] = '10.67'
df_eval2.loc[53, "prison_term"] = '8.0'
df_eval2.loc[59, "prison_term"] = '8.5'
df_eval2.loc[65, "prison_term"] = '11'
df_eval2.loc[71, "prison_term"] = '9.08'
df_eval2.loc[74, "prison_term"] = '6.5'
df_eval2.loc[84, "prison_term"] = '7.25'
df_eval2.loc[85, "prison_term"] = '6.58'
df_eval2.loc[91, "prison_term"] = '10'
df_eval2.loc[92, "prison_term"] = '9' # тут почему-то еще 0 у меня
df_eval2.loc[96, "prison_term"] = '13'
df_eval2.loc[97, "prison_term"] = '9'

In [ ]:
import pandas as pd
import ast  

def format_prison_term(value):
    
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)  
            return ', '.join([f"{float(x):.2f}" for x in numbers])
        except:
            return value
    
    else:
        try:
            return f"{float(value):.2f}"
        except:
            return value

df_eval2['prison_term2'] = df_eval2['prison_term'].apply(format_prison_term)
print(df_eval2['prison_term2'].head())

0            6.50
1            8.08
2    18.00, 20.00
3            3.00
4            9.25
Name: prison_term2, dtype: object

In [ ]:
y_true_prison_term = df_eval2["prison_term2"]
y_pred_prison_term = df_eval2["predicted_prison_term"]

accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval2[["prison_term2", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.9200
Precision: 0.9500
Recall:    0.9200
F1-score:  0.9340

Пример предсказаний:
   prison_term2 predicted_prison_term
0          6.50                  6.50
1          8.08                  8.08
2  18.00, 20.00          18.00, 20.00
3          3.00                  3.00
4          9.25                  9.25

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

client = OpenAI(api_key='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')

df_eval2 = dfac.iloc[0:].copy()  

tqdm.pandas()

# Очистка текста
# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"Статья \d+ УК РФ", "", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации о сроке заключения из описания преступления.

Твоя задача — извлечь из текста финальный срок лишения свободы для каждого преступника в порядке их упоминания, но только для тех, в отношении которых упоминается статья 105 УК РФ. 

**Правила:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Если статья 105 УК РФ не упоминается в тексте, не возвращай никаких сроков (верни пустую строку).
- Если преступников несколько, перечисли сроки через запятую в порядке упоминания преступников.
- Преобразуй сроки в десятичные числа:
  - 1 год = 1.0
  - 1 месяц = 0.083
  - 1 день = 0.00274 (1/365 года)
  - Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83
  - Пример: "три года пять дней" → 3.01
- Если срок не указан явно (например, "<данные изъяты>", "лишения свободы сроком №", или наказание не связано с лишением свободы, например, штраф), верни пустую строку для этого преступника.
- Если в тексте нет информации о сроке или нет упоминания статьи 105 УК РФ, верни пустую строку.
- Ответ должен быть в формате:
  ```
  срок: <срок_1, срок_2, ... или пустая строка>
  ```

**Примеры:**
- Текст: Иванов был приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ.
  Ответ:
  ```
  срок: 4.83
  ```
- Текст: Петров и Сидоров получили 3 года и 5 лет 6 месяцев соответственно по статье 105 УК РФ.
  Ответ:
  ```
  срок: 3.00, 5.50
  ```
- Текст: Обвиняемый получил штраф по статье 105 УК РФ.
  Ответ:
  ```
  срок: 
  ```
- Текст: Двое обвиняемых напали на прохожего, <данные изъяты> по статье 105 УК РФ.
  Ответ:
  ```
  срок: , 
  ```
- Текст: Суд приговорил Иванова к 7 годам, но после апелляции срок сократили до 5 лет по статье 105 УК РФ.
  Ответ:
  ```
  срок: 5.00
  ```
- Текст: Иванов получил 3 года по статье 158 УК РФ.
  Ответ:
  ```
  срок: 
  ```
- Текст: Иванов получил лишения свободы сроком № по статье 105 УК РФ.
  Ответ:
  ```
  срок: 
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return ""


def normalize_prediction(text):
    try:
        
        match = re.search(r"срок:\s*(.+)?", text)
        if not match or not match.group(1):
            return ""
        
        terms = match.group(1).strip().split(",")
        normalized_terms = []
        for term in terms:
            term = term.strip()
            try:
                
                value = float(term)
                
                normalized_terms.append(f"{value:.2f}")
            except ValueError:
                normalized_terms.append("")
        
        return ", ".join(normalized_terms)
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
        return ""

df_eval2["predicted_prison_term"] = df_eval2["sentence"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [01:44<00:00,  1.05s/it]

In [419]:
def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)  
            return ', '.join([f"{float(x):.2f}" for x in numbers])
        except:
            return value
    else:
        try:
            return f"{float(value):.2f}"
        except:
            return value


df_eval2['prison_term2'] = df_eval2['prison_term'].apply(format_prison_term)

print(df_eval2['prison_term2'].head())

0            6.50
1            8.08
2    18.00, 20.00
3            3.00
4            9.25
Name: prison_term2, dtype: object

In [420]:
y_true_prison_term = df_eval2["prison_term2"]
y_pred_prison_term = df_eval2["predicted_prison_term"]

accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval2[["prison_term2", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.8100
Precision: 0.9000
Recall:    0.8100
F1-score:  0.8470

Пример предсказаний:
   prison_term2 predicted_prison_term
0          6.50                  6.50
1          8.08                  8.08
2  18.00, 20.00          18.00, 20.00
3          3.00
4          9.25                  9.25

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support


client = OpenAI(api_key='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')

df_eval2 = dfac.iloc[0:].copy()  

tqdm.pandas()

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации о сроке заключения из описания преступления.

Твоя задача — извлечь из текста финальный срок лишения свободы для каждого преступника в порядке их упоминания. 

**Правила:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Если преступников несколько, перечисли сроки через запятую в порядке упоминания преступников. Если у какого-нибудь преступника нет упоминания статьи 105 УК РФ или наказание не связано с лишением свободы то выводить для него значение не надо.
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.083. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан или наказание не связано с лишением свободы (например, штраф) или у преступника нет упоминания статьи 105 УК РФ, верни 'nan' для этого преступника.
- Если в тексте нет информации о сроке, верни 'nan'
- Ответ должен быть в формате:
  ```
  срок: <срок_1, срок_2, ... или 0.0>
  ```

**Примеры:**
- Текст: Иванов был приговорен к 4 годам 10 месяцам лишения свободы.
  Ответ:
  ```
  срок: 4.83
  ```
- Текст: Петров и Сидоров получили 3 года и 5 лет 6 месяцев соответственно.
  Ответ:
  ```
  срок: 3.00, 5.50
  ```
- Текст: Обвиняемый получил штраф.
  Ответ:
  ```
  срок: nan
  ```
- Текст: Двое обвиняемых напали на прохожего, но срок не указан.
  Ответ:
  ```
  срок: nan
  ```
- Текст: Суд приговорил Иванова к 7 годам, но после апелляции срок сократили до 5 лет.
  Ответ:
  ```
  срок: 5.00
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(clean_text(text))
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return 'nan'

def normalize_prediction(text):
    try:
        
        match = re.search(r"срок:\s*(.+)", text)
        if not match:
            return ""
        
        terms = match.group(1).strip().split(",")
        normalized_terms = []
        for term in terms:
            term = term.strip()
            try:
                
                value = float(term)
                
                normalized_terms.append(f"{value:.2f}")
            except ValueError:
                normalized_terms.append('nan')
        
        return ", ".join(normalized_terms) or 'nan'
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
        return 'nan'


df_eval2["predicted_prison_term"] = df_eval2["sentence"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [01:39<00:00,  1.01it/s]

In [459]:
df_eval2.loc[9, "prison_term"] = '[20, 18]'
df_eval2.loc[12, "prison_term"] = '20.0'
df_eval2.loc[16, "prison_term"] = '14.0'
df_eval2.loc[25, "prison_term"] = '15.0'
df_eval2.loc[26, "prison_term"] = '9.0' # тут почему-то еще 0 у меня
df_eval2.loc[28, "prison_term"] = '7.0' 
df_eval2.loc[41, "prison_term"] = '[18.0, 19.08]'
# 41 убрать 3 чела не по 105
# 44 и 69 81 у меня 0 а надо нан - там данные изьяты
# 79 у меня 10 месяцев а не дней
# 86 вопрос точности сколько 3 идет после 8 для 1 месяца
df_eval2.loc[45, "prison_term"] = '10.67'
df_eval2.loc[53, "prison_term"] = '8.0'
df_eval2.loc[59, "prison_term"] = '8.5'
df_eval2.loc[65, "prison_term"] = '11'
df_eval2.loc[71, "prison_term"] = '9.08'
df_eval2.loc[74, "prison_term"] = '6.5'
df_eval2.loc[84, "prison_term"] = '7.25'
df_eval2.loc[85, "prison_term"] = '6.58'
df_eval2.loc[91, "prison_term"] = '10'
df_eval2.loc[92, "prison_term"] = '9' # тут почему-то еще 0 у меня
df_eval2.loc[96, "prison_term"] = '13'
df_eval2.loc[97, "prison_term"] = '9'

In [460]:
def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)  
            return ', '.join([f"{float(x):.2f}" for x in numbers])
        except:
            return value
    else:
        try:
            return f"{float(value):.2f}"
        except:
            return value


df_eval2['prison_term2'] = df_eval2['prison_term'].apply(format_prison_term)

print(df_eval2['prison_term2'].head())

0            6.50
1            8.08
2    18.00, 20.00
3            3.00
4            9.25
Name: prison_term2, dtype: object

In [461]:
y_true_prison_term = df_eval2["prison_term2"]
y_pred_prison_term = df_eval2["predicted_prison_term"]

accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-score:  {f1:.4f}")

print("\nПример предсказаний:")
print(df_eval2[["prison_term2", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.8700
Precision: 0.9075
Recall:    0.8700
F1-score:  0.8783

Пример предсказаний:
   prison_term2 predicted_prison_term
0          6.50                  6.50
1          8.08                  8.08
2  18.00, 20.00          18.00, 20.00
3          3.00                   nan
4          9.25                  9.25

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import ast
import numpy as np


client = OpenAI(api_key='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')

df_eval = dfac.iloc[0:].copy()  

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_eval["combined_text"] = df_eval["preamble"].str.cat(df_eval["sentence"], sep=" ").apply(clean_text)

def create_prompt(text):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ:
1. Пол обвиняемого (мужчина или женщина).
2. Были ли у обвиняемого судимости ранее.
3. Финальный срок лишения свободы.

**Правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ. Если статья 105 не упоминается для обвиняемого, не возвращай никаких данных для него (ни пол, ни судимости, ни срок).
- Если обвиняемых несколько, возвращай значения для каждого в порядке их упоминания в тексте, разделяя запятыми.
- Количество значений для пола, судимостей и сроков должно совпадать: если обвиняемый не связан со статьей 105, он исключается из всех трех признаков.
- Если статья 105 не упоминается в тексте вообще, верни пустые строки для пола и судимостей, и nan для срока.

**Правила для пола:**
- Если есть явное указание (например, "мужчина", "женщина", мужские/женские имена, местоимения "он"/"она"), укажи "мужчина" или "женщина".
- Если информации нет, укажи "неизвестно".
- Для нескольких обвиняемых возвращай список: [<мужчина/женщина/неизвестно>, ...].

**Правила для судимостей:**
- Если есть явное указание (например, "ранее судим", "имеет судимость"), укажи "да".
- Если указано отсутствие (например, "не судим"), укажи "нет".
- Если информации нет, укажи "нет".
- Для нескольких обвиняемых возвращай список: [<да/нет>, ...].

**Правила для срока лишения свободы:**
- Извлеки только финальный срок лишения свободы (например, после апелляций или окончательного приговора).
- Преобразуй сроки в десятичные числа: 1 год = 1.0, 1 месяц = 0.0833. Округли до двух знаков после запятой.
  - Пример: "четыре года десять месяцев" → 4.83.
  - Пример: "три года" → 3.00.
- Если срок не указан, не может быть определен (например, вместо конкретных чисел написано "<данные изъяты>"), или наказание не связано с лишением свободы (например, штраф), верни nan для этого обвиняемого.
- Если для нескольких обвиняемых есть сроки, включай только тех, у кого срок больше 0 и не nan, в порядке упоминания.
- Если информация о сроке отсутствует для всех обвиняемых, верни nan (по количеству обвиняемых).
- Для нескольких обвиняемых возвращай список: [<срок_1, срок_2, ...>] только для ненулевых сроков.

**Формат ответа:**
```
пол: <мужчина/женщина/неизвестно или [мужчина/женщина/неизвестно, ...] или пустая строка>
судимости: <да/нет или [да/нет, ...] или пустая строка>
срок: <число или [число, ...] или nan>
```

**Примеры:**
- Текст: Иванов, ранее судимый, приговорен к 4 годам 10 месяцам лишения свободы по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: да
  срок: 4.83
  ```

- Текст: Обвиняемый получил штраф по статье 105 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: nan
  ```
- Текст: Иванов и Петрова, ранее судимые, <данные изъяты> по статье 105 УК РФ.
  Ответ:
  ```
  пол: [мужчина, женщина]
  судимости: [да, да]
  срок: nan, nan
  ```

- Текст: Петров получил 3 года по статье 105 УК РФ, Сидоров — 3 года по статье 158 УК РФ.
  Ответ:
  ```
  пол: мужчина
  судимости: нет
  срок: 3.00
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(text, retries=3):
    prompt = create_prompt(text)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {"gender": "", "prior_convictions": "", "prison_term": "nan"}

def normalize_prediction(text):
    result = {"gender": "", "prior_convictions": "", "prison_term": "nan"}
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("пол:"):
                gender_part = line.replace("пол:", "").strip()
                if gender_part.startswith("[") and gender_part.endswith("]"):
                    gender_values = [v.strip() for v in gender_part[1:-1].split(",") if v.strip()]
                    result["gender"] = [v if v in ["мужчина", "женщина", "неизвестно"] else "неизвестно" for v in gender_values]
                else:
                    result["gender"] = gender_part if gender_part in ["мужчина", "женщина", "неизвестно", ""] else "неизвестно"
                    
            elif line.startswith("судимости:"):
                convictions_part = line.replace("судимости:", "").strip()
                if convictions_part.startswith("[") and convictions_part.endswith("]"):
                    convictions_values = [v.strip() for v in convictions_part[1:-1].split(",") if v.strip()]
                    result["prior_convictions"] = [v if v in ["да", "нет"] else "нет" for v in convictions_values]
                else:
                    result["prior_convictions"] = convictions_part if convictions_part in ["да", "нет", ""] else "нет"
                    
            elif line.startswith("срок:"):
                prison_term_part = line.replace("срок:", "").strip()
                if prison_term_part == "nan":
                    result["prison_term"] = "nan"
                elif prison_term_part.startswith("[") and prison_term_part.endswith("]"):
                    terms = [v.strip() for v in prison_term_part[1:-1].split(",") if v.strip()]
                    normalized_terms = []
                    for term in terms:
                        try:
                            value = float(term)
                            if value > 0:
                                normalized_terms.append(f"{value:.2f}")
                        except ValueError:
                            continue  
                    result["prison_term"] = normalized_terms if normalized_terms else "nan"
                else:
                    try:
                        value = float(prison_term_part)
                        if value > 0:
                            result["prison_term"] = f"{value:.2f}"
                        else:
                            result["prison_term"] = "nan"
                    except ValueError:
                        result["prison_term"] = "nan"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["predictions"] = df_eval["combined_text"].progress_apply(classify_with_gpt4)

100%|██████████| 100/100 [02:17<00:00,  1.37s/it]

In [ ]:
df_eval["predicted_gender"] = df_eval["predictions"].apply(lambda x: ", ".join(x["gender"]) if isinstance(x["gender"], list) else x["gender"])
df_eval["predicted_prior_convictions"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prior_convictions"]) if isinstance(x["prior_convictions"], list) else x["prior_convictions"])
df_eval["predicted_prison_term"] = df_eval["predictions"].apply(lambda x: ", ".join(x["prison_term"]) if isinstance(x["prison_term"], list) else x["prison_term"])

In [482]:
df_eval.loc[9, "prison_term"] = '[20, 18]'
df_eval.loc[12, "prison_term"] = '20.0'
df_eval.loc[16, "prison_term"] = '14.0'
df_eval.loc[25, "prison_term"] = '15.0'
df_eval.loc[26, "prison_term"] = '9.0' # тут почему-то еще 0 у меня
df_eval.loc[28, "prison_term"] = '7.0' 
df_eval.loc[41, "prison_term"] = '[18.0, 19.08]'
# 41 убрать 3 чела не по 105
# 44 и 69 81 у меня 0 а надо нан - там данные изьяты
# 79 у меня 10 месяцев а не дней
# 86 вопрос точности сколько 3 идет после 8 для 1 месяца
df_eval.loc[45, "prison_term"] = '10.67'
df_eval.loc[53, "prison_term"] = '8.0'
df_eval.loc[59, "prison_term"] = '8.5'
df_eval.loc[65, "prison_term"] = '11'
df_eval.loc[71, "prison_term"] = '9.08'
df_eval.loc[74, "prison_term"] = '6.5'
df_eval.loc[84, "prison_term"] = '7.25'
df_eval.loc[85, "prison_term"] = '6.58'
df_eval.loc[91, "prison_term"] = '10'
df_eval.loc[92, "prison_term"] = '9' # тут почему-то еще 0 у меня
df_eval.loc[96, "prison_term"] = '13'
df_eval.loc[97, "prison_term"] = '9'

In [ ]:
def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)
            formatted = [f"{float(x):.2f}" for x in numbers if float(x) > 0]
            return ', '.join(formatted) if formatted else 'nan'
        except:
            return 'nan'
    else:
        try:
            value = float(value)
            return f"{value:.2f}" if value > 0 else 'nan'
        except:
            return 'nan'

df_eval['prison_term_formatted'] = df_eval['prison_term'].apply(format_prison_term)

y_true_gender = df_eval["gender_accused"].astype(str)
y_pred_gender = df_eval["predicted_gender"].astype(str)
y_true_convictions = df_eval["prior_convictions"].astype(str)
y_pred_convictions = df_eval["predicted_prior_convictions"].astype(str)
y_true_prison_term = df_eval["prison_term_formatted"].astype(str)
y_pred_prison_term = df_eval["predicted_prison_term"].astype(str)

gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

prison_term_accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
prison_term_precision, prison_term_recall, prison_term_f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {prison_term_accuracy:.4f}")
print(f"Precision: {prison_term_precision:.4f}")
print(f"Recall:    {prison_term_recall:.4f}")
print(f"F1-score:  {prison_term_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_accused", "predicted_gender", "prior_convictions", "predicted_prior_convictions", "prison_term_formatted", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9500
Precision: 0.9606
Recall:    0.9500
F1-score:  0.9550

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8000
Precision: 0.8225
Recall:    0.8000
F1-score:  0.8094

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.9300
Precision: 0.9629
Recall:    0.9300
F1-score:  0.9399

Пример предсказаний:
           gender_accused  predicted_gender prior_convictions  \
0                 мужчина           мужчина               нет
1                 мужчина           мужчина               нет
2  ['мужчина', 'мужчина']  мужчина, женщина    ['нет', 'нет']
3                 мужчина           мужчина               нет
4                 мужчина           мужчина               нет

  predicted_prior_convictions prison_term_formatted predicted_prison_term
0                         нет                  6.50                  6.50
1                         нет                  8.08                  8.08
2                    нет, нет          18.00, 20.00          18.00, 20.00
3                         нет                  3.00                  3.00
4                         нет                  9.25                  9.25

In [ ]:
def format_gender(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["мужчина", "женщина", "неизвестно"]]
            return ', '.join(formatted) if formatted else 'неизвестно'
        except:
            return 'неизвестно'
    else:
        return str(value) if str(value) in ["мужчина", "женщина", "неизвестно"] else 'неизвестно'

def format_prior_convictions(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in ["да", "нет"]]
            return ', '.join(formatted) if formatted else 'нет'
        except:
            return 'нет'
    else:
        return str(value) if str(value) in ["да", "нет"] else 'нет'

def format_prison_term(value):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            numbers = ast.literal_eval(value)
            formatted = [f"{float(x):.2f}" for x in numbers if float(x) > 0]
            return ', '.join(formatted) if formatted else 'nan'
        except:
            return 'nan'
    else:
        try:
            value = float(value)
            return f"{value:.2f}" if value > 0 else 'nan'
        except:
            return 'nan'

df_eval['gender_formatted'] = df_eval['gender_accused'].apply(format_gender)
df_eval['prior_convictions_formatted'] = df_eval['prior_convictions'].apply(format_prior_convictions)
df_eval['prison_term_formatted'] = df_eval['prison_term'].apply(format_prison_term)

y_true_gender = df_eval["gender_formatted"]
y_pred_gender = df_eval["predicted_gender"]
y_true_convictions = df_eval["prior_convictions_formatted"]
y_pred_convictions = df_eval["predicted_prior_convictions"]
y_true_prison_term = df_eval["prison_term_formatted"]
y_pred_prison_term = df_eval["predicted_prison_term"]

gender_accuracy = accuracy_score(y_true_gender, y_pred_gender)
gender_precision, gender_recall, gender_f1, _ = precision_recall_fscore_support(
    y_true_gender, y_pred_gender, average="weighted", zero_division=0
)

convictions_accuracy = accuracy_score(y_true_convictions, y_pred_convictions)
convictions_precision, convictions_recall, convictions_f1, _ = precision_recall_fscore_support(
    y_true_convictions, y_pred_convictions, average="weighted", zero_division=0
)

prison_term_accuracy = accuracy_score(y_true_prison_term, y_pred_prison_term)
prison_term_precision, prison_term_recall, prison_term_f1, _ = precision_recall_fscore_support(
    y_true_prison_term, y_pred_prison_term, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Пол обвиняемого):")
print(f"Accuracy:  {gender_accuracy:.4f}")
print(f"Precision: {gender_precision:.4f}")
print(f"Recall:    {gender_recall:.4f}")
print(f"F1-score:  {gender_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ранее судим):")
print(f"Accuracy:  {convictions_accuracy:.4f}")
print(f"Precision: {convictions_precision:.4f}")
print(f"Recall:    {convictions_recall:.4f}")
print(f"F1-score:  {convictions_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Срок заключения):")
print(f"Accuracy:  {prison_term_accuracy:.4f}")
print(f"Precision: {prison_term_precision:.4f}")
print(f"Recall:    {prison_term_recall:.4f}")
print(f"F1-score:  {prison_term_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["gender_formatted", "predicted_gender", "prior_convictions_formatted", "predicted_prior_convictions", "prison_term_formatted", "predicted_prison_term"]].head())

ОЦЕНКА GPT-4o-mini (Пол обвиняемого):
Accuracy:  0.9700
Precision: 0.9906
Recall:    0.9700
F1-score:  0.9790

ОЦЕНКА GPT-4o-mini (Ранее судим):
Accuracy:  0.8100
Precision: 0.8425
Recall:    0.8100
F1-score:  0.8228

ОЦЕНКА GPT-4o-mini (Срок заключения):
Accuracy:  0.9300
Precision: 0.9629
Recall:    0.9300
F1-score:  0.9399

Пример предсказаний:
   gender_formatted  predicted_gender prior_convictions_formatted  \
0           мужчина           мужчина                         нет
1           мужчина           мужчина                         нет
2  мужчина, мужчина  мужчина, женщина                    нет, нет
3           мужчина           мужчина                         нет
4           мужчина           мужчина                         нет

  predicted_prior_convictions prison_term_formatted predicted_prison_term
0                         нет                  6.50                  6.50
1                         нет                  8.08                  8.08
2                    нет, нет          18.00, 20.00          18.00, 20.00
3                         нет                  3.00                  3.00
4                         нет                  9.25                  9.25

In [553]:
file_path5 = 'nemogy.csv'
dfa = pd.read_csv(file_path5, on_bad_lines='warn')
dfa.head(5)

,id,region,entryDate,names,judge,decision,accused,articles,link_text,gender_accused,...,preamble,description,sentence,victim_count,killer_count,extracted_prison_term,prison_term_re,num_victims,has_woman_victim,has_man_victim
0,57844,29,2018-05-11,Газизов Дмитрий Рустамович - ст.105 ч.1 УК РФ,Аршинов Алексей Александрович,Вынесен ПРИГОВОР,Газизов Дмитрий Рустамович,ст.105 ч.1,http://lomonosovsky--arh.sudrf.ru/modules.php?...,мужчина,...,Дело <№> (29RS0<№>-58)\nПРИГОВОР\nименем Росси...,УСТАНОВИЛ:\nГ.Д.Р. совершил убийство при следу...,ПРИГОВОРИЛ:\nГ.Д.Р. признать виновным в соверш...,1,1,NaN,6.0,1,0,1
1,71745,23,2019-08-26,"Жмурко Юрий Геннадьевич - ст.167 ч.1, ст.105 ч...",Сапега Н.Н.,Вынесен ПРИГОВОР,Жмурко Юрий Геннадьевич,"ст.167 ч.1, ст.105 ч.1",http://novopokrovsky--krd.sudrf.ru/modules.php...,мужчина,...,К делу № 1-141/2019 г.\nПРИГОВОР\nИменем Росси...,"УСТАНОВИЛ:\nЖмурко Ю.Г. совершил убийство, т.е...",ПРИГОВОРИЛ:\nПризнать Жмурко Юрия Геннадьевича...,1,1,NaN,8.0,1,0,1
2,41579,50,2017-06-30,"Скворцов Евгений Владимирович - ст.325 ч.1, ст...",Мядзелец О.А.,Вынесен ПРИГОВОР,"Скворцов Евгений Владимирович, Скородумов Серг...","ст.325 ч.1, ст.325 ч.1, ст.325 ч.2, ст.162 ч.4...",http://oblsud--mo.sudrf.ru/modules.php?name=su...,"['мужчина', 'мужчина']",...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\n25 дека...,УСТАНОВИЛ:\nВердиктом коллегии присяжных засед...,ПРИГОВОРИЛ:\nСкородумова Сергея Юрьевича призн...,2,2,NaN,2017.0,2,1,0
3,116462,50,2022-05-04,"Матвеев Сергей Владимирович - ст. 30 ч.3, ст.1...",Перминова Е.А.,Вынесен ПРИГОВОР,Матвеев Сергей Владимирович,"ст. 30 ч.3, ст.105 ч.1",http://volokolamsk--mo.sudrf.ru/modules.php?na...,мужчина,...,Решение по уголовному делу\nИнформация по делу...,УСТАНОВИЛ:\nМатвеев С.В. совершил умышленное п...,ПРИГОВОРИЛ:\nпризнать виновным в совершении пр...,1,1,NaN,3.0,1,0,1
4,102232,38,2021-04-19,Шамов Сергей Викторович - ст.105 ч.1 УК РФ,Иванов Д.В.,Вынесен ПРИГОВОР,Шамов Сергей Викторович,ст.105 ч.1,http://angarsky--irk.sudrf.ru/modules.php?name...,мужчина,...,ПРИГОВОР\nИМЕНЕМ РОССИЙСКОЙ ФЕДЕРАЦИИ\nг.Ангар...,У С Т А Н О В И Л:\nНа основании вердикта колл...,ПРИГОВОРИЛ:\nПризнать Ш.С.В. виновным в соверш...,1,1,9.25,9.0,1,0,1

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
import ast

client = OpenAI(api_key='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')

df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ или 111 УК РФ или 30 УК РФ:
1. Находился ли обвиняемый в состоянии алкогольного опьянения в момент совершения преступления.
2. Была ли ссора между преступником и жертвой перед преступлением.
3. Мотив преступления (мульти-лейбл).
4. Связь между преступником и жертвой.
5. Наличие жертвы женского пола.
6. Наличие жертвы мужского пола.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ или 111 УК РФ или 30 УК РФ. Если статья 105 и 111 и 30 не упоминается для обвиняемого, не возвращай никаких данных для него.
- Количество ответов для признаков 1, 2 и 4 должно совпадать с числом обвиняемых, указанным в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если статья 105 не упоминается в тексте вообще, верни пустые списки для признаков 1, 2, 4, "неизвестно" для мотива, и 0 для признаков 5 и 6.
- Если killer_count больше числа упомянутых обвиняемых, заполни недостающие значения для признаков 1, 2, 4 значениями по умолчанию ("нет" для 1 и 2, "неизвестно" для 4).

**Правила для признаков:**

1. **Алкогольное опьянение**:
   - Если есть явное указание (например, "был пьян", "в состоянии опьянения"), укажи "да".
   - Если указано отсутствие (например, "не употреблял алкоголь"), укажи "нет".
   - Если информации нет, укажи "нет".
   - Формат: "алкоголь: [<да/нет>, ...]", где значения для каждого обвиняемого указаны в порядке их упоминания в тексте.

2. **Ссора перед преступлением (precrime_argument)**:
   - Если есть указание на ссору (например, "в ходе конфликта", "после спора"), укажи "была".
   - Если указано отсутствие ссоры или информации нет, укажи "нет".
   - Формат: "ссора: [<была/нет>, ...]".

3. **Мотив преступления**:
   - Укажи мотивы в начальной форме единственного числа (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство).
   - Если мотивов несколько, перечисли через запятую.
   - Если мотив не указан, верни "неизвестно".
   - Извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь").
   - Формат: "мотив: <мотив1, мотив2, ... или неизвестно>".

4. **Связь между преступником и жертвой**:
   - Укажи, кем каждый преступник является для жертвы (например, знакомый, зять, супруг, родственник, сожитель, друг, сосед, коллега, работник, незнакомец).
   - Если у преступника несколько жертв с разными связями, выбери наиболее значимую связь по приоритету: родственник > супруг > зять > сожитель > бывший супруг > друг > знакомый > сосед > коллега > работник > незнакомец.
   - Все ответы в единственном числе в начальной мужской форме (например, "супруга" → "супруг").
   - Если связь не указана, верни "неизвестно".
   - Формат: "связь: [<связь1>, <связь2>, ...]".

5. **Наличие жертвы женского пола**:
   - Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("она") или явные указания ("женщина").
   - Формат: "жертва_женщина: <1/0>".

6. **Наличие жертвы мужского пола**:
   - Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("он") или явные указания ("мужчина").
   - Формат: "жертва_мужчина: <1/0>".

**Примеры:**
- Текст: Иванов, будучи пьяным, после ссоры убил свою жену по мотивам ревности по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: [да]
  ссора: [была]
  мотив: ревность
  связь: [супруг]
  жертва_женщина: 1
  жертва_мужчина: 0
  ```
- Текст: Петров и Сидоров, трезвые, убили знакомого в ходе драки по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет, нет]
  ссора: [была, была]
  мотив: личная неприязнь
  связь: [знакомый, знакомый]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Иванов убил незнакомца ради кражи по статье 105 УК РФ, Сидоров украл деньги по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет]
  ссора: [нет]
  мотив: ограбление
  связь: [незнакомец]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: []
  ссора: []
  мотив: неизвестно
  связь: []
  жертва_женщина: 0
  жертва_мужчина: 0
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["description"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }

def normalize_prediction(text, killer_count):
    result = {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }
    try:
        lines = text.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("алкоголь:"):
                alcohol_part = line.replace("алкоголь:", "").strip()
                if alcohol_part.startswith("[") and alcohol_part.endswith("]"):
                    values = [v.strip() for v in alcohol_part[1:-1].split(",") if v.strip()]
                    result["alcohol"] = [v if v in ["да", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["alcohol"] = [alcohol_part if alcohol_part in ["да", "нет"] else "нет"][:killer_count]
                
                result["alcohol"] += ["нет"] * (killer_count - len(result["alcohol"]))
                
            elif line.startswith("ссора:"):
                argument_part = line.replace("ссора:", "").strip()
                if argument_part.startswith("[") and argument_part.endswith("]"):
                    values = [v.strip() for v in argument_part[1:-1].split(",") if v.strip()]
                    result["precrime_argument"] = [v if v in ["была", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["precrime_argument"] = [argument_part if argument_part in ["была", "нет"] else "нет"][:killer_count]
                result["precrime_argument"] += ["нет"] * (killer_count - len(result["precrime_argument"]))
                
            elif line.startswith("мотив:"):
                motive_part = line.replace("мотив:", "").strip()
                motives = [m.strip() for m in motive_part.split(",") if m.strip()]
                result["motive"] = ", ".join(motives) if motives else "неизвестно"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                if rel_part.startswith("[") and rel_part.endswith("]"):
                    values = [v.strip() for v in rel_part[1:-1].split(",") if v.strip()]
                    result["relationship"] = values[:killer_count]
                else:
                    result["relationship"] = [rel_part][:killer_count]
                result["relationship"] += ["неизвестно"] * (killer_count - len(result["relationship"]))
                
            elif line.startswith("жертва_женщина:"):
                woman_part = line.replace("жертва_женщина:", "").strip()
                result["has_woman_victim"] = woman_part if woman_part in ["0", "1"] else "0"
                
            elif line.startswith("жертва_мужчина:"):
                man_part = line.replace("жертва_мужчина:", "").strip()
                result["has_man_victim"] = man_part if man_part in ["0", "1"] else "0"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["predictions"] = df_eval[["description", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

df_eval["predicted_alcohol"] = df_eval["predictions"].apply(lambda x: ", ".join(x["alcohol"]))
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: ", ".join(x["precrime_argument"]))
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])
df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: ", ".join(x["relationship"]))
df_eval["predicted_has_woman_victim"] = df_eval["predictions"].apply(lambda x: x["has_woman_victim"])
df_eval["predicted_has_man_victim"] = df_eval["predictions"].apply(lambda x: x["has_man_victim"])

100%|██████████| 100/100 [05:31<00:00,  3.31s/it]

In [ ]:
def format_list(value, valid_values, default):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in valid_values]
            return ', '.join(formatted) if formatted else default
        except:
            return default
    else:
        return str(value) if str(value) in valid_values else default

# def format_motive(value):
#     if isinstance(value, str):
#         motives = [m.strip() for m in value.split(",") if m.strip()]
#         return ", ".join(motives) if motives else "неизвестно"
#     return "неизвестно"

df_eval["alcohol_formatted"] = df_eval["alcohol"].apply(lambda x: format_list(x, ["да", "нет"], "нет"))
df_eval["precrime_argument_formatted"] = df_eval["precrime_argument"].apply(lambda x: format_list(x, ["была", "нет"], "нет"))
# df_eval["motive_formatted"] = df_eval["motive"].apply(format_motive)
df_eval["relationship_formatted"] = df_eval["relationship_between_accused_and_victim"].apply(lambda x: format_list(x, [
    "знакомый", "зять", "супруг", "родственник", "сожитель", "друг", "сосед", "коллега", "работник", "незнакомец", "неизвестно"
], "неизвестно"))
df_eval["has_woman_victim_formatted"] = df_eval["has_woman_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")
df_eval["has_man_victim_formatted"] = df_eval["has_man_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")

y_true_alcohol = df_eval["alcohol_formatted"]
y_pred_alcohol = df_eval["predicted_alcohol"]
y_true_precrime_argument = df_eval["precrime_argument_formatted"]
y_pred_precrime_argument = df_eval["predicted_precrime_argument"]
y_true_relationship = df_eval["relationship_formatted"]
y_pred_relationship = df_eval["predicted_relationship"]
y_true_has_woman_victim = df_eval["has_woman_victim_formatted"]
y_pred_has_woman_victim = df_eval["predicted_has_woman_victim"]
y_true_has_man_victim = df_eval["has_man_victim_formatted"]
y_pred_has_man_victim = df_eval["predicted_has_man_victim"]

# mlb = MultiLabelBinarizer()
# y_true_motive = mlb.fit_transform(df_eval["motive_formatted"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))
# y_pred_motive = mlb.transform(df_eval["predicted_motive"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))

alcohol_accuracy = accuracy_score(y_true_alcohol, y_pred_alcohol)
alcohol_precision, alcohol_recall, alcohol_f1, _ = precision_recall_fscore_support(
    y_true_alcohol, y_pred_alcohol, average="weighted", zero_division=0
)

precrime_argument_accuracy = accuracy_score(y_true_precrime_argument, y_pred_precrime_argument)
precrime_argument_precision, precrime_argument_recall, precrime_argument_f1, _ = precision_recall_fscore_support(
    y_true_precrime_argument, y_pred_precrime_argument, average="weighted", zero_division=0
)

# motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
#     y_true_motive, y_pred_motive, average="micro", zero_division=0
# )
# motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

has_woman_victim_accuracy = accuracy_score(y_true_has_woman_victim, y_pred_has_woman_victim)
has_woman_victim_precision, has_woman_victim_recall, has_woman_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_woman_victim, y_pred_has_woman_victim, average="weighted", zero_division=0
)

has_man_victim_accuracy = accuracy_score(y_true_has_man_victim, y_pred_has_man_victim)
has_man_victim_precision, has_man_victim_recall, has_man_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_man_victim, y_pred_has_man_victim, average="weighted", zero_division=0
)


print("\nОЦЕНКА GPT-4o-mini (Алкогольное опьянение):")
print(f"Accuracy:  {alcohol_accuracy:.4f}")
print(f"Precision: {alcohol_precision:.4f}")
print(f"Recall:    {alcohol_recall:.4f}")
print(f"F1-score:  {alcohol_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ссора перед преступлением):")
print(f"Accuracy:  {precrime_argument_accuracy:.4f}")
print(f"Precision: {precrime_argument_precision:.4f}")
print(f"Recall:    {precrime_argument_recall:.4f}")
print(f"F1-score:  {precrime_argument_f1:.4f}")

# print("\nОЦЕНКА GPT-4o-mini (Мотив преступления):")
# print(f"Accuracy:  {motive_accuracy:.4f}")
# print(f"Precision: {motive_precision:.4f}")
# print(f"Recall:    {motive_recall:.4f}")
# print(f"F1-score:  {motive_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Связь с жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва женского пола):")
print(f"Accuracy:  {has_woman_victim_accuracy:.4f}")
print(f"Precision: {has_woman_victim_precision:.4f}")
print(f"Recall:    {has_woman_victim_recall:.4f}")
print(f"F1-score:  {has_woman_victim_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва мужского пола):")
print(f"Accuracy:  {has_man_victim_accuracy:.4f}")
print(f"Precision: {has_man_victim_precision:.4f}")
print(f"Recall:    {has_man_victim_recall:.4f}")
print(f"F1-score:  {has_man_victim_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "alcohol_formatted", "predicted_alcohol",
    "precrime_argument_formatted", "predicted_precrime_argument",
    "relationship_formatted", "predicted_relationship",
    "has_woman_victim_formatted", "predicted_has_woman_victim",
    "has_man_victim_formatted", "predicted_has_man_victim"
]].head())

ОЦЕНКА GPT-4o-mini (Алкогольное опьянение):
Accuracy:  0.8600
Precision: 0.8611
Recall:    0.8600
F1-score:  0.8555

ОЦЕНКА GPT-4o-mini (Ссора перед преступлением):
Accuracy:  0.9400
Precision: 0.9706
Recall:    0.9400
F1-score:  0.9439

ОЦЕНКА GPT-4o-mini (Связь с жертвой):
Accuracy:  0.4600
Precision: 0.5096
Recall:    0.4600
F1-score:  0.4614

ОЦЕНКА GPT-4o-mini (Жертва женского пола):
Accuracy:  0.8300
Precision: 0.8846
Recall:    0.8300
F1-score:  0.8387

ОЦЕНКА GPT-4o-mini (Жертва мужского пола):
Accuracy:  0.9600
Precision: 0.9599
Recall:    0.9600
F1-score:  0.9594

Пример предсказаний:
  alcohol_formatted predicted_alcohol precrime_argument_formatted  \
0                да                да                        была
1                да                да                        была
2          нет, нет          нет, нет                         нет
3                да                да                        была
4                да                да                        была

  predicted_precrime_argument  relationship_formatted predicted_relationship  \
0                        была                знакомый             незнакомец
1                        была                знакомый               сожитель
2                    нет, нет  неизвестно, неизвестно     знакомый, знакомый
3                        была                работник               работник
4                        была                знакомый             незнакомец

  has_woman_victim_formatted predicted_has_woman_victim  \
0                          0                          0
1                          0                          0
2                          1                          1
3                          0                          0
4                          0                          0

  has_man_victim_formatted predicted_has_man_victim
0                        1                        1
1                        1                        1
2                        0                        0
3                        1                        1
4                        1                        1

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['аморальное поведение', 'вымогательство', 'корысть', 'материальная выгода', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [568]:
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)

mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)
motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Accuracy:  {motive_accuracy:.4f}")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["motive2", "predicted_motive"]].head())

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Accuracy:  0.8000
Precision: 0.9065
Recall:    0.8509
F1-score:  0.8778

Пример предсказаний:
                      motive2            predicted_motive
0     личная неприязнь, месть     месть, личная неприязнь
1  личная неприязнь, ревность  ревность, личная неприязнь
2           деньги, имущество                   имущество
3            личная неприязнь   личная неприязнь, корысть
4            личная неприязнь            личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['аморальное поведение', 'вымогательство', 'корысть', 'материальная выгода', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
import ast

client = OpenAI(api_key='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')

df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

# def clean_text(text):
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"\s+", " ", text)
#     return text.strip()

# df_eval["combined_text"] = df_eval["preamble"].str.cat(df_eval["sentence"], sep=" ").apply(clean_text)

def map_relationship_to_category(value):
    family = ['брат', 'зять', 'супруг', 'родственник', 'сын', 'мать сожительницы']
    romantic = ['сожитель', 'бывший супруг', 'интимные отношения']
    acquaintance = ['знакомый', 'друг', 'сосед']
    professional = ['работник', 'коллега']
    
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = []
            for item in items:
                item = item.strip()
                if item in family:
                    formatted.append('семья')
                elif item in romantic:
                    formatted.append('романтические отношения')
                elif item in acquaintance:
                    formatted.append('друзья/знакомые')
                elif item in professional:
                    formatted.append('профессиональные отношения')
                elif item == 'незнакомец':
                    formatted.append('незнакомец')
                else:
                    formatted.append('неизвестно')
            return ', '.join(formatted) if formatted else 'неизвестно'
        except:
            return 'неизвестно'
    else:
        value = str(value).strip()
        if value in family:
            return 'семья'
        elif value in romantic:
            return 'романтические отношения'
        elif value in acquaintance:
            return 'друзья/знакомые'
        elif value in professional:
            return 'профессиональные отношения'
        elif value == 'незнакомец':
            return 'незнакомец'
        else:
            return 'неизвестно'

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ:
1. Находился ли обвиняемый в состоянии алкогольного опьянения в момент совершения преступления.
2. Была ли ссора между преступником и жертвой перед преступлением.
3. Мотив преступления (мульти-лейбл).
4. Связь между преступником и жертвой (кем преступник является для жертвы).
5. Наличие жертвы женского пола.
6. Наличие жертвы мужского пола.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ. Если статья 105 не упоминается для обвиняемого, не возвращай никаких данных для него.
- Количество ответов для признаков 1, 2 и 4 должно совпадать с числом обвиняемых, указанным в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если статья 105 не упоминается в тексте вообще, верни пустые списки для признаков 1, 2, 4, "неизвестно" для мотива, и 0 для признаков 5 и 6.
- Если killer_count больше числа упомянутых обвиняемых, заполни недостающие значения для признаков 1, 2, 4 значениями по умолчанию ("нет" для 1 и 2, "неизвестно" для 4).

**Правила для признаков:**

1. **Алкогольное опьянение**:
   - Если есть явное указание (например, "был пьян", "в состоянии опьянения"), укажи "да".
   - Если указано отсутствие (например, "не употреблял алкоголь"), укажи "нет".
   - Если информации нет, укажи "нет".
   - Формат: "алкоголь: [<да/нет>, ...]", где значения для каждого обвиняемого указаны в порядке их упоминания в тексте.

2. **Ссора перед преступлением (precrime_argument)**:
   - Если есть указание на ссору (например, "в ходе конфликта", "после спора"), укажи "была".
   - Если указано отсутствие ссоры или информации нет, укажи "нет".
   - Формат: "ссора: [<была/нет>, ...]".

3. **Мотив преступления**:
   - Укажи мотивы в начальной форме единственного числа (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство).
   - Если мотивов несколько, перечисли через запятую.
   - Если мотив не указан, верни "неизвестно".
   - Извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь").
   - Формат: "мотив: <мотив1, мотив2, ... или неизвестно>".

4. **Связь между преступником и жертвой**:
   - Укажи, кем каждый преступник является для жертвы, классифицируя связь в одну из следующих категорий: семья, романтические отношения, друзья/знакомые, профессиональные отношения, незнакомец, неизвестно.
   - Категории определяются следующим образом:
     - Семья: родственник, супруг, зять, сын, брат, мать сожительницы.
     - Романтические отношения: сожитель, бывший супруг, интимные отношения.
     - Друзья/знакомые: знакомый, друг, сосед.
     - Профессиональные отношения: работник, коллега.
     - Незнакомец: незнакомец.
     - Неизвестно: если связь не указана или неясна.
   - Опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников.
   - Если у преступника несколько жертв с разными связями, выбери наиболее значимую категорию по приоритету: семья > романтические отношения > друзья/знакомые > профессиональные отношения > незнакомец > неизвестно.
   - Формат: "связь: [<категория1>, <категория2>, ...]".

5. **Наличие жертвы женского пола**:
   - Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("она") или явные указания ("женщина").
   - Формат: "жертва_женщина: <1/0>".

6. **Наличие жертвы мужского пола**:
   - Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("он") или явные указания ("мужчина").
   - Формат: "жертва_мужчина: <1/0>".

**Примеры:**
- Текст: Иванов, будучи пьяным, после ссоры убил свою жену по мотивам ревности по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: [да]
  ссора: [была]
  мотив: ревность
  связь: [семья]
  жертва_женщина: 1
  жертва_мужчина: 0
  ```
- Текст: Петров и Сидоров, трезвые, убили знакомого в ходе драки по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет, нет]
  ссора: [была, была]
  мотив: личная неприязнь
  связь: [друзья/знакомые, друзья/знакомые]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Иванов убил незнакомца ради кражи по статье 105 УК РФ, Сидоров украл деньги по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет]
  ссора: [нет]
  мотив: ограбление
  связь: [незнакомец]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: []
  ссора: []
  мотив: неизвестно
  связь: []
  жертва_женщина: 0
  жертва_мужчина: 0
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["description"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }

def normalize_prediction(text, killer_count):
    result = {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }
    try:
        lines = text.split("\n")
        valid_relationships = ['семья', 'романтические отношения', 'друзья/знакомые', 'профессиональные отношения', 'незнакомец', 'неизвестно']
        for line in lines:
            line = line.strip()
            if line.startswith("алкоголь:"):
                alcohol_part = line.replace("алкоголь:", "").strip()
                if alcohol_part.startswith("[") and alcohol_part.endswith("]"):
                    values = [v.strip() for v in alcohol_part[1:-1].split(",") if v.strip()]
                    result["alcohol"] = [v if v in ["да", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["alcohol"] = [alcohol_part if alcohol_part in ["да", "нет"] else "нет"][:killer_count]
                result["alcohol"] += ["нет"] * (killer_count - len(result["alcohol"]))
                
            elif line.startswith("ссора:"):
                argument_part = line.replace("ссора:", "").strip()
                if argument_part.startswith("[") and argument_part.endswith("]"):
                    values = [v.strip() for v in argument_part[1:-1].split(",") if v.strip()]
                    result["precrime_argument"] = [v if v in ["была", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["precrime_argument"] = [argument_part if argument_part in ["была", "нет"] else "нет"][:killer_count]
                result["precrime_argument"] += ["нет"] * (killer_count - len(result["precrime_argument"]))
                
            elif line.startswith("мотив:"):
                motive_part = line.replace("мотив:", "").strip()
                motives = [m.strip() for m in motive_part.split(",") if m.strip()]
                result["motive"] = ", ".join(motives) if motives else "неизвестно"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                if rel_part.startswith("[") and rel_part.endswith("]"):
                    values = [v.strip() for v in rel_part[1:-1].split(",") if v.strip()]
                    result["relationship"] = [v if v in valid_relationships else "неизвестно" for v in values][:killer_count]
                else:
                    result["relationship"] = [rel_part if rel_part in valid_relationships else "неизвестно"][:killer_count]
                result["relationship"] += ["неизвестно"] * (killer_count - len(result["relationship"]))
                
            elif line.startswith("жертва_женщина:"):
                woman_part = line.replace("жертва_женщина:", "").strip()
                result["has_woman_victim"] = woman_part if woman_part in ["0", "1"] else "0"
                
            elif line.startswith("жертва_мужчина:"):
                man_part = line.replace("жертва_мужчина:", "").strip()
                result["has_man_victim"] = man_part if man_part in ["0", "1"] else "0"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result


df_eval["predictions"] = df_eval[["description", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

df_eval["predicted_alcohol"] = df_eval["predictions"].apply(lambda x: ", ".join(x["alcohol"]))
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: ", ".join(x["precrime_argument"]))
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])
df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: ", ".join(x["relationship"]))
df_eval["predicted_has_woman_victim"] = df_eval["predictions"].apply(lambda x: x["has_woman_victim"])
df_eval["predicted_has_man_victim"] = df_eval["predictions"].apply(lambda x: x["has_man_victim"])

100%|██████████| 100/100 [05:32<00:00,  3.33s/it]

In [ ]:
def format_list(value, valid_values, default):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in valid_values]
            return ', '.join(formatted) if formatted else default
        except:
            return default
    else:
        return str(value) if str(value) in valid_values else default

# def format_motive(value):
#     if isinstance(value, str):
#         motives = [m.strip() for m in value.split(",") if m.strip()]
#         return ", ".join(motives) if motives else "неизвестно"
#     return "неизвестно"

df_eval["alcohol_formatted"] = df_eval["alcohol"].apply(lambda x: format_list(x, ["да", "нет"], "нет"))
df_eval["precrime_argument_formatted"] = df_eval["precrime_argument"].apply(lambda x: format_list(x, ["была", "нет"], "нет"))
# df_eval["motive_formatted"] = df_eval["motive"].apply(format_motive)
df_eval["relationship_between_accused_and_victim2"] = df_eval["relationship_between_accused_and_victim"].apply(map_relationship_to_category)
df_eval["has_woman_victim_formatted"] = df_eval["has_woman_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")
df_eval["has_man_victim_formatted"] = df_eval["has_man_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")

y_true_alcohol = df_eval["alcohol_formatted"]
y_pred_alcohol = df_eval["predicted_alcohol"]
y_true_precrime_argument = df_eval["precrime_argument_formatted"]
y_pred_precrime_argument = df_eval["predicted_precrime_argument"]
y_true_relationship = df_eval["relationship_between_accused_and_victim2"]
y_pred_relationship = df_eval["predicted_relationship"]
y_true_has_woman_victim = df_eval["has_woman_victim_formatted"]
y_pred_has_woman_victim = df_eval["predicted_has_woman_victim"]
y_true_has_man_victim = df_eval["has_man_victim_formatted"]
y_pred_has_man_victim = df_eval["predicted_has_man_victim"]

# Мульти-лейбл классификация для мотива
# mlb = MultiLabelBinarizer()
# y_true_motive = mlb.fit_transform(df_eval["motive_formatted"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))
# y_pred_motive = mlb.transform(df_eval["predicted_motive"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))

alcohol_accuracy = accuracy_score(y_true_alcohol, y_pred_alcohol)
alcohol_precision, alcohol_recall, alcohol_f1, _ = precision_recall_fscore_support(
    y_true_alcohol, y_pred_alcohol, average="weighted", zero_division=0
)

precrime_argument_accuracy = accuracy_score(y_true_precrime_argument, y_pred_precrime_argument)
precrime_argument_precision, precrime_argument_recall, precrime_argument_f1, _ = precision_recall_fscore_support(
    y_true_precrime_argument, y_pred_precrime_argument, average="weighted", zero_division=0
)

# motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
#     y_true_motive, y_pred_motive, average="weighted", zero_division=0
# )
# motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

has_woman_victim_accuracy = accuracy_score(y_true_has_woman_victim, y_pred_has_woman_victim)
has_woman_victim_precision, has_woman_victim_recall, has_woman_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_woman_victim, y_pred_has_woman_victim, average="weighted", zero_division=0
)

has_man_victim_accuracy = accuracy_score(y_true_has_man_victim, y_pred_has_man_victim)
has_man_victim_precision, has_man_victim_recall, has_man_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_man_victim, y_pred_has_man_victim, average="weighted", zero_division=0
)

print("\nОЦЕНКА GPT-4o-mini (Алкогольное опьянение):")
print(f"Accuracy:  {alcohol_accuracy:.4f}")
print(f"Precision: {alcohol_precision:.4f}")
print(f"Recall:    {alcohol_recall:.4f}")
print(f"F1-score:  {alcohol_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ссора перед преступлением):")
print(f"Accuracy:  {precrime_argument_accuracy:.4f}")
print(f"Precision: {precrime_argument_precision:.4f}")
print(f"Recall:    {precrime_argument_recall:.4f}")
print(f"F1-score:  {precrime_argument_f1:.4f}")

# print("\nОЦЕНКА GPT-4o-mini (Мотив преступления):")
# print(f"Accuracy:  {motive_accuracy:.4f}")
# print(f"Precision: {motive_precision:.4f}")
# print(f"Recall:    {motive_recall:.4f}")
# print(f"F1-score:  {motive_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Связь с жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва женского пола):")
print(f"Accuracy:  {has_woman_victim_accuracy:.4f}")
print(f"Precision: {has_woman_victim_precision:.4f}")
print(f"Recall:    {has_woman_victim_recall:.4f}")
print(f"F1-score:  {has_woman_victim_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва мужского пола):")
print(f"Accuracy:  {has_man_victim_accuracy:.4f}")
print(f"Precision: {has_man_victim_precision:.4f}")
print(f"Recall:    {has_man_victim_recall:.4f}")
print(f"F1-score:  {has_man_victim_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "alcohol_formatted", "predicted_alcohol",
    "precrime_argument_formatted", "predicted_precrime_argument",
    "relationship_between_accused_and_victim2", "predicted_relationship",
    "has_woman_victim_formatted", "predicted_has_woman_victim",
    "has_man_victim_formatted", "predicted_has_man_victim"
]].head())

ОЦЕНКА GPT-4o-mini (Алкогольное опьянение):
Accuracy:  0.8500
Precision: 0.8511
Recall:    0.8500
F1-score:  0.8468

ОЦЕНКА GPT-4o-mini (Ссора перед преступлением):
Accuracy:  0.9400
Precision: 0.9706
Recall:    0.9400
F1-score:  0.9439

ОЦЕНКА GPT-4o-mini (Связь с жертвой):
Accuracy:  0.4100
Precision: 0.5984
Recall:    0.4100
F1-score:  0.3898

ОЦЕНКА GPT-4o-mini (Жертва женского пола):
Accuracy:  0.7800
Precision: 0.8656
Recall:    0.7800
F1-score:  0.7923

ОЦЕНКА GPT-4o-mini (Жертва мужского пола):
Accuracy:  0.9600
Precision: 0.9599
Recall:    0.9600
F1-score:  0.9594

Пример предсказаний:
  alcohol_formatted predicted_alcohol precrime_argument_formatted  \
0                да                да                        была
1                да                да                        была
2          нет, нет          нет, нет                         нет
3                да                да                        была
4                да                да                        была

  predicted_precrime_argument relationship_between_accused_and_victim2  \
0                        была                          друзья/знакомые
1                        была                          друзья/знакомые
2                    нет, нет                   неизвестно, неизвестно
3                        была               профессиональные отношения
4                        была                          друзья/знакомые

   predicted_relationship has_woman_victim_formatted  \
0              незнакомец                          0
1                   семья                          0
2  незнакомец, незнакомец                          1
3         друзья/знакомые                          0
4                   семья                          0

  predicted_has_woman_victim has_man_victim_formatted predicted_has_man_victim
0                          0                        1                        1
1                          0                        1                        1
2                          1                        0                        0
3                          0                        1                        1
4                          0                        1                        1

In [578]:
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)

mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)
motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Accuracy:  {motive_accuracy:.4f}")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["motive2", "predicted_motive"]].head())

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Accuracy:  0.8200
Precision: 0.9167
Recall:    0.8684
F1-score:  0.8919

Пример предсказаний:
                      motive2             predicted_motive
0     личная неприязнь, месть      месть, личная неприязнь
1  личная неприязнь, ревность                     ревность
2           деньги, имущество  имущество, личная неприязнь
3            личная неприязнь    личная неприязнь, корысть
4            личная неприязнь             личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['защита', 'корысть', 'стремление скрыть преступление'] will be ignored
  warnings.warn(

In [ ]:
import pandas as pd
import re
from tqdm import tqdm
from openai import OpenAI
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MultiLabelBinarizer
import numpy as np
import ast

client = OpenAI(api_key='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')

df_eval = dfa.iloc[0:].copy() 

tqdm.pandas()

def clean_text(text):
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_eval["combined_text"] = df_eval["description"].apply(clean_text)

def map_relationship_to_category(value):
    family = ['брат', 'зять', 'супруг', 'родственник', 'сын', 'мать сожительницы']
    romantic = ['сожитель', 'бывший супруг', 'интимные отношения']
    acquaintance = ['знакомый', 'друг', 'сосед']
    professional = ['работник', 'коллега']
    
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = []
            for item in items:
                item = item.strip()
                if item in family:
                    formatted.append('семья')
                elif item in romantic:
                    formatted.append('романтические отношения')
                elif item in acquaintance:
                    formatted.append('друзья/знакомые')
                elif item in professional:
                    formatted.append('профессиональные отношения')
                elif item == 'незнакомец':
                    formatted.append('незнакомец')
                else:
                    formatted.append('неизвестно')
            return ', '.join(formatted) if formatted else 'неизвестно'
        except:
            return 'неизвестно'
    else:
        value = str(value).strip()
        if value in family:
            return 'семья'
        elif value in romantic:
            return 'романтические отношения'
        elif value in acquaintance:
            return 'друзья/знакомые'
        elif value in professional:
            return 'профессиональные отношения'
        elif value == 'незнакомец':
            return 'незнакомец'
        else:
            return 'неизвестно'

def create_prompt(text, killer_count):
    return f"""
Ты — модель для извлечения информации из описания преступления.

Твоя задача — извлечь из текста следующую информацию только для обвиняемых, в отношении которых явно упоминается статья 105 УК РФ, 111 УК РФ или 30 УК РФ:
1. Находился ли обвиняемый в состоянии алкогольного опьянения в момент совершения преступления.
2. Была ли ссора между преступником и жертвой перед преступлением.
3. Мотив преступления (мульти-лейбл).
4. Связь между преступником и жертвой (кем преступник является для жертвы).
5. Наличие жертвы женского пола.
6. Наличие жертвы мужского пола.

**Общие правила:**
- Извлекай информацию только для обвиняемых, связанных со статьей 105 УК РФ, 111 УК РФ или 30 УК РФ. Если эти статьи не упоминаются для обвиняемого, не возвращай никаких данных для него.
- Количество ответов для признаков 1, 2 и 4 должно совпадать с числом обвиняемых, указанным в killer_count ({killer_count}), и соответствовать порядку их упоминания в тексте.
- Если статьи 105, 111 или 30 не упоминаются в тексте вообще, верни пустые списки для признаков 1, 2, 4, "неизвестно" для мотива, и 0 для признаков 5 и 6.
- Если killer_count больше числа упомянутых обвиняемых, заполни недостающие значения для признаков 1, 2, 4 значениями по умолчанию ("нет" для 1 и 2, "неизвестно" для 4).

**Правила для признаков:**

1. **Алкогольное опьянение**:
   - Если есть явное указание (например, "был пьян", "в состоянии опьянения"), укажи "да".
   - Если указано отсутствие (например, "не употреблял алкоголь"), укажи "нет".
   - Если информации нет, укажи "нет".
   - Формат: "алкоголь: [<да/нет>, ...]", где значения для каждого обвиняемого указаны в порядке их упоминания в тексте.

2. **Ссора перед преступлением (precrime_argument)**:
   - Если есть указание на ссору (например, "в ходе конфликта", "после спора"), укажи "была".
   - Если указано отсутствие ссоры или информации нет, укажи "нет".
   - Формат: "ссора: [<была/нет>, ...]".

3. **Мотив преступления**:
   - Укажи мотивы в начальной форме единственного числа (например, личная неприязнь, месть, ревность, имущество, ограбление, корысть, хулиганство).
   - Если мотивов несколько, перечисли через запятую.
   - Если мотив не указан, верни "неизвестно".
   - Извлеки мотивы на основе явных указаний или контекста (например, "кража" → "имущество", "драка на почве спора" → "личная неприязнь").
   - Формат: "мотив: <мотив1, мотив2, ... или неизвестно>".

4. **Связь между преступником и жертвой**:
   - Укажи, кем каждый преступник является для жертвы, классифицируя связь в одну из следующих категорий: семья, романтические отношения, друзья/знакомые, профессиональные отношения, незнакомец, неизвестно.
   - Категории определяются следующим образом:
     - Семья: родственник, супруг, зять, сын, брат, мать сожительницы.
     - Романтические отношения: сожитель, бывший супруг, интимные отношения.
     - Друзья/знакомые: знакомый, друг, сосед.
     - Профессиональные отношения: работник, коллега.
     - Незнакомец: незнакомец.
     - Неизвестно: если связь не указана или неясна.
   - Опирайся на явные указания (например, "супруг", "знакомый") или контекст (например, имена, местоимения). Учитывай порядок упоминания преступников.
   - Если у преступника несколько жертв с разными связями, выбери наиболее значимую категорию по приоритету: семья > романтические отношения > друзья/знакомые > профессиональные отношения > незнакомец > неизвестно.
   - Все ответы должны быть в единственном числе в начальной мужской форме (например, "супруга" → "супруг") при определении исходной связи перед классификацией.
   - Формат: "связь: [<категория1>, <категория2>, ...]".

5. **Наличие жертвы женского пола**:
   - Если есть хотя бы одна женщина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("она") или явные указания ("женщина").
   - Формат: "жертва_женщина: <1/0>".

6. **Наличие жертвы мужского пола**:
   - Если есть хотя бы один мужчина-жертва, верни "1", иначе "0".
   - Опирайся на имена, местоимения ("он") или явные указания ("мужчина").
   - Формат: "жертва_мужчина: <1/0>".

**Примеры:**
- Текст: Иванов, будучи пьяным, после ссоры убил свою жену по мотивам ревности по статье 105 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: [да]
  ссора: [была]
  мотив: ревность
  связь: [семья]
  жертва_женщина: 1
  жертва_мужчина: 0
  ```
- Текст: Петров и Сидоров, трезвые, убили знакомого в ходе драки по статье 105 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет, нет]
  ссора: [была, была]
  мотив: личная неприязнь
  связь: [друзья/знакомые, друзья/знакомые]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Иванов убил незнакомца ради кражи по статье 105 УК РФ, Сидоров украл деньги по статье 158 УК РФ. killer_count=2
  Ответ:
  ```
  алкоголь: [нет]
  ссора: [нет]
  мотив: ограбление
  связь: [незнакомец]
  жертва_женщина: 0
  жертва_мужчина: 1
  ```
- Текст: Обвиняемый совершил кражу по статье 158 УК РФ. killer_count=1
  Ответ:
  ```
  алкоголь: []
  ссора: []
  мотив: неизвестно
  связь: []
  жертва_женщина: 0
  жертва_мужчина: 0
  ```

**Описание:**
{text}

**Ответ:**
""".strip()

def classify_with_gpt4(row, retries=3):
    text = row["combined_text"]
    killer_count = row["killer_count"]
    prompt = create_prompt(text, killer_count)
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                temperature=0
            )
            reply = response.choices[0].message.content.strip().lower()
            return normalize_prediction(reply, killer_count)
        except Exception as e:
            if attempt == retries - 1:
                print(f"Ошибка обработки текста: {e}")
            continue
    return {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }

def normalize_prediction(text, killer_count):
    result = {
        "alcohol": ["нет"] * killer_count,
        "precrime_argument": ["нет"] * killer_count,
        "motive": "неизвестно",
        "relationship": ["неизвестно"] * killer_count,
        "has_woman_victim": "0",
        "has_man_victim": "0"
    }
    try:
        lines = text.split("\n")
        valid_relationships = ['семья', 'романтические отношения', 'друзья/знакомые', 'профессиональные отношения', 'незнакомец', 'неизвестно']
        for line in lines:
            line = line.strip()
            if line.startswith("алкоголь:"):
                alcohol_part = line.replace("алкоголь:", "").strip()
                if alcohol_part.startswith("[") and alcohol_part.endswith("]"):
                    values = [v.strip() for v in alcohol_part[1:-1].split(",") if v.strip()]
                    result["alcohol"] = [v if v in ["да", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["alcohol"] = [alcohol_part if alcohol_part in ["да", "нет"] else "нет"][:killer_count]
                result["alcohol"] += ["нет"] * (killer_count - len(result["alcohol"]))
                
            elif line.startswith("ссора:"):
                argument_part = line.replace("ссора:", "").strip()
                if argument_part.startswith("[") and argument_part.endswith("]"):
                    values = [v.strip() for v in argument_part[1:-1].split(",") if v.strip()]
                    result["precrime_argument"] = [v if v in ["была", "нет"] else "нет" for v in values][:killer_count]
                else:
                    result["precrime_argument"] = [argument_part if argument_part in ["была", "нет"] else "нет"][:killer_count]
                result["precrime_argument"] += ["нет"] * (killer_count - len(result["precrime_argument"]))
                
            elif line.startswith("мотив:"):
                motive_part = line.replace("мотив:", "").strip()
                motives = [m.strip() for m in motive_part.split(",") if m.strip()]
                result["motive"] = ", ".join(motives) if motives else "неизвестно"
                
            elif line.startswith("связь:"):
                rel_part = line.replace("связь:", "").strip()
                if rel_part.startswith("[") and rel_part.endswith("]"):
                    values = [v.strip() for v in rel_part[1:-1].split(",") if v.strip()]
                    result["relationship"] = [v if v in valid_relationships else "неизвестно" for v in values][:killer_count]
                else:
                    result["relationship"] = [rel_part if rel_part in valid_relationships else "неизвестно"][:killer_count]
                result["relationship"] += ["неизвестно"] * (killer_count - len(result["relationship"]))
                
            elif line.startswith("жертва_женщина:"):
                woman_part = line.replace("жертва_женщина:", "").strip()
                result["has_woman_victim"] = woman_part if woman_part in ["0", "1"] else "0"
                
            elif line.startswith("жертва_мужчина:"):
                man_part = line.replace("жертва_мужчина:", "").strip()
                result["has_man_victim"] = man_part if man_part in ["0", "1"] else "0"
                        
    except Exception as e:
        print(f"Ошибка парсинга ответа: {text}, ошибка: {str(e)}")
    
    return result

df_eval["predictions"] = df_eval[["combined_text", "killer_count"]].progress_apply(classify_with_gpt4, axis=1)

df_eval["predicted_alcohol"] = df_eval["predictions"].apply(lambda x: ", ".join(x["alcohol"]))
df_eval["predicted_precrime_argument"] = df_eval["predictions"].apply(lambda x: ", ".join(x["precrime_argument"]))
df_eval["predicted_motive"] = df_eval["predictions"].apply(lambda x: x["motive"])
df_eval["predicted_relationship"] = df_eval["predictions"].apply(lambda x: ", ".join(x["relationship"]))
df_eval["predicted_has_woman_victim"] = df_eval["predictions"].apply(lambda x: x["has_woman_victim"])
df_eval["predicted_has_man_victim"] = df_eval["predictions"].apply(lambda x: x["has_man_victim"])

100%|██████████| 100/100 [05:30<00:00,  3.30s/it]

In [ ]:
def format_list(value, valid_values, default):
    if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
        try:
            items = ast.literal_eval(value)
            formatted = [str(x) for x in items if str(x) in valid_values]
            return ', '.join(formatted) if formatted else default
        except:
            return default
    else:
        return str(value) if str(value) in valid_values else default

def format_motive(value):
    if isinstance(value, str):
        motives = [m.strip() for m in value.split(",") if m.strip()]
        return ", ".join(motives) if motives else "неизвестно"
    return "неизвестно"

df_eval["alcohol_formatted"] = df_eval["alcohol"].apply(lambda x: format_list(x, ["да", "нет"], "нет"))
df_eval["precrime_argument_formatted"] = df_eval["precrime_argument"].apply(lambda x: format_list(x, ["была", "нет"], "нет"))
# df_eval["motive_formatted"] = df_eval["motive"].apply(format_motive)
df_eval["relationship_between_accused_and_victim2"] = df_eval["relationship_between_accused_and_victim"].apply(map_relationship_to_category)
df_eval["has_woman_victim_formatted"] = df_eval["has_woman_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")
df_eval["has_man_victim_formatted"] = df_eval["has_man_victim"].apply(lambda x: str(x) if str(x) in ["0", "1"] else "0")

y_true_alcohol = df_eval["alcohol_formatted"]
y_pred_alcohol = df_eval["predicted_alcohol"]
y_true_precrime_argument = df_eval["precrime_argument_formatted"]
y_pred_precrime_argument = df_eval["predicted_precrime_argument"]
y_true_relationship = df_eval["relationship_between_accused_and_victim2"]
y_pred_relationship = df_eval["predicted_relationship"]
y_true_has_woman_victim = df_eval["has_woman_victim_formatted"]
y_pred_has_woman_victim = df_eval["predicted_has_woman_victim"]
y_true_has_man_victim = df_eval["has_man_victim_formatted"]
y_pred_has_man_victim = df_eval["predicted_has_man_victim"]

# Мульти-лейбл классификация для мотива
# mlb = MultiLabelBinarizer()
# y_true_motive = mlb.fit_transform(df_eval["motive_formatted"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))
# y_pred_motive = mlb.transform(df_eval["predicted_motive"].apply(lambda x: x.split(", ") if x != "неизвестно" else ["неизвестно"]))

alcohol_accuracy = accuracy_score(y_true_alcohol, y_pred_alcohol)
alcohol_precision, alcohol_recall, alcohol_f1, _ = precision_recall_fscore_support(
    y_true_alcohol, y_pred_alcohol, average="weighted", zero_division=0
)

precrime_argument_accuracy = accuracy_score(y_true_precrime_argument, y_pred_precrime_argument)
precrime_argument_precision, precrime_argument_recall, precrime_argument_f1, _ = precision_recall_fscore_support(
    y_true_precrime_argument, y_pred_precrime_argument, average="weighted", zero_division=0
)

# motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
#     y_true_motive, y_pred_motive, average="weighted", zero_division=0
# )
# motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

relationship_accuracy = accuracy_score(y_true_relationship, y_pred_relationship)
relationship_precision, relationship_recall, relationship_f1, _ = precision_recall_fscore_support(
    y_true_relationship, y_pred_relationship, average="weighted", zero_division=0
)

has_woman_victim_accuracy = accuracy_score(y_true_has_woman_victim, y_pred_has_woman_victim)
has_woman_victim_precision, has_woman_victim_recall, has_woman_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_woman_victim, y_pred_has_woman_victim, average="weighted", zero_division=0
)

has_man_victim_accuracy = accuracy_score(y_true_has_man_victim, y_pred_has_man_victim)
has_man_victim_precision, has_man_victim_recall, has_man_victim_f1, _ = precision_recall_fscore_support(
    y_true_has_man_victim, y_pred_has_man_victim, average="weighted", zero_division=0
)

# Вывод результатов
print("\nОЦЕНКА GPT-4o-mini (Алкогольное опьянение):")
print(f"Accuracy:  {alcohol_accuracy:.4f}")
print(f"Precision: {alcohol_precision:.4f}")
print(f"Recall:    {alcohol_recall:.4f}")
print(f"F1-score:  {alcohol_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Ссора перед преступлением):")
print(f"Accuracy:  {precrime_argument_accuracy:.4f}")
print(f"Precision: {precrime_argument_precision:.4f}")
print(f"Recall:    {precrime_argument_recall:.4f}")
print(f"F1-score:  {precrime_argument_f1:.4f}")

# print("\nОЦЕНКА GPT-4o-mini (Мотив преступления):")
# print(f"Accuracy:  {motive_accuracy:.4f}")
# print(f"Precision: {motive_precision:.4f}")
# print(f"Recall:    {motive_recall:.4f}")
# print(f"F1-score:  {motive_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Связь с жертвой):")
print(f"Accuracy:  {relationship_accuracy:.4f}")
print(f"Precision: {relationship_precision:.4f}")
print(f"Recall:    {relationship_recall:.4f}")
print(f"F1-score:  {relationship_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва женского пола):")
print(f"Accuracy:  {has_woman_victim_accuracy:.4f}")
print(f"Precision: {has_woman_victim_precision:.4f}")
print(f"Recall:    {has_woman_victim_recall:.4f}")
print(f"F1-score:  {has_woman_victim_f1:.4f}")

print("\nОЦЕНКА GPT-4o-mini (Жертва мужского пола):")
print(f"Accuracy:  {has_man_victim_accuracy:.4f}")
print(f"Precision: {has_man_victim_precision:.4f}")
print(f"Recall:    {has_man_victim_recall:.4f}")
print(f"F1-score:  {has_man_victim_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[[
    "alcohol_formatted", "predicted_alcohol",
    "precrime_argument_formatted", "predicted_precrime_argument",
    "relationship_between_accused_and_victim2", "predicted_relationship",
    "has_woman_victim_formatted", "predicted_has_woman_victim",
    "has_man_victim_formatted", "predicted_has_man_victim"
]].head())

ОЦЕНКА GPT-4o-mini (Алкогольное опьянение):
Accuracy:  0.8600
Precision: 0.8611
Recall:    0.8600
F1-score:  0.8555

ОЦЕНКА GPT-4o-mini (Ссора перед преступлением):
Accuracy:  0.9400
Precision: 0.9706
Recall:    0.9400
F1-score:  0.9439

ОЦЕНКА GPT-4o-mini (Связь с жертвой):
Accuracy:  0.3700
Precision: 0.6160
Recall:    0.3700
F1-score:  0.3641

ОЦЕНКА GPT-4o-mini (Жертва женского пола):
Accuracy:  0.7800
Precision: 0.8656
Recall:    0.7800
F1-score:  0.7923

ОЦЕНКА GPT-4o-mini (Жертва мужского пола):
Accuracy:  0.9600
Precision: 0.9599
Recall:    0.9600
F1-score:  0.9594

Пример предсказаний:
  alcohol_formatted predicted_alcohol precrime_argument_formatted  \
0                да                да                        была
1                да                да                        была
2          нет, нет          нет, нет                         нет
3                да                да                        была
4                да                да                        была

  predicted_precrime_argument relationship_between_accused_and_victim2  \
0                        была                          друзья/знакомые
1                        была                          друзья/знакомые
2                    нет, нет                   неизвестно, неизвестно
3                        была               профессиональные отношения
4                        была                          друзья/знакомые

   predicted_relationship has_woman_victim_formatted  \
0              незнакомец                          0
1                   семья                          0
2  незнакомец, незнакомец                          1
3         друзья/знакомые                          0
4              незнакомец                          0

  predicted_has_woman_victim has_man_victim_formatted predicted_has_man_victim
0                          0                        1                        1
1                          1                        1                        1
2                          1                        0                        0
3                          0                        1                        1
4                          0                        1                        1

In [586]:
def format(value):
    try:
        if isinstance(value, str) and value.startswith('[') and value.endswith(']'):
            parsed_list = ast.literal_eval(value)
            if isinstance(parsed_list, list) and all(isinstance(item, str) for item in parsed_list):
                return ", ".join(parsed_list)
        return value
    except (ValueError, SyntaxError):
        return value

df_eval["motive2"] = df_eval["motive"].apply(format)

mlb = MultiLabelBinarizer()
y_true_motive = mlb.fit_transform(df_eval["motive2"].str.split(", ").fillna("неизвестно"))
y_pred_motive = mlb.transform(df_eval["predicted_motive"].str.split(", "))


motive_precision, motive_recall, motive_f1, _ = precision_recall_fscore_support(
    y_true_motive, y_pred_motive, average="micro", zero_division=0
)
motive_accuracy = accuracy_score(y_true_motive, y_pred_motive)

print("\nОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):")
print(f"Accuracy:  {motive_accuracy:.4f}")
print(f"Precision: {motive_precision:.4f}")
print(f"Recall:    {motive_recall:.4f}")
print(f"F1-score:  {motive_f1:.4f}")

print("\nПример предсказаний:")
print(df_eval[["motive2", "predicted_motive"]].head())

ОЦЕНКА GPT-4o-mini (Мотив преступления, multi-label):
Accuracy:  0.8100
Precision: 0.9151
Recall:    0.8509
F1-score:  0.8818

Пример предсказаний:
                      motive2            predicted_motive
0     личная неприязнь, месть     месть, личная неприязнь
1  личная неприязнь, ревность  ревность, личная неприязнь
2           деньги, имущество       имущество, ограбление
3            личная неприязнь   личная неприязнь, корысть
4            личная неприязнь            личная неприязнь

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) ['аморальное поведение', 'вымогательство', 'защита', 'корысть', 'материальное вознаграждение', 'оскорбление', 'побои', 'стремление скрыть преступление'] will be ignored
  warnings.warn(